frankframework/frankframework

README.md
There was a Example directory missing in the links
=> Corrected the links to example files

core/src/main/java/nl/nn/adapterframework/extensions/esb/EsbSoapWrapperPipe.java
for testing purposes for WAS-team, there are 2 aliasses created for ESB and P2P message layer.
=> deleted allowedMessagingLayers 

example/src/main/resources/ConfigurationSaveGUI3.0Feedback.xml, example/src/main/resources/Feedback/xsl/FormatMail.xsl
correct email address and anonymous name
=> Fix GUI3.0Feedback adapter to send mails instead of adding a database entry

core/src/main/java/nl/nn/adapterframework/extensions/esb/WsdlGeneratorPipe.java, core/src/main/java/nl/nn/adapterframework/receivers/JavaListener.java, core/src/main/java/nl/nn/adapterframework/soap/SoapWrapper.java, core/src/main/java/nl/nn/adapterframework/soap/SoapWrapperPipe.java, core/src/main/java/nl/nn/adapterframework/soap/Wsdl.java
-Removed need of WebserviceListener in adapter to be able to get EndPointURL in wsdl
-Now Able to wrap soapmessages in v1.2
-Code improvements
=> Removed need of webserviceListener to get EndPointURL in wsdl

RELEASES.md, core/src/main/java/nl/nn/adapterframework/util/Misc.java, core/src/main/java/nl/nn/adapterframework/webcontrol/action/ShowSecurityItems.java, webapp/src/main/webapp/jsp/showSecurityItems.jsp
Ha Niels,
Dit is even een eerste pull requests om na te gaan of dit een handige werkwijze is
Gr, Peter
=> Improve 'error' handling in Show Security Items

core/src/main/java/nl/nn/adapterframework/filesystem/Samba2FileSystem.java, core/src/test/java/it/nl/nn/adapterframework/senders/BasicFileSystemTestBase.java, core/src/test/java/it/nl/nn/adapterframework/senders/ExchangeFileSystemTest.java, core/src/test/java/it/nl/nn/adapterframework/senders/Samba2FileSystemSenderTest.java, core/src/test/java/it/nl/nn/adapterframework/senders/Samba2FileSystemTestHelper.java, core/src/test/java/it/nl/nn/adapterframework/senders/SambaFileSystemSenderTest.java, core/src/test/java/it/nl/nn/adapterframework/senders/SambaFileSystemTestHelper.java
filename is improved by adding folder name as prefix. List action is improved not to return unnecessary files and folder. Null check added while closing connection
=> Fix Samba file system 

core/src/main/java/nl/nn/adapterframework/util/Misc.java, core/src/main/java/nl/nn/adapterframework/webcontrol/api/ShowSecurityItems.java
- throw exception to be displayed in security role bindings list.
- Fix string comparisons in showSecurityItems class gui3.0
=> Improve security role bindings handle implementation

core/src/main/java/nl/nn/adapterframework/core/Adapter.java, core/src/main/java/nl/nn/adapterframework/core/ITransactionalStorage.java, core/src/main/java/nl/nn/adapterframework/jdbc/JdbcTransactionalStorage.java, core/src/main/java/nl/nn/adapterframework/receivers/ReceiverBase.java, core/src/main/java/nl/nn/adapterframework/util/LogUtil.java
- Call Ndc.remove if the depth is zero
- Limit character length stored in process result cache
=> Fix Memory leak

core/src/main/java/nl/nn/adapterframework/doc/IbisDocExtractor.java, core/src/main/java/nl/nn/adapterframework/doc/IbisDocPipe.java, core/src/main/java/nl/nn/adapterframework/pipes/Base64Pipe.java, example/pom.xml, webapp/src/main/webapp/iaf/ibisdoc/css/style.css, webapp/src/main/webapp/iaf/ibisdoc/index.html, webapp/src/main/webapp/iaf/ibisdoc/javascript/application.js
- Changed the ordering of the attributes and the parent classes in the IbisDoc. 
- Also some small CSS fixes.
=> Ibisdoc ordering

core/src/main/java/nl/nn/adapterframework/configuration/IbisApplicationContext.java, core/src/main/resources/xml/xsl/web/adapterSite.xsl, ear-example/src/main/application/META-INF/ibmconfig/cells/defaultCell/applications/defaultApp/deployments/defaultApp/deployment.xml
En twee andere kleine aanpassingen
=> Set Parent Last automatically from ear project

pom.xml
See: https://commons.apache.org/proper/commons-codec/changes-report.html#a1.13 for the full release notes
=> Upgrade apache commons codec to the latest version

webapp/src/main/webapp/WEB-INF/web.xml
Roles will automatically be enabled when used
=> Fix Security Roles bug with IbisWarPlugin, PR: #201

core/src/main/java/nl/nn/adapterframework/http/HttpSecurityHandler.java, core/src/main/java/nl/nn/adapterframework/http/HttpSender.java, core/src/main/java/nl/nn/adapterframework/http/HttpSenderBase.java, core/src/main/java/nl/nn/adapterframework/http/MultipartHttpSender.java, core/src/main/java/nl/nn/adapterframework/http/rest/ApiEhcache.java, core/src/main/java/nl/nn/adapterframework/http/rest/ApiListener.java, core/src/main/java/nl/nn/adapterframework/http/rest/ApiListenerServlet.java, core/src/main/java/nl/nn/adapterframework/http/rest/ApiMemcached.java, core/src/main/java/nl/nn/adapterframework/http/rest/ApiPrincipalPipe.java, core/src/main/java/nl/nn/adapterframework/http/rest/ApiServiceDispatcher.java, core/src/main/java/nl/nn/adapterframework/http/rest/ApiUriComparator.java, core/src/main/java/nl/nn/adapterframework/http/rest/MediaTypes.java, core/src/test/java/nl/nn/adapterframework/http/rest/ApiListenerServletTest.java, core/src/test/java/nl/nn/adapterframework/http/rest/ApiListenerTest.java, core/src/test/java/nl/nn/adapterframework/http/rest/ApiServiceDispatcherTest.java, core/src/test/java/nl/nn/adapterframework/http/rest/MediaTypeTest.java
Add unittests for the ApiListenerServlet
Add ability to use application server roles to authenticate against
Add overrides in http.rest classes
Turn Lists into Enums
Fix patternSegments bug where you couldn't get the resolved segment name
=> Add (extra) unit tests for ApiListener

core/src/main/java/nl/nn/adapterframework/configuration/IbisContext.java, core/src/main/java/nl/nn/adapterframework/webcontrol/ConfigurationServlet.java
Fix Graphviz issues blocking ibis startup
Display error message when failing to start ibis
=> Throw exception when ibis fails to start up

core/src/main/java/nl/nn/adapterframework/parameters/Parameter.java
Kleine correctie van 2 exceptions
=> Fix 2 exception messages that used minExclusive instead of maxExclusive

core/src/main/java/nl/nn/adapterframework/xml/ElementFilter.java, core/src/test/java/nl/nn/adapterframework/validation/XmlValidatorExtraTest.java, core/src/test/java/nl/nn/adapterframework/xml/ElementFilterTest.java, core/src/test/resources/Validation/OverrideAndRedefine/Override.xsd, core/src/test/resources/Validation/OverrideAndRedefine/Redefine.xsd, core/src/test/resources/Validation/OverrideAndRedefine/RequestSchema.xsd, core/src/test/resources/Validation/OverrideAndRedefine/UDTSchema.xsd, core/src/test/resources/Validation/OverrideAndRedefine/in_OK.xml
A test that failed in iaf-test, now included in unit tests
=> Add test for redefine in XmlValidator

RELEASES.md, core/src/main/java/nl/nn/adapterframework/util/Misc.java, core/src/main/java/nl/nn/adapterframework/webcontrol/action/ShowSecurityItems.java, webapp/src/main/webapp/jsp/showSecurityItems.jsp
- for 'Used JmsRealms' and 'Used Authentication Entries'
- also including feature that IbisDataAdmin can see first and last
character of password
=> Show Security Items: Improve error handling

TESTING_WITH_IAF-TEST.md
- Repo in settings.xml moved to troubleshoot in TESTING_WITH_IAF-TEST.md
- Header added for database in TESTING_WITH_IAF-TEST.md
- Ant build setupDir added to Ant build section
=> corrections on the test md

TESTING_WITH_IAF-TEST.md
=> space added

ladybug/pom.xml
Tested it locally and all looks good!
=> Upgrade ladybug to version 2.0.9

core/src/main/resources/AppConstants.properties, core/src/main/resources/log4j4ibis.properties, ladybug/src/main/resources/TestTool/xsl/Default.xsl, ladybug/src/main/resources/springIbisTestTool.xml
This change has a dependency on the changes made in [this pull request](https://github.com/ibissource/ibis-ladybug/pull/3).
=> Add Spring property for Ladybug message capping

CONTRIBUTING.md
Small extension to Contributing.md for more clear instructions on setting up and running the iaf project with IntelliJ IDEA.
Changes made on file:
- iaf/Contributing.md lines 117, 127.
=> Extend Contributing.md

core/src/main/java/nl/nn/adapterframework/configuration/IbisContext.java, core/src/main/java/nl/nn/adapterframework/lifecycle/IbisApplicationContext.java, core/src/main/java/nl/nn/adapterframework/lifecycle/IbisApplicationInitializer.java, core/src/main/java/nl/nn/adapterframework/lifecycle/IbisApplicationServlet.java, core/src/main/java/nl/nn/adapterframework/util/AppConstants.java
Cleanup code and move it to the IbisApplicationInitializer
=> Dynamically determine ApplicationServerType

core/src/main/java/nl/nn/adapterframework/configuration/Configuration.java, core/src/main/java/nl/nn/adapterframework/configuration/ConfigurationDigester.java, core/src/main/java/nl/nn/adapterframework/configuration/ConfigurationUtils.java, core/src/main/java/nl/nn/adapterframework/extensions/esb/EsbSoapWrapperPipe.java, core/src/main/java/nl/nn/adapterframework/parameters/Parameter.java, core/src/main/java/nl/nn/adapterframework/pipes/MessageSendingPipe.java, core/src/main/java/nl/nn/adapterframework/pipes/PutSystemDateInSession.java, core/src/main/java/nl/nn/adapterframework/webcontrol/api/ServerStatistics.java, core/src/main/java/nl/nn/adapterframework/webcontrol/api/ShowEnvironmentVariables.java, webapp/src/main/webapp/iaf/gui/css/style.css, webapp/src/main/webapp/iaf/gui/js/controllers.js, webapp/src/main/webapp/iaf/gui/views/ShowConfigurationStatus.html, webapp/src/main/webapp/iaf/gui/views/ShowEnvironmentVariables.html, webapp/src/main/webapp/iaf/gui/views/common/topnavbar.html
Redo the GUI 3.0 environment variables page
Add otap.side to the gui
Add stubbed label to configs when they are stubbed
=> Change environmentVariables to show properties per config

example/pom.xml
Upgrade Jetty
Reduce jar-scanning
Add loginservice
=> Fix jetty plugin startup issues

core/src/main/java/nl/nn/adapterframework/doc/IbisDocExtractor.java, core/src/main/java/nl/nn/adapterframework/doc/IbisDocPipe.java, core/src/main/java/nl/nn/adapterframework/doc/objects/AClass.java, core/src/main/java/nl/nn/adapterframework/doc/objects/AFolder.java, core/src/main/java/nl/nn/adapterframework/doc/objects/AMethod.java, core/src/main/java/nl/nn/adapterframework/doc/objects/DigesterXmlHandler.java, core/src/main/java/nl/nn/adapterframework/doc/objects/IbisBean.java, core/src/main/java/nl/nn/adapterframework/doc/objects/IbisMethod.java, core/src/main/java/nl/nn/adapterframework/doc/objects/SpringBean.java, webapp/src/main/webapp/iaf/ibisdoc/css/style.css, webapp/src/main/webapp/iaf/ibisdoc/index.html, webapp/src/main/webapp/iaf/ibisdoc/javascript/application.js
New update for the IbisDoc
- Bug fix where not all classes were shown correctly
- Downsizing the JSON file containing all IbisDoc information
- Refactor the classes in IbisDocPipe and IbisDocExtractor
- Show if a method (attribute) is deprecated
=> Ibisdoc(v5)

core/src/main/java/nl/nn/adapterframework/core/PipeLine.java, core/src/main/java/nl/nn/adapterframework/doc/IbisDocPipe.java, core/src/main/java/nl/nn/adapterframework/doc/objects/AClass.java, core/src/main/java/nl/nn/adapterframework/doc/objects/AMethod.java, core/src/main/java/nl/nn/adapterframework/http/WebServiceListener.java, core/src/main/java/nl/nn/adapterframework/jdbc/JdbcTransactionalStorage.java, core/src/main/java/nl/nn/adapterframework/ldap/LdapFindGroupMembershipsPipe.java, core/src/main/java/nl/nn/adapterframework/pipes/AbstractPipe.java, core/src/main/java/nl/nn/adapterframework/pipes/Base64Pipe.java, core/src/main/java/nl/nn/adapterframework/pipes/FilenameSwitch.java, core/src/main/java/nl/nn/adapterframework/pipes/IsXmlIfPipe.java, core/src/main/java/nl/nn/adapterframework/pipes/PutSystemDateInSession.java, core/src/main/java/nl/nn/adapterframework/pipes/XmlIf.java, core/src/main/java/nl/nn/adapterframework/receivers/ReceiverBase.java, core/src/main/java/nl/nn/adapterframework/scheduler/JobDef.java, ladybug/src/main/java/nl/nn/ibistesttool/LadybugPipe.java
Fix bugs in the IbisDoc 
- Javadoc bugs
- Unwanted classes in the xsd
- Bugs in descriptions of @IbisDoc
=> Bug fixes ibis doc

core/src/main/java/nl/nn/adapterframework/doc/IbisDocPipe.java
Add IbisDoc taken from IbisDocRef to the xsd
=> Add ibis doc ref to xsd

ladybug/pom.xml, ladybug/src/main/java/nl/nn/ibistesttool/Debugger.java, ladybug/src/main/java/nl/nn/ibistesttool/DeploymentSpecificsBeanPostProcessor.java, ladybug/src/main/java/nl/nn/ibistesttool/IbisDebuggerAdvice.java, ladybug/src/main/java/nl/nn/ibistesttool/LadybugPipe.java, ladybug/src/main/java/nl/nn/ibistesttool/tibet2/Debugger.java
This pull request needs a Travis rerun after the next Ladybug release.
=> Sync Ladybug's enable toggle with GUI 3.0's

webapp/src/main/webapp/iaf/gui/css/style.css
=> Fix minimized menu logo

core/src/main/java/nl/nn/adapterframework/core/IListenerConnector.java, core/src/main/java/nl/nn/adapterframework/jms/IbisMessageListenerContainer.java, core/src/main/java/nl/nn/adapterframework/jms/JMSFacade.java, core/src/main/java/nl/nn/adapterframework/jms/PushingJmsListener.java, core/src/main/java/nl/nn/adapterframework/unmanaged/SpringJmsConnector.java, ibm/src/main/java/nl/nn/adapterframework/ejb/EjbListenerPortConnector.java, ifsa/src/main/java/nl/nn/adapterframework/extensions/ifsa/ejb/IfsaProviderListener.java, ifsa/src/main/java/nl/nn/adapterframework/extensions/ifsa/jms/PushingIfsaProviderListener.java
=> #491 support credentials in pushing jms listener, fix for IBM module, (7.5 branch)

ladybug/pom.xml
- [Fix] Correct comparison when searching parent thread
- [Feature] Simplify syntax of cross-report variables
- [Feature] Add toggle options for showing report storage IDs and checkpoint IDs in more relevant places of the UI
- [Feature] Add timestamp to filename when downloading zipped reports
=> Upgrade Ladybug to 2.0.15-20200323.164327

core/src/main/java/nl/nn/adapterframework/http/HttpSenderBase.java, core/src/test/java/nl/nn/adapterframework/http/HttpSenderTest.java, core/src/test/resources/nl/nn/adapterframework/http/response/specialCharactersDoubleEscaped.txt, core/src/test/resources/nl/nn/adapterframework/http/response/specialCharactersInURLParam.txt
Re-encoding the characters during URI Build solves the problem.
This pull requiest will resolve #571
=> URL Query Special Characters Fix

core/src/main/java/nl/nn/adapterframework/http/rest/ApiPrincipalPipe.java, core/src/main/java/nl/nn/adapterframework/lifecycle/ServletManager.java
Repalced random with Secure Random
Added httpOnly
And refactored servletManager to be able to retrieve transport guarantee.
Added useSecure() if transport guarantee is confidential.
Closes #595
=> Apply necessary changes for ApiPrincipal Hardening, #595

core/src/main/java/nl/nn/adapterframework/http/HttpSenderBase.java, core/src/test/java/nl/nn/adapterframework/http/HttpSenderTest.java
Added a check for URI scheme.
closes #592
=> Httpsender SSRF

core/src/main/java/nl/nn/adapterframework/pipes/LocalFileSystemPipe.java
=> Add wildcard and excludeWildcard to LocalFileSystemPipe

core/src/main/java/nl/nn/adapterframework/webcontrol/api/ExecuteJdbcQuery.java, core/src/main/resources/log4j4ibis.xml, core/src/main/resources/springTOMCATBTM.xml, ibm/src/main/java/nl/nn/adapterframework/util/IbmMisc.java
Don't display the same datasourceName twice in the console
Replace the custom logger example
Fix the JNDI datasource proxyInterface
Fix logger name in IbmMisc
=> Minor Bugfixes

core/src/main/java/nl/nn/adapterframework/extensions/esb/DirectWrapperPipe.java, core/src/main/java/nl/nn/adapterframework/pipes/TimeoutGuardPipe.java, core/src/main/java/nl/nn/adapterframework/task/TimeoutGuard.java, core/src/main/java/nl/nn/adapterframework/webcontrol/pipes/ConfigurationBase.java, core/src/main/java/nl/nn/adapterframework/webcontrol/pipes/ExecuteJdbcProperties.java, core/src/main/java/nl/nn/adapterframework/webcontrol/pipes/ShowConfig.java, core/src/main/java/nl/nn/adapterframework/webcontrol/pipes/ShowConfigExe.java, core/src/main/java/nl/nn/adapterframework/webcontrol/pipes/ShowEnvironmentVariables.java, core/src/main/java/nl/nn/adapterframework/webcontrol/pipes/ShowFlowDiagram.java, core/src/main/java/nl/nn/adapterframework/webcontrol/pipes/TestPipeLine.java, core/src/main/java/nl/nn/adapterframework/webcontrol/pipes/UploadConfig.java, core/src/main/java/nl/nn/adapterframework/webcontrol/pipes/Webservices.java, core/src/test/java/nl/nn/adapterframework/pipes/PipeTestBase.java, core/src/test/java/nl/nn/adapterframework/pipes/TimeoutGuardPipeTest.java
The main reason I'm trying to keep this class (semi-)alive is because it's used in a few ibisses as custom (webservice) code.
=> Refactor TimeoutGuardPipe

webapp/src/main/webapp/iaf/gui/js/controllers.js
Show an error message when updating dynamic parameters but not having the correct permissions.
=> Show error message when updating dynamic params #660

core/src/main/java/nl/nn/adapterframework/configuration/IbisContext.java, core/src/main/java/nl/nn/adapterframework/extensions/esb/WsdlGeneratorPipe.java, core/src/main/java/nl/nn/adapterframework/util/flow/FlowDiagram.java, core/src/main/java/nl/nn/adapterframework/util/flow/FlowDiagramManager.java, core/src/main/java/nl/nn/adapterframework/util/flow/IFlowGenerator.java, core/src/main/java/nl/nn/adapterframework/util/flow/V8FlowGenerator.java, core/src/main/java/nl/nn/adapterframework/webcontrol/api/Base.java, core/src/main/java/nl/nn/adapterframework/webcontrol/api/ShowConfiguration.java, core/src/main/java/nl/nn/adapterframework/webcontrol/api/ShowConfigurationStatus.java, core/src/main/resources/springCommon.xml, core/src/test/java/nl/nn/adapterframework/util/FlowDiagramTest.java
Fix ibis fails to start when FlowDiagram bean cant be initialized
Fix ibis not generating new flow images
Fix wsdl generator pipe issue
=> Allow different flow generator implementations

core/src/test/java/nl/nn/adapterframework/jdbc/transformer/ToMap.java
import org.codehaus.jackson.map.ObjectMapper was replaced by import com.fasterxml.jackson.databind.ObjectMapper;
=> import org.codehaus.jackson.map.ObjectMapper was removed

core/src/main/java/nl/nn/adapterframework/webcontrol/api/SendJmsMessage.java, core/src/main/java/nl/nn/adapterframework/webcontrol/api/ShowConfiguration.java, core/src/main/java/nl/nn/adapterframework/webcontrol/api/TestPipeline.java, core/src/main/java/nl/nn/adapterframework/webcontrol/api/TestServiceListener.java
=> Add ability to change message encoding and set default encoding properly

core/src/main/java/nl/nn/adapterframework/configuration/Configuration.java, core/src/main/java/nl/nn/adapterframework/webcontrol/api/SendJmsMessage.java, core/src/main/java/nl/nn/adapterframework/webcontrol/api/ServerStatistics.java, core/src/main/java/nl/nn/adapterframework/webcontrol/api/ShowConfiguration.java, core/src/main/java/nl/nn/adapterframework/webcontrol/api/TestServiceListener.java, core/src/test/java/nl/nn/adapterframework/webcontrol/api/ApiTestBase.java, core/src/test/java/nl/nn/adapterframework/webcontrol/api/MockHttpRequest.java, core/src/test/java/nl/nn/adapterframework/webcontrol/api/MockIbisManager.java, core/src/test/java/nl/nn/adapterframework/webcontrol/api/ServerStatisticsTest.java
Add health endpoint for configurations
Make user field configurable when uploading a configuration
Uniform multipart field extraction
=> Add health endpoint for configurations

test/src/test/testtool/ResultSet2FileSender/01/xqs-in2.xml, test/src/test/testtool/ResultSet2FileSender/01/xqs-out2.xml
Deze was uit het andere PR gevallen, helaas.
=> Remove dbms dependency of ResultSet2FileSender test

core/src/main/java/nl/nn/adapterframework/webcontrol/api/ServerStatistics.java, webapp/src/main/webapp/iaf/gui/js/controllers.js, webapp/src/main/webapp/iaf/gui/js/services.js, webapp/src/main/webapp/iaf/gui/views/information.html
Add Frank! version
Fix file uploads
Fix errorStorage deleteSelected
=> Multiple GUI fixes

webapp/src/main/webapp/WEB-INF/web.xml
Removes the authentication for the root and redirects the user to status page.
Fixes #802
=> Remove authentication for the base url and redirect to status

core/src/main/java/nl/nn/adapterframework/extensions/fxf/FxfListener.java, core/src/main/java/nl/nn/adapterframework/jdbc/ResultSetIteratingPipe.java, core/src/main/java/nl/nn/adapterframework/jms/PullingJmsListener.java, core/src/main/java/nl/nn/adapterframework/jms/PushingJmsListener.java
And two cosmetic changes in other files
=> Make Jms afterMessageProcessed resilient to other message types

ladybug/pom.xml, ladybug/src/main/resources/springIbisTestTool.xml
Ladybug RELEASES.md between 2.0.15-20200610.174932 and 2.0.15-20200624.163950:
Check file system free space (show warning and don't store report to prevent corrupt storage files)
=> Ladybug check free space

core/src/main/java/nl/nn/adapterframework/core/IMessageBrowsingIterator.java, core/src/main/java/nl/nn/adapterframework/jdbc/JdbcQuerySenderBase.java, core/src/main/java/nl/nn/adapterframework/jdbc/JdbcTableListener.java, core/src/main/java/nl/nn/adapterframework/jdbc/JdbcTransactionalStorage.java, core/src/main/java/nl/nn/adapterframework/webcontrol/api/BrowseJdbcTable.java, core/src/main/java/nl/nn/adapterframework/webcontrol/api/BrowseQueue.java, core/src/main/java/nl/nn/adapterframework/webcontrol/api/ExecuteJdbcQuery.java, core/src/main/java/nl/nn/adapterframework/webcontrol/api/TransactionalStorage.java, webapp/src/main/webapp/iaf/gui/views/ExecuteJdbcQuery.html
Fix #932 Too many closes after browsing messageLog
Fix #921 avoid lowercasing in Browse Tables
Add dirty read option to Execute Jdbc Query
=> Fix #932 Too many closes after browsing messageLog

core/src/main/java/nl/nn/adapterframework/webcontrol/api/ShowScheduler.java, core/src/main/resources/IAF_WebControl/IAF_DatabaseChangelog.xml, example/src/test/resources/webcontrol/pipes/ShowConfigurationStatus_all.xml, webapp/src/main/webapp/iaf/gui/js/controllers.js, webapp/src/main/webapp/iaf/gui/views/AddEditSchedule.html, webapp/src/main/webapp/iaf/gui/views/ShowScheduler.html
- Sort schedulers by name
- Allow configuring the job group name
- Allow configuring description for a job
=> Sort Schedulers by name and add new fields while configuring the job

core/src/main/java/nl/nn/adapterframework/util/Misc.java
- Added javadoc to all the methods I have tested in the Misc class.
- Some system methods still lack javadocs.
- Also in the hide method, changed the variable name of hideRegex into regexForHiding as the former can be understood as a boolean to whether hide the regexes or not.
=> Add javadoc to Misc class

core/src/main/java/nl/nn/adapterframework/scheduler/JobDef.java, core/src/main/java/nl/nn/adapterframework/webcontrol/api/Base.java, core/src/main/java/nl/nn/adapterframework/webcontrol/api/ShowScheduler.java, core/src/main/resources/AppConstants.properties, webapp/src/main/webapp/iaf/gui/views/ShowScheduler.html
Also introduce AppConstant cleanup.database.maxrows with default 25000
=> Fix#1001 include receiver messagelogs in cleanup

webapp/src/main/webapp/iaf/gui/js/controllers.js, webapp/src/main/webapp/iaf/gui/js/main.js, webapp/src/main/webapp/iaf/gui/js/services.js
(cherry picked from commit d2dadd135390f613a0c8d2a54c44838320bbfff7)
=> Add gui notification when connection drops (#979)

CONTRIBUTING.md, core/pom.xml, core/src/main/java/nl/nn/adapterframework/doc/IbisDocPipe.java, core/src/main/java/nl/nn/adapterframework/doc/objects/SchemaInfo.java, pom.xml
This is the first step to generate the Frank configuration schema, the
FrankDoc and the syntax 1.0 lookup compile-time. The plan is to
separate the logic to gather the relevant information from the
logic that writes the generated files.
=> Add Lombok and start separating content from information gathering

core/src/main/java/nl/nn/adapterframework/http/rest/ApiServiceDispatcher.java, core/src/main/java/nl/nn/adapterframework/webcontrol/api/Webservices.java, webapp/src/main/webapp/iaf/gui/js/controllers.js, webapp/src/main/webapp/iaf/gui/views/Webservices.html
- Fix REST services, like IbisDoc
- Fix OpenAPI3.0 download
- reorder and rename WSDL downloads
=> Fix webservices service page

core/src/test/java/nl/nn/adapterframework/pipes/CounterSwitchPipeTest.java, core/src/test/java/nl/nn/adapterframework/pipes/PipeTestBase.java, core/src/test/java/nl/nn/adapterframework/pipes/PutSystemDateInSessionTest.java, core/src/test/java/nl/nn/adapterframework/pipes/TimeoutGuardPipeTest.java, core/src/test/java/nl/nn/adapterframework/pipes/UploadFilePipeTest.java
Removes `hoooray.zip` file from project root folder
=> Use folder relative to tempdir and not the root of the project

webapp/src/main/webapp/iaf/gui/js/controllers.js, webapp/src/main/webapp/iaf/gui/js/directives.js, webapp/src/main/webapp/iaf/gui/views/ShowConfigurationStatus.html
Add configuration name to adapter info
Fix uptime calculator
=> Add configuration name to adapter info and fix uptime calculator

webapp/src/main/webapp/iaf/gui/js/controllers.js, webapp/src/main/webapp/iaf/gui/js/directives.js, webapp/src/main/webapp/iaf/gui/views/ShowConfigurationStatus.html
(cherry picked from commit 8a1db4cbcf2e057f985833b756a036d915e58ec7)
=> Add configuration name to adapter info + Fix uptime calculator (#1107)

.github/workflows/codeql-analysis.yml
https://github.blog/2020-09-30-code-scanning-is-now-available/
=> Enable GitHub code analysis

ladybug/pom.xml, ladybug/src/main/resources/springIbisTestTool.xml
runStorage -> testStorage
logStorage -> debugStorage
RunComponent -> TestComponent
RunPane -> TestPane
=> Ladybug: Rename internal objects from run to test and from log to debug

core/src/main/java/nl/nn/adapterframework/http/rest/ApiListener.java, core/src/main/java/nl/nn/adapterframework/http/rest/ApiListenerServlet.java, core/src/test/java/nl/nn/adapterframework/http/rest/ApiListenerTest.java
Fix datatype for authentication attributes to let property utils to find appropriate write method
Fixes #1056
=> Fix type mismatch between return datatype of getter and argumet datatype of setter

.github/workflows/codeql-analysis.yml, core/src/main/resources/FrankFrameworkCanonical.xsd
=> Add namespace to FrankFrameworkCanonical.xsd

core/src/main/java/nl/nn/adapterframework/util/AppConstants.java, core/src/main/java/nl/nn/adapterframework/util/StringResolver.java, pom.xml
=> Enable to override properties with environment variables

core/src/main/java/nl/nn/adapterframework/batch/AbstractResultHandler.java, core/src/main/java/nl/nn/adapterframework/batch/IResultHandler.java, core/src/main/java/nl/nn/adapterframework/batch/StreamTransformerPipe.java, core/src/main/java/nl/nn/adapterframework/configuration/AbstractSpringPoweredDigesterFactory.java, core/src/main/java/nl/nn/adapterframework/configuration/ConfigurationWarnings.java, core/src/main/java/nl/nn/adapterframework/core/IConfigurable.java, core/src/main/java/nl/nn/adapterframework/jdbc/DirectQuerySender.java, core/src/main/java/nl/nn/adapterframework/jdbc/JdbcFacade.java, core/src/main/java/nl/nn/adapterframework/jdbc/JdbcIteratingPipeBase.java, core/src/main/java/nl/nn/adapterframework/jms/JMSFacade.java, core/src/main/java/nl/nn/adapterframework/pipes/AbstractPipe.java, core/src/main/java/nl/nn/adapterframework/pipes/MessageSendingPipe.java
=> Generic way to store ConfigurationWarnings

sap/src/main/java/nl/nn/adapterframework/extensions/sap/jco3/SapListener.java, sap/src/main/java/nl/nn/adapterframework/extensions/sap/jco3/SapSystem.java, sap/src/main/java/nl/nn/adapterframework/extensions/sap/jco3/SapSystemDataProvider.java
(cherry picked from commit a5d6b37c364a31c411386613d78cfb6872f95831)
=> Change sap setSncQop getter to int (7.5)

core/src/main/java/nl/nn/adapterframework/processors/CorePipeLineProcessor.java, core/src/main/java/nl/nn/adapterframework/util/XmlUtils.java
=> Disable output validation for empty result exits

larva/src/main/java/nl/nn/adapterframework/testtool/TestTool.java
Currenly, Larva read and write steps use filenames, like:
```
step1.java.queuename.write = scenario01/in.xml
step2.java.queuename.read = scenario01/out.xml
```
where the files contain the request message and the expected response, for instance:
scenario01/in.xml:
```
<request query="select count(*) from table"/>
```
scenario02/out.xml:
```
<response>23</response>
```
In case the files contain a single line only (like in the example above), then using this PR, this can also be written like:
```
step1.java.queuename.writeline = <request query="select count(*) from table"/>
step2.java.queuename.readline = <response>23</response>
```
N.B. the 'readline' functionality has been disabled for now, as it does not prevent the 'saveResults' feature from writing unwanted files.
=> Allow Larva inline messages

core/src/main/java/nl/nn/adapterframework/webcontrol/api/ServletDispatcher.java
=> Fix logging in security log for the actions from gui3

cmis/src/main/java/nl/nn/adapterframework/extensions/cmis/mtom/MtomProxy.java, core/src/main/java/nl/nn/adapterframework/configuration/AbstractSpringPoweredDigesterFactory.java, core/src/main/java/nl/nn/adapterframework/configuration/ClassLoaderManager.java, core/src/main/java/nl/nn/adapterframework/configuration/Configuration.java, core/src/main/java/nl/nn/adapterframework/configuration/ConfigurationDigester.java, core/src/main/java/nl/nn/adapterframework/configuration/ConfigurationWarnings.java, core/src/main/java/nl/nn/adapterframework/configuration/IbisContext.java, core/src/main/java/nl/nn/adapterframework/configuration/classloaders/ClassLoaderBase.java, core/src/main/java/nl/nn/adapterframework/http/rest/ApiMemcached.java, core/src/main/java/nl/nn/adapterframework/jdbc/DirectQuerySender.java, core/src/main/java/nl/nn/adapterframework/jdbc/migration/LiquibaseImpl.java, core/src/main/java/nl/nn/adapterframework/jdbc/migration/Migrator.java, core/src/main/java/nl/nn/adapterframework/lifecycle/DetermineApplicationServerBean.java, core/src/main/java/nl/nn/adapterframework/unmanaged/DefaultIbisManager.java, core/src/main/java/nl/nn/adapterframework/validation/XercesXmlValidator.java
=> Show liquibase exceptions in configuration warnings

core/src/main/java/nl/nn/adapterframework/webcontrol/api/ServerStatistics.java, webapp/src/main/webapp/iaf/gui/js/controllers.js, webapp/src/main/webapp/iaf/gui/js/directives.js, webapp/src/main/webapp/iaf/gui/views/ShowConfigurationStatus.html, webapp/src/main/webapp/iaf/gui/views/ShowIbisstoreSummary.html, webapp/src/main/webapp/iaf/gui/views/common/errorpage.html, webapp/src/main/webapp/iaf/gui/views/txstorage/adapter_errorstorage_list.html, webapp/src/main/webapp/iaf/gui/views/txstorage/adapter_errorstorage_view.html, webapp/src/main/webapp/iaf/gui/views/txstorage/adapter_messagelog_list.html, webapp/src/main/webapp/iaf/gui/views/txstorage/adapter_messagelog_view.html, webapp/src/main/webapp/iaf/gui/views/txstorage/pipe_messagelog_list.html, webapp/src/main/webapp/iaf/gui/views/txstorage/pipe_messagelog_view.html
Fix error message format and healthcheck error format
Fix back button not always going back to the correct view
Add pipe message log to Show IBISSTORE Summary page
=> Add pipe message log to Show IBISSTORE Summary page

core/src/main/java/nl/nn/adapterframework/jdbc/JdbcFacade.java, core/src/main/java/nl/nn/adapterframework/jms/JMSFacade.java, core/src/main/java/nl/nn/adapterframework/jms/JNDIBase.java, core/src/main/java/nl/nn/adapterframework/ldap/LdapSender.java
=> Fix#1142 datasource lookup with tomcat jndi prefix

core/src/main/java/nl/nn/adapterframework/webcontrol/api/TestPipeline.java
(cherry picked from commit 371433e94590c7e81a5c693244dbe231aedf5106)
=> Fix test-pipeline zip handling when unable to determine zip entry size

core/src/main/java/nl/nn/adapterframework/filesystem/ExchangeFileSystem.java, core/src/main/java/nl/nn/adapterframework/filesystem/IMailFileSystem.java, core/src/main/java/nl/nn/adapterframework/filesystem/MailFileSystemUtils.java, core/src/main/java/nl/nn/adapterframework/receivers/ExchangeMailListener.java, core/src/main/java/nl/nn/adapterframework/senders/ExchangeFolderSender.java, core/src/test/java/nl/nn/adapterframework/filesystem/MailFileSystemUtilsTest.java, test-integration/src/test/java/nl/nn/adapterframework/filesystem/ExchangeFileSystemTest.java, test-integration/src/test/resources/ExchangeMailAttachedMessage.xml, test-integration/src/test/resources/ExchangeMailNormal.xml, test-integration/src/test/resources/ExchangeMailProblem.xml
Added ``<bestReplyAddress>`` field to email-xml
=> Fix #1279 EWS address parsing problem, added 'bestReplyAddress'

core/src/main/java/nl/nn/adapterframework/filesystem/FileSystemActor.java, core/src/test/java/nl/nn/adapterframework/filesystem/FileSystemActorTest.java
=> Introduce "action" parameter for file systems

core/src/main/java/nl/nn/adapterframework/pipes/CompareIntegerPipe.java, core/src/main/java/nl/nn/adapterframework/pipes/CompareStringPipe.java, core/src/test/java/nl/nn/adapterframework/pipes/CompareIntegerPipeTest.java
=> Introduce operand parameters in CompareIntegerPipe

docker/dbms/MsSqlServer/dockerInit.sh, docker/dbms/Oracle/entrypoint.sh, test-integration/src/test/java/nl/nn/adapterframework/ldap/LdapFindMembershipsPipeTest.java, test/src/main/resources/DeploymentSpecifics.properties
=> Small fixes

core/src/main/java/nl/nn/adapterframework/receivers/Receiver.java
Does not really 'solve' #905, but rearranges the IbisDoc, so that solution (setting maxRetries=-1) can be found more easily
=> Fix #1266 Set Retry flag also when retried from queue + reorder IbisDoc

core/src/main/resources/xml/xsl/stub4testtool.xsl
Refactors stub4testtool.xsl to enable the following items:
- Senders in senders (#674)
- Multiple receivers (#1102)
=> Refactor stub4testtool.xsl

core/src/main/resources/IAF_WebControl/GenerateFlowDiagram/xsl/config2dot.xsl, core/src/main/resources/xml/xsl/uglify_lookup.xml
@Laurens-makel liep er tegenaan dat de CmisSender het niet meer deed in syntax2
=> Fix lookup

core/src/main/java/nl/nn/adapterframework/webcontrol/api/ServerStatistics.java
=> Minor fix #1335 log debugger switch action in security log

ladybug/pom.xml
See also https://github.com/ibissource/ibis-ladybug/issues/50
=> Upgrade Ladybug to add thread with warning

core/src/main/java/nl/nn/adapterframework/pipes/IncreaseIntegerPipe.java, core/src/test/java/nl/nn/adapterframework/pipes/IncreaseIntegerPipeTest.java
=> Introduce increment parameter in IncreaseIntegerPipe

core/src/main/java/nl/nn/adapterframework/pipes/XmlIf.java, core/src/test/java/nl/nn/adapterframework/pipes/XmlIfTest.java
=> Introduce namespaceDefs attribute in XmlIfPipe

core/src/main/java/nl/nn/adapterframework/configuration/ConfigurationUtils.java, core/src/main/java/nl/nn/adapterframework/webcontrol/api/ShowConfiguration.java, core/src/test/java/nl/nn/adapterframework/configuration/ConfigurationUtilsTest.java, webapp/src/main/webapp/iaf/gui/js/controllers.js
=> Improve reply message of 'upload configuration' event

core/src/main/java/nl/nn/adapterframework/webcontrol/api/SendJmsMessage.java, webapp/src/main/webapp/iaf/gui/js/controllers.js, webapp/src/main/webapp/iaf/gui/views/SendJmsMessage.html
=> Make 'Reply To' field optional in send jms message view

core/src/main/java/nl/nn/adapterframework/webcontrol/api/ShowConfigurationStatus.java, webapp/src/main/webapp/iaf/gui/views/ShowConfigurationStatus.html
=> Show ibisstore message count details in adapter status collapsed view

core/src/main/java/nl/nn/adapterframework/scheduler/JobDef.java, core/src/main/java/nl/nn/adapterframework/util/Locker.java
=> Improve logging in messagekeeper for scheduled Jobs

core/src/main/java/nl/nn/adapterframework/configuration/IbisContext.java, core/src/main/java/nl/nn/adapterframework/jdbc/migration/LiquibaseImpl.java, core/src/main/java/nl/nn/adapterframework/jdbc/migration/Migrator.java, core/src/main/java/nl/nn/adapterframework/webcontrol/api/ShowLiquibaseScript.java, webapp/src/main/webapp/iaf/gui/js/controllers.js, webapp/src/main/webapp/iaf/gui/views/ShowLiquibaseScript.html
=> Migrator implements autoClosable

core/src/main/java/nl/nn/adapterframework/core/ITransactionalStorage.java, core/src/main/java/nl/nn/adapterframework/jdbc/JdbcQuerySenderBase.java, core/src/main/java/nl/nn/adapterframework/jdbc/JdbcTransactionalStorage.java, core/src/main/java/nl/nn/adapterframework/jdbc/Result2BlobWriter.java, core/src/main/java/nl/nn/adapterframework/jdbc/Result2ClobWriter.java, core/src/main/java/nl/nn/adapterframework/jdbc/Result2LobWriterBase.java, core/src/main/java/nl/nn/adapterframework/jdbc/ResultSetIterator.java, core/src/main/java/nl/nn/adapterframework/jdbc/SpringDataSourceFactory.java, core/src/main/java/nl/nn/adapterframework/jdbc/dbms/Dbms.java, core/src/main/java/nl/nn/adapterframework/jdbc/dbms/DbmsSupportFactory.java, core/src/main/java/nl/nn/adapterframework/jdbc/dbms/GenericDbmsSupport.java, core/src/main/java/nl/nn/adapterframework/jdbc/dbms/H2DbmsSupport.java, core/src/main/java/nl/nn/adapterframework/jdbc/dbms/IDbmsSupport.java, core/src/main/java/nl/nn/adapterframework/jdbc/dbms/MariaDbDbmsSupport.java, core/src/main/java/nl/nn/adapterframework/jdbc/dbms/PostgresqlDbmsSupport.java, core/src/main/java/nl/nn/adapterframework/util/JdbcUtil.java, core/src/main/resources/IAF_WebControl/IAF_DatabaseChangelog.xml, core/src/test/java/nl/nn/adapterframework/jdbc/dbms/DbmsSupportTest.java, core/src/test/java/nl/nn/adapterframework/jdbc/dbms/TestBlobs.java, docker/dbms/MariaDB/rebuild.bat
+ set column type for IBISCONFIG.CONFIG to LONGBLOB
=> Add support for single statement step BLOB insert

core/src/main/java/nl/nn/adapterframework/http/rest/ApiListenerServlet.java, core/src/main/java/nl/nn/adapterframework/http/rest/ApiPrincipalPipe.java, core/src/main/java/nl/nn/adapterframework/util/CookieUtil.java, core/src/main/java/nl/nn/adapterframework/webcontrol/action/BrowseJdbcTable.java, core/src/main/java/nl/nn/adapterframework/webcontrol/action/BrowseQueue.java, core/src/main/java/nl/nn/adapterframework/webcontrol/action/ExecuteJdbcQuery.java, core/src/main/java/nl/nn/adapterframework/webcontrol/action/SendJmsMessage.java, core/src/main/java/nl/nn/adapterframework/webcontrol/action/ShowIbisstoreSummary.java
=> Change level for 4xx status code related log lines ApiListener

core/src/main/java/nl/nn/adapterframework/webcontrol/api/ServerStatistics.java, core/src/test/java/nl/nn/adapterframework/webcontrol/api/ApiTestBase.java, webapp/src/main/webapp/iaf/gui/js/controllers.js, webapp/src/main/webapp/iaf/gui/views/common/topnavbar.html
=> Display user in gui

README.md, core/src/main/java/nl/nn/adapterframework/jdbc/JndiDataSourceFactory.java, core/src/main/resources/springCommon.xml
Add GitHub Actions badge
Add # PR badge
=> Set JndiContextPrefix if not set explicitly

aspose/src/main/java/nl/nn/adapterframework/extensions/aspose/services/conv/CisConversionResult.java, aspose/src/main/java/nl/nn/adapterframework/extensions/aspose/services/conv/CisConversionService.java, aspose/src/main/java/nl/nn/adapterframework/extensions/aspose/services/conv/impl/MediaTypeValidator.java, aspose/src/main/java/nl/nn/adapterframework/extensions/aspose/services/conv/impl/convertors/Convertor.java, aspose/src/main/java/nl/nn/adapterframework/extensions/aspose/services/conv/impl/convertors/ConvertorFactory.java, aspose/src/main/java/nl/nn/adapterframework/extensions/aspose/services/conv/impl/convertors/MailConvertor.java, aspose/src/main/java/nl/nn/adapterframework/extensions/aspose/services/conv/impl/convertors/PageConvertUtil.java, aspose/src/main/java/nl/nn/adapterframework/extensions/aspose/services/conv/impl/convertors/UniqueFileGenerator.java, aspose/src/main/java/nl/nn/adapterframework/extensions/aspose/services/util/ConvertorUtil.java, aspose/src/main/java/nl/nn/adapterframework/extensions/aspose/services/util/StringsUtil.java, core/src/main/java/nl/nn/adapterframework/configuration/BaseConfigurationWarnings.java, core/src/main/java/nl/nn/adapterframework/pipes/CompareIntegerPipe.java, core/src/test/java/nl/nn/adapterframework/filesystem/FileSystemTestBase.java, core/src/test/java/nl/nn/adapterframework/filesystem/HelperedBasicFileSystemTest.java, core/src/test/java/nl/nn/adapterframework/filesystem/HelperedFileSystemTestBase.java
enable to switch on javadoc validation for missing @return tags
=> Fix Javadoc @return syntax

core/src/main/java/nl/nn/adapterframework/http/rest/ApiListenerServlet.java, core/src/main/java/nl/nn/adapterframework/webcontrol/api/Webservices.java
=> Unique file name for Open Api Schemas

core/src/main/java/nl/nn/adapterframework/filesystem/FileSystemPipe.java, core/src/main/java/nl/nn/adapterframework/filesystem/FileSystemSender.java
=> Missing attributes in ibisdoc FileSystemPipe

core/src/main/java/nl/nn/adapterframework/util/FileUtils.java
=> Use week year in stats log file name

core/src/main/java/nl/nn/adapterframework/util/Dir2Map.java
=> Do not canonicalize file path in logging view

core/src/main/java/nl/nn/adapterframework/batch/AbstractRecordHandler.java, core/src/main/java/nl/nn/adapterframework/batch/AbstractResultHandler.java, core/src/main/java/nl/nn/adapterframework/batch/BatchFileTransformerPipe.java, core/src/main/java/nl/nn/adapterframework/batch/FieldPositionRecordHandlerManager.java, core/src/main/java/nl/nn/adapterframework/batch/FixedPositionRecordHandlerManager.java, core/src/main/java/nl/nn/adapterframework/batch/InputfieldsPart.java, core/src/main/java/nl/nn/adapterframework/batch/OutputfieldsPart.java, core/src/main/java/nl/nn/adapterframework/batch/RecordHandlerManager.java, core/src/main/java/nl/nn/adapterframework/batch/RecordHandlingFlow.java, core/src/main/java/nl/nn/adapterframework/batch/RecordTransformer.java, core/src/main/java/nl/nn/adapterframework/batch/RecordXmlTransformer.java, core/src/main/java/nl/nn/adapterframework/batch/Result2Filewriter.java, core/src/main/java/nl/nn/adapterframework/batch/StreamTransformerPipe.java, core/src/main/resources/log4j4ibis.xml, docker/appserver/WebSphere/Dockerfile
=> BatchFileTransformerPipe code cleanup and fix IbisDoc

core/src/main/java/nl/nn/adapterframework/core/PipeLine.java, core/src/main/java/nl/nn/adapterframework/receivers/ReceiverBase.java, core/src/main/resources/AppConstants.properties
=> Ability to suppress transaction related warnings (7.5)

RELEASES.md
=> Update non-backward compatible changes in the release notes (7.6)

core/src/main/java/nl/nn/adapterframework/pipes/SignaturePipe.java
=> Use CredentialFactory in signaturePipe

core/src/main/java/nl/nn/adapterframework/jdbc/FixedQuerySender.java, core/src/main/java/nl/nn/adapterframework/jdbc/JdbcQuerySenderBase.java, core/src/main/java/nl/nn/adapterframework/jdbc/QueryExecutionContext.java, core/src/main/java/nl/nn/adapterframework/jdbc/XmlQuerySender.java, core/src/test/java/nl/nn/adapterframework/jdbc/JdbcTableListenerTest.java, core/src/test/java/nl/nn/adapterframework/jdbc/JdbcTestBase.java, core/src/test/java/nl/nn/adapterframework/jdbc/dbms/DbmsSupportTest.java, core/src/test/java/nl/nn/adapterframework/jdbc/dbms/TestBlobs.java, core/src/test/java/nl/nn/adapterframework/util/LockerTest.java
=> QueryType string to enum

core/src/main/java/nl/nn/adapterframework/http/HttpSender.java, core/src/main/java/nl/nn/adapterframework/receivers/Receiver.java
(cherry picked from commit 1728a6f5ed95aac30ce0735e9796fe4872d8ac34)
=> Fix NPE and preserve message

core/src/main/java/nl/nn/adapterframework/core/IHasProcessState.java, core/src/main/java/nl/nn/adapterframework/filesystem/FileSystemListener.java, core/src/main/java/nl/nn/adapterframework/jdbc/JdbcListener.java, core/src/main/java/nl/nn/adapterframework/jdbc/JdbcTableListener.java, core/src/main/java/nl/nn/adapterframework/jdbc/MessageStoreListener.java, core/src/main/java/nl/nn/adapterframework/receivers/PullingListenerContainer.java, core/src/main/java/nl/nn/adapterframework/receivers/Receiver.java, core/src/main/java/nl/nn/adapterframework/stream/Message.java, core/src/main/java/nl/nn/adapterframework/webcontrol/api/TransactionalStorage.java, core/src/test/java/nl/nn/adapterframework/filesystem/FileSystemListenerTest.java, core/src/test/java/nl/nn/adapterframework/jdbc/JdbcTableListenerTest.java, core/src/test/java/nl/nn/adapterframework/stream/MessageTest.java, test/src/main/configurations/JDBC/ConfigurationJdbcListener.xml, test/src/main/configurations/JDBC/xsl/md2-in-select-data.xsl, test/src/test/testtool/JdbcListener/scenario01.properties, test/src/test/testtool/JdbcListener/scenario01/result.xml, test/src/test/testtool/JdbcListener/scenario02.properties, test/src/test/testtool/JdbcListener/scenario02/result.xml, test/src/test/testtool/JdbcListener/scenario11.properties, test/src/test/testtool/JdbcListener/scenario11/result.xml, test/src/test/testtool/JdbcListener/scenario12.properties, test/src/test/testtool/JdbcListener/scenario12/result.xml
In this PR the moving of message to DONE or ERROR is relocated, from listener.afterMessageProcessed() to the Receiver
=> Fix #1736 JdbcTableListener messagebrowser containing error messages

aspose/src/main/java/nl/nn/adapterframework/extensions/aspose/pipe/PdfPipe.java, cmis/src/main/java/nl/nn/adapterframework/extensions/cmis/CmisSender.java, cmis/src/test/java/nl/nn/adapterframework/extensions/cmis/CmisSenderTest.java, core/src/main/java/nl/nn/adapterframework/pipes/FixedResultPipe.java, core/src/main/resources/IAF_WebControl/ConfigurationShowFlowDiagram.xml
#1685 had some updates recently
=> Change more fileName attributes to filename

core/src/main/java/nl/nn/adapterframework/core/PipeLine.java, core/src/main/java/nl/nn/adapterframework/core/PipeLineExit.java, core/src/main/java/nl/nn/adapterframework/core/PipeRunResult.java, core/src/main/java/nl/nn/adapterframework/http/rest/ApiServiceDispatcher.java, core/src/main/java/nl/nn/adapterframework/pipes/MessageSendingPipe.java, core/src/main/java/nl/nn/adapterframework/processors/CorePipeLineProcessor.java, core/src/main/java/nl/nn/adapterframework/processors/LockerPipeLineProcessor.java, core/src/main/java/nl/nn/adapterframework/webcontrol/api/TestServiceListener.java, core/src/test/java/nl/nn/adapterframework/validation/Json2XmlValidatorTest.java, ladybug/src/main/java/nl/nn/ibistesttool/filter/TibetView.java, ladybug/src/main/java/nl/nn/ibistesttool/tibet2/Debugger.java, ladybug/src/main/java/nl/nn/ibistesttool/tibet2/Storage.java
Use method to do the comparion of the state
Closes #1701
=> Use static variables instead of success string

core/src/main/java/nl/nn/adapterframework/http/cxf/SOAPProviderBase.java, core/src/main/java/nl/nn/adapterframework/processors/InputOutputPipeProcessor.java, core/src/test/java/nl/nn/adapterframework/processors/InputOutputPipeProcessorTest.java
and also for attachments in SOAPProviderBase
=> Fix #1819 Message support for restoreMovedElements

core/src/main/java/nl/nn/adapterframework/core/PipeLine.java, core/src/main/java/nl/nn/adapterframework/webcontrol/api/ShowLogging.java, webapp/src/main/webapp/iaf/gui/css/style.css, webapp/src/main/webapp/iaf/gui/js/config.js, webapp/src/main/webapp/iaf/gui/js/controllers.js, webapp/src/main/webapp/iaf/gui/views/ManageLogging.html, webapp/src/main/webapp/iaf/gui/views/ShowEnvironmentVariables.html, webapp/src/main/webapp/iaf/gui/views/ShowLogging.html, webapp/src/main/webapp/iaf/gui/views/common/errorpage.html, webapp/src/main/webapp/iaf/gui/views/common/navigation.html, webapp/src/main/webapp/ie4.css
=> Make Loggers configurable

core/pom.xml, core/src/main/java/nl/nn/adapterframework/cache/CacheAdapterBase.java, core/src/main/java/nl/nn/adapterframework/cache/IbisCacheManager.java, core/src/main/java/nl/nn/adapterframework/webcontrol/api/ServerStatistics.java, core/src/test/java/nl/nn/adapterframework/extensions/javascript/JavascriptSenderTest.java, core/src/test/java/nl/nn/adapterframework/pipes/PgpPipeTest.java
Remove edu.emory.mathcs.backport.java.util.*
=> Update EhCache to latest 2.x release

core/src/main/java/nl/nn/adapterframework/webcontrol/api/Webservices.java, webapp/src/main/webapp/iaf/gui/js/controllers.js, webapp/src/main/webapp/iaf/gui/views/TestServiceListener.html
=> Fix determining service location in the generated wsdl

webapp/src/main/webapp/iaf/gui/js/controllers.js, webapp/src/main/webapp/iaf/gui/views/information.html
(cherry picked from commit 7b86d2187a3c01dfd483ca66189f4b6514044079)
=> Show error warning only when server in state error (7.6)

core/src/main/java/nl/nn/adapterframework/jdbc/JdbcQuerySenderBase.java, core/src/test/java/nl/nn/adapterframework/jdbc/FixedQuerySenderTest.java
=> Auto detect namedParameters in the query

webapp/src/main/webapp/iaf/gui/js/controllers.js, webapp/src/main/webapp/iaf/gui/views/ManageConfigurationsUpload.html
=> Change the appearance for the response of Upload Configuration action

core/src/main/java/nl/nn/adapterframework/filesystem/ForEachAttachmentPipe.java, core/src/main/java/nl/nn/adapterframework/pipes/CsvParserPipe.java, core/src/main/java/nl/nn/adapterframework/soap/SoapWrapperPipe.java, core/src/test/java/nl/nn/adapterframework/configuration/digester/MapPropertyDescriptorsTest.java, core/src/test/java/nl/nn/adapterframework/pipes/CsvParserPipeTest.java
=> Introduce headerCase attribute in the CsvParserPipe

core/src/main/java/nl/nn/adapterframework/pipes/CsvParserPipe.java, core/src/test/java/nl/nn/adapterframework/pipes/CsvParserPipeTest.java
=> Fix bug in CsvParserPipe

core/src/main/java/nl/nn/adapterframework/core/PipeForward.java, core/src/main/java/nl/nn/adapterframework/filesystem/FileSystemPipe.java, core/src/main/java/nl/nn/adapterframework/ftp/FtpFileRetrieverPipe.java, core/src/main/java/nl/nn/adapterframework/http/rest/ApiPrincipalPipe.java, core/src/main/java/nl/nn/adapterframework/pipes/CompressPipe.java, core/src/main/java/nl/nn/adapterframework/pipes/EtagHandlerPipe.java, core/src/main/java/nl/nn/adapterframework/pipes/FilePipe.java, core/src/main/java/nl/nn/adapterframework/pipes/MessageSendingPipe.java, core/src/main/java/nl/nn/adapterframework/processors/ExceptionHandlingPipeProcessor.java, core/src/test/java/nl/nn/adapterframework/pipes/Json2XmlValidatorTest.java
=> Fix #1892 exception pipe should not follow exception forward

core/src/main/java/nl/nn/adapterframework/filesystem/FileSystemActor.java, core/src/main/java/nl/nn/adapterframework/filesystem/FileSystemPipe.java, core/src/main/java/nl/nn/adapterframework/filesystem/FileSystemSender.java, core/src/test/java/nl/nn/adapterframework/filesystem/FileSystemActorTest.java
=> Add writeLineSeparator attribute to FileSystemPipe

core/src/main/resources/xml/xsl/uglify_lookup.xml
=> Add CsvParserPipe to 'uglify' lookup table

core/src/main/java/nl/nn/adapterframework/pipes/WsdlXmlValidator.java, core/src/main/java/nl/nn/adapterframework/pipes/XmlValidator.java, core/src/main/java/nl/nn/adapterframework/soap/WsdlGenerator.java, core/src/main/java/nl/nn/adapterframework/soap/WsdlGeneratorUtils.java, core/src/main/java/nl/nn/adapterframework/webcontrol/api/Webservices.java, core/src/test/java/nl/nn/adapterframework/soap/WsdlGeneratorTest.java, core/src/test/resources/WsdlGenerator/GeneratedHelloWorld.wsdl, core/src/test/resources/WsdlGenerator/HelloWorld.wsdl
Rework #1508 to remove some restrictions on the eligibility to have a WSDL
=> Show potential endpoints that can provide a WSDL

core/src/main/java/nl/nn/adapterframework/doc/IbisDocPipe.java, core/src/main/java/nl/nn/adapterframework/webcontrol/api/FrankDoc.java, core/src/main/resources/AppConstants.properties, example/src/main/resources/StageSpecifics_PRD.properties, webapp/src/main/webapp/iaf/frankdoc/css/style.css, webapp/src/main/webapp/iaf/frankdoc/index.html, webapp/src/main/webapp/iaf/frankdoc/js/app.js, webapp/src/main/webapp/iaf/frankdoc/js/controllers.js, webapp/src/main/webapp/iaf/frankdoc/js/directives.js, webapp/src/main/webapp/iaf/frankdoc/views/element-children.html, webapp/src/main/webapp/iaf/frankdoc/views/element.html, webapp/src/main/webapp/iaf/frankdoc/views/sidebar-elements.html, webapp/src/main/webapp/iaf/frankdoc/views/sidebar.html
Add searchbox + 'ALL' group so a global search can be performed
=> Add searchbox to Frankdoc

core/src/main/java/nl/nn/adapterframework/http/rest/ApiDispatchConfig.java, core/src/main/java/nl/nn/adapterframework/http/rest/ApiServiceDispatcher.java, core/src/test/java/nl/nn/adapterframework/http/rest/ApiServiceDispatcherTest.java, webapp/src/main/webapp/iaf/gui/views/login.html
Add easy login form selectors such as 
`$$(".FrankLogin #username")`, `$$(".FrankLogin #password")`, `$$(".FrankLogin button")`
=> Synchronize ApiDispatchers ServiceClients

core/src/main/java/nl/nn/adapterframework/configuration/Configuration.java, core/src/main/java/nl/nn/adapterframework/core/IbisException.java, core/src/main/java/nl/nn/adapterframework/core/IbisExceptionListener.java, core/src/main/java/nl/nn/adapterframework/extensions/bis/BisUtils.java, core/src/main/java/nl/nn/adapterframework/processors/CorePipeLineProcessor.java, core/src/main/java/nl/nn/adapterframework/util/Misc.java, core/src/test/java/nl/nn/adapterframework/pipes/StreamPipeTest.java, core/src/test/java/nl/nn/adapterframework/util/MiscTest.java, ladybug/src/main/java/nl/nn/ibistesttool/PipeDescriptionProvider.java
Change ApplicationContext to ConfigurationContext
Remove `ExceptionUtils` from `IbisExecption`
Remove NPE nightmare: `pipeLine.getAdapter().getConfiguration().getIbisManager()`
Use String Iterator for `Misc#listToString(...)`
Fix and refactor StreamPipeTest
=> Clean up classes

RELEASES.md, core/src/main/java/nl/nn/adapterframework/http/HttpSender.java, core/src/main/java/nl/nn/adapterframework/jdbc/JdbcQuerySenderBase.java, core/src/main/java/nl/nn/adapterframework/pipes/CleanupOldFilesPipe.java, core/src/main/java/nl/nn/adapterframework/pipes/CompareStringPipe.java, core/src/main/java/nl/nn/adapterframework/pipes/Json2XmlValidator.java, core/src/main/java/nl/nn/adapterframework/pipes/MessageSendingPipe.java, core/src/main/java/nl/nn/adapterframework/pipes/PasswordHashPipe.java, core/src/main/java/nl/nn/adapterframework/pipes/XmlSwitch.java, core/src/main/java/nl/nn/adapterframework/pipes/XmlValidator.java, core/src/main/java/nl/nn/adapterframework/processors/InputOutputSenderWrapperProcessor.java, core/src/main/java/nl/nn/adapterframework/senders/IbisJavaSender.java, core/src/main/java/nl/nn/adapterframework/senders/XsltSender.java, test/src/test/testtool/JsonPipe/scenario01/send_out.txt
=> Fix #1959 get session key as string

core/src/main/java/nl/nn/adapterframework/filesystem/AmazonS3FileSystem.java, core/src/main/java/nl/nn/adapterframework/filesystem/ExchangeFileSystem.java, core/src/main/java/nl/nn/adapterframework/filesystem/FileSystemActor.java, core/src/main/java/nl/nn/adapterframework/filesystem/FileSystemBase.java, core/src/main/java/nl/nn/adapterframework/filesystem/FileSystemListener.java, core/src/main/java/nl/nn/adapterframework/filesystem/FileSystemPipe.java, core/src/main/java/nl/nn/adapterframework/filesystem/FileSystemSender.java, core/src/main/java/nl/nn/adapterframework/filesystem/FtpFileSystem.java, core/src/main/java/nl/nn/adapterframework/filesystem/IBasicFileSystem.java, core/src/main/java/nl/nn/adapterframework/filesystem/ImapFileSystem.java, core/src/main/java/nl/nn/adapterframework/filesystem/LocalFileSystem.java, core/src/main/java/nl/nn/adapterframework/filesystem/MailFileSystemUtils.java, core/src/main/java/nl/nn/adapterframework/filesystem/Samba1FileSystem.java, core/src/main/java/nl/nn/adapterframework/filesystem/Samba2FileSystem.java, core/src/test/java/nl/nn/adapterframework/filesystem/BasicFileSystemTest.java, core/src/test/java/nl/nn/adapterframework/filesystem/FileSystemActorTest.java, core/src/test/java/nl/nn/adapterframework/filesystem/FileSystemTest.java, core/src/test/java/nl/nn/adapterframework/filesystem/MockFileSystem.java, pom.xml, test-integration/src/test/java/nl/nn/adapterframework/filesystem/BasicFileSystemTestBase.java, test-integration/src/test/java/nl/nn/adapterframework/filesystem/MailFileSystemTestBase.java
=> Introduce charset attribute for the filesystems (7.6)

core/src/main/java/nl/nn/adapterframework/extensions/graphviz/GraphvizEngine.java, core/src/main/java/nl/nn/adapterframework/extensions/javascript/JavascriptEngine.java, core/src/main/java/nl/nn/adapterframework/extensions/javascript/Nashorn.java, core/src/main/java/nl/nn/adapterframework/util/flow/DefaultFlowGenerator.java, core/src/main/java/nl/nn/adapterframework/util/flow/JavaScriptFlowGenerator.java, core/src/main/resources/springCommon.xml, core/src/test/java/nl/nn/adapterframework/util/FlowDiagramTest.java
Ensures that Nashorn cannot initialise when promise.js cannot be loaded
=> Rename FlowGenerator class to avoid confusion

core/src/main/java/nl/nn/adapterframework/core/IPipe.java, core/src/main/java/nl/nn/adapterframework/extensions/esb/DirectWrapperPipe.java, core/src/main/java/nl/nn/adapterframework/pipes/AbstractPipe.java, core/src/test/java/nl/nn/adapterframework/pipes/CounterSwitchPipeTest.java, core/src/test/java/nl/nn/adapterframework/pipes/IsXmlIfPipeTest.java, core/src/test/java/nl/nn/adapterframework/pipes/PgpPipeTest.java, core/src/test/java/nl/nn/adapterframework/pipes/PipeTestBase.java, core/src/test/java/nl/nn/adapterframework/pipes/XmlIfTest.java, core/src/test/java/nl/nn/adapterframework/pipes/XmlValidatorTest.java, test-integration/src/test/java/nl/nn/adapterframework/ldap/LdapFindMemberPipeTest.java, test-integration/src/test/java/nl/nn/adapterframework/ldap/LdapFindMembershipsPipeTest.java
=> Fix #1924 throw exception in case PipeForward does not have a name

core/src/main/java/nl/nn/adapterframework/extensions/fxf/FxfWrapperPipe.java, core/src/test/java/nl/nn/adapterframework/extensions/fxf/FxfWrapperPipeTest.java
=> Fix #1751 Add option to use ServerFileName as the filename to FxfWrapperPipe

core/src/main/java/nl/nn/adapterframework/extensions/graphviz/GraphvizEngine.java, core/src/main/java/nl/nn/adapterframework/extensions/javascript/J2V8.java, core/src/main/java/nl/nn/adapterframework/extensions/javascript/JavascriptEngine.java, core/src/main/java/nl/nn/adapterframework/extensions/javascript/JavascriptException.java, core/src/main/java/nl/nn/adapterframework/extensions/javascript/Nashorn.java, core/src/main/java/nl/nn/adapterframework/extensions/javascript/Rhino.java, core/src/main/java/nl/nn/adapterframework/senders/JavascriptSender.java, core/src/main/java/nl/nn/adapterframework/util/flow/FlowDiagramManager.java, core/src/test/java/nl/nn/adapterframework/extensions/javascript/JavascriptSenderTest.java, core/src/test/java/nl/nn/adapterframework/extensions/javascript/NashornTest.java
Backport javascript changes #2049 and #2058
=> Throw exception when unable to load Promise.JS

core/src/main/java/nl/nn/adapterframework/extensions/javascript/Nashorn.java, core/src/main/java/nl/nn/adapterframework/senders/JavascriptSender.java, core/src/main/java/nl/nn/adapterframework/util/flow/FlowDiagramManager.java, core/src/test/java/nl/nn/adapterframework/extensions/javascript/JavascriptSenderCallbackTest.java, core/src/test/java/nl/nn/adapterframework/extensions/javascript/JavascriptSenderTest.java, core/src/test/resources/Javascript/JavascriptTest.js
=> Use functional interfaces with exceptions

core/src/main/java/nl/nn/adapterframework/doc/DocumentedEnum.java, core/src/main/java/nl/nn/adapterframework/doc/EnumLabel.java, core/src/main/java/nl/nn/adapterframework/ftp/FtpSession.java, core/src/main/java/nl/nn/adapterframework/jms/JMSFacade.java, core/src/main/java/nl/nn/adapterframework/scheduler/JobDefFunctions.java, core/src/main/java/nl/nn/adapterframework/senders/FtpFileSystemSender.java, core/src/test/java/nl/nn/adapterframework/jdbc/ResultSetIteratingPipeTest.java, core/src/test/java/nl/nn/adapterframework/jms/JmsFacadeDocumentedEnumTest.java, ifsa/src/main/java/nl/nn/adapterframework/extensions/ifsa/IfsaMessageProtocolEnum.java, ifsa/src/main/java/nl/nn/adapterframework/extensions/ifsa/jms/IfsaFacade.java, ifsa/src/main/java/nl/nn/adapterframework/extensions/ifsa/jms/IfsaRequesterSender.java, ifsa/src/main/java/nl/nn/adapterframework/extensions/ifsa/jms/PullingIfsaProviderListener.java, ifsa/src/main/java/nl/nn/adapterframework/extensions/ifsa/jms/PushingIfsaProviderListener.java, pom.xml, webapp/src/main/webapp/iaf/frankdoc/js/controllers.js, webapp/src/main/webapp/iaf/frankdoc/views/attribute-description.html, webapp/src/main/webapp/iaf/frankdoc/views/element-attributes.html, webapp/src/main/webapp/iaf/frankdoc/views/element-children.html
Deprecate methods/elements to cleanup Frank!Doc
=> Implement documented enums

docker/appserver/Tomcat/pom.xml, test/src/test/testtool/ResultSetIteratingPipe/common.properties
- Make credentialProvider version overridable
- Fix ResultSetIteratingPipe larva test scenario
=> Fix CI build

core/src/main/java/nl/nn/adapterframework/scheduler/JobDef.java, core/src/test/java/nl/nn/adapterframework/scheduler/JobDefTest.java
=> Fix #2089 additional check for maxrows not being effective

webapp/src/main/webapp/iaf/gui/js/controllers.js
=> Prefill executeJdbcQuery form with last used data

core/src/main/java/nl/nn/adapterframework/util/MessageBrowsingFilter.java, core/src/main/java/nl/nn/adapterframework/webcontrol/api/TransactionalStorage.java, core/src/test/java/nl/nn/adapterframework/util/MessageBrowsingFilterTest.java, webapp/src/main/webapp/iaf/gui/views/txstorage/adapter_storage_list.html, webapp/src/main/webapp/iaf/gui/views/txstorage/pipe_messagelog_list.html
=> Add ability to filter messages in ProcessState store by message text

core/src/main/java/nl/nn/adapterframework/scheduler/JobDef.java
=> Log warning when cleaning IBISLOCK

core/src/main/java/nl/nn/adapterframework/pipes/XmlSwitch.java, core/src/test/java/nl/nn/adapterframework/pipes/XmlSwitchTest.java, test/src/main/configurations/HTTP/ConfigurationApiListener.xml, test/src/main/configurations/JDBC/ConfigurationJdbcListener.xml, test/src/main/configurations/MainConfig/ConfigurationChecksum.xml, test/src/main/configurations/MainConfig/ConfigurationEsbSoapValidator.xml, test/src/main/configurations/MainConfig/ConfigurationEsbSoapWrapperPipe.xml, test/src/main/configurations/MainConfig/ConfigurationIfsaProviderListener.xml, test/src/main/configurations/MainConfig/ConfigurationReturnedSessionKeys.xml, test/src/main/configurations/MainConfig/ConfigurationSoapWrapperPipe.xml, test/src/main/configurations/MainConfig/ConfigurationWsdlXmlValidator.xml, test/src/main/configurations/MainConfig/ConfigurationXmlValidator.xml, test/src/main/configurations/UTIL/ConfigurationLarva.xml, test/src/main/configurations/UTIL/ConfigurationUploadFiles.xml
=> Deprecate session key attribute in XmlSwitchPipe

core/src/main/java/nl/nn/adapterframework/util/StringResolver.java, core/src/test/java/nl/nn/adapterframework/util/CredentialFactoryTest.java, core/src/test/java/nl/nn/adapterframework/util/MockCredentialFactory.java, core/src/test/java/nl/nn/adapterframework/util/StringResolverTest.java, core/src/test/resources/credentialprovider.properties, core/src/test/resources/mockCredentials.properties, credentialProvider/src/main/java/nl/nn/credentialprovider/MapCredentials.java
resolve credentials, and auto-hide where applicable
=> Impl #2189 ability to refer to credentials when resolving placeholders

core/src/main/java/nl/nn/adapterframework/logging/IbisThrowablePatternConverter.java, core/src/main/resources/log4j4ibis.xml, core/src/test/java/nl/nn/adapterframework/logging/IbisThrowablePatternConverterTest.java
=> Do not duplicate the stack trace in the log file

core/src/main/java/nl/nn/adapterframework/pipes/XsltPipe.java, core/src/test/java/nl/nn/adapterframework/xslt/XsltPipeTest.java, test/src/main/configurations/HTTP/ConfigurationRestListener.xml, test/src/main/configurations/MainConfig/ConfigurationXmlFileElementIteratorPipe.xml
=> Deprecate XsltPipe sessionKey attribute

ladybug/src/main/java/nl/nn/ibistesttool/tibet2/Storage.java
(cherry picked from commit 766630e185237b404603383bbeefd336df54be98)
=> Fix Tibet2 storage when retrieving blob values (7.6)

core/src/main/java/nl/nn/adapterframework/pipes/ForEachChildElementPipe.java, core/src/main/java/nl/nn/adapterframework/pipes/IteratingPipe.java, core/src/main/java/nl/nn/adapterframework/pipes/StringIteratorPipe.java, core/src/main/java/nl/nn/adapterframework/pipes/XmlFileElementIteratorPipe.java, core/src/test/java/nl/nn/adapterframework/pipes/ForEachChildElementPipeTest.java, core/src/test/java/nl/nn/adapterframework/pipes/IteratingPipeTest.java, core/src/test/java/nl/nn/adapterframework/pipes/StreamLineIteratorPipeTest.java, core/src/test/resources/IteratingPipe/TenLinesResultStopConditionXpath.xml
=> Introduce special stop condition forwards to IteratingPipe

webapp/src/main/webapp/iaf/gui/views/txstorage/adapter_storage_list.html, webapp/src/main/webapp/iaf/gui/views/txstorage/pipe_messagelog_list.html
=> Rename the title of the filters box in ibisstore list view

core/src/main/java/nl/nn/adapterframework/pipes/XmlSwitch.java, core/src/test/java/nl/nn/adapterframework/pipes/XmlSwitchTest.java
=> Fix initialization of transformer pool with different xslt versions in XmlSwitch pipe

core/src/main/java/nl/nn/adapterframework/extensions/esb/DirectWrapperPipe.java
=> Fix #2224 use configured success forward in DirectWrapperPipe (7.6)

core/src/main/java/nl/nn/adapterframework/extensions/esb/DirectWrapperPipe.java, core/src/test/java/nl/nn/adapterframework/core/PipeLineTest.java
=> Fix #2224 use configured success forward in DirectWrapperPipe

core/src/main/java/nl/nn/adapterframework/pipes/AbstractPipe.java
=> Skip forward path validation if there is no pipeline (7.6)

webapp/src/main/webapp/iaf/gui/views/ShowEnvironmentVariables.html
=> Rename title of the tab 'All' to 'Global' in environment variables view

core/src/main/java/nl/nn/adapterframework/configuration/filters/SkipContainersFilter.java, core/src/main/resources/xml/xsd/FrankConfig-compatibility.xsd, core/src/main/resources/xml/xsd/FrankConfig-strict.xsd, pom.xml, test/src/main/configurations/JDBC/ConfigurationJdbcListener.xml, test/src/main/configurations/JDBC/ConfigurationJdbcSenders.xml, test/src/main/configurations/MainConfig/ConfigurationErrorMessageFormatter.xml, webapp/src/main/webapp/iaf/frankdoc/css/style.css, webapp/src/main/webapp/iaf/frankdoc/index.html
- Solve a few IAF-Test console warnings
- Fix git project directory being relative during maven module builds
=> Prevent error message from showing up when loading the Frank!Doc

core/src/main/java/nl/nn/adapterframework/webcontrol/api/ExecuteJdbcQuery.java, webapp/src/main/webapp/iaf/gui/js/controllers.js, webapp/src/main/webapp/iaf/gui/views/ExecuteJdbcQuery.html
=> Add query type to execute query view

core/src/main/java/nl/nn/adapterframework/core/IMessageBrowser.java, core/src/main/java/nl/nn/adapterframework/jdbc/JdbcMessageBrowser.java, core/src/main/java/nl/nn/adapterframework/webcontrol/api/TransactionalStorage.java, core/src/test/java/nl/nn/adapterframework/jdbc/JdbcTransactionalStorageTest.java, webapp/src/main/webapp/iaf/gui/js/controllers.js, webapp/src/main/webapp/iaf/gui/views/txstorage/adapter_storage_view.html, webapp/src/main/webapp/iaf/gui/views/txstorage/pipe_messagelog_view.html
=> Message store gui fixes

core/pom.xml, core/src/main/java/nl/nn/adapterframework/logging/IbisLoggerConfigurationFactory.java, core/src/main/resources/FrankFrameworkApiContext.xml, core/src/main/resources/SpringEnvironmentContext.xml, core/src/main/resources/log4j4ibis.xml, pom.xml
=> Disable CXF logging by default

cmis/src/main/java/nl/nn/adapterframework/extensions/cmis/CmisSender.java, cmis/src/test/java/nl/nn/adapterframework/extensions/cmis/CmisSenderTest.java, core/src/main/java/nl/nn/adapterframework/http/rest/ApiListenerServlet.java, core/src/main/java/nl/nn/adapterframework/jms/JMSFacade.java, core/src/main/java/nl/nn/adapterframework/receivers/Receiver.java, core/src/main/java/nl/nn/adapterframework/util/EnumUtils.java, core/src/test/java/nl/nn/adapterframework/http/rest/ApiListenerServletTest.java, core/src/test/java/nl/nn/adapterframework/jms/JmsFacadeDocumentedEnumTest.java, core/src/test/java/nl/nn/adapterframework/util/EnumUtilsTest.java
Add field values for CmisEnums
=> Don't pass inputstream when no content is available

core/pom.xml, core/src/main/java/nl/nn/adapterframework/webcontrol/api/TransactionalStorage.java, core/src/main/resources/FrankFrameworkApiContext.xml
=> Upgrade jackson to version 2.13

core/src/main/java/nl/nn/adapterframework/configuration/Configuration.java, core/src/main/java/nl/nn/adapterframework/configuration/ConfigurationDigester.java, core/src/main/java/nl/nn/adapterframework/configuration/ConfigurationUtils.java
Validation error in [classpath:./load.xml] at line [17] when validating against schema [/xml/xsd/FrankConfig-compatibility.xsd]: cvc-complex-type.3.2.2: Attribute 'attr' is not allowed to appear in element 'XsltPipe'.
=> Fix digester parse error messages

core/src/main/java/nl/nn/adapterframework/cache/CacheAdapterBase.java, core/src/main/java/nl/nn/adapterframework/pipes/FixedResultPipe.java, core/src/main/java/nl/nn/adapterframework/pipes/MailSenderPipe.java, core/src/main/java/nl/nn/adapterframework/receivers/Receiver.java, core/src/main/java/nl/nn/adapterframework/senders/SenderWrapper.java
Some javadoc cleanup + a fix for cache.configure()
=> Fix cache configure issue

core/src/main/java/nl/nn/adapterframework/webcontrol/api/Webservices.java, webapp/src/main/webapp/iaf/gui/views/Webservices.html
=> Show restlistener method in webservices view

larva/src/main/java/nl/nn/adapterframework/testtool/TestTool.java, test/src/test/testtool/Validators/Json2XmlValidator/scenario25.properties, test/src/test/testtool/Validators/Json2XmlValidator/scenario26.properties, test/src/test/testtool/Validators/SoapValidator/scenario25.properties
=> Fix larva scenarios that fail in jboss

core/src/main/java/nl/nn/adapterframework/webcontrol/api/ShowSecurityItems.java
=> Display jms realms by definition in Security Items page

core/src/main/java/nl/nn/adapterframework/pipes/ChecksumPipe.java, core/src/test/java/nl/nn/adapterframework/pipes/ChecksumPipeTest.java
=> Add tests for ChecksumPipe

larva/src/main/java/nl/nn/adapterframework/testtool/TestTool.java, webapp/src/main/webapp/larva/assets/lib.js
=> Update scenarios dropdown dynamically in larva when the scenario's root folder changes

ladybug/pom.xml
Fix https://github.com/ibissource/ibis-ladybug/issues/104
=> Bump Ladybug version, fix StackOverflowError

webapp/src/main/webapp/iaf/frankdoc/js/controllers.js
=> Make nested element hover result property dependent in frankdoc

core/src/main/java/nl/nn/adapterframework/jdbc/JdbcIteratingPipeBase.java, example/src/main/resources/ConfigurationHelloWorlds.xml
=> Show sql injection config warning when there is no query specified

core/src/main/java/nl/nn/adapterframework/pipes/XmlIf.java, core/src/test/java/nl/nn/adapterframework/pipes/XmlIfTest.java
=> Add support for having parameters in xpath in XmlIf pipe

cmis/src/main/java/nl/nn/adapterframework/extensions/cmis/CmisHttpSender.java, cmis/src/main/java/nl/nn/adapterframework/extensions/cmis/CmisSender.java, cmis/src/main/java/nl/nn/adapterframework/extensions/cmis/servlets/AtomPubServletBase.java, cmis/src/main/java/nl/nn/adapterframework/extensions/cmis/servlets/BrowserBinding.java, cmis/src/main/java/nl/nn/adapterframework/extensions/cmis/servlets/WebServicesServletBase.java, core/pom.xml, core/src/main/java/nl/nn/adapterframework/lifecycle/DynamicRegistration.java, core/src/test/java/nl/nn/adapterframework/configuration/ClassLoaderManagerTest.java, core/src/test/java/nl/nn/adapterframework/testutil/URLDataSourceFactory.java, larva/pom.xml, pom.xml
LCM H2 / Spring (Larva) dependency
=> Lazyload CMIS servlets

core/src/main/java/nl/nn/adapterframework/util/MessageBrowsingFilter.java, webapp/src/main/webapp/iaf/gui/js/controllers.js, webapp/src/main/webapp/iaf/gui/views/txstorage/adapter_storage_list.html, webapp/src/main/webapp/iaf/gui/views/txstorage/pipe_messagelog_list.html
=> Small fixes in gui

core/src/main/java/nl/nn/adapterframework/scheduler/JobDef.java, core/src/main/java/nl/nn/adapterframework/scheduler/job/CleanupDatabaseJob.java, core/src/test/java/nl/nn/adapterframework/scheduler/CleanupDatabaseJobTest.java
=> Clean up ibislock table without using locker

core/src/main/java/nl/nn/adapterframework/http/mime/MultipartUtils.java, core/src/main/java/nl/nn/adapterframework/http/rest/ApiListenerServlet.java, core/src/test/java/nl/nn/adapterframework/http/mime/MultipartUtilsTest.java, core/src/test/java/nl/nn/adapterframework/http/rest/ApiListenerServletTest.java, docker/pom.xml
Fixes small issue introduced in #2544
=> Fix binary form fields

core/src/main/resources/xml/xsl/stub4testtool.xsl, core/src/test/java/nl/nn/adapterframework/configuration/ConfigurationUtilsTest.java, core/src/test/resources/ConfigurationUtils/stub4testtool/FullAdapter/expected.xml, core/src/test/resources/ConfigurationUtils/stub4testtool/JdbcQueryListener/expected.xml, core/src/test/resources/ConfigurationUtils/stub4testtool/JdbcTableListener/expected.xml, core/src/test/resources/ConfigurationUtils/stub4testtool/MessageStoreListener/expected.xml, core/src/test/resources/ConfigurationUtils/stub4testtool/MultipleReceivers/expected.xml, core/src/test/resources/ConfigurationUtils/stub4testtool/ReceiverTransactionAttribute/expected.xml, core/src/test/resources/ConfigurationUtils/stub4testtool/ReceiverTransactionAttribute/original.xml
=> Include transactionAttribute for receivers when stubbing

core/src/main/java/nl/nn/adapterframework/configuration/Configuration.java
=> Backwards compatibility for digesting jmsRealms

core/src/main/java/nl/nn/adapterframework/configuration/SuppressKeys.java, core/src/main/java/nl/nn/adapterframework/pipes/ForEachChildElementPipe.java, core/src/main/resources/AppConstants.properties
=> Create suppress key for xslt streaming warning

core/src/test/resources/springTEST.xml, ladybug/src/main/resources/springIbisTestTool.xml, ladybug/src/main/resources/springIbisTestToolApi.xml, ladybug/src/main/resources/springIbisTestToolBaco.xml, ladybug/src/main/resources/springIbisTestToolBipa.xml, ladybug/src/main/resources/springIbisTestToolIgnoreReport.xml, ladybug/src/main/resources/springIbisTestToolJuice.xml, ladybug/src/main/resources/springIbisTestToolTibet2.xml, ladybug/src/main/resources/springIbisTestToolToegang.xml
=> Fix schema path in testtool spring configurations

larva/src/main/java/nl/nn/adapterframework/testtool/TestTool.java, test/src/test/testtool/UnzipPipeExceptionForwardTest/scenario01.properties, test/src/test/testtool/UnzipPipeExceptionForwardTest/scenario02.properties, test/src/test/testtool/Zip/ZipIterator/scenario 01.properties, test/src/test/testtool/Zip/ZipIterator/scenario 02.properties
=> Backport #2768 Make larva scenario file parameters available as FileMessage in session (7.7)

core/src/main/java/nl/nn/adapterframework/jta/SpringTxManagerProxy.java, core/src/main/java/nl/nn/adapterframework/jta/StatusRecordingTransactionManager.java, core/src/main/java/nl/nn/adapterframework/jta/btm/BtmDataSourceFactory.java, core/src/main/java/nl/nn/adapterframework/jta/btm/BtmJtaTransactionManager.java, core/src/main/resources/SpringApplicationContext.xml, core/src/test/java/nl/nn/adapterframework/jta/StatusRecordingTransactionManagerTest.java, core/src/test/java/nl/nn/adapterframework/jta/btm/BtmJtaTransactionManagerTest.java
(cherry picked from commit 97f5c128c17a702d0e36c8c45576f1b117dc4971)
=> Close BTM connections and remove BeanFactory from txManagerProxy (7.7)

pom.xml
(cherry picked from commit be7ffb6051df6a43979eb87d18c56298b0bc05a1)
=> Remove <?m2e ingore?> tag from pom

webapp/src/main/webapp/iaf/gui/js/controllers.js, webapp/src/main/webapp/iaf/gui/views/ManageLogging.html
=> Drop up dropdowns for the last 5 rows in log settings page

credentialProvider/pom.xml, credentialProvider/src/main/java/nl/nn/credentialprovider/RoleToGroupMappingJndiRealm.java, credentialProvider/src/main/java/nl/nn/credentialprovider/rolemapping/RoleGroupMapper.java, credentialProvider/src/main/java/nl/nn/credentialprovider/rolemapping/RoleGroupMappingRuleSet.java, credentialProvider/src/test/java/nl/nn/credentialprovider/rolemapping/RoleGroupMapperTest.java, credentialProvider/src/test/java/org/apache/tomcat/unittest/TesterContext.java, credentialProvider/src/test/resources/conf/tomcat-role-group-mapping.xml, credentialProvider/src/test/resources/users.ldif
Adapted copy of JNDIRealmEx by Fabian van Druenen
=> Implement Tomcat Role LDAP Group mapper

core/src/main/java/nl/nn/adapterframework/filesystem/ConnectedFileSystemBase.java, core/src/main/java/nl/nn/adapterframework/filesystem/ExchangeFileSystem.java, core/src/main/java/nl/nn/adapterframework/filesystem/ImapFileSystem.java, core/src/main/java/nl/nn/adapterframework/filesystem/MailListener.java, core/src/main/java/nl/nn/adapterframework/receivers/Receiver.java, test/src/main/configurations/MainConfig/ConfigurationExchangeMail.xml
- do not release connection if it has been invalidated
- do not start listenerContainer if an exception occurred
=> Fix ExchangeMailListener problems (7.7)

core/pom.xml
=> LCM upgrade jackson dependencies (7.7)

webapp/src/main/webapp/iaf/gui/js/controllers.js
looks like solving merge conflict went wrong
=> Add missing connection overview controller

larva/pom.xml
(cherry picked from commit 5c466b86165908d9091fe3de1f7094bda7daf67f)
=> LCM Spring and Ant in Larva module (7.7)

core/src/main/java/nl/nn/adapterframework/webcontrol/api/ShowInlineMessageStoreOverview.java, webapp/src/main/webapp/iaf/gui/css/style.css, webapp/src/main/webapp/iaf/gui/js/config.js, webapp/src/main/webapp/iaf/gui/js/controllers.js, webapp/src/main/webapp/iaf/gui/views/ShowInlineMessageStoreOverview.html, webapp/src/main/webapp/iaf/gui/views/common/navigation.html
=> Introduce inline store overview page

core/src/main/java/nl/nn/adapterframework/jdbc/MessageStoreSender.java, core/src/main/java/nl/nn/adapterframework/webcontrol/api/ShowConfigurationStatus.java, test/src/main/configurations/MainConfig/ConfigurationMessageStoreSenderAndListenerPeek.xml
=> Display messageStoreSender messagelog in gui

core/pom.xml
=> Revert cxf upgrade

core/src/main/java/nl/nn/adapterframework/webcontrol/api/ApiExceptionHandler.java, webapp/src/main/webapp/iaf/frankdoc/css/style.css, webapp/src/main/webapp/iaf/frankdoc/js/app.js, webapp/src/main/webapp/iaf/frankdoc/js/controllers.js, webapp/src/main/webapp/iaf/frankdoc/js/directives.js, webapp/src/main/webapp/iaf/frankdoc/views/element.html, webapp/src/main/webapp/iaf/frankdoc/views/overview.html
Display element name in page title
=> Add version to frankdoc and display element name in page title

core/src/main/java/nl/nn/adapterframework/core/BytesResource.java, core/src/main/java/nl/nn/adapterframework/jdbc/migration/DatabaseMigratorBase.java, core/src/main/java/nl/nn/adapterframework/jdbc/migration/LiquibaseMigrator.java, core/src/main/java/nl/nn/adapterframework/jdbc/migration/LiquibaseResourceAccessor.java, core/src/main/java/nl/nn/adapterframework/webcontrol/api/ShowLiquibaseScript.java
=> Fix liquibase include file issue (7.7)

core/src/main/java/nl/nn/adapterframework/lifecycle/IbisApplicationServlet.java, core/src/main/java/nl/nn/adapterframework/webcontrol/api/ApiException.java, core/src/main/java/nl/nn/adapterframework/webcontrol/api/Base.java, core/src/main/java/nl/nn/adapterframework/webcontrol/api/ServerStatistics.java
=> Always store IbisContext in ServletConfig (7.7)

core/src/main/java/nl/nn/adapterframework/parameters/Parameter.java, core/src/main/java/nl/nn/adapterframework/pipes/CompareStringPipe.java, core/src/test/java/nl/nn/adapterframework/parameters/ParameterTest.java, core/src/test/java/nl/nn/adapterframework/pipes/CompareStringPipeTest.java
=> Fix NPE in CompareStringPipe and in Parameter

larva/pom.xml, larva/src/main/java/nl/nn/adapterframework/pipes/LarvaPipe.java, test/src/main/configurations/UTIL/ConfigurationLarva.xml
=> Rename fail forward in larva pipe

core/src/main/java/nl/nn/adapterframework/configuration/ConfigurationWarnings.java, core/src/main/resources/AppConstants.properties
=> Make sqlInjection Configuration warnings suppressable by setting a system property (7.7)

webapp/src/main/webapp/iaf/gui/js/controllers.js, webapp/src/main/webapp/iaf/gui/views/txstorage/adapter_storage_list.html
=> Optional text truncate in message store

webapp/src/main/webapp/iaf/gui/js/controllers.js, webapp/src/main/webapp/iaf/gui/views/txstorage/adapter_storage_list.html
=> Optional text truncate in message store (7.7)

core/src/main/java/nl/nn/adapterframework/pipes/DomainTransformerPipe.java
=> Add datasourceName field to DomainTransformerPipe

core/src/main/java/nl/nn/adapterframework/pipes/MessageSendingPipe.java
=> Suppress integrity check warning for messageStoreSender

RELEASES.md, larva/src/main/java/nl/nn/adapterframework/testtool/SenderThread.java, larva/src/main/java/nl/nn/adapterframework/testtool/TestTool.java, test/src/test/testtool/Senders/common.properties, test/src/test/testtool/Senders/scenario01.properties, test/src/test/testtool/Senders/scenario02.properties, test/src/test/testtool/Senders/scenario03.properties, test/src/test/testtool/Senders/scenario04.properties, test/src/test/testtool/TransactionHandling/common.properties, test/src/test/testtool/TransactionHandling/scenario01.properties, test/src/test/testtool/TransactionHandling/scenario02.properties, test/src/test/testtool/TransactionHandling/scenario03.properties, test/src/test/testtool/TransactionHandling/scenario04.properties, test/src/test/testtool/TransactionHandling/scenario05.properties, test/src/test/testtool/TransactionHandling/scenario06.properties, test/src/test/testtool/TransactionHandling/scenario07.properties, test/src/test/testtool/TransactionHandling/scenario08.properties, test/src/test/testtool/TransactionHandling/scenario09.properties, test/src/test/testtool/global.properties
=> Use scenario specific correlationId in Larva

core/src/main/java/nl/nn/adapterframework/scheduler/job/DatabaseJob.java
=> Hide DatabaseJob in frankdoc

core/src/main/java/nl/nn/adapterframework/extensions/api/ApiSoapWrapperPipe.java, core/src/main/java/nl/nn/adapterframework/extensions/esb/DirectWrapperPipe.java, core/src/main/java/nl/nn/adapterframework/extensions/esb/EsbJmsSender.java, core/src/main/java/nl/nn/adapterframework/extensions/esb/EsbSoapWrapperPipe.java, core/src/main/java/nl/nn/adapterframework/extensions/fxf/FxfWrapperPipe.java, core/src/main/java/nl/nn/adapterframework/jms/JmsSender.java, core/src/main/java/nl/nn/adapterframework/scheduler/SchedulerSender.java, core/src/main/java/nl/nn/adapterframework/webcontrol/api/SendJmsMessage.java, core/src/test/java/nl/nn/adapterframework/scheduler/SchedulerSenderTest.java, core/src/test/java/nl/nn/adapterframework/scheduler/SchedulerTestBase.java
=> Create runtime parameters as bean

core/src/main/java/nl/nn/adapterframework/http/WebServiceListener.java, core/src/main/java/nl/nn/adapterframework/http/rest/ApiListener.java
=> Improve physical destination name for Api and webService listener

test/src/main/configurations/UTIL/ConfigurationTestSendMail.xml, webapp/src/main/webapp/iaf/frankdoc/css/style.css, webapp/src/main/webapp/iaf/frankdoc/views/element-attributes.html, webapp/src/main/webapp/iaf/frankdoc/views/element-children.html
=> Frankdoc display mandatory components with asteriks

core/src/main/java/nl/nn/adapterframework/webcontrol/api/TransactionalStorage.java, webapp/src/main/webapp/iaf/gui/js/controllers.js
=> Fix message log page navigation and total message count (7.6)

core/src/main/java/nl/nn/adapterframework/http/rest/ApiListener.java, core/src/main/java/nl/nn/adapterframework/http/rest/ApiListenerServlet.java
=> Add contentDispositionHeaderSessionKey to ApiListener

docker/pom.xml, test/pom.xml
See https://github.com/ibissource/iaf/pull/3261#discussion_r883403401
=> Cleanup/fix iaf.version in pom

ladybug/src/main/java/nl/nn/ibistesttool/PipeLineSessionDebugger.java
=> Display session keys used by pipes in ladybug

webapp/src/main/webapp/iaf/gui/views/ShowConfigurationStatus.html
=> Fix missing curly bracket (7.6)

webapp/src/main/webapp/iaf/gui/views/ShowConfigurationStatus.html
=> Fix missing curly bracket (7.7)

webapp/src/main/webapp/iaf/gui/views/ShowConfigurationStatus.html
=> Fix missing curly bracket

webapp/src/main/webapp/iaf/gui/js/controllers.js
=> Rephrase successful resend feedback message

core/pom.xml, core/src/main/java/nl/nn/adapterframework/pipes/XQueryPipe.java, core/src/main/java/nl/nn/adapterframework/util/TransformerPool.java, core/src/main/java/nl/nn/adapterframework/util/XmlUtils.java, core/src/main/java/nl/nn/adapterframework/xml/XmlWriter.java, core/src/test/java/nl/nn/adapterframework/pipes/XmlIfTest.java, core/src/test/java/nl/nn/adapterframework/pipes/XmlSwitchTest.java, core/src/test/java/nl/nn/adapterframework/util/XmlUtilsTest.java, core/src/test/java/nl/nn/adapterframework/util/XpathTest.java, core/src/test/java/nl/nn/adapterframework/xml/XmlWriterTest.java, core/src/test/java/nl/nn/adapterframework/xslt/XsltErrorTestBase.java, core/src/test/resources/Xslt/MultiNamespace/out.xml, ladybug/pom.xml, pom.xml, test/src/test/testtool/XmlParsers/expectedParsers.xml
Upgrade to Saxon HE 10.8.
From version 11, duplicate imported resources cause an exception.
=> Bump Saxon to 10.8

core/src/main/java/nl/nn/adapterframework/batch/BatchFileTransformerPipe.java, core/src/main/java/nl/nn/adapterframework/batch/IResultHandler.java, core/src/main/java/nl/nn/adapterframework/batch/ResultBlock2Sender.java, core/src/main/java/nl/nn/adapterframework/batch/ResultWriter.java, core/src/main/java/nl/nn/adapterframework/batch/StreamTransformerPipe.java
=> Update originalBlock session key once for each block in BatchFileTransformerPipe

core/src/main/java/nl/nn/adapterframework/pipes/MessageSendingPipe.java, webapp/src/main/webapp/iaf/frankdoc/js/app.js, webapp/src/main/webapp/iaf/frankdoc/js/controllers.js, webapp/src/main/webapp/iaf/frankdoc/views/element-attributes.html
=> Display javadoc on hovering referenced element in javadoc

core/src/main/resources/xml/xsl/stub4testtool.xsl, core/src/test/java/nl/nn/adapterframework/configuration/ConfigurationUtilsTest.java, core/src/test/java/nl/nn/adapterframework/configuration/digester/ConfigurationDigesterTest.java, core/src/test/java/nl/nn/adapterframework/testutil/MatchUtils.java, core/src/test/resources/ConfigurationUtils/stub4testtool/EsbJmsListener/expected.xml, core/src/test/resources/ConfigurationUtils/stub4testtool/EsbJmsListener/original.xml
=> Fix disable template in stubbing xsl

core/src/main/java/nl/nn/adapterframework/http/rest/ApiServiceDispatcher.java
=> Fix splitting requestUrl in openApi schema generation (7.7)

core/src/main/java/nl/nn/adapterframework/http/rest/ApiServiceDispatcher.java, core/src/main/java/nl/nn/adapterframework/util/Misc.java, core/src/test/java/nl/nn/adapterframework/http/rest/OpenApiTest.java
=> Fix splitting requestUrl in openApi schema generation

core/src/main/java/nl/nn/adapterframework/core/PipeLine.java, core/src/main/java/nl/nn/adapterframework/http/rest/ApiListener.java, core/src/main/java/nl/nn/adapterframework/util/ClassUtils.java, core/src/main/java/nl/nn/adapterframework/webcontrol/api/ClassInfo.java, core/src/main/java/nl/nn/adapterframework/webcontrol/api/ShowLogging.java, core/src/main/java/nl/nn/adapterframework/webcontrol/api/UpdateLoggingConfig.java, core/src/test/java/nl/nn/adapterframework/webcontrol/api/TestLoggingSettings.java
Also includes API to view class info
=> Enable to view log files even when application failed to start

core/src/main/java/nl/nn/adapterframework/filesystem/ExchangeFileSystem.java, core/src/main/java/nl/nn/adapterframework/filesystem/MsalClientAdapter.java
Backport of https://github.com/ibissource/iaf/pull/3368 includes #3422
=> Plug custom HttpClient in MSAL for handling proxy settings (7.7)

webapp/src/main/webapp/iaf/gui/js/controllers.js, webapp/src/main/webapp/iaf/gui/views/ShowConfigurationStatus.html
=> Fix adapter status in GUI and escape adapter + receiver names (7.7)

core/src/main/java/nl/nn/adapterframework/core/PipeLineSession.java, core/src/main/java/nl/nn/adapterframework/jms/JMSFacade.java
Change log level of AutoClose resources in PipeLineSession
=> Fix log warnings when JmsRealm not found (in JmsFacade) (7.7)

docker/appserver/Tomcat/Dockerfile, docker/appserver/Tomcat/example/Dockerfile, docker/appserver/Tomcat/test/Dockerfile, docker/appserver/Tomcat/webapp/Dockerfile
Use the tomcat user earlier in the Dockerfile and add chown=tomcat for clearity
=> Fix iaf test by adding chown=tomcat to the COPY instruction.

.github/workflows/maven-build.yml, aspose/src/main/java/nl/nn/adapterframework/extensions/aspose/AsposeFontManager.java, aspose/src/main/java/nl/nn/adapterframework/extensions/aspose/pipe/PdfPipe.java, aspose/src/main/java/nl/nn/adapterframework/extensions/aspose/services/conv/CisConfiguration.java, aspose/src/main/java/nl/nn/adapterframework/extensions/aspose/services/conv/CisConversionResult.java, aspose/src/main/java/nl/nn/adapterframework/extensions/aspose/services/conv/CisConversionService.java, aspose/src/main/java/nl/nn/adapterframework/extensions/aspose/services/conv/impl/CisConversionServiceImpl.java, aspose/src/main/java/nl/nn/adapterframework/extensions/aspose/services/conv/impl/convertors/AbstractConvertor.java, aspose/src/main/java/nl/nn/adapterframework/extensions/aspose/services/conv/impl/convertors/CellsConvertor.java, aspose/src/main/java/nl/nn/adapterframework/extensions/aspose/services/conv/impl/convertors/Convertor.java, aspose/src/main/java/nl/nn/adapterframework/extensions/aspose/services/conv/impl/convertors/ConvertorFactory.java, aspose/src/main/java/nl/nn/adapterframework/extensions/aspose/services/conv/impl/convertors/MailConvertor.java, aspose/src/main/java/nl/nn/adapterframework/extensions/aspose/services/conv/impl/convertors/OfflineResourceLoader.java, aspose/src/main/java/nl/nn/adapterframework/extensions/aspose/services/conv/impl/convertors/PdfAttachmentUtil.java, aspose/src/main/java/nl/nn/adapterframework/extensions/aspose/services/conv/impl/convertors/PdfConvertor.java, aspose/src/main/java/nl/nn/adapterframework/extensions/aspose/services/conv/impl/convertors/PdfImageConvertor.java, aspose/src/main/java/nl/nn/adapterframework/extensions/aspose/services/conv/impl/convertors/PdfStandaardConvertor.java, aspose/src/main/java/nl/nn/adapterframework/extensions/aspose/services/conv/impl/convertors/SlidesConvertor.java, aspose/src/main/java/nl/nn/adapterframework/extensions/aspose/services/conv/impl/convertors/UniqueFileGenerator.java, aspose/src/main/java/nl/nn/adapterframework/extensions/aspose/services/conv/impl/convertors/WordConvertor.java, aspose/src/test/resources/log4j4ibis.xml, pom.xml
=> Backport Aspose external resource loading

core/src/main/java/nl/nn/adapterframework/lifecycle/IbisApplicationContext.java, core/src/main/resources/AppConstants.properties, core/src/main/resources/SpringApplicationContext.xml, core/src/main/resources/SpringApplicationContextJMX.xml, core/src/main/resources/springTOMCATBTM.xml
Conform Spring's JMX properties: https://docs.spring.io/spring-boot/docs/2.1.1.RELEASE/reference/html/production-ready-jmx.html
=> Move JMX beans to a custom context descriptor file

core/src/main/java/nl/nn/adapterframework/jta/TransactionConnector.java, core/src/main/java/nl/nn/adapterframework/jta/TransactionConnectorCoordinator.java, core/src/main/java/nl/nn/adapterframework/pipes/XsltPipe.java, core/src/main/java/nl/nn/adapterframework/senders/JsonXsltSender.java, core/src/main/java/nl/nn/adapterframework/senders/XsltSender.java, core/src/main/java/nl/nn/adapterframework/stream/StreamingSenderBase.java, core/src/main/java/nl/nn/adapterframework/stream/ThreadLifeCycleEventListener.java, core/src/main/java/nl/nn/adapterframework/xml/ExceptionCatchingFilter.java, core/src/main/java/nl/nn/adapterframework/xml/ThreadConnectingFilter.java, ladybug/src/main/java/nl/nn/ibistesttool/IbisDebuggerAdvice.java
=> Fix resumeTransaction always being forced when tx sync is inactive

core/src/main/java/nl/nn/adapterframework/filesystem/FileSystemMessageBrowser.java, core/src/test/java/nl/nn/adapterframework/filesystem/FileSystemActorTest.java, core/src/test/java/nl/nn/adapterframework/filesystem/FileSystemMessageBrowserTest.java, core/src/test/java/nl/nn/adapterframework/filesystem/HelperedFileSystemTestBase.java, core/src/test/java/nl/nn/adapterframework/filesystem/LocalFileSystemMessageBrowserTest.java, core/src/test/java/nl/nn/adapterframework/filesystem/MockFile.java, core/src/test/java/nl/nn/adapterframework/filesystem/MockFileSystemMessageBrowserTest.java, core/src/test/java/nl/nn/adapterframework/filesystem/MockFolder.java
=> fix FileSystemMessageBrowser.containsMessageId

larva/src/main/java/nl/nn/adapterframework/testtool/FileSender.java, larva/src/main/java/nl/nn/adapterframework/testtool/LarvaServlet.java, larva/src/main/java/nl/nn/adapterframework/testtool/TestTool.java, larva/src/main/java/nl/nn/adapterframework/testtool/XsltProviderListener.java, larva/src/main/java/nl/nn/adapterframework/testtool/queues/QueueCreator.java, test/src/test/testtool/XsltProviderListener/01/in.xml, test/src/test/testtool/XsltProviderListener/01/name.xsl, test/src/test/testtool/XsltProviderListener/01/out.xml, test/src/test/testtool/XsltProviderListener/02/in.xml, test/src/test/testtool/XsltProviderListener/02/out.json, test/src/test/testtool/XsltProviderListener/scenario01.properties, test/src/test/testtool/XsltProviderListener/scenario02.properties
Reverts https://github.com/ibissource/iaf/pull/3496/files#diff-583be98996663d96c1b09314731ae271bbf673f4dbc3e12ca4a9f7a54a9450a4R1185
=> Cleanup larva and xsltProviderListener

core/pom.xml, docker/pom.xml, larva/pom.xml
Fix issues:
CVE-2022-42004
CVE-2022-42003
CVE-2022-31159
CVE-2022-22971
CVE-2022-22968
CVE-2021-2471
=> Fix security issues (7.7)

aspose/pom.xml, core/pom.xml
Fix security issues:
CVE-2022-42004
CVE-2022-42003
update spring framework to version updated in 7.7 for security fix there
=> Fix security issues (7.8)

core/src/main/java/nl/nn/adapterframework/senders/MailSender.java, core/src/main/java/nl/nn/adapterframework/senders/MailSenderBase.java
=> Preset CommandMap to avoid javax.activation related ClassCastException

core/src/main/resources/AppConstants.properties, docker/appserver/JBoss/src/configuration/standalone.xml, docker/appserver/JBoss/src/scripts/start-with-mariadb.bat, docker/appserver/JBoss/src/scripts/start-with-mssql.bat, docker/appserver/JBoss/src/scripts/start-with-mysql.bat, docker/appserver/JBoss/src/scripts/start-with-oracle.bat, docker/appserver/JBoss/src/scripts/start-with-postgresql.bat, docker/appserver/WebSphere/src/configuration/02-configureJdbc.py, docker/appserver/WebSphere/src/scripts/start-with-mssql.bat, docker/appserver/WebSphere/src/scripts/start-with-mysql.bat, docker/appserver/WebSphere/src/scripts/start-with-oracle.bat, docker/appserver/WildFly/src/scripts/start-with-mariadb.bat, docker/appserver/WildFly/src/scripts/start-with-mssql.bat, docker/appserver/WildFly/src/scripts/start-with-mysql.bat, docker/appserver/WildFly/src/scripts/start-with-oracle.bat, docker/appserver/WildFly/src/scripts/start-with-postgresql.bat, webapp/src/main/webapp/WEB-INF/jboss-deployment-structure.xml
WebSphere mysql driver
JBoss/WildFly javamail 2 support
Docker start scripts
apiAlias
Cloudwatch default namespace
=> Fix iaf-test problems

.lift.toml, akamai/pom.xml, aspose/pom.xml, aws/pom.xml, cmis/pom.xml, core/pom.xml, credentialProvider/pom.xml, credentialProvider/src/main/java/nl/nn/credentialprovider/WildFlyCredentialFactory.java, credentialProvider/src/test/java/net/wedjaa/ansible/vault/crypto/VaultHandlerTest.java, credentialProvider/src/test/java/nl/nn/credentialprovider/AnsibleVaultCredentialFactoryTest.java, credentialProvider/src/test/java/nl/nn/credentialprovider/CredentialFactoryTest.java, credentialProvider/src/test/java/nl/nn/credentialprovider/CredentialProvidingPropertySourceTest.java, credentialProvider/src/test/java/nl/nn/credentialprovider/FileSystemCredentialsTest.java, credentialProvider/src/test/java/nl/nn/credentialprovider/MapCredentialsTest.java, credentialProvider/src/test/java/nl/nn/credentialprovider/PropertyFileCredentialFactoryTest.java, credentialProvider/src/test/java/nl/nn/credentialprovider/WildFlyCredentialFactoryTest.java, credentialProvider/src/test/java/nl/nn/credentialprovider/rolemapping/RoleGroupMapperTest.java, credentialProvider/src/test/resources/mockito-extensions/org.mockito.plugins.MockMaker, credentialProvider/src/test/resources/users.ldif, ibm/pom.xml, idin/pom.xml, ladybug/pom.xml, larva/pom.xml, pom.xml
Be aware when converting to a Junit 5 test that:
- Method argument order is different
- Annotations may function differently
JUnit 4 | JUnit 5
-- | --
`@Test` | `@Test`
`@Before` | `@BeforeEach`
`@After` | `@AfterEach`
`@BeforeClass` | `@BeforeAll`
`@AfterClass` | `@AfterAll`
`@Ignore` | `@Disabled`
`@Category` | `@Tag`
=> Upgrade to Junit 5

.lift.toml, .lift/setup.sh
Big thanks to @mattjohnson for helping out!
=> Fix and optimize Sonatype Lift builds

core/src/main/java/nl/nn/adapterframework/jndi/TransactionalDbmsSupportAwareDataSourceProxy.java
=> Add JDBC info to the security items page (7.7)

core/src/main/resources/IAF_Util/Configuration.xml, test/src/main/configurations/FileHandling/Configuration.xml, test/src/main/configurations/HTTP/Configuration.xml, test/src/main/configurations/JDBC/Configuration.xml, test/src/main/configurations/JMS/Configuration.xml, test/src/main/configurations/MainConfig/Configuration.xml, test/src/main/configurations/SAP/Configuration.xml, test/src/main/configurations/TX/Configuration.xml, test/src/main/configurations/UTIL/Configuration.xml, test/src/main/configurations/WSS_HTTP/Configuration.xml
=> Remove name attribute from Configuration element (7.8)

core/src/main/java/nl/nn/adapterframework/webcontrol/api/ShowScheduler.java, webapp/src/main/webapp/iaf/gui/js/controllers.js, webapp/src/main/webapp/iaf/gui/js/main.js, webapp/src/main/webapp/iaf/gui/js/services.js, webapp/src/main/webapp/iaf/gui/views/AddEditSchedule.html, webapp/src/main/webapp/iaf/gui/views/ShowConfigurationStatus.html, webapp/src/main/webapp/iaf/gui/views/ShowEnvironmentVariables.html, webapp/src/main/webapp/iaf/gui/views/ShowLogging.html, webapp/src/main/webapp/iaf/gui/views/ShowScheduler.html, webapp/src/main/webapp/iaf/gui/views/TestServiceListener.html
=> Fix scheduler endpoints, configuration awareness and listener name (7.8)

aspose/pom.xml, credentialProvider/pom.xml, credentialProvider/src/test/java/nl/nn/credentialprovider/rolemapping/RoleGroupMapperTest.java, credentialProvider/src/test/resources/users.ldif
https://snyk.io/vuln/SNYK-JAVA-ORGBOUNCYCASTLE-1296075
https://snyk.io/vuln/SNYK-JAVA-ORGBOUNCYCASTLE-2841508
https://snyk.io/vuln/SNYK-JAVA-ORGAPACHEDIRECTORYSERVER-1063040
https://snyk.io/vuln/SNYK-JAVA-ORGAPACHETOMCAT-3097828
https://snyk.io/vuln/SNYK-JAVA-COMGOOGLEPROTOBUF-3040284
(indirectly https://snyk.io/vuln/SNYK-JAVA-COMFASTERXMLJACKSONCORE-3038426)
=> Cleanup code and fix a bunch of CVE's in credential provider test classes and aspose (7.8)

webapp/src/main/webapp/iaf/gui/js/controllers.js
(cherry picked from commit 321cf9315077059c88b912278a4635d7c0426cde) #4086
=> Fix error response when browsing TX messages (7.8)

core/src/main/java/nl/nn/adapterframework/configuration/Configuration.java
(cherry picked from commit 48be4b5db715689122d95a02b145048ebd7dbe5f) #4091
=> Reintroduce name attribute on Configurations

core/src/main/resources/log4j4ibis.xml
(cherry picked from commit 16811e8574a647df4d049d3ec7463d4f0ef1bee8) #4100
=> Reduce narayana jta transaction manager log clutter

core/src/main/java/nl/nn/adapterframework/http/rest/ApiListenerServlet.java
=> Set content type header to application/json when ApiListenerServlet returns Open API JSON

.run/IAF-Example.run.xml, CONTRIBUTING.md, TESTING_WITH_IAF-TEST.md, docker/appserver/Tomcat/pom.xml, docker/pom.xml, pom.xml, test/pom.xml
- Updated instructions for running in IntelliJ.
- Add an IntelliJ run-configuration for the Example configuration.
- Add runtime dependencies to the IAF-Test project for specific libraries which it needs.
=> Updated instructions for running in IntelliJ.

core/src/main/java/nl/nn/adapterframework/http/CacheControlFilter.java, core/src/main/java/nl/nn/adapterframework/http/rest/ApiListenerServlet.java, core/src/test/java/nl/nn/adapterframework/http/rest/ApiListenerServletTest.java, webapp/src/main/webapp/WEB-INF/web.xml
=> Change CacheControl header to only work when no-etag is present

.run/IAF-Example.run.xml, CONTRIBUTING.md, TESTING_WITH_IAF-TEST.md, docker/appserver/Tomcat/pom.xml, docker/pom.xml, pom.xml, test/pom.xml
I'm back porting this change too because I expect I may have to work on 7.8 issues too sometimes and then it may be practical if I can quickly run things in IntelliJ.
(cherry picked from commit b1d2ddb82dc95bda9d9b4d2ecf2a93156769c729)
=> Updated instructions for running in IntelliJ (#4285)

core/src/main/java/nl/nn/adapterframework/http/rest/ApiListener.java, core/src/main/java/nl/nn/adapterframework/http/rest/ApiListenerServlet.java, core/src/main/java/nl/nn/adapterframework/http/rest/MediaTypes.java, core/src/test/java/nl/nn/adapterframework/http/rest/ApiListenerServletTest.java, core/src/test/java/nl/nn/adapterframework/http/rest/ApiListenerTest.java, core/src/test/java/nl/nn/adapterframework/http/rest/MediaTypeTest.java
(cherry picked from commit a6fcd5216db842bcc1a07cef84ff1b5231cd77b1)
=> Abort request when Content-Type does not match consumes (#4274)

core/src/main/java/nl/nn/adapterframework/pipes/Json2XmlValidator.java, core/src/main/java/nl/nn/adapterframework/stream/Message.java, core/src/main/java/nl/nn/adapterframework/stream/MessageContext.java, core/src/main/java/nl/nn/adapterframework/util/MessageUtils.java, core/src/test/java/nl/nn/adapterframework/http/rest/ApiListenerServletTest.java, core/src/test/java/nl/nn/adapterframework/pipes/Json2XmlValidatorTest.java
=> Fix missing message context headers on GET requests

core/src/main/java/nl/nn/adapterframework/mongodb/StrictJsonDocumentWriter.java, core/src/main/java/nl/nn/adapterframework/stream/document/ArrayBuilder.java, core/src/main/java/nl/nn/adapterframework/stream/document/DocumentUtils.java, core/src/main/java/nl/nn/adapterframework/stream/document/INodeBuilder.java, core/src/main/java/nl/nn/adapterframework/stream/document/Json2XmlHandler.java, core/src/main/java/nl/nn/adapterframework/stream/document/JsonNodeBuilder.java, core/src/main/java/nl/nn/adapterframework/stream/document/ObjectBuilder.java, core/src/main/java/nl/nn/adapterframework/stream/document/XmlNodeBuilder.java, core/src/main/java/nl/nn/adapterframework/stream/document/XmlObjectBuilder.java, core/src/main/java/nl/nn/adapterframework/stream/xml/JsonXslt3XmlHandler.java, core/src/main/java/nl/nn/adapterframework/util/DB2DocumentWriter.java, core/src/test/java/nl/nn/adapterframework/stream/document/DocumentBuilderTest.java, core/src/test/java/nl/nn/adapterframework/stream/document/DocumentUtilsTest.java, test/src/test/testtool/MongoDbSender/scenario09.properties, test/src/test/testtool/MongoDbSender/scenario09/in.xml, test/src/test/testtool/MongoDbSender/scenario09/out.txt, test/src/test/testtool/MongoDbSender/scenario10.properties, test/src/test/testtool/MongoDbSender/scenario10/in.xml, test/src/test/testtool/MongoDbSender/scenario10/out.txt
As a start, I made a Larva test that reproduces the error reported in issue https://github.com/ibissource/iaf/issues/4303. @gvanbrakel, can you continue this work to fix the issue?
=> Fix MongoDB for use with MongoDB Atlas shipwrecks collection

.github/workflows/codeql-analysis.yml, core/src/main/java/nl/nn/adapterframework/configuration/digester/ValidateAttributeRule.java, core/src/test/java/nl/nn/adapterframework/configuration/digester/ValidateAttributeRuleTest.java
=> Ensure that that fieldname in configuration warnings is correct 

core/src/main/java/nl/nn/adapterframework/configuration/Configuration.java, core/src/main/java/nl/nn/adapterframework/scheduler/job/CleanupDatabaseJob.java, core/src/test/java/nl/nn/adapterframework/configuration/ConfigurationTest.java, core/src/test/java/nl/nn/adapterframework/scheduler/CleanupDatabaseJobTest.java
(cherry picked from commit 298bba60a9e93f3f220c1bd7f63b28dacdcf9e0f)
=> Backport 7.8 Fix NPE getting scheduled jobs from inactive configuration (#4363)

core/src/main/java/nl/nn/adapterframework/pipes/AbstractPipe.java, test/src/main/configurations/MainConfig/ConfigurationExits.xml, test/src/test/testtool/Exits/xmlif/out01.txt, test/src/test/testtool/Exits/xmlif/scenario01.properties
=> When searching forward find exit too (7.8) partial backport of #3727

core/src/main/java/nl/nn/adapterframework/configuration/digester/DigesterRuleBase.java, core/src/main/java/nl/nn/adapterframework/configuration/digester/ValidateAttributeRule.java, core/src/test/java/nl/nn/adapterframework/configuration/digester/ValidateAttributeRuleTest.java
(cherry picked from commit 833ebfaf0541e0979750b1121e30331cc5450ef7)
=> Backport 7.8 Fix suppression of default attribute warnings (#4389)

cmis/pom.xml, core/pom.xml, core/src/main/java/nl/nn/adapterframework/webcontrol/api/Base.java, core/src/test/java/nl/nn/adapterframework/webcontrol/api/ApiTestBaseTest.java, core/src/test/java/nl/nn/adapterframework/webcontrol/api/TestPipelineTest.java, pom.xml
Backport of #3426 and partial backport of #3066
=> Upgrade CXF

copyrightExcludeFile.txt, core/src/main/java/nl/nn/adapterframework/receivers/Receiver.java, core/src/main/java/nl/nn/adapterframework/task/TimeoutGuard.java, core/src/main/java/nl/nn/adapterframework/unmanaged/PollGuard.java, core/src/main/java/nl/nn/adapterframework/unmanaged/SpringJmsConnector.java, core/src/test/java/nl/nn/adapterframework/receivers/ReceiverTest.java, core/src/test/java/nl/nn/adapterframework/receivers/SlowListenerBase.java, core/src/test/java/nl/nn/adapterframework/receivers/SlowListenerWithPollGuard.java, core/src/test/java/nl/nn/adapterframework/receivers/SlowPullingListener.java, core/src/test/java/nl/nn/adapterframework/receivers/SlowPushingListener.java
PR against 7.7 release branch to add more logging and some tests to observe behaviour.
Written against 7.7 because that's the version used for report of the issue, so the most likely to get deployed for more testing, I expect?
=> Issues/4276 timeout guards extra logging (7.7)

core/src/main/java/nl/nn/adapterframework/filesystem/ConnectedFileSystemBase.java, core/src/main/java/nl/nn/adapterframework/filesystem/ExchangeFileSystem.java, core/src/main/java/nl/nn/adapterframework/filesystem/FileSystemListener.java, core/src/main/java/nl/nn/adapterframework/receivers/ExchangeMailListener.java, core/src/main/java/nl/nn/adapterframework/receivers/PullingListenerContainer.java
Add debug logging to get more info on what is going on before the exception happens.
PR against 7.8 branch first since that was the version used for testing.
=> Add debug logging for Exchange handling (7.8)

docker/appserver/JBoss/src/configuration/standalone.xml, docker/appserver/WildFly/src/configuration/standalone.xml, test/src/main/webapp/META-INF/context.xml
Create a variable for the jdbc. So the user can change it from the default: host.docker.internal
=> Change parameters in context.xml and standalone.xml

core/src/main/java/nl/nn/adapterframework/filesystem/ConnectedFileSystemBase.java, core/src/main/java/nl/nn/adapterframework/filesystem/ExchangeFileSystem.java, core/src/main/java/nl/nn/adapterframework/filesystem/FileSystemListener.java, core/src/main/java/nl/nn/adapterframework/receivers/ExchangeMailListener.java, core/src/main/java/nl/nn/adapterframework/receivers/PullingListenerContainer.java
Port from 7.8 to master of extra debug logging for Exchange Mail handling issues.
=> Add debug logging for Exchange handling

core/src/main/java/nl/nn/adapterframework/receivers/Receiver.java, core/src/main/java/nl/nn/adapterframework/task/TimeoutGuard.java, core/src/main/java/nl/nn/adapterframework/unmanaged/PollGuard.java, core/src/main/java/nl/nn/adapterframework/unmanaged/SpringJmsConnector.java, core/src/test/java/nl/nn/adapterframework/receivers/ReceiverTest.java, core/src/test/java/nl/nn/adapterframework/receivers/SlowListenerBase.java, core/src/test/java/nl/nn/adapterframework/receivers/SlowListenerWithPollGuard.java, core/src/test/java/nl/nn/adapterframework/receivers/SlowPullingListener.java, core/src/test/java/nl/nn/adapterframework/receivers/SlowPushingListener.java
Port extra logging for timeout guards from 7.7 branch to Master.
=> Pollguard / TimeoutGuard extra logging (master)

ear/src/main/application/META-INF/was.policy
=> Update was.policy for accessClassInPackage.sun.reflect.annotation

core/src/main/java/nl/nn/adapterframework/filesystem/ConnectedFileSystemBase.java, core/src/main/java/nl/nn/adapterframework/filesystem/ExchangeFileSystem.java
Issue 4328 - Update logging for exchange mail handling now that we have somewhat better insight into cause of the problem.
=> Updated logging for Exchange handling

core/src/main/java/nl/nn/adapterframework/receivers/Receiver.java, core/src/main/java/nl/nn/adapterframework/task/TimeoutGuard.java, core/src/main/java/nl/nn/adapterframework/unmanaged/PollGuard.java, core/src/main/java/nl/nn/adapterframework/unmanaged/SpringJmsConnector.java, core/src/test/java/nl/nn/adapterframework/receivers/ReceiverTest.java, core/src/test/java/nl/nn/adapterframework/receivers/SlowListenerBase.java, core/src/test/java/nl/nn/adapterframework/receivers/SlowListenerWithPollGuard.java, core/src/test/java/nl/nn/adapterframework/receivers/SlowPullingListener.java, core/src/test/java/nl/nn/adapterframework/receivers/SlowPushingListener.java
7.8 port of the extra logging for PollGuard and TimeoutGuard "Adapter Stopped" issue.
=> TimeoutGuard extra logging (7.8)

core/src/main/java/nl/nn/adapterframework/filesystem/ConnectedFileSystemBase.java, core/src/main/java/nl/nn/adapterframework/filesystem/ExchangeFileSystem.java
(cherry picked from commit 83045f7951c2e99a486d2f52c6742b2f6e8ef408)
=> 7.8 Backport Update logging for Exchange handling (#4421)

core/src/test/java/nl/nn/adapterframework/receivers/ReceiverTest.java
=> 4276 Fix intermittent timing issue with tests.

core/src/main/java/nl/nn/adapterframework/filesystem/ExchangeAttachmentReference.java, core/src/main/java/nl/nn/adapterframework/filesystem/ExchangeFileSystem.java, core/src/main/java/nl/nn/adapterframework/filesystem/ExchangeMessageReference.java, core/src/main/java/nl/nn/adapterframework/filesystem/ExchangeObjectReference.java, core/src/main/java/nl/nn/adapterframework/filesystem/FileSystemListener.java, core/src/main/java/nl/nn/adapterframework/receivers/ExchangeMailListener.java, core/src/main/java/nl/nn/adapterframework/senders/ExchangeFolderSender.java, test-integration/pom.xml, test-integration/src/test/java/nl/nn/adapterframework/filesystem/ExchangeFileSystemTest.java, test-integration/src/test/java/nl/nn/adapterframework/filesystem/ExchangeMailListenerTest.java, test-integration/src/test/java/nl/nn/adapterframework/filesystem/ExchangeMailListenerTestBase.java, test-integration/src/test/java/nl/nn/adapterframework/filesystem/ImapFileSystemTest.java, test-integration/src/test/java/nl/nn/adapterframework/filesystem/MailFileSystemTestBase.java
(cherry picked from commit 90e9328c9bd0d1c78d4745cbf378a468b5286bd8)
=> (Backport 7.8) Add mailbox reference to mail-messages (#4457)

core/src/main/java/nl/nn/adapterframework/util/AppConstants.java, core/src/test/java/nl/nn/adapterframework/pipes/XmlValidatorTest.java, core/src/test/java/nl/nn/adapterframework/util/AppConstantsTest.java, core/src/test/resources/AppConstants/AppConstants.properties, core/src/test/resources/Validation/ImportInclude/root-err.xml, core/src/test/resources/Validation/ImportInclude/root-ok.xml, core/src/test/resources/Validation/ImportInclude/xsd/root.xsd, core/src/test/resources/Validation/ImportInclude/xsd/root2.xsd, core/src/test/resources/Validation/ImportInclude/xsd/root3.xsd, core/src/test/resources/Validation/ImportInclude/xsd/root4.xsd, core/src/test/resources/Validation/ImportInclude/xsd/sub01.xsd, core/src/test/resources/Validation/ImportInclude/xsd/sub01a.xsd, core/src/test/resources/Validation/ImportInclude/xsd/sub02.xsd, core/src/test/resources/Validation/ImportInclude/xsd/sub03.xsd, core/src/test/resources/Validation/ImportInclude/xsd/sub04.xsd, core/src/test/resources/Validation/ImportInclude/xsd/sub05.xsd, larva/src/main/java/nl/nn/adapterframework/testtool/TestTool.java
=> AppConstants doesn't use correct file encoding (7.7)

core/src/main/java/nl/nn/adapterframework/util/AppConstants.java, core/src/test/java/nl/nn/adapterframework/util/AppConstantsTest.java, core/src/test/resources/AppConstants/AppConstants.properties, larva/src/main/java/nl/nn/adapterframework/testtool/TestTool.java
=> AppConstants doesn't use correct file encoding (7.8)

core/src/main/java/nl/nn/adapterframework/configuration/AdapterManager.java, core/src/main/java/nl/nn/adapterframework/core/Adapter.java
(cherry picked from commit c108cb4b61c70b7bc3f30de5be16a742f133f77a)
=> Fix recursive invocation of logger (#4515)

core/src/main/java/nl/nn/adapterframework/filesystem/ExchangeFileSystem.java
=> Add token refresh to ExchangeMailListener

core/pom.xml, core/src/main/java/nl/nn/adapterframework/jms/JmsMessagingSourceFactory.java, core/src/main/java/nl/nn/adapterframework/jndi/JndiConnectionFactoryFactory.java, core/src/main/java/nl/nn/adapterframework/jndi/JndiDataSourceFactory.java, core/src/main/java/nl/nn/adapterframework/jndi/ObjectFactoryBase.java, core/src/main/java/nl/nn/adapterframework/jta/btm/BtmConnectionFactoryFactory.java, core/src/main/java/nl/nn/adapterframework/jta/btm/BtmDataSourceFactory.java, core/src/main/java/nl/nn/adapterframework/jta/narayana/NarayanaConnectionFactoryFactory.java, core/src/main/java/nl/nn/adapterframework/jta/narayana/NarayanaDataSource.java, core/src/main/java/nl/nn/adapterframework/jta/narayana/NarayanaDataSourceFactory.java, core/src/main/java/nl/nn/adapterframework/jta/narayana/NarayanaJtaTransactionManager.java, core/src/main/java/nl/nn/adapterframework/jta/narayana/NarayanaTransactionHelper.java, core/src/main/resources/AppConstants.properties, core/src/main/resources/springTOMCATBTM.xml, core/src/main/resources/springTOMCATNARAYANA.xml, core/src/test/java/nl/nn/adapterframework/jta/btm/BtmConnectionFactoryFactoryTest.java, core/src/test/java/nl/nn/adapterframework/jta/btm/BtmDataSourceFactoryTest.java, core/src/test/java/nl/nn/adapterframework/jta/narayana/NarayanaConnectionFactoryFactoryTest.java, core/src/test/java/nl/nn/adapterframework/jta/narayana/NarayanaDataSourceFactoryTest.java, core/src/test/java/nl/nn/adapterframework/jta/narayana/NarayanaTransactionHelperTest.java, ibm/src/test/java/nl/nn/adapterframework/extensions/ibm/IMSSenderTest.java, ibm/src/test/java/nl/nn/adapterframework/extensions/ibm/TestJMSMessage.java, test/pom.xml, test/src/main/configurations/JMS/Configuration.xml, test/src/main/configurations/JMS/TestHighDeliveryCountWithEsbJmsListener.xml, test/src/main/java/nl/nn/adapterframework/listeners/CustomHighDeliveryCountEsbJmsListener.java
Backport of #4521, #4517 and #4513
=> Backport Narayana pooling and default transaction timeouts

test/src/test/testtool/XmlParsers/expectedParsers.xml
Fixes test that failes because of the Saxon dependency upgrade #4533
=> Update Saxon version in iaf-test scenario

core/src/main/java/nl/nn/adapterframework/http/rest/ApiMemcached.java
=> Set default operation timeout for ApiMemcached to 10 seconds

.github/workflows/maven-build.yml, .mvn/wrapper/maven-wrapper.properties, copyrightExcludeFile.txt, core/src/main/java/nl/nn/adapterframework/core/Adapter.java, mvnw, mvnw.cmd
Automatic update on Github to maven 3.9.0 broke the build.
Try some ways to get this fixed.
=> Fixing build with maven 3.9.0

docker/JBoss/Dockerfile, docker/JBoss/src/configuration/createCS.sh, docker/Tomcat/webapp/Dockerfile, docker/WebSphere/src/configuration/01-configureAuthAlias.py, docker/WebSphere/src/configuration/02-configureJdbc.py, docker/WebSphere/src/configuration/03-configureJms.py, docker/WebSphere/src/configuration/04-configureJvmProperties.py, docker/WebSphere/src/configuration/05-installApp.py, docker/WildFly/src/configuration/createCS.sh
Also fixed the other issues in #4589
=> Fix `useradd` without flag `-l` and high UID will result in excessively large image

core/src/main/java/nl/nn/adapterframework/jdbc/BlobLineIteratingPipe.java, core/src/main/java/nl/nn/adapterframework/jdbc/JdbcIteratingPipeBase.java, core/src/main/java/nl/nn/adapterframework/jdbc/LobLineIteratingPipeBase.java, core/src/main/java/nl/nn/adapterframework/jdbc/ResultSetIteratingPipe.java, core/src/main/java/nl/nn/adapterframework/jdbc/ResultSetIterator.java, core/src/main/java/nl/nn/adapterframework/util/ReaderLineIterator.java, core/src/test/java/nl/nn/adapterframework/jdbc/ResultSetIteratingPipeTest.java, core/src/test/resources/Pipes/ResultSetIteratingPipe/testCompressedAndUncompressedBlob.xml
=> Add blob attributes to ResultSetIteratingPipe

core/src/main/java/nl/nn/adapterframework/jta/SpringTxManagerProxy.java, core/src/main/java/nl/nn/adapterframework/jta/btm/BtmDiskJournal.java, core/src/main/resources/springTOMCATBTM.xml, core/src/test/java/nl/nn/adapterframework/jdbc/JdbcTestBase.java, core/src/test/java/nl/nn/adapterframework/jta/btm/TestSelfRecoveringBTMDiskJournal.java
=> Attempt to recover BTM disk journal

core/src/main/java/nl/nn/adapterframework/jms/MessagingSource.java, webapp/src/main/webapp/iaf/gui/js/controllers.js, webapp/src/main/webapp/iaf/gui/js/services.js
=> Improve display of ConnectionFactory info

core/src/main/java/nl/nn/adapterframework/jta/btm/BtmDiskJournal.java
=> Attempt to reopen BtmDiskJournal

.github/workflows/codeql-analysis.yml, .github/workflows/maven-build.yml, console/src/main/java/nl/nn/adapterframework/management/web/TestPipeline.java, console/src/test/java/nl/nn/adapterframework/management/web/TestPipelineTest.java
Ik ben de overige `sendSyncMessage(input)` nagelopen, daar speelt dit niet.
=> Update github actions + Fix test-pipeline binary responses

core/src/main/java/nl/nn/adapterframework/jta/btm/BtmDataSourceFactory.java, core/src/test/java/nl/nn/adapterframework/jta/btm/BtmDataSourceFactoryTest.java
(cherry picked from commit 9810803a3899e87b55dbb7e8770173d0e882fe34)
=> Add isValid check to BTM pooled connections

core/src/main/java/nl/nn/adapterframework/jdbc/JdbcListener.java, core/src/main/java/nl/nn/adapterframework/jdbc/MessageStoreListener.java, core/src/main/java/nl/nn/adapterframework/receivers/Receiver.java, core/src/test/java/nl/nn/adapterframework/receivers/ReceiverTest.java
Ugly fixes and ugly test-mocks for ugly code.
=> Workaround for bug that manual retry does not extract msg from CSV row

docker/WebSphere/Dockerfile
I ran the tests and they came out positive.
=> Update the base image of WebSphere for FF!Test

core/src/main/java/nl/nn/adapterframework/receivers/Receiver.java, core/src/main/resources/digester-rules.xml
This functionality has been deprecated for over 11 years. I think it's time to clean up some code in the Receiver class..
=> Remove inProcessStorage

core/src/main/java/nl/nn/adapterframework/align/AlignmentContext.java, core/src/main/java/nl/nn/adapterframework/align/Json2Xml.java, core/src/main/java/nl/nn/adapterframework/align/OverridesMap.java, core/src/main/java/nl/nn/adapterframework/align/Properties2Xml.java, core/src/main/java/nl/nn/adapterframework/align/XmlAligner.java, core/src/main/java/nl/nn/adapterframework/pipes/Json2XmlValidator.java, core/src/main/java/nl/nn/adapterframework/validation/AbstractXmlValidator.java, core/src/test/java/nl/nn/adapterframework/align/OverridesMapTest.java, core/src/test/java/nl/nn/adapterframework/align/TestJson2Xml.java, core/src/test/java/nl/nn/adapterframework/pipes/Json2XmlValidatorTest.java, core/src/test/resources/Align/TextAndAttributes/input-compact.json, core/src/test/resources/Align/TextAndAttributes/input-full.json, core/src/test/resources/Align/TextAndAttributes/input.properties, core/src/test/resources/Align/TextAndAttributes/input.xml, core/src/test/resources/Align/TextAndAttributes/schema-compact-Root.jsd, core/src/test/resources/Align/TextAndAttributes/schema-full-Root.jsd, core/src/test/resources/Align/TextAndAttributes/schema.xsd
=> Fix Attributes on RootElements in Json2XmlValidator

core/src/main/java/nl/nn/adapterframework/core/IMessageHandler.java, core/src/main/java/nl/nn/adapterframework/extensions/mqtt/MqttListener.java, core/src/main/java/nl/nn/adapterframework/receivers/Receiver.java, core/src/test/java/nl/nn/adapterframework/http/rest/ApiListenerServletTest.java, larva/src/main/java/nl/nn/adapterframework/testtool/ListenerMessageHandler.java, sap/src/main/java/nl/nn/adapterframework/extensions/sap/jco3/SapListenerImpl.java
NB: It is unfortunately really hard to test this as there's no SAP environment from which to actually use the SAP Listener.
How much of an effort do we want to put into mocking that?
=> SapListenerImpl would trigger NPE in Receiver

core/src/main/java/nl/nn/adapterframework/core/RequestReplyExecutor.java, core/src/main/java/nl/nn/adapterframework/pipes/IsolatedServiceExecutor.java, core/src/main/java/nl/nn/adapterframework/senders/IbisLocalSender.java, core/src/main/java/nl/nn/adapterframework/stream/StreamingPipe.java, core/src/main/java/nl/nn/adapterframework/stream/ThreadConnector.java, core/src/test/java/nl/nn/adapterframework/filesystem/FileSystemPipeTest.java, ladybug/src/main/java/nl/nn/ibistesttool/IbisDebuggerAdvice.java, test/src/main/configurations/MainConfig/ConfigurationCompareStringPipe.xml
* Only return output-stream if streaming actually active.
* Fix for LadyBug reports nog closing when called an adapter in Isolated thread.
=> Fix for Ladybug Report not being closed with IbisLocalSender "Isolated" option

aspose/src/main/java/nl/nn/adapterframework/extensions/aspose/AsposeFontManager.java, aspose/src/main/java/nl/nn/adapterframework/extensions/aspose/pipe/PdfPipe.java, cmis/src/main/java/nl/nn/adapterframework/extensions/cmis/server/RepositoryConnectorFactory.java, core/src/main/java/nl/nn/adapterframework/extensions/esb/WsdlGeneratorPipe.java, core/src/main/java/nl/nn/adapterframework/extensions/javascript/J2V8.java, core/src/main/java/nl/nn/adapterframework/filesystem/FileSystemActor.java, core/src/main/java/nl/nn/adapterframework/pipes/UnzipPipe.java, core/src/main/java/nl/nn/adapterframework/util/FileHandler.java, core/src/main/java/nl/nn/adapterframework/util/FileUtils.java, core/src/test/java/nl/nn/adapterframework/pipes/CompressPipeTest.java, core/src/test/java/nl/nn/adapterframework/pipes/UnzipPipeTest.java, core/src/test/java/nl/nn/adapterframework/util/FileUtilsTest.java, larva/src/main/java/nl/nn/adapterframework/testtool/TestTool.java
Prerequisite for implementation of issue #4759
=> Backport of improvements to temporary file handling

core/src/main/java/nl/nn/adapterframework/filesystem/ImapFileSystem.java, core/src/main/java/nl/nn/adapterframework/stream/FileMessage.java, core/src/main/java/nl/nn/adapterframework/stream/Message.java, core/src/main/java/nl/nn/adapterframework/stream/MessageContext.java, core/src/main/java/nl/nn/adapterframework/stream/PathMessage.java, core/src/main/java/nl/nn/adapterframework/stream/SerializableFileReference.java, core/src/main/java/nl/nn/adapterframework/util/AppConstants.java, core/src/main/java/nl/nn/adapterframework/util/FileUtils.java, core/src/main/resources/AppConstants.properties, core/src/test/java/nl/nn/adapterframework/stream/FileMessageTest.java, core/src/test/java/nl/nn/adapterframework/stream/MessageTest.java, core/src/test/java/nl/nn/adapterframework/stream/SerializableFileReferenceTest.java, core/src/test/java/nl/nn/adapterframework/testutil/SerializationTester.java, iaf-commons/src/main/java/nl/nn/adapterframework/util/StreamUtil.java
=> Preserve large messages to disk (#4759)

core/src/main/java/nl/nn/adapterframework/core/PipeLineSession.java, core/src/main/java/nl/nn/adapterframework/http/cxf/SOAPProviderBase.java, core/src/main/java/nl/nn/adapterframework/http/cxf/SourceClosingDataHandler.java, core/src/main/java/nl/nn/adapterframework/stream/Message.java, core/src/main/java/nl/nn/adapterframework/util/MessageDataSource.java
=> Call close after writeTo has been called

core/src/main/java/nl/nn/adapterframework/core/PipeLine.java, core/src/test/java/nl/nn/adapterframework/core/PipeLineTest.java
=> Fix selection of default pipeline exit

core/src/main/java/nl/nn/adapterframework/core/PipeLine.java, core/src/test/java/nl/nn/adapterframework/core/PipeLineTest.java
Fixes a bug introduced in #2851
=> Fix selection of default pipeline exit (#4989)

aws/src/main/java/nl/nn/adapterframework/filesystem/AmazonS3FileSystem.java, core/src/main/java/nl/nn/adapterframework/compression/ZipWriter.java, core/src/main/java/nl/nn/adapterframework/filesystem/Samba1FileSystem.java, core/src/main/java/nl/nn/adapterframework/filesystem/Samba2FileSystem.java, core/src/main/java/nl/nn/adapterframework/stream/Message.java, core/src/main/java/nl/nn/adapterframework/stream/MessageContext.java, core/src/main/java/nl/nn/adapterframework/stream/PathMessage.java, core/src/main/java/nl/nn/adapterframework/util/MessageUtils.java
Ik zag in #4978 wat context dingen voorkomen en dacht laat ik maar gelijk een eerste stap maken..
=> Make Message return a MessageContext object

console/frontend/src/main/frontend/js/app/components/input-file-upload/input-file-upload.component.js, console/frontend/src/main/frontend/js/app/views/configuration/configurations-upload/ManageConfigurationsUpload.html, console/frontend/src/main/frontend/js/app/views/configuration/configurations-upload/configurations-upload.controller.js, console/frontend/src/main/frontend/js/app/views/jms/jms-send-message/SendJmsMessage.html, console/frontend/src/main/frontend/js/app/views/jms/jms-send-message/jms-send-message.controller.js, console/frontend/src/main/frontend/js/app/views/liquibase/ShowLiquibaseScript.html, console/frontend/src/main/frontend/js/app/views/liquibase/liquibase.controller.js, console/frontend/src/main/frontend/js/app/views/test-pipeline/TestPipeline.html, console/frontend/src/main/frontend/js/app/views/test-pipeline/test-pipeline.controller.js, console/frontend/src/main/frontend/js/app/views/test-service-listener/TestServiceListener.html, console/frontend/src/main/frontend/js/app/views/test-service-listener/test-service-listener.controller.js
All controllers now properly use input-file-upload component
=> fix input-file-upload usages

core/src/main/java/nl/nn/adapterframework/jta/btm/BtmDiskJournal.java
(cherry picked from commit 1835862fcad7860dc81817d78d17728f11dbb9be)
=> Fix review comments

core/src/main/java/nl/nn/adapterframework/jta/btm/BtmDiskJournal.java
=> Limit amount of BTM DiskJournal retries

core/src/main/java/nl/nn/adapterframework/core/PipeLineSession.java, core/src/main/java/nl/nn/adapterframework/http/rest/ApiListener.java, core/src/main/java/nl/nn/adapterframework/receivers/JavaListener.java, core/src/main/java/nl/nn/adapterframework/receivers/Receiver.java, core/src/main/java/nl/nn/adapterframework/receivers/ServiceClient.java, core/src/main/java/nl/nn/adapterframework/senders/IbisLocalSender.java, core/src/test/java/nl/nn/adapterframework/receivers/JavaListenerTest.java, core/src/test/java/nl/nn/adapterframework/senders/IbisLocalSenderTest.java
Copy message-id from input-session into the RawMessageWrapper of the sub-adapter.
=> Copy session into new session created for the sub-adapter call

console/frontend/src/main/frontend/js/app/views/status/status.component.html
https://jenkins.interpar.nl/job/IAF-GUI-Protractor/1608/consoleFull
other issues are mostly related to protractor trying to work but failing with the new angularjs component views
=> fix protractor found issues

docker/Tomcat/test/Dockerfile, docker/Tomcat/webapp/Dockerfile
This is to pass CIS Benchmarks
=> Secure files and add healthcheck to Dockerfile to pass CIS Benchmarks

core/src/main/java/nl/nn/adapterframework/http/rest/ApiListener.java, core/src/main/java/nl/nn/adapterframework/http/rest/ApiListenerServlet.java, core/src/test/java/nl/nn/adapterframework/http/rest/ApiListenerServletTest.java
=> Configurable header to extract jwt from

core/src/main/java/nl/nn/adapterframework/http/rest/ApiListener.java, core/src/main/java/nl/nn/adapterframework/http/rest/ApiListenerServlet.java, core/src/test/java/nl/nn/adapterframework/http/rest/ApiListenerServletTest.java
=> Configurable header to extract jwt from (7.8)

core/src/main/java/nl/nn/adapterframework/http/RestListenerServlet.java, core/src/main/java/nl/nn/adapterframework/management/bus/endpoints/Monitoring.java, core/src/main/java/nl/nn/adapterframework/monitoring/MonitorDestinationBase.java, core/src/main/java/nl/nn/adapterframework/monitoring/MonitorManager.java, core/src/main/java/nl/nn/adapterframework/monitoring/SenderMonitorAdapter.java, core/src/test/java/nl/nn/adapterframework/monitoring/MonitorTest.java, core/src/test/java/nl/nn/adapterframework/monitoring/SenderMonitorAdapterTest.java, core/src/test/resources/Management/Monitoring/getManagerToXML.xml, core/src/test/resources/Management/Monitoring/getMonitors.json, core/src/test/resources/Management/Monitoring/getMonitors.xml, core/src/test/resources/testMonitoringContext.xml
Add ALL_IBIS_ROLES to RestListener endpoint
Create end2end monitoring test
=> Add RestListener authroles and monitor test

core/src/main/java/nl/nn/adapterframework/pipes/CompressPipe.java, core/src/test/java/nl/nn/adapterframework/pipes/CompressPipeTest.java
=> Fix CompressPipe not closing streams

core/src/main/java/nl/nn/adapterframework/pipes/Json2XmlValidator.java, core/src/test/java/nl/nn/adapterframework/pipes/Json2XmlValidatorTest.java
Feature introduced in https://github.com/ibissource/iaf/pull/4314 not taking into effect the accept header can be */* or contain multiple values.
Backport of #5126
=> Fix Json2XmlValidator response type parsing (7.8)

core/src/main/java/nl/nn/adapterframework/core/Adapter.java
Enables https://github.com/Laurens-makel/frank-otel-instrumentation/issues/42 
If approved, I will make a PR for master as well.
=> Introduce getter method for msgLogLevel (7.8)

core/src/main/java/nl/nn/adapterframework/http/rest/ApiListener.java, core/src/main/java/nl/nn/adapterframework/http/rest/ApiListenerServlet.java, core/src/main/java/nl/nn/adapterframework/jwt/JwtSecurityHandler.java
=> Backport JWT principal claim name to 7.8

sap/src/main/java/nl/nn/adapterframework/extensions/sap/jco3/SapListenerImpl.java
Partial fix which was also applied to the master in 6b4d02b93b58daa27193f2abd25479c958b2ef0d.
=> Add session to SapListeners

core/pom.xml, core/src/main/java/nl/nn/adapterframework/jms/JmsMessagingSource.java, core/src/main/java/nl/nn/adapterframework/jms/JmsMessagingSourceFactory.java, core/src/main/java/nl/nn/adapterframework/jms/MessagingSource.java, core/src/main/java/nl/nn/adapterframework/jta/btm/BtmDataSourceFactory.java, core/src/main/java/nl/nn/adapterframework/jta/narayana/NarayanaConnectionFactoryFactory.java, core/src/main/java/nl/nn/adapterframework/jta/narayana/NarayanaDataSource.java, core/src/main/java/nl/nn/adapterframework/jta/narayana/NarayanaDataSourceFactory.java, core/src/main/java/nl/nn/adapterframework/receivers/PullingListenerContainer.java, core/src/main/resources/AppConstants.properties, core/src/test/java/nl/nn/adapterframework/jdbc/JdbcTestBase.java, core/src/test/java/nl/nn/adapterframework/testutil/NarayanaXADataSourceFactory.java
Also cleaned up some code as stated in #4390
Supersedes #4572
=> Add more JDBC and JMS pooling

core/src/main/java/nl/nn/adapterframework/jwt/JwtSecurityHandler.java
=> Prevent runtime type exceptions and check lists for JWT role claim

core/src/main/java/nl/nn/adapterframework/jwt/JwtSecurityHandler.java
closes https://github.com/ibissource/iaf/issues/5139
=> Prevent runtime type exceptions and check lists for JWT role claim (7.8)

docker/appserver/JBoss/src/configuration/standalone.xml, docker/appserver/WebSphere/src/scripts/configureJdbc.py, docker/appserver/WildFly/src/configuration/standalone.xml, test/src/main/webapp/META-INF/context.xml
=> MariaDB support using MariaDB native driver instead of MySQL

core/src/main/java/nl/nn/adapterframework/lifecycle/WebContentServlet.java, docker/appserver/WebSphere/src/scripts/configureJdbc.py, docker/appserver/WebSphere/src/scripts/configureJvmProperties.py, docker/appserver/WebSphere/src/scripts/wasap.policy, ear/src/main/application/META-INF/was.policy, larva/src/main/java/nl/nn/adapterframework/testtool/LarvaServlet.java
Secure Larva and WebContent servlets
Fix MariaDB URL
Fix WebSphere dtap.stage
=> Update WAS policy files

core/src/main/java/nl/nn/adapterframework/jta/narayana/NarayanaDataSource.java, core/src/main/java/nl/nn/adapterframework/jta/narayana/NarayanaDataSourceFactory.java, core/src/test/java/nl/nn/adapterframework/jdbc/FixedQuerySenderTest.java, core/src/test/java/nl/nn/adapterframework/jdbc/JdbcTestBase.java, core/src/test/java/nl/nn/adapterframework/jdbc/TransactionManagerTest.java, core/src/test/java/nl/nn/adapterframework/jdbc/TransactionManagerTestBase.java, core/src/test/java/nl/nn/adapterframework/jdbc/migration/MigratorTest.java, core/src/test/java/nl/nn/adapterframework/jta/StatusRecordingTransactionManagerTest.java, core/src/test/java/nl/nn/adapterframework/jta/TransactionConnectorTest.java, core/src/test/java/nl/nn/adapterframework/jta/btm/TestSelfRecoveringBTMDiskJournal.java, core/src/test/java/nl/nn/adapterframework/testutil/BTMXADataSourceFactory.java, core/src/test/java/nl/nn/adapterframework/testutil/NarayanaXADataSourceFactory.java, core/src/test/java/nl/nn/adapterframework/testutil/TransactionManagerType.java, core/src/test/java/nl/nn/adapterframework/testutil/URLXADataSourceFactory.java, core/src/test/java/nl/nn/adapterframework/util/LockerTest.java, core/src/test/java/nl/nn/adapterframework/util/MessageBrowsingFilterTest.java, core/src/test/resources/AppConstants.properties, pom.xml
Improve stability of various JTA / JDBC tests and fixes to creation of XA data sources.
=> XA DataSource creation fix

CONTRIBUTING.md, README.md
Added some info and links to make the available info in md files better available
Will close #5234
=> Jjansenvr link md files

core/src/main/java/nl/nn/adapterframework/filesystem/AmazonS3FileSystem.java, core/src/main/java/nl/nn/adapterframework/senders/AmazonS3Sender.java
closes #5233
@nielsm5 Ik heb wat setters op de s3 sender toegevoegd, volgens mij ontbreken deze in #5068
=> Backport StorageClass attribute to 7.8 release

core/src/main/java/nl/nn/adapterframework/processors/ExceptionHandlingPipeProcessor.java, core/src/main/java/nl/nn/adapterframework/processors/InputOutputPipeProcessor.java, core/src/main/java/nl/nn/adapterframework/senders/IbisLocalSender.java, core/src/test/java/nl/nn/adapterframework/processors/InputOutputPipeProcessorTest.java, core/src/test/java/nl/nn/adapterframework/senders/IbisLocalSenderTest.java, ladybug/src/main/java/nl/nn/ibistesttool/Debugger.java, ladybug/src/main/java/nl/nn/ibistesttool/PipeLineSessionDebugger.java
Minor code cleanups that I did while investigating SessionKey-closed issue but that I want to keep separate from the fixes for that.
=> Miscellaneous minor code cleanups

core/src/main/java/nl/nn/adapterframework/jdbc/FixedQuerySender.java, core/src/test/java/nl/nn/adapterframework/jdbc/FixedQuerySenderTest.java
(cherry picked from commit 9cc29944bb436c9a4cef09f67a1377539d74da64)
=> Fix detection of named parameters

core/src/main/java/nl/nn/adapterframework/http/cxf/SOAPProviderBase.java
(cherry picked from commit 02c45fedc846f752d7eccd3f3645fab9f743ed15)
=> Add ContentDisposition header to WSS responses

core/src/main/java/nl/nn/adapterframework/http/rest/ApiListenerServlet.java, core/src/main/java/nl/nn/adapterframework/util/MessageUtils.java
=> Create 1 Tika config and catch InvalidMimeTypeExceptions (7.8)

akamai/pom.xml, aspose/pom.xml, cmis/pom.xml, core/pom.xml, core/src/main/java/nl/nn/adapterframework/scheduler/job/SendMessageJob.java, core/src/test/java/nl/nn/adapterframework/scheduler/job/SendMessageJobTest.java, credentialProvider/pom.xml, ibm/pom.xml, idin/pom.xml, ladybug/pom.xml, larva/pom.xml, pom.xml, test-integration/pom.xml
(cherry picked from commit 6901bf9f2bbb352a4a3d8d376f4575ed0f4cc89b)
=> Fix Job response not read and closed (#5340) - backport

CONTRIBUTING.md, Docker.md, README.md, console/frontend/src/main/frontend/js/app/views/login/login.component.html, core/src/test/java/nl/nn/adapterframework/filesystem/SftpFileSystemSenderTest.java, core/src/test/java/nl/nn/adapterframework/filesystem/SftpFileSystemTest.java, docker/Tomcat/example/Dockerfile, docker/Tomcat/test/Dockerfile, docker/Tomcat/webapp/pom.xml, example/src/main/resources/ManualExerciseMundo/input.xsd, example/src/test/resources/TestTool/ManualExerciseMundo/invalidBodyNotBase64.xml, example/src/test/resources/TestTool/ManualExerciseMundo/invalidNoDisplayName.xml, example/src/test/resources/TestTool/ManualExerciseMundo/valid.xml, example/src/test/resources/TestTool/ManualExerciseMundo/validNoCC.xml, pom.xml
I also fixed some typos and renamed the Docker image.
=> Remove mentions of WeAreFrank!

docker/Tomcat/example/Dockerfile, docker/Tomcat/test/Dockerfile, docker/Tomcat/webapp/pom.xml
Changed `frank-framework` to `frankframework`
=> Backport changing the Docker name to `frankframework`

core/src/main/java/nl/nn/adapterframework/util/CompactSaxHandler.java, core/src/test/java/nl/nn/adapterframework/util/CompactSaxHandlerTest.java, core/src/test/resources/Util/CompactSaxHandler/input.xml, core/src/test/resources/Util/CompactSaxHandler/output.xml
=> CompactSaxHandler: removeCompactMsgNamespaces does not work

console/frontend/src/main/frontend/js/app/components/custom-views/custom-views.component.js
=> Frontend custom views fix

core/src/main/java/nl/nn/adapterframework/soap/SoapWrapperPipe.java, core/src/test/java/nl/nn/adapterframework/pipes/SoapWrapperPipeTest.java
Same as https://github.com/ibissource/iaf/pull/5417 but now with only one fresh commit
=> Use SOAP namespace from soapVersion pipe configuration if set (#5207)

aspose/pom.xml, credentialProvider/pom.xml, iaf-commons/pom.xml, idin/pom.xml, pom.xml, test-integration/pom.xml, test/pom.xml
Nothing to do with Java 11, so should be fine to merge 😉
=> Generic pom.xml cleanups

aspose/pom.xml, idin/pom.xml, pom.xml
Backport Maven improvements: 
1. Maven Central first
2. security enforcement
3. set Java version once
4. fix wrong Mockito
=> Backport Maven improvements

core/src/main/java/nl/nn/adapterframework/receivers/JavaListener.java, core/src/main/java/nl/nn/adapterframework/senders/IbisLocalSender.java, test/src/main/configurations/MainConfig/ConfigurationReturnedSessionKeys.xml, test/src/test/testtool/ReturnedSessionKeys/scenario05.properties, test/src/test/testtool/ReturnedSessionKeys/scenario05/out.xml
=> Ensure the original message wont be closed when using an IbisLocalSender

core/src/main/java/nl/nn/adapterframework/logging/IbisLoggerConfigurationFactory.java, core/src/test/java/nl/nn/adapterframework/extensions/fxf/FxfWrapperPipeTest.java, core/src/test/java/nl/nn/adapterframework/logging/IbisLoggerConfigurationFactoryTest.java, core/src/test/resources/DeploymentSpecifics.properties
Fix the regex for log configuration properties so that it handles the defaults in logfiles.
=> Fix default values in log configuration

core/src/main/java/nl/nn/adapterframework/pipes/Json2XmlValidator.java, core/src/main/java/nl/nn/adapterframework/util/Misc.java, core/src/test/java/nl/nn/adapterframework/pipes/Json2XmlValidatorTest.java
=> Read entire Accept header and filter on XML and JSON

core/src/main/java/nl/nn/adapterframework/webcontrol/api/CompatibilityShowScheduler.java, core/src/main/java/nl/nn/adapterframework/webcontrol/api/DeprecationFilter.java, core/src/main/java/nl/nn/adapterframework/webcontrol/api/ShowScheduler.java, core/src/main/java/nl/nn/adapterframework/webcontrol/api/ShowSchedulerBase.java, core/src/test/java/nl/nn/adapterframework/webcontrol/api/TestDeprecationFilter.java
Backport of  #5576 (fcd050d4abc3a43e04aa7f0382abdfe128615d21)
=> Fix CXF duplicate endpoints errors

console/frontend/src/main/frontend/js/app/views/storage/storage-list/storage-list.component.js
=> console storage properly initialize resend & delete message functions

iaf-commons/pom.xml, iaf-commons/src/main/java/nl/nn/adapterframework/core/IbisException.java, iaf-commons/src/test/java/nl/nn/adapterframework/core/IbisExceptionTest.java, management-gateway/pom.xml, management-gateway/src/main/java/nl/nn/adapterframework/management/security/JwtKeyGenerator.java, management-gateway/src/main/java/nl/nn/adapterframework/management/security/JwtSecurityFilter.java
Small changes that I needed to get these modules to work with JDK17, making it easier for me to switch between JDK11 and JDK17 and test progress of build fixes.
=> Some small preparatory changes for JDK17 support

core/pom.xml, core/src/main/java/nl/nn/adapterframework/jta/btm/BtmDiskJournal.java, core/src/main/java/nl/nn/adapterframework/jta/btm/BtmJtaTransactionManager.java, core/src/test/java/nl/nn/adapterframework/jta/btm/TestSelfRecoveringBTMDiskJournal.java, pom.xml
Surprise surprise: with small fix got BTM to work on JDK17.
Helps me to focus on what is really not working on JDK17 (SAAJ / SOAP).
=> Surprise: Fix BTM with JDK17

docker/JBoss/Dockerfile, docker/JBoss/src/configuration/configuration.py, docker/JBoss/src/configuration/createCS.sh, docker/JBoss/src/configuration/standalone.xml
I couldn't upgrade further because the elytron tool didn't work in the newer versions that I tried. We need that for creating a credential store.
In the future, we could do this in an extra build step or by using the tool in the CI.
=> Upgrade the IAF-Test JBoss Docker test image to 7.4.0

docker/JBoss/src/configuration/standalone.xml, docker/WildFly/src/configuration/standalone.xml, docker/oracle-xa.yml, test/src/main/webapp/META-INF/context.xml
Added an XA variant for Oracle to match PostgreSQL and DB2.
Also changed all default hostnames to `localhost`,
=> Change test resources to fix Tomcat w/ Oracle in CI

core/src/main/java/nl/nn/adapterframework/encryption/AuthSSLContextFactory.java, core/src/main/java/nl/nn/adapterframework/http/HttpSessionBase.java, core/src/test/java/nl/nn/adapterframework/http/HttpSenderTest.java
(cherry picked from commit 43fd3ab19118e1eb9bc5b722f59beaccc805e4b1)
=> Add supportedCipherSuites attribute to HTTP senders

docker/JBoss/src/configuration/standalone.xml, docker/WebSphere/src/configuration/02-configureJdbc.py, docker/WildFly/src/configuration/standalone.xml, docker/oracle-xa.yml, test/src/main/webapp/META-INF/context.xml
=> Backport Oracle xa resource

core/src/main/java/nl/nn/adapterframework/http/rest/ApiListener.java, core/src/main/java/nl/nn/adapterframework/http/rest/ApiListenerServlet.java, core/src/main/java/nl/nn/adapterframework/jwt/JwtSecurityHandler.java, core/src/test/java/nl/nn/adapterframework/http/rest/ApiListenerServletTest.java
implements #5201 
open for suggestion for improvements 
open tasks:
- unit testing
=> Introduce matchOneOfClaims attribute

core/src/main/java/nl/nn/adapterframework/receivers/Receiver.java, core/src/test/java/nl/nn/adapterframework/receivers/ReceiverTest.java
Fix issue #5752 for version 7.8 (against which this was reported as production issue).
Forward-ports for 7.9 and master will come once the fix is merged.
=> Fix for StringIndexOutOfBoundsException (#5752)

core/src/main/java/nl/nn/adapterframework/soap/SoapVersion.java, core/src/main/java/nl/nn/adapterframework/soap/WsdlGeneratorUtils.java, core/src/main/java/nl/nn/adapterframework/util/MessageBrowsingFilter.java, core/src/main/java/nl/nn/adapterframework/util/flow/graphviz/GraphvizEngine.java, core/src/test/java/nl/nn/adapterframework/http/HttpResponseMock.java, core/src/test/java/nl/nn/adapterframework/http/RestSenderTest.java, core/src/test/java/nl/nn/adapterframework/http/cxf/SoapProviderTest.java, core/src/test/java/nl/nn/adapterframework/jdbc/migration/MigratorTest.java, core/src/test/java/nl/nn/adapterframework/stream/document/DocumentBuilderTest.java, core/src/test/java/nl/nn/adapterframework/util/XmlBuilderTest.java, dbms/src/main/java/nl/nn/adapterframework/dbms/GenericDbmsSupport.java, dbms/src/test/java/nl/nn/adapterframework/dbms/SqlTranslatorOracleToH2Test.java, dbms/src/test/java/nl/nn/adapterframework/dbms/SqlTranslatorOracleToMsSqlTest.java, nn-specials/src/main/java/nl/nn/adapterframework/extensions/afm/Afm2EdiFactSender.java, nn-specials/src/main/java/nl/nn/adapterframework/extensions/esb/WsdlGeneratorPipe.java
Thanks to OpenRewrite:
https://docs.openrewrite.org/recipes/staticanalysis/indexofreplaceablebycontains
https://docs.openrewrite.org/recipes/staticanalysis/usestringreplace 
2 separate commits.
=> Code Quality: String replace fixes

core/src/main/java/nl/nn/adapterframework/extensions/esb/EsbJmsListener.java, core/src/main/java/nl/nn/adapterframework/jms/BytesMessageInputStream.java, core/src/main/java/nl/nn/adapterframework/jms/JmsListener.java, core/src/main/java/nl/nn/adapterframework/jms/JmsMessageBrowserIteratorItem.java, core/src/main/java/nl/nn/adapterframework/util/JdbcUtil.java, core/src/test/java/nl/nn/adapterframework/extensions/esb/EsbJmsListenerTest.java, core/src/test/resources/AppConstants.properties, tibco/src/main/java/nl/nn/adapterframework/extensions/tibco/SendTibcoMessage.java
(cherry picked from commit ab786f342e16c689f4b681ba59ea071c6733767d)
=> Fix issue with BytesMessage not being correctly processed (#5794)

core/src/main/java/nl/nn/adapterframework/pipes/CleanupOldFilesPipe.java, core/src/main/java/nl/nn/adapterframework/pipes/MoveFilePipe.java, core/src/main/java/nl/nn/adapterframework/util/FileUtils.java, larva/src/main/java/nl/nn/adapterframework/testtool/FileListener.java
=> Minor code cleanups in FileUtils and FileListener

core/src/main/java/nl/nn/adapterframework/pipes/JwtPipe.java, core/src/main/resources/AppConstants.properties, core/src/test/java/nl/nn/adapterframework/pipes/JwtPipeTest.java
* Add right padding to fill them, when property allows it
=> Allow short JWT secrets too (#5645)

core/src/main/java/nl/nn/adapterframework/http/HttpSender.java, core/src/test/resources/Http/Responses/simpleMtomFromParametersAndMultipartXml.txt, core/src/test/resources/Http/Responses/simpleMtomFromParametersAndMultipartXmlNoPartName.txt, core/src/test/resources/Http/Responses/simpleMultipartFromParametersAndMultipartXml.txt, core/src/test/resources/Http/Responses/simpleMultipartFromParametersAndMultipartXmlNoPartName.txt
(cherry picked from commit ae1b005bda0a9ce0bbc55c53844bc5fe5b7aefac)
=> Actually implement type=file attribute when using multipartXml

core/src/main/java/nl/nn/adapterframework/compression/ZipWriterPipe.java, core/src/main/java/nl/nn/adapterframework/compression/ZipWriterSender.java, test/src/main/configurations/HTTP/ConfigurationApiListener.xml, test/src/main/configurations/HTTP/ConfigurationWebServiceListenerSenderAddress.xml, test/src/main/configurations/JDBC/ConfigurationJdbcListener.xml, test/src/main/configurations/JDBC/ConfigurationManageDatabaseWrapper.xml, test/src/main/configurations/MainConfig/ConfigurationCompactMessage.xml, test/src/main/configurations/MainConfig/ConfigurationXsltPipe.xml, test/src/main/configurations/MainConfig/ConfigurationZip.xml
(cherry picked from commit 5544b9baec35a92dc75330bf7ee7b047ac30386e)
=> Remove default values from Larva test configurations

core/src/main/java/nl/nn/adapterframework/jdbc/StoredProcedureQuerySender.java, core/src/main/java/nl/nn/adapterframework/util/JdbcUtil.java, core/src/test/java/nl/nn/adapterframework/jdbc/StoredProcedureQuerySenderTest.java
Forward-port & Cherrypick van 7.9 fix
=> Fix error setting CLOB parameter for stored procedure (#5978)

.github/workflows/codeql-java.yml, .github/workflows/maven-build.yml, pom.xml
Small tests to see if we can build successfully with JDK17. Seems to be the case. Requires further integration testing.
=> Make CI JDK17 compatible

console/frontend/src/main/frontend/src/app/app.component.ts, console/frontend/src/main/frontend/src/app/views/scheduler/scheduler-add-edit-parent.component.html, console/frontend/src/main/frontend/src/app/views/scheduler/scheduler-add-edit-parent.ts, console/frontend/src/main/frontend/src/app/views/scheduler/scheduler-add/scheduler-add.component.ts, console/frontend/src/main/frontend/src/app/views/scheduler/scheduler-edit/scheduler-edit.component.ts, console/frontend/src/main/frontend/src/app/views/scheduler/scheduler.component.html, console/frontend/src/main/frontend/src/app/views/scheduler/scheduler.service.ts, console/frontend/src/main/frontend/src/app/views/security-items/security-items.component.ts, console/frontend/src/main/frontend/src/app/views/status/status.component.html, console/frontend/src/main/frontend/src/app/views/status/status.component.ts
=> 7.9 backport console adapter record keys are now changed for namespace instead of adaptername

console/frontend/src/main/frontend/src/app/app.component.ts, console/frontend/src/main/frontend/src/app/views/scheduler/scheduler-add-edit-parent.component.html, console/frontend/src/main/frontend/src/app/views/scheduler/scheduler-add-edit-parent.ts, console/frontend/src/main/frontend/src/app/views/scheduler/scheduler-add/scheduler-add.component.ts, console/frontend/src/main/frontend/src/app/views/scheduler/scheduler-edit/scheduler-edit.component.ts, console/frontend/src/main/frontend/src/app/views/scheduler/scheduler.component.html, console/frontend/src/main/frontend/src/app/views/scheduler/scheduler.service.ts, console/frontend/src/main/frontend/src/app/views/security-items/security-items.component.ts, console/frontend/src/main/frontend/src/app/views/status/status.component.html, console/frontend/src/main/frontend/src/app/views/status/status.component.ts
An adapter record key is now `ConfigurationName/AdapterName` instead of only `AdapterName`
=> Console adapter record keys are now changed for namespace instead of adaptername

console/frontend/src/main/frontend/src/app/views/error/error.component.ts, console/frontend/src/main/frontend/src/app/views/status/status.component.html
also fixes `&nbsp;` HTML entities missing a `;`
=> fix error status checks in error page

console/frontend/src/main/frontend/src/app/views/error/error.component.ts, console/frontend/src/main/frontend/src/app/views/status/status.component.html
=> Backport 7.9 fix error page

console/frontend/src/main/frontend/src/app/components/pages/pages-navigation/pages-navigation.component.html, console/frontend/src/main/frontend/src/app/components/pages/pages-navigation/pages-navigation.component.ts
=> Backport 7.9 fix sidebar categories expand collapse

console/frontend/src/main/frontend/src/app/views/connections/connections.component.html, console/frontend/src/main/frontend/src/app/views/connections/connections.component.ts
truncates cells with length longer than 100 characters but you can click to copy the original text
=> truncate connections columns & click to copy

console/frontend/src/main/frontend/src/app/app.service.ts, console/frontend/src/main/frontend/src/app/views/status/status.component.html
=> improve pipes type & show slotid on status page

console/frontend/src/main/frontend/src/app/views/security-items/security-items.component.html, console/frontend/src/main/frontend/src/app/views/security-items/security-items.component.ts, console/frontend/src/main/frontend/src/app/views/security-items/security-items.service.ts
Fixes types in security item, changed security roles to be handled as a record object
Needs to also be backported to 7.9 and 8.0
=> Fix security roles in security items

console/frontend/src/main/frontend/src/app/views/security-items/security-items.component.html, console/frontend/src/main/frontend/src/app/views/security-items/security-items.component.ts, console/frontend/src/main/frontend/src/app/views/security-items/security-items.service.ts
=> Backport to 8.0 of Fix security roles in security items

console/frontend/src/main/frontend/src/app/views/security-items/security-items.component.html, console/frontend/src/main/frontend/src/app/views/security-items/security-items.component.ts, console/frontend/src/main/frontend/src/app/views/security-items/security-items.service.ts
=> Backport to 7.9 of Fix security roles in security items

console/frontend/src/main/frontend/src/app/views/storage/storage-list/storage-list.component.html, console/frontend/src/main/frontend/src/app/views/storage/storage-list/storage-list.component.ts, console/frontend/src/main/frontend/src/app/views/storage/storage.service.ts, console/frontend/src/main/frontend/src/app/views/test-pipeline/test-pipeline.component.ts
=> Fowardport of Fix wrong targetStates type breaking (error) message store in the console

console/frontend/src/main/frontend/src/app/views/storage/storage-list/storage-list.component.html, console/frontend/src/main/frontend/src/app/views/storage/storage-list/storage-list.component.ts, console/frontend/src/main/frontend/src/app/views/storage/storage.service.ts, console/frontend/src/main/frontend/src/app/views/test-pipeline/test-pipeline.component.ts
=> 8.0 Forwardport of Fix wrong target states type breaking (error) message store in the console

cmis/src/main/java/nl/nn/adapterframework/extensions/cmis/CmisSender.java, cmis/src/main/java/nl/nn/adapterframework/extensions/cmis/CmisSessionBuilder.java, cmis/src/main/java/nl/nn/adapterframework/extensions/cmis/CmisSessionWrapper.java, cmis/src/main/java/nl/nn/adapterframework/extensions/cmis/server/BridgedCmisService.java, cmis/src/test/java/nl/nn/adapterframework/extensions/cmis/CmisSenderTestBase.java
No tests yet, need to think about how to make a good test for this.
=> Don't close CMIS Session & Bindings before reading the stream

console/frontend/src/main/frontend/src/app/views/scheduler/scheduler-add-edit-parent.component.html, console/frontend/src/main/frontend/src/app/views/test-pipeline/test-pipeline.component.html
See https://github.com/frankframework/frankframework/issues/6150#issuecomment-1915050775 and https://github.com/frankframework/frankframework/issues/6150#issuecomment-1915542769
=> Fix weird evaluation of truncated adapter dropdowns

core/src/main/resources/AppConstants.properties, ladybug/pom.xml, ladybug/src/main/java/org/frankframework/ibistesttool/DeploymentSpecificsBeanPostProcessor.java, ladybug/src/main/resources/springIbisTestTool.xml, ladybug/src/main/resources/springIbisTestToolApi.xml, ladybug/src/main/resources/springIbisTestToolBaco.xml, ladybug/src/main/resources/springIbisTestToolBipa.xml, ladybug/src/main/resources/springIbisTestToolIgnoreReport.xml, ladybug/src/main/resources/springIbisTestToolJuice.xml, ladybug/src/main/resources/springIbisTestToolTibet2.xml, ladybug/src/main/resources/springIbisTestToolToegang.xml
This reverts commit a05d0c6f3e617f0caf7715242b2b5a6afa1e6b9c  (#6068).
=> Revert "Support Ladybug database storage"

core/src/test/java/org/frankframework/jdbc/FixedQuerySenderTest.java, core/src/test/java/org/frankframework/jdbc/MessageStoreListenerTest.java, core/src/test/java/org/frankframework/jdbc/datasource/TestBlobs.java, core/src/test/java/org/frankframework/scheduler/CheckReloadJobTest.java, core/src/test/java/org/frankframework/testutil/junit/BTMArgumentSource.java, core/src/test/java/org/frankframework/testutil/junit/BTMArgumentsProvider.java, core/src/test/java/org/frankframework/testutil/junit/DatabaseTest.java, core/src/test/java/org/frankframework/testutil/junit/DatabaseTestEnvironment.java, core/src/test/java/org/frankframework/testutil/junit/DatasourceArgumentSource.java, core/src/test/java/org/frankframework/testutil/junit/JUnitLiquibaseExtension.java, core/src/test/java/org/frankframework/testutil/junit/NarayanaArgumentSource.java, core/src/test/java/org/frankframework/testutil/junit/NarayanaArgumentsProvider.java, core/src/test/java/org/frankframework/testutil/junit/TxManagerTest.java
Nog even een handigheidje verzinnen om niet alle transactionmanagers te testen...
=> Convert MessageStoreListenerTest

core/src/main/java/nl/nn/adapterframework/senders/ParallelSenders.java, core/src/main/java/nl/nn/adapterframework/senders/ShadowSender.java, core/src/test/java/nl/nn/adapterframework/senders/ParallelSendersTest.java, core/src/test/java/nl/nn/adapterframework/senders/ShadowSenderTest.java, core/src/test/resources/Senders/ParallelSenders/test10SubSendersNonRepeatableMessage.txt
- Fix ParallelSender and ShadowSender when messages are not repeatable
- Fix ShadowSender when not waiting for all senders to finish, and pipeline finishes before all senders have finished.
-
=> Improve reliability of ParallelSender and ShadowSender

core/src/main/java/org/frankframework/util/flow/MermaidFlowGenerator.java, core/src/test/java/org/frankframework/configuration/digester/MapPropertyDescriptorsTest.java, core/src/test/java/org/frankframework/configuration/digester/TestAnnotationUtils.java, core/src/test/java/org/frankframework/util/flow/UnloadableClass.java
Backport of fix on Master.
(cherry picked from commit b790ffe619bca599ebaf415f5e8e9e09fd9a9451)
=> Make MermaidFlowGenerator more resilient to class loading errors

core/src/main/java/org/frankframework/jdbc/datasource/GenericObjectPoolUtil.java, core/src/main/java/org/frankframework/jdbc/datasource/OpenManagedDataSource.java, core/src/main/java/org/frankframework/jdbc/datasource/OpenPoolingDataSource.java, core/src/main/java/org/frankframework/jdbc/datasource/TransactionalDbmsSupportAwareDataSourceProxy.java, core/src/main/java/org/frankframework/jndi/AbstractXADataSourceFactory.java, core/src/main/java/org/frankframework/jndi/JndiDataSourceFactory.java, core/src/main/java/org/frankframework/jndi/PoolingJndiDataSourceFactory.java, core/src/main/java/org/frankframework/jta/btm/BtmConnectionFactoryFactory.java, core/src/main/java/org/frankframework/jta/btm/BtmDataSourceFactory.java, core/src/main/java/org/frankframework/jta/narayana/NarayanaConnectionFactoryFactory.java, core/src/main/java/org/frankframework/jta/narayana/NarayanaDataSourceFactory.java, core/src/main/resources/AppConstants.properties, core/src/main/resources/springTOMCAT.xml, core/src/test/java/org/frankframework/jta/btm/BtmDataSourceFactoryTest.java, core/src/test/java/org/frankframework/receivers/MessageStoreListenerTest.java, core/src/test/java/org/frankframework/testutil/URLDataSourceFactory.java, core/src/test/java/org/frankframework/testutil/URLXADataSourceFactory.java, nn-specials/src/main/java/org/frankframework/extensions/esb/EsbJmsListener.java, test/src/main/resources/DeploymentSpecifics.properties, test/src/main/webapp/META-INF/context.xml
* Add Connection Pool Validation (#6119) (Cherrypick from 8a26d34c099ae9c2b9c28390df9e4e45fedc101c)
* PoolingJndiDataSourceFactory shouldn't check for DataSource to be XA or not XA (#6187)
* Try to determine if a datasource already does pooling (#6199)
(cherry picked from commit 281bf1e30fa416c2d47ad7254b8e85e71a0d3c9e)
=> Add Connection Validation and Pool configuration

core/src/test/java/org/frankframework/jdbc/migration/MigratorTest.java, core/src/test/java/org/frankframework/testutil/junit/DatabaseTestEnvironment.java, core/src/test/java/org/frankframework/util/LockerTest.java
=> Chore: Convert Liquibase Migrator tests to junit5

console/frontend/src/main/frontend/src/app/views/status/status.component.html, console/frontend/src/main/frontend/src/app/views/status/status.component.scss
Needs to be forward ported to 8.0 & master
=> Improve visibility of error message summary & counters on status page

console/frontend/src/main/frontend/src/app/views/status/status.component.html, console/frontend/src/main/frontend/src/app/views/status/status.component.scss
=> Forwardport 8.0 of  Improve visibility of error message summary on status page

console/frontend/src/main/frontend/src/app/views/status/status.component.html, console/frontend/src/main/frontend/src/app/views/status/status.component.scss
=> Forwardport of Improve visibility of error message counters on status page

aws/src/main/java/org/frankframework/filesystem/AmazonS3FileSystem.java, aws/src/test/java/org/frankframework/filesystem/AmazonS3FileSystemActorTest.java, aws/src/test/java/org/frankframework/filesystem/AmazonS3FileSystemTest.java, aws/src/test/java/org/frankframework/filesystem/AmazonS3FileSystemTestHelper.java, core/src/main/java/org/frankframework/filesystem/Samba1FileSystem.java, core/src/main/java/org/frankframework/filesystem/Samba2FileSystem.java, core/src/main/java/org/frankframework/filesystem/SftpFileSystem.java, core/src/test/java/org/frankframework/filesystem/FileSystemActorTest.java, core/src/test/java/org/frankframework/filesystem/FileSystemTest.java, core/src/test/java/org/frankframework/filesystem/LocalFileSystemActorTest.java, core/src/test/java/org/frankframework/filesystem/SftpFileSystemActorTest.java, core/src/test/java/org/frankframework/filesystem/SftpFileSystemTestHelper.java, core/src/test/java/org/frankframework/filesystem/mock/MockFileSystemTest.java, core/src/test/java/org/frankframework/filesystem/smb/Samba1FileSystemActorTest.java, core/src/test/java/org/frankframework/filesystem/smb/Samba2FileSystemActorTest.java
=> Make all FileSystems behave more consistent

core/src/main/java/org/frankframework/pipes/AbstractPipe.java, core/src/main/java/org/frankframework/pipes/JwtPipe.java, core/src/main/java/org/frankframework/util/CredentialFactory.java, core/src/test/java/org/frankframework/pipes/JwtPipeTest.java, credentialProvider/pom.xml, credentialProvider/src/main/java/org/frankframework/credentialprovider/Credentials.java, credentialProvider/src/main/java/org/frankframework/credentialprovider/ICredentialFactory.java, credentialProvider/src/main/java/org/frankframework/credentialprovider/ICredentials.java, credentialProvider/src/main/java/org/frankframework/credentialprovider/MapCredentials.java
(cherry picked from commit c7bce1841f03f1f6584242aadf008a7ce4d1522d)
=> Pad authAlias and sharedSecret parameter when jwtAllowWeakSecrets is true

core/src/main/resources/log4j4ibis.xml
=> Hide SMB logging by default

core/src/main/java/org/frankframework/core/ParameterException.java, core/src/main/java/org/frankframework/parameters/Parameter.java, core/src/main/java/org/frankframework/parameters/ParameterList.java, core/src/main/java/org/frankframework/parameters/ParameterValue.java, core/src/main/java/org/frankframework/pipes/LogContextPipe.java, core/src/main/java/org/frankframework/util/FileUtils.java, core/src/test/java/org/frankframework/parameters/ParameterTest.java, core/src/test/java/org/frankframework/pipes/LogContextPipeTest.java
Forward-port of the 7.9 change.
=> Make LogContextPipe not throw when it has an error during execution

core/src/main/java/org/frankframework/javascript/J2V8.java, core/src/main/java/org/frankframework/senders/JavascriptSender.java, core/src/test/java/org/frankframework/senders/JavascriptSenderTest.java, core/src/test/resources/Javascript/JavascriptTest.js
=> Fix JS engine exit error by releasing the handle to result

core/src/main/java/org/frankframework/receivers/Receiver.java, core/src/test/java/org/frankframework/receivers/MockListenerBase.java, core/src/test/java/org/frankframework/receivers/MockPullingListener.java, core/src/test/java/org/frankframework/receivers/MockPushingListener.java, core/src/test/java/org/frankframework/receivers/TestReceiverOnError.java
(cherry picked from commit d22273966650fe54de6b914c97bf532a2c7183ba)
=> Don't catch all exceptions but rethrow (#6284)

core/src/main/java/org/frankframework/filesystem/FtpFileSystem.java, core/src/main/java/org/frankframework/pipes/FilePipe.java, core/src/test/java/org/frankframework/filesystem/FileSystemActorTest.java, core/src/test/java/org/frankframework/filesystem/FtpFileSystemActorTest.java, core/src/test/java/org/frankframework/filesystem/FtpFileSystemTest.java, core/src/test/java/org/frankframework/filesystem/FtpFileSystemTestHelper.java, core/src/test/java/org/frankframework/testutil/junit/LocalFileServer.java, core/src/test/java/org/frankframework/util/FileHandlerTestBase.java
And bugfix: throw removing and creation failures
* Add more debug logging, to see what's really going on.
=> Add FtpFileSystemActorTest and improve FTP implementation

core/src/main/java/org/frankframework/filesystem/FtpFileSystem.java, core/src/main/java/org/frankframework/pipes/FilePipe.java, core/src/test/java/org/frankframework/filesystem/FileSystemActorTest.java, core/src/test/java/org/frankframework/filesystem/FtpFileSystemActorTest.java, core/src/test/java/org/frankframework/filesystem/FtpFileSystemTest.java, core/src/test/java/org/frankframework/filesystem/FtpFileSystemTestHelper.java, core/src/test/java/org/frankframework/testutil/junit/LocalFileServer.java, core/src/test/java/org/frankframework/util/FileHandlerTestBase.java
(cherry picked from commit 35b2ba9d8c590633568625ca05037a0e72721cec)
=> Add FtpFileSystemActorTest and improve FTP implementation (#6317)

core/src/main/java/org/frankframework/filesystem/SftpFileSystem.java, core/src/test/java/org/frankframework/filesystem/SftpFileSystemTest.java
* kept the enhanced isOpen method, while not actively being used
* 3 unit tests are not needed anymore as well, I think
Accidentally referred to the wrong issue number in the Git Branch Name, should be #6003
=> Remove the SFTP Reconnect mechanism

security/src/main/java/org/frankframework/lifecycle/servlets/OAuth2Authenticator.java
(cherry picked from commit aa08ff09835c347141954fe3cde1e8fa83cd9527)
=> Fix Oauth2 exception flow (#6395)

console/frontend/pom.xml, larva/pom.xml, larva/src/main/java/org/frankframework/larva/LarvaTool.java, larva/src/main/java/org/frankframework/larva/ListenerMessageHandler.java, larva/src/main/java/org/frankframework/pipes/LarvaPipe.java, larva/src/test/java/org/frankframework/pipes/LarvaPipeTest.java, pom.xml
Two small things:
1. Add basic unit tests to the LarvaPipe
2. Upgrade non-maintained directory-maven-plugin to recent version
=> Add basic unit tests to LarvaPipe; upgrade plugin

core/src/main/resources/AppConstants.properties, ladybug/pom.xml, ladybug/src/main/java/org/frankframework/ibistesttool/DeploymentSpecificsBeanPostProcessor.java, ladybug/src/main/resources/springIbisTestTool.xml, ladybug/src/main/resources/springIbisTestToolApi.xml, ladybug/src/main/resources/springIbisTestToolBaco.xml, ladybug/src/main/resources/springIbisTestToolBipa.xml, ladybug/src/main/resources/springIbisTestToolIgnoreReport.xml, ladybug/src/main/resources/springIbisTestToolJuice.xml, ladybug/src/main/resources/springIbisTestToolTibet2.xml, ladybug/src/main/resources/springIbisTestToolToegang.xml
Cherrypicked Commit: a05d0c6f3e617f0caf7715242b2b5a6afa1e6b9c (#6068)
=> Support Ladybug database storage

filesystem/src/test/java/org/frankframework/filesystem/SftpFileSystemActorTest.java, filesystem/src/test/java/org/frankframework/filesystem/SftpFileSystemSenderTest.java, filesystem/src/test/java/org/frankframework/filesystem/SftpFileSystemTest.java, filesystem/src/test/java/org/frankframework/filesystem/SftpFileSystemTestHelper.java
* Also clean up code and reuse setting up SFTP server
Prevents issues on GitHub builds with port is used
=> SFTP Unit testing: Test if port is free, before using it for unit test

core/src/main/java/org/frankframework/util/flow/DotFlowGenerator.java, core/src/main/java/org/frankframework/util/flow/GraphvizJsFlowGenerator.java, ladybug/src/main/java/org/frankframework/ibistesttool/Debugger.java, ladybug/src/main/java/org/frankframework/ibistesttool/IbisDebuggerAdvice.java, ladybug/src/main/java/org/frankframework/ibistesttool/jdbc/DataSourceFactory.java, ladybug/src/main/resources/springIbisTestTool.xml
- Fix testtool rerun functionality
- Reduct flow logging
- Close rerun result message
- Fix rerun reports not closing
- Add XA DataSource wrapper when using Narayana
=> Fix ladybug rerun

core/src/main/java/org/frankframework/stream/Message.java, core/src/test/java/org/frankframework/util/XmlUtilsTest.java, core/src/test/resources/Util/MessageUtils/iso-8859-1.xml, core/src/test/resources/Util/MessageUtils/iso-8859-1_without_xml_declaration.xml, core/src/test/resources/Util/MessageUtils/utf8-with-bom.xml, core/src/test/resources/Util/MessageUtils/utf8-without-bom.xml, core/src/test/resources/Util/MessageUtils/utf8.xml
=> Use provided charset when converting to InputSource

console/frontend/src/main/frontend/src/app/views/ibisstore-summary/ibisstore-summary.component.html, console/frontend/src/main/frontend/src/app/views/jdbc/jdbc.service.ts, core/src/main/java/org/frankframework/management/bus/endpoints/IbisstoreSummary.java
=> Ibisstore fix table columns & link to store

ladybug/src/main/resources/springIbisTestTool.xml
Copy of https://github.com/frankframework/frankframework/pull/6474 
(with valid branch name)
=> Fix Ladybug doesn't wait for database connection

console/frontend/src/main/frontend/src/app/views/test-pipeline/test-pipeline.component.html, console/frontend/src/main/frontend/src/app/views/test-service-listener/test-service-listener.component.html
=> Add dynamic drop-down to faster select an adapter in Test a Pipeline

filesystem/src/main/java/org/frankframework/filesystem/ExchangeFileSystem.java
...since it is not supported by Microsoft anymore
* Applied a few code cleanups
=> Remove basic authentication support on ExchangeFileSystem

pom.xml
=> Update maven plugins: SureFire, Deploy, Release

core/src/main/java/org/frankframework/senders/MailSender.java, test/src/main/resources/DeploymentSpecifics.properties
* and optimize some older code
=> Display MailSender physical destination data (host, port, TLS)

tibco/pom.xml, tibco/src/main/java/org/frankframework/extensions/tibco/pipes/ObfuscatePipe.java, tibco/src/test/java/org/frankframework/extensions/tibco/pipes/ObfuscatePipeTest.java
* Decryption does not always work, so disabled 2 unit tests
=> Add ObfuscatePipe to Tibco module

cmis/src/main/java/org/frankframework/extensions/cmis/mtom/MtomFilter.java, cmis/src/main/java/org/frankframework/extensions/cmis/mtom/MtomProxy.java, cmis/src/main/java/org/frankframework/extensions/cmis/servlets/CmisLifecycleBean.java, console/war/src/main/java/org/frankframework/web/ServletRegistration.java, core/src/main/java/org/frankframework/http/rest/ApiListener.java, core/src/test/java/org/frankframework/http/openapi/OpenApiTestBase.java, core/src/test/java/org/frankframework/http/rest/ApiListenerTest.java, ladybug/src/main/java/org/frankframework/ibistesttool/Debugger.java, ladybug/src/main/java/org/frankframework/ibistesttool/IbisDebuggerAdvice.java
And also clean some 'throws Exceptions'.
I'll add a comment to the real fix.
=> Remove '/*' from single endpoint ApiListener in physicalDestinationName

console/war/pom.xml, ladybug/pom.xml, pom.xml
=> Dependency management in parent pom

aws/pom.xml, core/pom.xml, management-gateway/pom.xml, pom.xml
* Can't update Spring to 6.x yet
=> Update vulnerable dependencies

pom.xml
Reverts frankframework/frankframework#6509
=> Revert "Bump org.apache.activemq:artemis-jms-client-all from 2.32.0 to 2.33.0"

console/frontend/src/main/frontend/src/app/services/poller.service.ts, console/frontend/src/main/frontend/src/app/views/jms/jms-send-message/jms-send-message.component.html, console/frontend/src/main/frontend/src/app/views/jms/jms-send-message/jms-send-message.component.ts, console/frontend/src/main/frontend/src/app/views/status/status.component.ts, console/frontend/src/main/frontend/src/app/views/test-service-listener/test-service-listener.component.ts
Backport of #6517 & poller fix
=> Add feedback on JMS 'Send Message' success & fix TestServiceListener

core/src/main/java/org/frankframework/receivers/Receiver.java, test/src/main/configurations/HTTP/ConfigurationApiListener.xml, test/src/main/configurations/JMS/ConfigurationJmsListenerSender.xml, test/src/test/testtool/ApiListener/04/call-exception-insert.xml, test/src/test/testtool/ApiListener/04/md-select-result.xml, test/src/test/testtool/ApiListener/04/md-select.xml, test/src/test/testtool/ApiListener/scenario04.properties, test/src/test/testtool/JmsListenerSender/FF/scenario03/in.xml, test/src/test/testtool/JmsListenerSender/FF/scenario03/md-select-result.xml, test/src/test/testtool/JmsListenerSender/FF/scenario03/out.xml
Add test to validate if elementToMove works correctly, and if the original message is stored in the ErrorStorage.
=> Fix elementToMove preserve

console/war/pom.xml, core/pom.xml, ladybug/pom.xml, pom.xml, test/pom.xml
Fixes a few CVE's
Fixes SLF4J2 log implementations
=> Add Spring Boot dependency management

core/src/main/java/org/frankframework/pipes/FixedForwardPipe.java, core/src/main/java/org/frankframework/processors/InputOutputPipeProcessor.java, core/src/main/java/org/frankframework/util/MessageUtils.java, core/src/test/java/org/frankframework/util/MessageUtilsTest.java
(cherry picked from commit 4616eccdb1d3cfa99e59cde328a3044745291c31)
=> Add log message when pipe is skipped

core/src/main/java/org/frankframework/jta/SpringTxManagerProxy.java
(cherry picked from commit 69bcf9c3431a644c80097ad6f57c45067a2fa252)
=> For now, remove noise when message is stored in ErrorStorage

core/src/main/java/org/frankframework/http/WebServiceListener.java, core/src/main/java/org/frankframework/soap/SoapWrapper.java, core/src/main/java/org/frankframework/soap/SoapWrapperPipe.java, core/src/main/java/org/frankframework/stream/MessageContext.java, core/src/main/java/org/frankframework/util/XmlUtils.java, core/src/test/java/org/frankframework/pipes/SoapWrapperPipeTest.java, core/src/test/java/org/frankframework/soap/SoapWrapperTest.java, core/src/test/java/org/frankframework/testutil/MessageTestUtils.java, core/src/test/java/org/frankframework/util/XmlUtilsTest.java, core/src/test/resources/Util/MessageUtils/iso-8859-1.txt, core/src/test/resources/Util/MessageUtils/utf8.xml
* cleanup some code, while working
=> Add XML declaration feature on attribute omitXmlDeclaration

.github/workflows/maven-build.yml, core/src/main/java/org/frankframework/core/Adapter.java, pom.xml
Once the artifact is available on Maven central we can use it.
=> Update Frank!Doc to 3.1

console/war/src/main/resources/FrankConsoleContext.xml, core/src/main/resources/SpringEnvironmentContext.xml
(cherry picked from commit d33880111be8892f52cdb36dbd864871b567fc7a)
=> AllowUrlEncodedSlash

console/frontend/src/main/frontend/src/app/views/jdbc/jdbc-execute-query/jdbc-execute-query.component.html, console/frontend/src/main/frontend/src/app/views/jdbc/jdbc-execute-query/jdbc-execute-query.component.ts, core/src/main/java/org/frankframework/management/bus/endpoints/ExecuteJdbcQuery.java
=> Improve user facing error messages on Console's JDBC Executy Query page

commons/src/main/java/org/frankframework/doc/FrankDocGroupValue.java, core/src/main/java/org/frankframework/lifecycle/ShowLogDirectory.java, core/src/main/java/org/frankframework/pipes/AbstractPipe.java, core/src/main/java/org/frankframework/pipes/MessageSendingPipe.java, core/src/main/resources/AppConstants.properties, filesystem/pom.xml, filesystem/src/test/java/org/frankframework/testutil/junit/LocalFileServer.java, pom.xml
[Rename Frank!Doc group names](https://github.com/frankframework/frankframework/commit/ce32672d5f996b1aef42024f72e3a7aa15faddbe) 
[Update SLF4J to API version 2.x](https://github.com/frankframework/frankframework/commit/59d0c4b2b4802878cb5241b203604bbf58ff99c2) 
[Bump org.filesys:jfileserver from 1.3.15 to 1.3.17](https://github.com/frankframework/frankframework/commit/0159b6df70a9423d13dc1cbd2f352626dcb79923) 
[Add HasStatistics interface to AbstractPipe](https://github.com/frankframework/frankframework/commit/ff9244823616b014c723356cb1bc39d73c129175)
=> Backports to 8.1

RELEASES.md, batch/src/main/java/org/frankframework/batch/RecordHandlerManager.java, core/src/main/java/org/frankframework/http/HttpSessionBase.java, core/src/main/java/org/frankframework/jdbc/JdbcQueryListener.java, core/src/main/java/org/frankframework/jdbc/JdbcTransactionalStorage.java, core/src/main/java/org/frankframework/jms/MessagingSource.java, core/src/main/java/org/frankframework/pipes/ForEachChildElementPipe.java, core/src/main/java/org/frankframework/pipes/IteratingPipe.java, core/src/main/java/org/frankframework/pipes/MessageSendingPipe.java, core/src/main/java/org/frankframework/pipes/StringIteratorPipe.java, core/src/main/java/org/frankframework/pipes/WsdlXmlValidator.java, core/src/main/java/org/frankframework/receivers/FileRecordListener.java, core/src/main/java/org/frankframework/scheduler/JobDef.java, core/src/main/java/org/frankframework/scheduler/NamedThreadFactory.java, core/src/main/java/org/frankframework/senders/IsolatedServiceCaller.java, core/src/main/java/org/frankframework/task/TimeoutGuard.java, core/src/main/resources/AppConstants.properties, core/src/test/java/org/frankframework/http/authentication/OAuthAccessTokenManagerRequestTest.java, core/src/test/java/org/frankframework/pipes/IteratingPipeTestBase.java, core/src/test/java/org/frankframework/pipes/StreamLineIteratorPipeTest.java, core/src/test/java/org/frankframework/testutil/ConcurrentActionTester.java, core/src/test/java/org/frankframework/testutil/junit/DatabaseTestEnvironment.java, filesystem/src/main/java/org/frankframework/filesystem/FileSystemListener.java
Some cleanups and changes from previous PR.
=> Chore: Code clean ups & persist disk size change from master PRs

management-gateway/src/main/java/org/frankframework/management/gateway/HttpInboundGateway.java, management-gateway/src/main/java/org/frankframework/management/security/JwtSecurityFilter.java
(cherry picked from commit 4dd2b1cfbf0b53f2906b8d407cd5f3d467c6aa43)
=> Register inbound http filter

console/frontend/src/main/frontend/angular.json, console/frontend/src/main/frontend/src/app/app-routing.module.ts, console/frontend/src/main/frontend/src/app/components/custom-views/custom-views.component.spec.ts, console/frontend/src/main/frontend/src/app/components/custom-views/custom-views.component.ts, console/frontend/src/main/frontend/src/app/components/file-viewer/file-viewer.component.spec.ts, console/frontend/src/main/frontend/src/app/components/input-file-upload/input-file-upload.component.spec.ts, console/frontend/src/main/frontend/src/app/components/pages/feedback-modal/feedback-modal.component.spec.ts, console/frontend/src/main/frontend/src/app/components/pages/information-modal/information-modal.component.spec.ts, console/frontend/src/main/frontend/src/app/components/pages/pages-footer/pages-footer.component.spec.ts, console/frontend/src/main/frontend/src/app/components/pages/pages-navigation/pages-navigation.component.spec.ts, console/frontend/src/main/frontend/src/app/components/pages/pages-navigation/pages-navigation.component.ts, console/frontend/src/main/frontend/src/app/components/pages/pages-topinfobar/pages-topinfobar.component.spec.ts, console/frontend/src/main/frontend/src/app/components/pages/pages-topnavbar/pages-topnavbar.component.spec.ts, console/frontend/src/main/frontend/src/app/components/pages/pages-topnavbar/pages-topnavbar.component.ts, console/frontend/src/main/frontend/src/app/components/pages/side-navigation.directive.spec.ts, console/frontend/src/main/frontend/src/app/components/th-sortable.directive.spec.ts, console/frontend/src/main/frontend/src/app/components/time-since.directive.spec.ts, console/frontend/src/main/frontend/src/app/components/to-date.directive.spec.ts, console/frontend/src/main/frontend/src/app/components/toasts-container/toasts-container.component.spec.ts, console/frontend/src/main/frontend/src/proxy-fftest.conf.json
=> Fix unit tests for standalone components

console/backend/src/main/java/org/frankframework/management/web/RequestMessageBuilder.java, core/src/main/java/org/frankframework/configuration/HostnamePropertySourcePostProcessor.java, core/src/main/java/org/frankframework/management/bus/MessageDispatcher.java, management-gateway/src/main/java/org/frankframework/management/bus/BusMessageUtils.java, management-gateway/src/main/java/org/frankframework/management/gateway/HttpInboundGateway.java, management-gateway/src/main/java/org/frankframework/management/gateway/HttpOutboundHandler.java
Allows frontend to target a specific backend by supplying the targets hostname.
=> Add Spring Bus hostname filter

console/frontend/src/main/frontend/src/app/app.module.ts, console/frontend/src/main/frontend/src/app/views/status/status.component.html, console/frontend/src/main/frontend/src/app/views/status/status.component.ts
=> Show warning on low free disk space

core/pom.xml
(cherry picked from commit 47831e3184c2d07fd14669100965b51b9f0c2de6)
(cherry picked from commit f766325832c8a3d7baeb65ce0a289383a9303b97)
(cherry picked from commit a8939d0b72871a769d42c8291d617a8184516cfd)
=> Bump bouncycastle

core/pom.xml
See https://github.com/messaginghub/pooled-jms/discussions/37
=> Invalidate managed jms sessions instead of resetting them

core/pom.xml
See https://github.com/messaginghub/pooled-jms/discussions/37
=> Invalide managed jms sessions instead of resetting them

core/src/main/java/org/frankframework/http/RestListener.java, core/src/main/java/org/frankframework/management/bus/endpoints/AdapterStatus.java, core/src/main/java/org/frankframework/pipes/JsonPipe.java
Now throws and NPE because the pipe is not configured
=> Fix json conversion in restlistener

core/src/main/java/org/frankframework/jdbc/datasource/ObjectFactoryBase.java, core/src/main/java/org/frankframework/management/bus/endpoints/ExecuteJdbcQuery.java, core/src/main/java/org/frankframework/management/bus/endpoints/SecurityItems.java
(cherry picked from commit c164af5d537805172d75843d7b67837cd5ccfdad)
=> Fix object order

aspose/src/main/java/org/frankframework/extensions/aspose/services/conv/impl/convertors/CellsConvertor.java, aspose/src/main/java/org/frankframework/extensions/aspose/services/conv/impl/convertors/PdfImageConvertor.java
(cherry picked from commit 9eb983dfb7e0bfbf358fd04274705fe756d64f70)
=> Close streams in Aspose

core/src/test/java/org/frankframework/jdbc/JdbcTableListenerTest.java, core/src/test/java/org/frankframework/jdbc/ResultSetIteratingPipeTest.java, core/src/test/java/org/frankframework/jdbc/TransactionManagerTest.java, core/src/test/resources/Migrator/ChangelogBlobTests.xml, dbms/src/main/java/org/frankframework/dbms/Db2DbmsSupport.java, dbms/src/main/java/org/frankframework/dbms/GenericDbmsSupport.java, dbms/src/main/java/org/frankframework/dbms/H2DbmsSupport.java, dbms/src/main/java/org/frankframework/dbms/IDbmsSupport.java, dbms/src/main/java/org/frankframework/dbms/MariaDbDbmsSupport.java, dbms/src/main/java/org/frankframework/dbms/MsSqlServerDbmsSupport.java, dbms/src/main/java/org/frankframework/dbms/MySqlDbmsSupport.java, dbms/src/main/java/org/frankframework/dbms/OracleDbmsSupport.java, dbms/src/main/java/org/frankframework/dbms/PostgresqlDbmsSupport.java
Clean up unused methods in IDbmsSupport, fix some issues breaking a number of database tests with Oracle & Postgresql.
=> Cleanup PR for IDbmsSupport

filesystem/src/main/java/org/frankframework/filesystem/FileSystemActor.java, filesystem/src/test/java/org/frankframework/filesystem/LocalFileSystemActorTest.java
if no absolute path is given for an uploaded file
=> Make sure the 'root' folder of a file system is used

commons/src/main/java/org/frankframework/util/DateFormatUtils.java, commons/src/test/java/org/frankframework/util/DateFormatUtilsTest.java
* Fix an issue with any-date-parsing
=> Fix for any-date parser (#6837)

console/frontend/src/main/frontend/src/app/app-routing.module.ts, console/frontend/src/main/frontend/src/app/app.module.ts, console/frontend/src/main/frontend/src/app/components/pages/pages-navigation/pages-navigation.component.html, console/frontend/src/main/frontend/src/app/views/iframe/iframe-ladybug-legacy/iframe-ladybug-legacy.component.ts, console/frontend/src/main/frontend/src/app/views/iframe/iframe-ladybug/iframe-ladybug.component.ts
And rename the other Ladybug to Ladybug (legacy)
=> Change Ladybug (beta) to the primary Ladybug

core/src/test/resources/Jdbc/StoredProcedureQuerySender/DatabaseChangelog-StoredProcedures.xml, core/src/test/resources/Migrator/ChangelogBlobTests.xml, core/src/test/resources/Migrator/CreateLockTable.xml, core/src/test/resources/Migrator/DatabaseChangelog.xml, core/src/test/resources/Migrator/DatabaseChangelogError.xml, core/src/test/resources/Migrator/DatabaseChangelog_inserts.xml, core/src/test/resources/Migrator/DatabaseChangelog_plus_changes.xml, core/src/test/resources/Migrator/Ibisconfig_4_unittests_changeset.xml, core/src/test/resources/Migrator/Ibisstore_4_unittests_changeset.xml
Postgres / Liquibase fix waar ik het eerder over had, om met tables met mixed-case te kunnen werken, zie:
https://stackoverflow.com/questions/2996020/making-case-insensitive-table-with-liquibase-in-postgres#2998130
Er zijn meer fixes nodig aan de JDBC tests maar deze is simpel, kleine stapjes.
=> Fix case-sensitivity issue with Postgres & Liquibase

bundle-minimal/pom.xml, core/src/main/java/org/frankframework/lifecycle/servlets/HttpSecurityConfigurer.java, core/src/main/java/org/frankframework/lifecycle/servlets/SecurityFilterChainConfigurer.java, ladybug/pom.xml, ladybug/src/main/java/org/frankframework/ibistesttool/config/SecurityChainConfigurer.java, ladybug/src/main/java/org/frankframework/ibistesttool/jdbc/LadyBugDataSourceFactory.java, ladybug/src/main/java/org/frankframework/ibistesttool/runner/LadybugWarInitializer.java, ladybug/src/main/java/org/frankframework/ibistesttool/tibet2/Storage.java, ladybug/src/main/resources/springIbisTestTool.xml, pom.xml, test/pom.xml, test/src/main/java/org/frankframework/runner/IafTestInitializer.java
=> Enable Ladybug

core/src/main/java/org/frankframework/processors/InputOutputPipeProcessor.java, core/src/main/java/org/frankframework/util/RestoreMovedElementsHandler.java, core/src/test/java/org/frankframework/processors/InputOutputPipeProcessorTest.java, core/src/test/java/org/frankframework/util/RestoreMovedElementsHandlerTest.java
1. Move restoreMovedElements method to new class; 
2. add more unit tests with nasty situations; 
3. fix and improve processing of empty & null input/session
=> Prepare changing the restoreMovedElements logic

docker/activemq.yml, docker/artemis.yml, docker/console.yml, docker/db2-xa.yml, docker/db2.yml, docker/embedded/console/Dockerfile, docker/embedded/console/pom.xml, docker/embedded/pom.xml, docker/jboss.yml, docker/mariadb.yml, docker/mongodb.yml, docker/mssql.yml, docker/mysql.yml, docker/oracle-xa.yml, docker/oracle.yml, docker/pom.xml, docker/postgres-xa.yml, docker/postgres.yml, docker/tomcat-debug.yml, docker/tomcat-narayana.yml, docker/tomcat.yml, docker/wildfly.yml
Also added an empty version, so IntelliJ recognizes the file as Docker compose.
Furthermore, reformatted the spacing and added project names so it is more obvious in the log.
=> Add Docker image for console

core/src/test/java/org/frankframework/jdbc/FixedQuerySenderTest.java, core/src/test/java/org/frankframework/jdbc/dbms/DbmsSupportTest.java
Gebaseerd op late feedback van Erik, en iets wat mij toevallig opviel in een test die ik nog open had, een paar kleine mini-changes in tests.
=> Few more small test improvements after code review

.mvn/wrapper/maven-wrapper.properties, core/src/main/resources/xml/xsd/FrankConfig-compatibility.xsd, core/src/main/resources/xml/xsd/FrankConfig.xsd, pom.xml
And bump software.amazon.awssdk
=> Bump FrankDoc and update FrankConfig files. Bump Maven to 3.9.7

.github/workflows/maven-build.yml, cmis/src/main/java/org/frankframework/extensions/cmis/servlets/CmisLifecycleBean.java, commons/src/main/java/org/frankframework/util/FieldNameSensitiveToStringStyle.java, console/backend/src/main/java/org/frankframework/management/web/ApiExceptionHandler.java, core/src/main/java/org/frankframework/jms/MessagingSource.java, core/src/main/java/org/frankframework/lifecycle/servlets/HttpSecurityConfigurer.java, core/src/main/resources/AppConstants.properties, core/src/test/resources/AppConstants.properties
Set default fileviewer access to the log directory.
=> Fix SonarCloud fetch depth

console/backend/src/main/java/org/frankframework/management/web/ApiExceptionHandler.java, console/backend/src/main/java/org/frankframework/management/web/FileViewer.java, console/backend/src/main/java/org/frankframework/management/web/SpringBusExceptionHandler.java, core/src/main/resources/META-INF/resources/iaf/jsp/debuginfo.jsp, core/src/main/resources/META-INF/resources/iaf/jsp/errorPage.jsp
Catch all Exceptions for the console API to have it return a json response for the frontend.
Sanitize variables used in errorPage.jsp to prevent XSS
=> Catch more Console API exceptions & Sanitize exception message in error page jsp

core/src/main/java/org/frankframework/mongodb/StrictJsonDocumentWriter.java, core/src/test/java/org/frankframework/mongodb/JsonDocumentWriterTest.java, core/src/test/java/org/frankframework/mongodb/MongoDbSenderTest.java
* Add more unit tests and coverage on more situations
Thanks to Tim to find the single line of code that was the real fix 👍🏻
=> Fix MongoDbSender: process array with objects

console/frontend/src/main/frontend/src/app/components/pages/pages-topnavbar/pages-topnavbar.component.html
- Remove margin class from stage span
- Update star link and icon in top navbar
Closes #7011
=> Update HTML in pages-topnavbar component

console/backend/src/main/java/org/frankframework/management/web/ApiExceptionHandler.java, console/backend/src/main/java/org/frankframework/management/web/SpringBusExceptionHandler.java, console/frontend/src/main/frontend/src/app/views/jdbc/jdbc-browse-tables/jdbc-browse-tables.component.ts
rowMin is now 1 & rowMax is now 100 as default
=> Set actual defaults of jdbc-browse-tables as set in core

larva/src/main/java/org/frankframework/larva/LarvaTool.java, larva/src/main/java/org/frankframework/larva/ScenarioRunner.java, larva/src/main/java/org/frankframework/larva/TestConfig.java
Turns multithreaded into opt-in.
Fixes:
=> Minor Larva bugfixes

console/frontend/src/main/frontend/src/app/app.component.html, console/frontend/src/main/frontend/src/app/app.component.ts, console/frontend/src/main/frontend/src/app/components/pages/pages-topnavbar/pages-topnavbar.component.html, console/frontend/src/main/frontend/src/app/components/pages/pages-topnavbar/pages-topnavbar.component.ts, console/frontend/src/main/frontend/src/app/http-interceptors/auth-interceptor.ts, console/frontend/src/main/frontend/src/app/services/auth.service.ts, console/frontend/src/main/frontend/src/app/views/login/login.component.html, console/frontend/src/main/frontend/src/app/views/login/login.component.ts
The button in the frontend does display now when a username is gotten from the backend.
PR #7101 should've made the `/logout` endpoint work but somehow it won't work in Firefox and is iffy in Chrome, this should be looked into.
=> Display logout button in console when properly logged in

ladybug/pom.xml
=> Use ladybug 3.0-20240710.181558 which includes frontend 0.1.0-20240710.153412

ladybug/pom.xml
=> Bump ladybug to 3.0-20240711.114955 to have frontend 0.1.0-20240711.113931

console/backend/src/main/java/org/frankframework/management/web/TransactionalStorage.java, console/backend/src/main/java/org/frankframework/management/web/configuration/WebConfiguration.java, console/backend/src/test/java/org/frankframework/management/web/TransactionalStorageTest.java
=> Fix console message store endpoints

akamai/src/main/java/org/frankframework/extensions/akamai/NetStorageSender.java, cmis/src/main/java/org/frankframework/extensions/cmis/CmisSender.java, core/src/main/java/org/frankframework/compression/ZipWriter.java, core/src/main/java/org/frankframework/jdbc/MessageStoreSender.java, core/src/main/java/org/frankframework/jms/JmsSender.java, core/src/main/java/org/frankframework/ldap/LdapChallengePipe.java, core/src/main/java/org/frankframework/ldap/LdapSender.java, core/src/main/java/org/frankframework/mongodb/MongoDbSender.java, core/src/main/java/org/frankframework/parameters/ParameterList.java, core/src/main/java/org/frankframework/pipes/CompareIntegerPipe.java, core/src/main/java/org/frankframework/pipes/CompareStringPipe.java, core/src/main/java/org/frankframework/pipes/JwtPipe.java, core/src/main/java/org/frankframework/pipes/SignaturePipe.java, core/src/main/java/org/frankframework/senders/LogSender.java, core/src/main/java/org/frankframework/senders/SenderWithParametersBase.java, core/src/test/java/org/frankframework/parameters/ParameterListTest.java, filesystem/src/main/java/org/frankframework/filesystem/FileSystemActor.java, nn-specials/src/main/java/org/frankframework/extensions/api/ApiSoapWrapperPipe.java, nn-specials/src/main/java/org/frankframework/extensions/esb/EsbJmsSender.java, nn-specials/src/main/java/org/frankframework/extensions/esb/EsbSoapWrapperPipe.java, nn-specials/src/main/java/org/frankframework/extensions/fxf/FxfWrapperPipe.java, sap/src/main/java/org/frankframework/extensions/sap/jco3/SapSenderBase.java, sap/src/main/java/org/frankframework/extensions/sap/jco3/SapSenderImpl.java, tibco/src/main/java/org/frankframework/extensions/tibco/GetTibcoQueues.java, tibco/src/main/java/org/frankframework/extensions/tibco/SendTibcoMessage.java
De check:
`if (parameterList.findParameter("x") == null) // ...`
Moet worden:
`if (!parameterList.hasParameter("x")) // ...`
En de check:
`if (parameterList.findParameter("x") != null) // ...`
Moet worden:
`if (parameterList.hasParameter("x")) // ...`
Ik ben alle changes 1 voor 1 nog een keer nagelopen en volgens mij heb ik dat overal goed gedaan maar misschien heb ik nog ergens een `!` vergeten en dat over het hoofd gezien!
=> Add method ParameterList#hasParameter and apply where relevant.

console/frontend/src/main/frontend/src/app/views/test-pipeline/test-pipeline.component.html, console/frontend/src/main/frontend/src/app/views/test-pipeline/test-pipeline.component.ts, core/src/main/java/org/frankframework/management/bus/endpoints/TestPipeline.java, core/src/test/java/org/frankframework/management/bus/endpoints/TestPipelineTest.java
=> Fix sessionkey types for both console & core

console/frontend/src/main/frontend/src/app/views/storage/storage-list/storage-list-dt/storage-list-dt.component.html, console/frontend/src/main/frontend/src/app/views/storage/storage.service.ts
=> Fix message browser selected messages with non-numbers

aws/src/main/java/org/frankframework/filesystem/AmazonS3FileSystem.java, aws/src/test/java/org/frankframework/filesystem/AmazonS3FileSystemTest.java, aws/src/test/java/org/frankframework/filesystem/AmazonS3FileSystemTestHelper.java, core/src/main/java/org/frankframework/util/flow/MermaidFlowGenerator.java
In https://github.com/frankframework/frankframework/issues/4326 we added the ability to dynamically change the bucketName, this however was very poorly documented and implemented!
This PR fixes the original behavior but whether we must keep it...
=> Fix bucketName prefix when creating files

core/src/main/java/org/frankframework/http/rest/ApiListenerServlet.java
(cherry picked from commit 672b9d495ba48ee08c19417da656b28f0632215c)
=> Log Mime Multipart exception in ApiListenerServlet (#7205)

core/src/main/java/org/frankframework/http/rest/ApiListenerServlet.java
(cherry picked from commit 672b9d495ba48ee08c19417da656b28f0632215c)
(cherry picked from commit 9151333d2e40af55cbeac698dcdde1c877123910)
=> Log Mime Multipart exception in ApiListenerServlet

core/src/main/java/org/frankframework/stream/OverflowToDiskOutputStream.java
I'm unsure if we should close the OutputStream as well...
=> Ensure the file is cleaned up in case it's not converted to a Message

CONTRIBUTING.md
I've improved the readability and clarity of the _developing with Intellij_ section of `CONTRIBUTING.md` after using it to setup Intellij on my machine.
=> Modify the developing with intellij documentation to make it more clear to future readers.

core/src/main/java/org/frankframework/pipes/IteratingPipe.java
I tried to clean up the code a bit, but ..
The main change was `message.close();` and `message.closeOnClose(session, ..);`.
=> Register IteratingPipe child message on Session close

commons/src/main/java/org/frankframework/util/PropertyLoader.java, tibco/src/main/java/org/frankframework/extensions/tibco/GetTibcoQueues.java, tibco/src/main/java/org/frankframework/extensions/tibco/SendTibcoMessage.java, tibco/src/main/java/org/frankframework/extensions/tibco/TibcoEmsProperties.java, tibco/src/main/java/org/frankframework/extensions/tibco/TibcoUtils.java, tibco/src/test/java/nl/nn/adapterframework/extensions/tibco/TibcoJndiPropertiesTest.java, tibco/src/test/java/org/frankframework/extensions/tibco/TibcoJndiPropertiesTest.java, tibco/src/test/resources/jndi.properties, tibco/src/test/resources/log4j4ibis.xml
=> Implement custom properties for Tibco classes

docker/Tomcat/example/Dockerfile
Remove unused context.xml file reference
=> Update example Dockerfile

console/backend/src/main/java/org/frankframework/management/web/BrowseQueue.java
Backport of main pr: #7180
Fixes #7240
=> Fix asserting empty value in BrowseQueue

console/frontend/src/main/frontend/src/app/views/liquibase/liquibase.component.ts
=> Remove '/' in liquibase download url

console/backend/src/main/java/org/frankframework/management/web/BrowseQueue.java
(cherry picked from commit 1d43f8ec9c2f33038cf51c59f8aa15122c429ddd)
=> Fix asserting empty value in BrowseQueue (#7250)

security/src/main/java/org/frankframework/lifecycle/servlets/AuthenticationType.java, security/src/main/java/org/frankframework/lifecycle/servlets/YmlFileAuthenticator.java
Backport ymlFileAuthenticator #7261
=> Add local users yaml authenticator

tibco/src/main/java/org/frankframework/extensions/tibco/TibcoUtils.java
(cherry picked from commit d6ffbc269164327492078b4bf9c8adeafe2ebdb9)
=> Tibco age field may not be negative (#7263)

console/frontend/pom.xml
Reverts frankframework/frankframework#7282
=> Revert "Bump org.codehaus.mojo:exec-maven-plugin from 3.3.0 to 3.4.0"

console/frontend/src/main/frontend/src/app/app.component.ts, console/frontend/src/main/frontend/src/app/components/monaco-editor/monaco-editor.component.scss, console/frontend/src/main/frontend/src/app/components/monaco-editor/monaco-editor.component.ts, console/frontend/src/main/frontend/src/app/views/jdbc/jdbc-execute-query/jdbc-execute-query.component.html, console/frontend/src/main/frontend/src/app/views/jdbc/jdbc-execute-query/jdbc-execute-query.component.ts, console/frontend/src/main/frontend/src/app/views/jms/jms-send-message/jms-send-message.component.html, console/frontend/src/main/frontend/src/app/views/jms/jms-send-message/jms-send-message.component.ts, console/frontend/src/main/frontend/src/app/views/scheduler/scheduler-add-edit-parent.component.html, console/frontend/src/main/frontend/src/app/views/test-pipeline/test-pipeline.component.html, console/frontend/src/main/frontend/src/app/views/test-pipeline/test-pipeline.component.ts, console/frontend/src/main/frontend/src/app/views/test-service-listener/test-service-listener.component.html, console/frontend/src/main/frontend/src/app/views/test-service-listener/test-service-listener.component.ts
Added to:
* JDBC > Execute Query
* JMS > Send Message
* Test > Test a Pipeline
* Test > Test a Service Listener
=> Integrate the Monaco Editor on more pages

docker/Tomcat/webapp/Dockerfile, docker/Tomcat/webapp/src/scripts/web.xml, webapp/src/main/webapp/WEB-INF/web.xml
=> Disable re-compilation of JSP scripts, because this is a security risk.

commons/src/main/java/org/frankframework/util/ClassUtils.java, core/src/main/java/org/frankframework/configuration/classloaders/ClassLoaderBase.java, core/src/main/java/org/frankframework/util/ClassLoaderUtils.java, management-gateway/src/test/java/org/frankframework/management/gateway/HazelcastEndToEndTest.java
Improve Hazelcast test stability
=> Allow local-file path to be used when looking up resources

core/src/main/java/org/frankframework/jms/JmsSender.java, core/src/test/java/org/frankframework/jms/JmsSenderTest.java
This took some time to correctly test it. Found out 'AdapterAware' fixed this - metrics without adapter won't work
=> Add metrics for JmsSender createSession

idin/src/main/java/nl/nn/adapterframework/extensions/idin/IdinSender.java, idin/src/test/java/nl/nn/adapterframework/extensions/idin/IdinSenderTest.java, idin/src/test/resources/expected/simpleRequestResponse.xml
(cherry picked from commit c69646d37d927cfab6742084f445ff6619262bc6)
=> Fix iDin equals check

core/src/main/java/org/frankframework/senders/FrankSender.java
Also closes https://github.com/frankframework/frank-doc/issues/196
=> Fix javadocs for the FrankSender.

console/frontend/src/main/frontend/src/app/views/test-pipeline/test-pipeline.component.html
=> Add `data-cy` tag to Monaco Editor in "Test a Pipeline"

core/src/main/java/org/frankframework/scheduler/JobDef.java, core/src/main/java/org/frankframework/scheduler/job/ActionJob.java, core/src/main/java/org/frankframework/scheduler/job/CheckReloadJob.java, core/src/main/java/org/frankframework/scheduler/job/CleanupDatabaseJob.java, core/src/main/java/org/frankframework/scheduler/job/CleanupFileSystemJob.java, core/src/main/java/org/frankframework/scheduler/job/ExecuteQueryJob.java, core/src/main/java/org/frankframework/scheduler/job/LoadDatabaseSchedulesJob.java, core/src/main/java/org/frankframework/scheduler/job/RecoverAdaptersJob.java, core/src/main/java/org/frankframework/scheduler/job/SendMessageJob.java
De vraag is nu hoe we de javadoc van de JobDef class in de overige jobs kunnen krijgen.
`{@inheritDoc}` werkt (voor Java) niet op class niveau.
=> Add documentation to scheduled jobs

core/src/main/resources/xml/xsl/adapter2mermaid.xsl, core/src/main/resources/xml/xsl/configuration2mermaid.xsl
this PR will fix the mermaid issue when a config has no forwards, and will also fix an issue when exits have their state attribute capitalized
=> fix mermaid xsl issues for config and adapter

core/src/main/java/org/frankframework/pipes/ChecksumPipe.java, core/src/main/java/org/frankframework/pipes/FixedResultPipe.java, core/src/main/java/org/frankframework/pipes/HashPipe.java, core/src/main/java/org/frankframework/pipes/hash/Algorithm.java, core/src/main/java/org/frankframework/pipes/hash/HashGenerator.java, core/src/test/java/org/frankframework/pipes/ChecksumPipeTest.java, core/src/test/java/org/frankframework/pipes/HashPipeTest.java
And add clear documentation and unit tests for HashPipe and ChecksumPipe
=> Merge CheckSumPipe and HashPipe and add hashEncoding

ladybug/src/main/resources/springIbisTestTool.xml
(cherry picked from commit ac56e9c67cca37e219acb3d953c94561178a57eb)
=> Prevent CloseReportsTask from throwing NPEs (#7490)

core/src/main/java/org/frankframework/http/authentication/OAuthAccessTokenManager.java, core/src/test/java/org/frankframework/http/authentication/OAuthAccessTokenManagerRequestTest.java
Voor nu even als draft, ik weet niet goed hoe ik het kan testen - gelukkig was er al wel een unit test om te bewijzen dat er nu uitkomt wat ik verwacht.
Wat denk jij ervan Niels?
=> Remove authentication header in case of request parameter authentication type

console/frontend/src/main/frontend/src/app/components/pages/pages-navigation/pages-navigation.component.html, console/frontend/src/main/frontend/src/app/components/pages/pages-navigation/pages-navigation.component.scss, console/frontend/src/main/frontend/src/app/components/pages/pages-navigation/pages-navigation.component.ts, console/frontend/src/main/frontend/src/assets/css/style.css
Remake of what Metismenu used to do, but now with 100% less jquery
=> Fancy side navigation menu animations

core/src/main/java/org/frankframework/core/PipeLine.java, core/src/main/java/org/frankframework/pipes/AbstractPipe.java, core/src/main/java/org/frankframework/pipes/CounterSwitchPipe.java, core/src/main/resources/xml/xsd/FrankConfig-compatibility.xsd, core/src/main/resources/xml/xsd/FrankConfig.xsd, core/src/test/java/org/frankframework/core/PipeLineTest.java, core/src/test/java/org/frankframework/pipes/ConsecutiveXsltPipeTest.java, core/src/test/java/org/frankframework/pipes/CounterSwitchPipeTest.java, core/src/test/java/org/frankframework/pipes/FilenameSwitchTest.java, core/src/test/java/org/frankframework/pipes/ForwardHandlingTest.java, core/src/test/java/org/frankframework/pipes/PasswordHashPipeTest.java, core/src/test/java/org/frankframework/pipes/SoapWrapperPipeTest.java, core/src/test/java/org/frankframework/receivers/MockListenerBase.java
Based on #7562, validation should happen during the configure phase not during the config xml phase.
=> Validate pipe forwards during configure phase

console/frontend/src/main/frontend/src/app/views/iframe/iframe-custom-view/iframe-custom-view.component.ts, console/frontend/src/main/frontend/src/app/views/iframe/iframe-ladybug-legacy/iframe-ladybug-legacy.component.ts, console/frontend/src/main/frontend/src/app/views/iframe/iframe-ladybug/iframe-ladybug.component.ts, console/frontend/src/main/frontend/src/app/views/iframe/iframe-larva/iframe-larva.component.ts, console/frontend/src/main/frontend/src/app/views/iframe/iframe.base.ts, console/frontend/src/main/frontend/src/assets/css/bootstrap-fix.css, console/frontend/src/main/frontend/src/assets/css/style.css
- Set minimum page height to 100vh as to fill the page
- Remove scrollbars on iframe pages like custom views, larva & ladybug
=> Fix minimum page height & hide scrollbars on testing & custom views

console/backend/src/test/java/org/frankframework/console/configuration/DeprecationInterceptorTest.java, console/backend/src/test/java/org/frankframework/console/util/TestAppender.java, core/src/test/java/org/frankframework/configuration/classloaders/DatabaseClassLoaderTest.java, core/src/test/java/org/frankframework/configuration/classloaders/JarFileClassLoaderTest.java, core/src/test/java/org/frankframework/core/AdapterHideRegexTest.java, core/src/test/java/org/frankframework/jdbc/migration/MigratorTest.java, core/src/test/java/org/frankframework/logging/TestLogMessages.java, core/src/test/java/org/frankframework/management/bus/BusExceptionTest.java, core/src/test/java/org/frankframework/pipes/ForwardHandlingTest.java, core/src/test/java/org/frankframework/pipes/WsdlXmlValidatorTest.java, core/src/test/java/org/frankframework/receivers/ReceiverTest.java, core/src/test/java/org/frankframework/receivers/TestReceiverOnError.java, core/src/test/java/org/frankframework/senders/LogSenderTest.java, core/src/test/java/org/frankframework/stream/MessageTest.java, core/src/test/java/org/frankframework/testutil/TestAppender.java, core/src/test/java/org/frankframework/util/flow/graphviz/GraphvizEngineTest.java, core/src/test/java/org/frankframework/xslt/ParallelXsltTest.java, core/src/test/java/org/frankframework/xslt/XsltErrorTestBase.java
=> Make TestAppender autocloseable.

console/backend/src/main/java/org/frankframework/console/configuration/SecurityChainConfigurer.java, core/src/main/resources/StageSpecifics_LOC.properties, ladybug/common/src/main/java/org/frankframework/ladybug/config/LadybugSecurityChainConfigurer.java, security/src/main/java/org/frankframework/lifecycle/servlets/AuthenticationType.java, security/src/main/java/org/frankframework/lifecycle/servlets/IAuthenticator.java, security/src/main/java/org/frankframework/lifecycle/servlets/InMemoryAuthenticator.java, security/src/main/java/org/frankframework/lifecycle/servlets/JeeAuthenticator.java, security/src/main/java/org/frankframework/lifecycle/servlets/NoOpAuthenticator.java, security/src/main/java/org/frankframework/lifecycle/servlets/OAuth2Authenticator.java, security/src/main/java/org/frankframework/lifecycle/servlets/SealedAuthenticator.java, security/src/main/java/org/frankframework/lifecycle/servlets/ServletConfiguration.java, security/src/main/java/org/frankframework/lifecycle/servlets/URLRequestMatcher.java, security/src/main/java/org/frankframework/lifecycle/servlets/YmlFileAuthenticator.java
=> Add SEALED authenticator and use it by default

core/src/main/java/org/frankframework/http/WebServiceListener.java
(cherry picked from commit c415fd490011a691d44afd89cc5a4e634da4e9c7)
=> Show WSS on Test-ServiceListener console page

core/src/main/java/org/frankframework/jdbc/datasource/FrankResources.java, ladybug/debugger/src/main/resources/springIbisTestTool.xml, test/src/main/resources/ladybug-resources.yml
And make the resource type also configurable
=> Add option to use custom resources.yml file for the ladybug

core/src/main/java/org/frankframework/pipes/RegExPipe.java, core/src/main/java/org/frankframework/pipes/XmlIf.java, core/src/test/java/org/frankframework/pipes/RegExPipeTest.java, test/src/main/configurations/MainConfig/Configuration.xml, test/src/main/configurations/MainConfig/ConfigurationRegExPipe.xml, test/src/test/testtool/RegExPipe/common.properties, test/src/test/testtool/RegExPipe/scenario01.properties, test/src/test/testtool/RegExPipe/scenario01/in.txt, test/src/test/testtool/RegExPipe/scenario01/out.txt
=> Implement the new RegExPipe.

core/src/main/resources/AppConstants.properties
Closes #7703 
A continuation of https://github.com/frankframework/frankframework/issues/4847 as preparation for the new FF!Ref frontend.
=> Add all viable parsed properties to AppConstants.properties

core/src/main/java/org/frankframework/pipes/AbstractPipe.java, core/src/main/java/org/frankframework/pipes/FixedForwardPipe.java, core/src/test/java/org/frankframework/core/PipeLineTest.java
=> Move success forward to FixedResultPipe

core/src/main/java/org/frankframework/ldap/LdapFindGroupMembershipsPipe.java, core/src/main/java/org/frankframework/ldap/LdapFindMemberPipe.java, core/src/main/java/org/frankframework/ldap/LdapQueryPipeBase.java, core/src/main/java/org/frankframework/ldap/LdapSender.java, core/src/test/java/org/frankframework/ldap/LdapFindGroupMembershipsPipeTest.java, core/src/test/java/org/frankframework/ldap/LdapFindMemberPipeTest.java, core/src/test/java/org/frankframework/ldap/LdapSenderTest.java, core/src/test/resources/Ldap/expected/create.xml, core/src/test/resources/Ldap/expected/search.xml
=> Improve test coverage of the ldap subpackage

core/src/main/java/org/frankframework/pipes/ForPipe.java, core/src/test/java/org/frankframework/pipes/ForPipeTest.java
instead of FixedForwardPipe to avoid having 'success' forward
=> Update ForPipe to extend AbstractPipe 

README.md
Depends on #7711 where some dependencies are shuffled around from implementation modules to the parent one.
=> Add Soos badge

core/src/main/java/org/frankframework/lifecycle/ShowLogDirectory.java
I'm sure I'm doing something wrong here, something that looked so simple is now super complex...
=> Fix excessive logging in showLogDirectory

checkstyle.xml, core/src/main/java/org/frankframework/jms/JmsSender.java, core/src/main/resources/AppConstants.properties, filesystem/src/test/java/org/frankframework/filesystem/GreenmailImapTestFileSystemHelper.java
- Change checkstyle severity level to block builds
- Return JMS message context when RR
- Remove half-deprecation for monitoring in appconstants.properties
=> Minor improvements

console/frontend/src/main/frontend/src/app/app-routing.module.ts, console/frontend/src/main/frontend/src/app/services/websocket.service.ts, console/frontend/src/main/frontend/src/app/views/monitors/monitors.service.ts
=> Fix monitor trigger url & missing 'Security Items' page title

filesystem/src/main/java/org/frankframework/filesystem/MailListener.java
Ik was deze vergeten toe te voegen aan de Maillistener
=> Add since version attributes to deprecated tags in MailListener

docker/nginx.yml, docker/nginx/.gitignore, docker/nginx/README.md, docker/nginx/conf.d/default.conf
This can be used for testing purposes.
=> Add a Docker Compose file for an Nginx reverse proxy

core/src/main/java/org/frankframework/http/MicrometerHttpClientInterceptor.java
(cherry picked from commit b01a45948797d67e16f5a8b693fcc37b4c3e0c02)
=> Use a ThreadLocal for the micrometer http interceptor (#7717)

core/src/main/java/nl/nn/adapterframework/management/bus/endpoints/TestPipeline.java, test/src/main/resources/DeploymentSpecifics.properties
Backport to 7.9 from https://github.com/frankframework/frankframework/pull/7535
=> Use CID in test pipeline when present

core/src/main/resources/AppConstants.properties, core/src/main/resources/StageSpecifics_DEV.properties, core/src/main/resources/StageSpecifics_LOC.properties, core/src/main/resources/StageSpecifics_TST.properties, core/src/test/resources/FlowDiagram/Mermaid/MultipleRealisticAdapters/original.xml, example/src/main/resources/StageSpecifics_ACC.properties, example/src/main/resources/StageSpecifics_DEV.properties, example/src/main/resources/StageSpecifics_LOC.properties, example/src/main/resources/StageSpecifics_PRD.properties, example/src/main/resources/StageSpecifics_TST.properties, nn-specials/src/main/java/org/frankframework/extensions/fxf/FxfWrapperPipe.java, test/src/main/resources/StageSpecifics_ACC.properties, test/src/main/resources/StageSpecifics_DEV.properties, test/src/main/resources/StageSpecifics_LOC.properties, test/src/main/resources/StageSpecifics_PRD.properties, test/src/main/resources/StageSpecifics_TST.properties
Fix some property descriptions
=> Fix some property descriptions in AppConstants.properties

core/src/main/java/org/frankframework/monitoring/Monitor.java, core/src/main/java/org/frankframework/monitoring/Trigger.java, core/src/test/resources/Management/Monitoring/getManagerToXML.xml, core/src/test/resources/Management/Monitoring/getMonitor.xml, core/src/test/resources/Management/Monitoring/getMonitors.xml
=> Change generated XML for monitors to the new style

core/src/main/java/org/frankframework/configuration/digester/DigesterRuleBase.java, core/src/main/java/org/frankframework/configuration/digester/ValidateAttributeRule.java, core/src/main/java/org/frankframework/core/PipeLine.java, core/src/main/java/org/frankframework/xml/NamespaceRemovingAttributesWrapper.java, core/src/test/java/org/frankframework/configuration/digester/ValidateAttributeRuleTest.java, core/src/test/java/org/frankframework/xml/AttributePropertyResolverTest.java, core/src/test/resources/Entities/AttributePropertyResolver/data.properties, core/src/test/resources/Entities/AttributePropertyResolver/property-resolving-result.xml, core/src/test/resources/Entities/AttributePropertyResolver/property-resolving.xml, test/src/main/configurations/HTTP/ConfigurationApiListener.xml, test/src/main/configurations/HTTP/DeploymentSpecifics.properties
=> Fix issue where the name attribute is not being substituted

console/frontend/src/main/frontend/package-lock.json, console/frontend/src/main/frontend/package.json
=> Revert monaco-editor update to 0.52.0

aspose/src/main/java/org/frankframework/extensions/aspose/services/conv/impl/convertors/PdfImageConvertor.java, aspose/src/test/java/org/frankframework/extensions/aspose/pipe/PdfPipeTest.java, core/src/main/java/org/frankframework/align/XmlAligner.java, core/src/main/java/org/frankframework/align/XmlTypeToJsonSchemaConverter.java, core/src/main/java/org/frankframework/http/WebServiceSender.java, core/src/main/java/org/frankframework/mongodb/MongoDbSender.java, core/src/main/java/org/frankframework/pipes/CompressPipe.java, core/src/main/java/org/frankframework/pipes/JsonWellFormedChecker.java, core/src/main/java/org/frankframework/pipes/MessageSendingPipe.java, core/src/main/java/org/frankframework/soap/SoapWrapper.java, core/src/main/java/org/frankframework/stream/Message.java, core/src/main/java/org/frankframework/util/CompactSaxHandler.java, core/src/main/java/org/frankframework/util/MessageBrowsingFilter.java, core/src/test/java/org/frankframework/core/PipeLineTest.java, core/src/test/java/org/frankframework/http/WebServiceSenderResultTest.java, core/src/test/java/org/frankframework/pipes/JsonWellFormedCheckerTest.java, core/src/test/java/org/frankframework/util/XpathTest.java, filesystem/src/main/java/org/frankframework/filesystem/MsalClientAdapter.java, security/src/test/java/org/frankframework/lifecycle/servlets/ServletAuthenticatorTest.java
=> Fix closeable not being closed

console/frontend/src/main/frontend/src/app/views/status/adapter-status/adapter-status.component.html
Backport to 8.3 of #7831 by @Thermalight
=> Fix js exception when no listener in receiver

docker/Tomcat/webapp/src/scripts/catalinaAdditional.properties
(cherry picked from commit d127f0c8b2bfb1755e74d1c39d7135bc454171ba)
=> Disable https setting by default in the Docker image

core/src/main/java/org/frankframework/pgp/Decrypt.java, core/src/main/java/org/frankframework/pgp/Encrypt.java, core/src/main/java/org/frankframework/pgp/PGPAction.java, core/src/main/java/org/frankframework/pgp/Sign.java, core/src/main/java/org/frankframework/pgp/Verify.java
Closes #7851 
This is a small refactor to remove a strange piece of code
=> Remove varargs from PGPAction

core/src/main/resources/digester-rules.xml
=> Change incorrect SapSystem beanClass

Docker.md, docker/Tomcat/webapp/src/scripts/catalinaAdditional.properties, test/src/main/secrets/credentials.propertis, test/src/main/secrets/influx/password, test/src/main/secrets/mongodb/password, test/src/main/secrets/mongodb/username, test/src/main/secrets/testalias/password, test/src/main/secrets/testalias/username, test/src/main/secrets/testiaf_user/password, test/src/main/secrets/testiaf_user/username
This pull request introduces significant updates to the HTTPS and secrets configuration for the Frank!Framework. The key changes include:
- **HTTPS Configuration Clarification**: The documentation now clearly states that the Frank!Framework operates on HTTP by default. It also provides guidance on how to secure the framework using a reverse proxy or system property.
- **Secrets Management Update**: The secrets management section has been enhanced to incorporate the use of the CredentialManager Capability, which allows for property substitution in configuration files. This addition aims to streamline the management of sensitive information.
- **Credential Mounting Instructions**: The instructions for mounting credentials have been revised to align with the preferred structure outlined in …
=> Update HTTPS instructions and secrets configuration

console/frontend/src/main/frontend/src/app/components/pages/pages-navigation/pages-navigation.component.html
=> Fix sidenav Overview menu closing on Connections page

core/src/main/java/org/frankframework/jdbc/JdbcListener.java, core/src/main/java/org/frankframework/jdbc/JdbcTableListener.java, core/src/test/java/org/frankframework/jdbc/JdbcTableListenerNonDbTest.java, core/src/test/java/org/frankframework/jdbc/JdbcTableListenerTest.java
Backport for issue #7500 for 8.3
=> Add validations to JdbcTableListener for fields used in the query (#7894)

console/frontend/src/main/frontend/src/app/views/monitors/monitors-add-edit/monitors-add-edit.component.ts
=> Fix monitor edit not using put on submit

console/frontend/src/main/frontend/src/app/app.component.ts, console/frontend/src/main/frontend/src/app/components/pages/information-modal/information-modal.component.html, console/frontend/src/main/frontend/src/app/components/pages/information-modal/information-modal.component.ts, console/frontend/src/main/frontend/src/app/components/pages/pages-navigation/pages-navigation.component.ts, console/frontend/src/main/frontend/src/app/components/pages/pages-topnavbar/pages-topnavbar.component.html, console/frontend/src/main/frontend/src/app/services/server-info.service.ts
=> Handle lack of server info in console on slow / no backend

console/frontend/src/main/frontend/src/app/views/scheduler/scheduler.component.html, console/frontend/src/main/frontend/src/app/views/scheduler/scheduler.component.ts
This pull request introduces job group filtering and selection functionality in the scheduler view. Key features include:
- **Tabbed Interface**: A new tabbed interface allows users to select and filter job groups easily.
- **Dynamic Filtering**: Users can filter displayed job groups based on their selection, improving the organization of the view.
- **State Management**: A new `selectedJobGroup` property has been added to manage the current selection, enabling conditional rendering of job groups.
These enhancements aim to improve the overall user experience by providing a more structured and intuitive way to navigate job groups within the scheduler.
Closes #7732
=> Add job group filtering and selection

core/src/main/java/org/frankframework/core/Adapter.java
Ik denk dat dit voldoende zou moeten zijn?
=> Add log with stacktrace when processMessageDirect has an error

console/backend/src/main/java/org/frankframework/console/controllers/ClusterMemberEndpoint.java, console/frontend/src/main/frontend/src/app/app.component.ts, console/frontend/src/main/frontend/src/app/components/pages/information-modal/information-modal.component.ts, console/frontend/src/main/frontend/src/app/services/server-info.service.ts
=> Select new cluster member when previous selected has disappeared

console/frontend/src/main/frontend/src/app/app.component.ts, console/frontend/src/main/frontend/src/app/app.module.ts, console/frontend/src/main/frontend/src/app/app.service.ts, console/frontend/src/main/frontend/src/app/components/pages/pages-navigation/pages-navigation.component.html, console/frontend/src/main/frontend/src/app/components/tab-list/configuration-tab-list.component.ts, console/frontend/src/main/frontend/src/app/components/tab-list/tab-list.component.html, console/frontend/src/main/frontend/src/app/components/tab-list/tab-list.component.spec.ts, console/frontend/src/main/frontend/src/app/components/tab-list/tab-list.component.ts, console/frontend/src/main/frontend/src/app/views/configurations/configurations-show/configurations-show.component.html, console/frontend/src/main/frontend/src/app/views/configurations/configurations-show/configurations-show.component.ts, console/frontend/src/main/frontend/src/app/views/environment-variables/environment-variables.component.html, console/frontend/src/main/frontend/src/app/views/environment-variables/environment-variables.component.ts, console/frontend/src/main/frontend/src/app/views/monitors/monitors.component.html, console/frontend/src/main/frontend/src/app/views/scheduler/scheduler.component.html, console/frontend/src/main/frontend/src/app/views/scheduler/scheduler.component.ts, console/frontend/src/main/frontend/src/app/views/status/status.component.html, console/frontend/src/main/frontend/src/app/views/status/status.component.ts
* Move tabs logic to tabs-list components
* Create configurations-tab-list component which extends tabs-list and handles configurations & managing query-parameters
* Ability to hide IAF_Util, change 'All' tab name or remove 'All' tab
=> Move configuration tabs to separate component

core/src/main/java/org/frankframework/monitoring/Monitor.java, core/src/main/java/org/frankframework/monitoring/Trigger.java
=> Improve documentation for monitoring

console/frontend/src/main/frontend/src/app/components/pages/information-modal/information-modal.component.html, console/frontend/src/main/frontend/src/app/components/pages/information-modal/information-modal.component.ts, console/frontend/src/main/frontend/src/app/components/pages/pages-topnavbar/pages-topnavbar.component.html, console/frontend/src/main/frontend/src/app/services/server-info.service.ts
Add the name of the timezone in the system information and on hover in the header.
I've tried to show the GMT+X, but it didn't work out with the current methods that angular provides. I still consider this a bug and an issue should be created.
=> Show the timezone in the header and modal

ladybug/src/main/java/org/frankframework/ibistesttool/DebuggerActive.java, ladybug/src/main/java/org/frankframework/ibistesttool/DeploymentSpecificsBeanPostProcessor.java, ladybug/src/main/resources/springIbisDebuggerAdvice.xml
to a different bean in the correct layer of the application to make sure the event handlers are present
=> Move conditional loading of 'test tool enabled' 

console/frontend/src/main/frontend/src/app/components/pages/pages-navigation/scroll-to-top.component.ts, console/frontend/src/main/frontend/src/assets/css/bootstrap-fix.css, console/frontend/src/main/frontend/src/main.ts
This pull request enhances the functionality of the scroll-to-top button by improving its visibility and behavior.
- Change animation JS to adding a class
- Use visibility so hover won't give a pointer when scroll is hidden.
=> Fix scroll-to-top button visibility and behavior

console/frontend/src/main/frontend/src/app/app-routing.module.ts, console/frontend/src/main/frontend/src/app/components/has-access-to-link.directive.spec.ts, console/frontend/src/main/frontend/src/app/components/has-access-to-link.directive.ts, console/frontend/src/main/frontend/src/app/components/pages/pages-navigation/pages-navigation.component.html, console/frontend/src/main/frontend/src/app/components/pages/pages-navigation/pages-navigation.component.ts, console/frontend/src/main/frontend/src/app/guards/auth.guard.spec.ts, console/frontend/src/main/frontend/src/app/guards/auth.guard.ts, console/frontend/src/main/frontend/src/app/services/auth.service.ts, console/frontend/src/main/frontend/src/app/views/security-items/security-items.component.html, console/frontend/src/main/frontend/src/app/views/security-items/security-items.component.ts, console/frontend/src/main/frontend/src/app/views/security-items/security-items.service.ts
**Description:**
This pull request introduces significant enhancements to the authentication and navigation components of the application, focusing on access control and permission management.
**Key Changes:**
1. **Auth Guard Implementation:**
- Added an authentication guard that utilizes the `appHasAccessTo` directive to control access specific navigation links. This ensures that only authorized users can view certain features, thereby improving security and user experience.
2. **Refactoring of AuthService:**
- The `AuthService` has been refactored to leverage Angular's dependency injection, enhancing maintainability and readability. 
- Introduced a new method for asynchronous permission loading, which reduces nested subscriptions and improves the overall structure of the code.
3. …
=> Hide navigation elements and check if user has access to routes

akamai/src/main/java/org/frankframework/extensions/akamai/NetStorageSender.java, commons/src/main/java/org/frankframework/util/StreamUtil.java, core/src/main/java/org/frankframework/http/AbstractHttpSession.java, core/src/main/java/org/frankframework/http/HttpMessageEntity.java, core/src/main/java/org/frankframework/http/HttpSender.java, core/src/main/java/org/frankframework/http/mime/MessageContentBody.java, core/src/main/java/org/frankframework/stream/SerializableFileReference.java, core/src/test/java/org/frankframework/http/HttpSenderTest.java, core/src/test/resources/Http/Responses/simpleMockedHttpGetWithUrlParamAndPath.txt, core/src/test/resources/Http/Responses/simpleMockedHttpMultipartWithUrlPathAndQueryParam.txt, core/src/test/resources/Http/Responses/simpleMockedHttpPostWithUrlPathAndQueryParam.txt
Some small refactorings that I'd like to merge before doing more work on copying some of the code out to reuse for ApiListener response.
=> Some small refactorings in HttpSender and related code

core/src/main/java/org/frankframework/http/HttpSender.java, core/src/test/resources/Http/Responses/mtomWithoutFirstBodyPartName.txt, core/src/test/resources/Http/Responses/multipartWithoutFirstBodyPartName.txt, core/src/test/resources/Http/Responses/parametersToSkip.txt, core/src/test/resources/Http/Responses/simpleMockedHttpMtom.txt, core/src/test/resources/Http/Responses/simpleMockedHttpMultipart.txt, core/src/test/resources/Http/Responses/simpleMockedHttpMultipartWithUrlPathAndQueryParam.txt, core/src/test/resources/Http/Responses/simpleMockedHttpPostUrlEncoded.txt, core/src/test/resources/Http/Responses/simpleMockedMultipartHttp1.txt, core/src/test/resources/Http/Responses/simpleMockedMultipartHttp2.txt, core/src/test/resources/Http/Responses/simpleMockedMultipartHttp3.txt, core/src/test/resources/Http/Responses/simpleMockedMultipartMtom1.txt, core/src/test/resources/Http/Responses/simpleMockedMultipartMtom2.txt, core/src/test/resources/Http/Responses/simpleMockedMultipartMtom3.txt, core/src/test/resources/Http/Responses/simpleMockedWssMtom.txt, core/src/test/resources/Http/Responses/simpleMockedWssMultipart.txt, core/src/test/resources/Http/Responses/simpleMockedWssMultipart2.txt, core/src/test/resources/Http/Responses/simpleMockedWssMultipartMtom.txt, core/src/test/resources/Http/Responses/simpleMtomFromParametersAndMultipartXml.txt, core/src/test/resources/Http/Responses/simpleMtomFromParametersAndMultipartXmlNoPartName.txt, core/src/test/resources/Http/Responses/simpleMultipartFromParametersAndMultipartXml.txt, core/src/test/resources/Http/Responses/simpleMultipartFromParametersAndMultipartXmlNoPartName.txt, core/src/test/resources/Http/Responses/skipEmptyMultipartXmlSessionKey.txt
One more cleanup in HttpSender code.
Does change several test-expectations, but only in a way that doesn't seem relevant to me.
=> One more cleanup in HttpSender code

console/frontend/src/main/frontend/src/app/views/monitors/monitors-add-edit/monitors-add-edit.component.html, console/frontend/src/main/frontend/src/app/views/monitors/monitors-add-edit/monitors-add-edit.component.ts, console/frontend/src/main/frontend/src/app/views/test-pipeline/test-pipeline.component.ts
This pull request introduces default initialization for trigger severity filters and implements validation to prevent negative values for period and threshold. It ensures that both values are set together and enhances HTML accessibility by improving label associations for form fields.
Closes #7967
=> Fix trigger: add defaults and add validation

console/frontend/src/main/frontend/src/app/views/inlinestore/inlinestore.component.html, core/src/main/java/org/frankframework/management/bus/endpoints/InlineStorage.java, core/src/main/java/org/frankframework/processors/TrackPreviousPipeInMetadataProcessor.java, core/src/test/resources/Management/getProcessStorage.json
=> Add missing configuration name attribute in `InlineStoreItem`

console/frontend/src/main/frontend/src/app/components/tab-list/configuration-tab-list.component.ts, console/frontend/src/main/frontend/src/app/views/environment-variables/environment-variables.component.html, console/frontend/src/main/frontend/src/app/views/environment-variables/environment-variables.component.ts, console/frontend/src/main/frontend/src/app/views/monitors/monitors.component.ts, console/frontend/src/main/frontend/src/app/views/status/status.component.ts, core/src/main/java/org/frankframework/management/bus/endpoints/EnvironmentVariables.java
This pull request addresses an issue where the browser location history was getting stuck when navigating through tabs. The fix ensures that the location history updates correctly, allowing for seamless tab navigation.
Closes #8068
=> Fix the browser history location getting stuck at tabs

pom.xml
This version hopefully finally fixes all issues we ran into.
=> Bump Log4J2 version to Log4J2.24.3

core/src/main/java/org/frankframework/align/Json2Xml.java, core/src/test/java/org/frankframework/pipes/Json2XmlValidatorTest.java, core/src/test/resources/Validation/Json2Xml/ParameterSubstitution/CommonResponse.xsd, core/src/test/resources/Validation/Json2Xml/ParameterSubstitution/Main.xsd, core/src/test/resources/Validation/Json2Xml/ParameterSubstitution/expected_output.json
=> JSON Validation parameter substitution deeper search

core/src/main/java/org/frankframework/http/HttpSessionBase.java
=> Create a new AuthState for each request instead of re-using it

console/frontend/src/main/frontend/src/app/app-routing.module.ts, console/frontend/src/main/frontend/src/app/app.module.ts, console/frontend/src/main/frontend/src/app/components/has-access-to-link.directive.ts, console/frontend/src/main/frontend/src/app/components/pages/pages-navigation/pages-navigation.component.html, console/frontend/src/main/frontend/src/app/guards/auth.guard.ts, console/frontend/src/main/frontend/src/app/views/configurations/configurations-manage/configurations-manage.component.html, console/frontend/src/main/frontend/src/app/views/ibisstore-summary/ibisstore-summary.component.html, console/frontend/src/main/frontend/src/app/views/logging/logging-manage/logging-manage.component.html, console/frontend/src/main/frontend/src/app/views/logging/logging-manage/logging-manage.component.ts, console/frontend/src/main/frontend/src/app/views/monitors/monitors.component.html, console/frontend/src/main/frontend/src/app/views/scheduler/scheduler.component.html, console/frontend/src/main/frontend/src/app/views/status/adapter-status/adapter-status.component.html, console/frontend/src/main/frontend/src/app/views/status/flow/flow.component.html, console/frontend/src/main/frontend/src/app/views/status/status.component.html, console/frontend/src/main/frontend/src/app/views/storage/storage-list/storage-list-dt/storage-list-dt.component.html, console/frontend/src/main/frontend/src/app/views/storage/storage-list/storage-list.component.html, console/frontend/src/main/frontend/src/app/views/storage/storage-view/storage-view.component.html, console/frontend/src/main/frontend/src/app/views/webservices/webservices.component.html, console/frontend/src/main/frontend/src/assets/css/bootstrap-fix.css
=> Disable or hide page elements and buttons if the user is not allowed to access these

messaging/src/main/java/org/frankframework/extensions/mqtt/MqttFacade.java, messaging/src/main/java/org/frankframework/extensions/mqtt/MqttSender.java
=>  Implement in memory store, make persistenceDirectory optional, improve documentation and minor refactor

core/src/main/java/org/frankframework/pipes/JsonPipe.java, core/src/test/java/org/frankframework/pipes/JsonPipeTest.java
=> Implement a custom name for the root element

console/frontend/src/main/frontend/src/app/components/quick-submit-form.directive.spec.ts, console/frontend/src/main/frontend/src/app/components/quick-submit-form.directive.ts, console/frontend/src/main/frontend/src/app/views/configurations/configurations-upload/configurations-upload.component.html, console/frontend/src/main/frontend/src/app/views/ibisstore-summary/ibisstore-summary.component.html, console/frontend/src/main/frontend/src/app/views/jdbc/jdbc-browse-tables/jdbc-browse-tables.component.html, console/frontend/src/main/frontend/src/app/views/jdbc/jdbc-execute-query/jdbc-execute-query.component.html, console/frontend/src/main/frontend/src/app/views/jms/jms-browse-queue/jms-browse-queue.component.html, console/frontend/src/main/frontend/src/app/views/jms/jms-send-message/jms-send-message.component.html, console/frontend/src/main/frontend/src/app/views/liquibase/liquibase.component.html, console/frontend/src/main/frontend/src/app/views/logging/logging-add/logging-add.component.html, console/frontend/src/main/frontend/src/app/views/monitors/monitors-add-edit/monitors-add-edit.component.html, console/frontend/src/main/frontend/src/app/views/monitors/monitors-new/monitors-new.component.html, console/frontend/src/main/frontend/src/app/views/monitors/monitors.component.html, console/frontend/src/main/frontend/src/app/views/scheduler/scheduler-add-edit-parent.component.html, console/frontend/src/main/frontend/src/app/views/test-pipeline/test-pipeline.component.html, console/frontend/src/main/frontend/src/app/views/test-service-listener/test-service-listener.component.html, console/frontend/src/main/frontend/src/app/views/websocket-test/websocket-test.component.html
=> Fix quick submit in forms

ladybug/pom.xml
(cherry picked from commit f898bd7a00d6b98010236c33314ce349eb3c7fae)
=> Bump Ladybug from 3.0-20241223.170709 to 3.0-20250107.001038

credentialProvider/src/main/java/org/frankframework/credentialprovider/delinea/DelineaClient.java, credentialProvider/src/main/java/org/frankframework/credentialprovider/delinea/DelineaCredentialFactory.java, credentialProvider/src/main/java/org/frankframework/credentialprovider/delinea/DelineaCredentials.java, credentialProvider/src/main/java/org/frankframework/credentialprovider/delinea/Secret.java, credentialProvider/src/test/java/org/frankframework/credentialprovider/delinea/DelineaClientTest.java, credentialProvider/src/test/java/org/frankframework/credentialprovider/delinea/DelineaCredentialFactoryTest.java, credentialProvider/src/test/java/org/frankframework/credentialprovider/delinea/DelineaCredentialFactoryWithAutoCommentTest.java
And added a few improvements we made along the way:
* new Credentials implementation without Supplier
* Remove overloaded getSecret
* return null credentials if there isn't one found
* use beforeeach instead of beforeall
=> Delinea implementation - fix the unit test

console/frontend/src/main/frontend/src/app/app.component.ts, console/frontend/src/main/frontend/src/app/components/custom-views/custom-views.component.ts
=> Update app initialization to use AppConstants 'Global' instead of 'All'

.github/workflows/maven-build.yml, filesystem/src/main/java/org/frankframework/filesystem/MsalClientAdapter.java, filesystem/src/main/java/org/frankframework/filesystem/exchange/ExchangeFileSystem.java, filesystem/src/test/java/org/frankframework/filesystem/exchange/ExchangeConnectionCache.java, filesystem/src/test/java/org/frankframework/filesystem/exchange/ExchangeFileSystemActorTest.java, filesystem/src/test/java/org/frankframework/filesystem/exchange/ExchangeFileSystemListenerTest.java, filesystem/src/test/java/org/frankframework/filesystem/exchange/ExchangeFileSystemSenderTest.java, filesystem/src/test/java/org/frankframework/filesystem/exchange/ExchangeFileSystemTest.java, filesystem/src/test/java/org/frankframework/filesystem/exchange/ExchangeFileSystemTestHelper.java
(cherry picked from commit 320ecd114c4b69ba207fa3b9c58a8a7ecf0a3593)
=> Only setup exchange graph connection once (#8188)

core/src/main/java/org/frankframework/align/XmlAligner.java, core/src/test/java/org/frankframework/pipes/Json2XmlValidatorTest.java, core/src/test/resources/Validation/Json2Xml/WildcardElements/ExpectedOutput.json, core/src/test/resources/Validation/Json2Xml/WildcardElements/Wildcard-Input.xml, core/src/test/resources/Validation/Json2Xml/WildcardElements/Wildcard.xsd, core/src/test/resources/Validation/Xsd1.1/Wildcard/in_OK.xml
=> Fix for XML2JSON mapping with wildcard-types that have nested elements

core/src/main/java/org/frankframework/align/XmlAligner.java, core/src/test/java/org/frankframework/pipes/Json2XmlValidatorTest.java, core/src/test/resources/Validation/Json2Xml/WildcardElements/ExpectedOutput.json, core/src/test/resources/Validation/Json2Xml/WildcardElements/Wildcard-Input.xml, core/src/test/resources/Validation/Json2Xml/WildcardElements/Wildcard.xsd, core/src/test/resources/Validation/Xsd1.1/Wildcard/in_OK.xml
Fix for XML2JSON mapping with wildcard-types that have nested elements (#8206)
(cherry picked from commit 2ac6aff87ca916f2df49c3451fa826d957714c77)
=> Fix for XML2JSON mapping with wildcard-elements with nested elements (#8206)

pom.xml
=> Bump Frank!Doc to 4.0-SNAPSHOT (with improved frontend)

console/backend/src/main/java/org/frankframework/console/controllers/Init.java, core/src/main/resources/AppConstants.properties
(cherry picked from commit 493b6f674fc692044b2007b5ea72500ac8dee47e)
=> Enable monitoring by default

core/src/main/java/org/frankframework/util/TransformerPool.java
Closes #8203.
Unfortunately I have no tests for this.
=> Fix race condition on TransformerPool#getConfigMap

core/src/main/java/org/frankframework/util/TransformerPool.java
(cherry picked from commit 789b56841c2549cd5a0a12e4f5371e5ad525f9f7)
=> Fix race condition on TransformerPool#getConfigMap (#8236)

messaging/src/main/java/org/frankframework/extensions/mqtt/MqttSender.java
I know that this is currently being refactored, but also in its refactored state, this needs to be repaired. Also I need this fix on production :-).
=> Fixed setting MQTT topic through dynamic paramater

core/src/main/java/org/frankframework/configuration/Configuration.java, core/src/main/java/org/frankframework/core/Adapter.java, core/src/main/java/org/frankframework/management/bus/endpoints/Monitoring.java, core/src/main/java/org/frankframework/monitoring/AbstractMonitorDestination.java, core/src/main/java/org/frankframework/monitoring/IMonitorDestination.java, core/src/main/java/org/frankframework/monitoring/ITrigger.java, core/src/main/java/org/frankframework/monitoring/Monitor.java, core/src/main/java/org/frankframework/monitoring/MonitorManager.java, core/src/main/java/org/frankframework/monitoring/Trigger.java, core/src/main/java/org/frankframework/pipes/AbstractPipe.java, core/src/main/java/org/frankframework/util/XmlBuilder.java, core/src/test/java/org/frankframework/core/AdapterHideRegexTest.java, core/src/test/java/org/frankframework/core/ConfiguredTestBase.java, core/src/test/java/org/frankframework/lifecycle/TestConfigurableLifeCycle.java, core/src/test/java/org/frankframework/management/bus/endpoints/TestMonitoring.java, core/src/test/java/org/frankframework/monitoring/MonitorTest.java, core/src/test/java/org/frankframework/monitoring/TriggerTest.java, core/src/test/java/org/frankframework/pipes/PipeTestBase.java, core/src/test/java/org/frankframework/receivers/ReceiverTest.java, core/src/test/resources/Management/Monitoring/getManagerToXML.xml, larva/src/main/java/org/frankframework/pipes/LarvaPipe.java, larva/src/test/java/org/frankframework/pipes/LarvaPipeTest.java
=> Refactor MonitorManager, turn it into Spring Context and use Spring LifeCycles

core/src/main/java/org/frankframework/jta/narayana/PoolingDataSourceJDBCAccess.java
Hopefully this will produce a useable exception opposed _none_.
=> Log potential errors when creating Narayana database

core/src/main/java/org/frankframework/scheduler/SchedulerSender.java
(cherry picked from commit 7b102f282e8cf1ed20d6ebea5463632ed1e99946)
=> Deprecate SchedulerSender

core/src/main/java/org/frankframework/jdbc/AbstractJdbcQuerySender.java, core/src/main/java/org/frankframework/parameters/ParameterList.java, core/src/main/java/org/frankframework/pipes/MessageSendingPipe.java, core/src/main/java/org/frankframework/util/FileUtils.java, core/src/test/java/org/frankframework/parameters/ParameterListTest.java
=> ParameterList has a List, not IS a List

console/backend/src/main/java/org/frankframework/console/controllers/FrankApiService.java, console/backend/src/main/java/org/frankframework/console/controllers/ServerStatistics.java, console/backend/src/main/java/org/frankframework/console/controllers/socket/FrankApiWebSocketBase.java, console/backend/src/test/java/org/frankframework/console/controllers/WebTestConfiguration.java, console/frontend/src/main/frontend/src/app/app.component.ts
Added message cache check to see if it can cache the first server warnings message requested by the Console
=> Fix duplicate server warning response

console/backend/src/main/java/org/frankframework/console/controllers/FrankApiService.java, console/backend/src/main/java/org/frankframework/console/controllers/ServerStatistics.java, console/backend/src/main/java/org/frankframework/console/controllers/socket/FrankApiWebSocketBase.java, console/backend/src/test/java/org/frankframework/console/controllers/WebTestConfiguration.java, console/frontend/src/main/frontend/src/app/app.component.ts
=>  Fix duplicate server warning response

example/src/main/resources/ConfigurationHelloBeautifulWorld.xml, messaging/pom.xml, test/src/main/configurations/MainConfig/Configuration.xml, test/src/main/configurations/MainConfig/ConfigurationForPipe.xml
See https://github.com/frankframework/frankframework/pull/8345
=> Update config xsd and kafka dep

pom.xml
to avoid vulnerable netty transitive dependency
=> Update aws sdk in pom.xml

console/frontend/src/main/frontend/package-lock.json, console/frontend/src/main/frontend/src/app/views/status/server-warnings/server-warnings.component.html
=> Show errorstore warnings even when no server warnings

core/src/main/java/org/frankframework/threading/ThreadNamingTaskDecorator.java, core/src/main/resources/SpringApplicationContext.xml, core/src/test/resources/testApplicationContext.xml
(cherry picked from commit fcaabace8e91fa867772c11211fe8170cc62e9c7) #8370
=> Fix reusing thread-names when reusing threads from pool

console/backend/src/main/java/org/frankframework/console/configuration/RegisterServletEndpoints.java, console/backend/src/main/java/org/frankframework/console/configuration/SecurityChainConfigurer.java, ladybug/common/src/main/java/org/frankframework/ladybug/config/LadybugConfiguration.java, ladybug/common/src/main/java/org/frankframework/ladybug/config/LadybugSecurityChainConfigurer.java, ladybug/common/src/main/java/org/frankframework/ladybug/config/ServletRegistration.java
(cherry picked from commit 91ae4bc6f5fd3f7dc8556a4aa35fff1dbe28be28) #8411
=> Fix JEE authentication in console and ladybug

console/frontend/src/main/frontend/src/app/views/logging/logging.component.html, console/frontend/src/main/frontend/src/app/views/logging/logging.component.scss, console/frontend/src/main/frontend/src/app/views/logging/logging.component.ts
=> Scroll to previously opened log file & log file popout button

console/frontend/src/main/frontend/src/app/components/combobox/combobox.component.html, console/frontend/src/main/frontend/src/app/components/combobox/combobox.component.ts, console/frontend/src/main/frontend/src/app/components/monaco-editor/monaco-editor.component.scss, console/frontend/src/main/frontend/src/app/components/quick-submit-form.directive.spec.ts, console/frontend/src/main/frontend/src/app/components/quick-submit-form.directive.ts, console/frontend/src/main/frontend/src/app/views/jdbc/jdbc-execute-query/jdbc-execute-query.component.html, console/frontend/src/main/frontend/src/app/views/jms/jms-send-message/jms-send-message.component.html, console/frontend/src/main/frontend/src/app/views/scheduler/scheduler-add-edit-parent.component.html, console/frontend/src/main/frontend/src/app/views/test-pipeline/test-pipeline.component.html, console/frontend/src/main/frontend/src/app/views/test-service-listener/test-service-listener.component.html
=> Make code editor resizable and fix newline bug

aws/src/test/java/org/frankframework/filesystem/AmazonS3FileSystemActorTest.java, aws/src/test/java/org/frankframework/filesystem/AmazonS3FileSystemTest.java, aws/src/test/java/org/frankframework/senders/AmazonS3SenderTest.java, core/src/main/java/org/frankframework/configuration/digester/Digester.java, example/src/main/resources/ConfigurationHelloBeautifulWorld.xml, messaging/src/test/java/org/frankframework/extensions/mqtt/MqttSenderTest.java
This just fixes iaf-example. I've created #8425 for this to be fixed ...
=> Fix iaf-example. You may not nest configuration elements

core/src/main/java/org/frankframework/core/PipeLine.java, core/src/main/java/org/frankframework/ldap/LdapSender.java, core/src/main/java/org/frankframework/util/StreamCaptureUtils.java, core/src/test/java/org/frankframework/http/HttpSenderResultTest.java, credentialProvider/src/test/java/org/frankframework/credentialprovider/delinea/DelineaCredentialFactoryTest.java, ladybug/debugger/src/main/java/org/frankframework/ladybug/larva/ConvertToLarvaAction.java, ladybug/debugger/src/test/java/org/frankframework/ladybug/MessageCapturerTest.java, ladybug/debugger/src/test/java/org/frankframework/ladybug/larva/ConvertToLarvaActionTest.java, messaging/src/main/java/org/frankframework/extensions/mqtt/MqttClientFactory.java
Minor things: hidden class members, string duplication, etc.
=> Fix some new sonar issues

aws/src/main/java/org/frankframework/filesystem/AmazonS3FileSystem.java, aws/src/main/java/org/frankframework/filesystem/S3FileRef.java, aws/src/test/java/org/frankframework/senders/AmazonS3SenderTest.java, filesystem/src/test/java/org/frankframework/filesystem/FileSystemSenderTest.java
=> Fix a NPE when trying to list files and folders using the AmazonS3sender

core/src/main/java/org/frankframework/http/AbstractHttpSender.java
=> Add HttpSender not encoding URL to FrankDoc

docker/embedded/console/Dockerfile
Not escaping the new line broke the build
=> Fix Dockerfile multiline formatting

console/frontend/src/main/frontend/package.json
The version is dependent on Angular
=> Lock TypeScript version

core/src/main/java/org/frankframework/parameters/AbstractParameter.java, core/src/test/java/org/frankframework/http/HttpSenderTest.java, core/src/test/java/org/frankframework/parameters/ParameterTest.java, core/src/test/java/org/frankframework/testutil/ParameterBuilder.java, core/src/test/resources/Http/Responses/simpleMockedHttpPostWithUrlPatternParam.txt
=> Fix broken parameter pattern substitution

console/frontend/src/main/frontend/cypress.config.ts, console/frontend/src/main/frontend/src/app/views/jdbc/jdbc-browse-tables/jdbc-browse-tables.component.ts, console/frontend/src/main/frontend/src/app/views/jdbc/jdbc-execute-query/jdbc-execute-query.component.ts, console/frontend/src/main/frontend/src/app/views/test-pipeline/test-pipeline.component.ts, console/frontend/src/main/frontend/src/app/views/test-service-listener/test-service-listener.component.ts
This fix is mainly for Cypress itself becouse a human can't possibly be fast enough to type something before it's overwriten.
Video's are saved on failure and will be archived on Jenkins.
=> Fix overwriting Monaco Editor with session value and add e2e video's

core/src/main/java/org/frankframework/http/rest/ApiListener.java
=> Add text 'SECURITY RISK' to ConfigurationWarning for implicitly allowing all HTTP Request parameter names

core/src/main/java/org/frankframework/pipes/AbstractPipe.java, core/src/main/java/org/frankframework/pipes/AbstractValidator.java, core/src/main/java/org/frankframework/pipes/AsyncSenderWithListenerPipe.java, core/src/main/java/org/frankframework/pipes/Base64Pipe.java, core/src/main/java/org/frankframework/pipes/BytesOutputPipe.java, core/src/main/java/org/frankframework/pipes/ChecksumPipe.java, core/src/main/java/org/frankframework/pipes/CompareIntegerPipe.java, core/src/main/java/org/frankframework/pipes/CompareStringPipe.java, core/src/main/java/org/frankframework/pipes/CompressPipe.java, core/src/main/java/org/frankframework/pipes/CsvParserPipe.java, core/src/main/java/org/frankframework/pipes/DataSonnetPipe.java, core/src/main/java/org/frankframework/pipes/DelayPipe.java, core/src/main/java/org/frankframework/pipes/DomainTransformerPipe.java, core/src/main/java/org/frankframework/pipes/EscapePipe.java, core/src/main/java/org/frankframework/pipes/EtagHandlerPipe.java, core/src/main/java/org/frankframework/pipes/ExceptionPipe.java, core/src/main/java/org/frankframework/pipes/FixedForwardPipe.java, core/src/main/java/org/frankframework/pipes/FixedResultPipe.java, core/src/main/java/org/frankframework/pipes/ForEachChildElementPipe.java, core/src/main/java/org/frankframework/pipes/ForPipe.java, core/src/main/java/org/frankframework/pipes/GetFromSession.java, core/src/main/java/org/frankframework/pipes/GetPrincipalPipe.java, core/src/main/java/org/frankframework/pipes/HashPipe.java, core/src/main/java/org/frankframework/pipes/IfPipe.java, core/src/main/java/org/frankframework/pipes/IncreaseIntegerPipe.java, core/src/main/java/org/frankframework/pipes/IsUserInRolePipe.java, core/src/main/java/org/frankframework/pipes/IsXmlPipe.java
Closes https://github.com/frankframework/frank-doc/issues/186
=> Some more documentation improvements

console/frontend/src/main/frontend/src/app/views/status/flow/flow-modal/flow-modal.component.html, console/frontend/src/main/frontend/src/app/views/status/flow/flow-modal/flow-modal.component.ts
temporary fix for https://github.com/frankframework/frankframework/issues/8529
=> Disable flow diagram 'New tab' button on firefox (temp fix)

aspose/src/main/java/org/frankframework/extensions/aspose/services/conv/impl/CisConversionServiceImpl.java, aspose/src/main/java/org/frankframework/extensions/aspose/services/conv/impl/MediaTypeValidator.java, aws/src/test/java/org/frankframework/senders/AmazonS3SenderTest.java, commons/src/main/java/org/frankframework/util/StreamUtil.java, core/src/main/java/org/frankframework/stream/Message.java, core/src/main/java/org/frankframework/stream/SerializableFileReference.java, core/src/main/java/org/frankframework/util/MessageUtils.java, core/src/main/java/org/frankframework/util/XmlUtils.java, core/src/test/java/org/frankframework/http/cxf/SoapProviderTest.java, core/src/test/java/org/frankframework/pipes/ReplacerPipeTest.java, core/src/test/java/org/frankframework/stream/MessageTest.java, core/src/test/java/org/frankframework/util/MessageUtilsTest.java, core/src/test/java/org/frankframework/util/StreamCaptureUtilsTest.java
Backport of #8460 - 9826a41cad5e48c605255ec632386d0d7d1b688a
=> Simplify peeking into message

core/src/main/resources/AppConstants.properties, core/src/test/java/org/frankframework/configuration/digester/ValidateAttributeRuleTest.java
(cherry picked from commit 59c1e3478dea163fed7164d66ae9f1ec20812a2a)
=> Disable default-value Configuration warnings

core/src/main/java/org/frankframework/jta/narayana/DataSourceXAResourceRecoveryHelper.java, core/src/main/java/org/frankframework/jta/narayana/HeuristicDetectingRecoveryModule.java, core/src/main/java/org/frankframework/jta/narayana/JmsXAResourceRecoveryHelper.java, core/src/main/java/org/frankframework/jta/narayana/NarayanaConfigurationBean.java, core/src/main/java/org/frankframework/jta/narayana/NarayanaConnectionFactoryFactory.java, core/src/main/java/org/frankframework/jta/narayana/NarayanaDataSource.java, core/src/main/java/org/frankframework/jta/narayana/NarayanaDataSourceFactory.java, core/src/main/java/org/frankframework/jta/narayana/NarayanaJtaTransactionManager.java, core/src/main/resources/AppConstants.properties, core/src/test/java/org/frankframework/jdbc/migration/MigratorTest.java, core/src/test/java/org/frankframework/jta/narayana/HeuristicDetectingRecoveryModuleTest.java, core/src/test/java/org/frankframework/testutil/TestNarayanaDataSourceFactory.java, core/src/test/resources/Migrator/DatabaseChangelogCreate.xml, core/src/test/resources/resources.yml, pom.xml
Add periodicRecoveryPeriod property (https://github.com/frankframework/frankframework/pull/8615)
=> Add periodicRecoveryPeriod property

core/src/main/java/org/frankframework/jdbc/JdbcListener.java, core/src/main/java/org/frankframework/jdbc/XmlQuerySender.java, core/src/main/java/org/frankframework/util/JdbcUtil.java, core/src/test/java/org/frankframework/jdbc/JdbcTableListenerTest.java
Potentially reduce amount of network access when setting parameters in JDBC prepared statement (effectiveness differes per database).
=> Minor Jdbc Optimisation

core/src/test/resources/lifecycle/nowebcontent.txt
From initial set of unit tests
=> Remove remaining folder

core/src/main/java/org/frankframework/http/HttpMessageEntity.java
(cherry picked from commit cb714eb4e3e41596070c033474e86f19fccf76c6)
=> Conditionally supress log warning

core/src/test/resources/Jdbc/StoredProcedureQuerySender/DatabaseChangelog-StoredProcedures.xml
See if this fixes broken Jenkins build
=> Fix PK name in test table

ladybug/debugger/src/main/java/org/frankframework/ladybug/larva/ConvertToLarvaAction.java
Moet ook gebackport worden naar de 7.9
=> Fix NPE in ladybug to larva code

credentialProvider/src/main/java/org/frankframework/credentialprovider/delinea/DelineaCredentialFactory.java
indenting spaces weren't processed correctly, removed them so the code blocks format nicely in the frank doc
=> remove spaces, this is formatted in the frank doc

core/src/main/java/org/frankframework/lifecycle/WebContentServlet.java
=> Make sure to output using text/html for the WebContentServlet overview page

core/src/main/java/org/frankframework/http/rest/ApiListenerServlet.java, core/src/test/java/org/frankframework/http/rest/ApiListenerServletTest.java
cherry picked from commit c44abdcc3ac40f19f11fc4603333192bd021c0f1
Backport of d56ac431999e95bf61e93d308daba88ee35753cc
=> Fix NPE in ApiListenerServlet

pom.xml
=> Update dependencies for CVE's

console/war/pom.xml, ladybug/common/pom.xml, ladybug/debugger/pom.xml, ladybug/pom.xml, ladybug/rerunner/pom.xml, pom.xml
Try again for all ladybug dependencies and update netty as well.
=> Update transitive cxf dependencies

pom.xml
Reverts frankframework/frankframework#8754
=> Revert "Bump org.liquibase:liquibase-core from 4.29.2 to 4.31.1"

FRANKDOC.md, credentialProvider/src/main/java/org/frankframework/credentialprovider/AbstractMapCredentialFactory.java, credentialProvider/src/main/java/org/frankframework/credentialprovider/AnsibleVaultCredentialFactory.java, credentialProvider/src/main/java/org/frankframework/credentialprovider/FileSystemCredentialFactory.java, credentialProvider/src/main/java/org/frankframework/credentialprovider/ICredentialFactory.java, credentialProvider/src/main/java/org/frankframework/credentialprovider/PropertyFileCredentialFactory.java, credentialProvider/src/main/java/org/frankframework/credentialprovider/WildFlyCredentialFactory.java, kubernetes/src/main/java/org/frankframework/credentialprovider/KubernetesCredentialFactory.java
=> Add documentation and lowered access modifiers where possible

akamai/src/main/java/org/frankframework/extensions/akamai/HashAlgorithm.java, akamai/src/main/java/org/frankframework/extensions/akamai/NetStorageRequest.java, akamai/src/main/java/org/frankframework/extensions/akamai/NetStorageSender.java, akamai/src/test/java/org/frankframework/extensions/akamai/NetStorageCmsSignerTest.java, akamai/src/test/java/org/frankframework/extensions/akamai/NetStorageSenderTest.java, console/backend/src/main/java/org/frankframework/console/util/RequestMessageBuilder.java, console/backend/src/main/java/org/frankframework/console/util/RequestUtils.java, console/backend/src/main/java/org/frankframework/console/util/ResponseUtils.java, console/backend/src/test/java/org/frankframework/console/controllers/ConfigurationStatusTest.java, console/backend/src/test/java/org/frankframework/console/controllers/ConfigurationsEndpointTest.java, console/backend/src/test/java/org/frankframework/console/controllers/ConnectionOverviewTest.java, console/backend/src/test/java/org/frankframework/console/controllers/EnvironmentVariablesTest.java, console/backend/src/test/java/org/frankframework/console/controllers/InlineMessageStoreOverviewTest.java, console/backend/src/test/java/org/frankframework/console/controllers/SecurityItemsTest.java, console/backend/src/test/java/org/frankframework/console/controllers/ServerStatisticsTest.java, console/war/src/main/resources/application.properties, core/src/main/resources/AppConstants.properties, management-gateway/src/main/java/org/frankframework/management/gateway/events/AbstractGatewayEvent.java, management-gateway/src/main/java/org/frankframework/management/gateway/events/ClusterMemberEvent.java, security/src/main/java/org/frankframework/lifecycle/servlets/ServletConfiguration.java, security/src/test/java/org/frankframework/lifecycle/servlets/DummyAuthenticator.java, security/src/test/java/org/frankframework/lifecycle/servlets/DummyAuthenticatorTest.java, security/src/test/java/org/frankframework/lifecycle/servlets/ServletAuthenticatorTest.java, security/src/test/java/org/frankframework/lifecycle/servlets/YmlFileAuthenticatorTest.java
Closes #8831.
Cherry-picked 2 previous commits to fix the issue, that touched a few extra files but none of the changes looks risky to me (changes to docs or formatting, basically).
=> Change Console Log Levels

batch/src/main/java/org/frankframework/jdbc/BatchTransformerPipeBase.java, batch/src/main/java/org/frankframework/jdbc/Result2LobWriterBase.java, core/src/main/java/org/frankframework/jdbc/JdbcFacade.java, core/src/main/java/org/frankframework/jdbc/JdbcIteratingPipeBase.java, core/src/test/java/org/frankframework/receivers/ReceiverTest.java, nn-specials/src/main/java/org/frankframework/extensions/api/ApiStreamPipe.java
Remove JmsRealm attribute from JDBC related frank elements.
See also; #8849
=> Remove JNDI base from JDBC facade

batch/src/main/java/org/frankframework/jdbc/Result2LobWriterBase.java, nn-specials/src/main/java/org/frankframework/extensions/api/ApiStreamPipe.java
=> Ensure there is an upgrade path and improve deprecation warnings

console/backend/src/test/java/org/frankframework/console/controllers/TransactionalStorageTest.java
Based on https://github.com/frankframework/frankframework/pull/8857/files where we found out a unit test was missing for this.
=> Check the bus action in the unit tests for resendReceiverMessage

test/src/main/configurations/JDBC/ConfigurationResultSetIteratingPipe.xml
Dit gaf een warning bij opstarten
=> Remove jmsRealm which is removed

test/src/test/java/org/frankframework/runner/RunCypressE2eTest.java
Use the `OutboundGateway` to gather health information and verify if the Framework has started (and loaded configurations).
After verification, the Test Container for Cypress will be started.
=> Wait on IafTestInitializer to be healthy before running e2e tests

core/src/test/java/org/frankframework/pipes/JwtPipeTest.java
* The `attributeAndParameter` tests now validate the signature instead of just checking the header.
* Fixed issues where time differences in JWT payloads caused test failures.
* Added a helper function to check if two tokens have the same signature.
* Introduced a method to retrieve the signature part of a JWT.
* The Base64 encoded header is now stored in a variable to improve readability when checking if a token contains the specified header.
Fixes ci issues mentioned at:
https://github.com/frankframework/frankframework/issues/8597#issuecomment-2777828904
https://github.com/frankframework/frankframework/issues/8597#issuecomment-2796630620
=> Refactor JWT pipe tests for clarity and consistency; fix processing time-related issue

core/src/test/java/org/frankframework/pipes/JwtPipeTest.java
This fix addresses a CI issue where differences in computation time resulted in varying JWT token signatures, leading to test failures. Instead of comparing the signatures directly, the approach has been changed to validate the signature using the same secret. This ensures that both tokens were created with the same secret.
Additionally, this change allows testing the right-padding functionality, ensuring consistency in token verification.
=> Fix CI issue caused by time-related differences in JWT signature generation

.github/ISSUE_TEMPLATE/4-documentation.yml
This is to request a change in the Docs. 
It has an option to be prefilled with the "Request a change" button in the Frank!Doc.
=> Add a "Documentation change" issue template

pom.xml
I was a bit too fast with the dependabot pr
=> Revert surefire update

.github/CODEOWNERS, .github/dependabot.yml
=> Change dependabot reviewers to CODEOWNERS file

pom.xml
We almost forgot to remove this profile along with the defunct module
=> Remove Maven profile test-integration

.github/CODEOWNERS
@nielsm5 , kan jij ook even kijken? Ik denk dat de opzet wel duidelijk is. Indien akkoord, even wachten met mergen totdat we de nieuwe -backend en -frontend groepen hebben aangemaakt.
Zie ook: https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/about-code-owners
=> Be more specific in the code owners file

CONTRIBUTING.md, RELEASES.md, TESTING_WITH_IAF-TEST.md, core/src/main/java/org/frankframework/management/bus/endpoints/SecurityItems.java, core/src/main/java/org/frankframework/pipes/CredentialCheckingPipe.java, core/src/main/java/org/frankframework/util/CredentialFactory.java, core/src/test/java/org/frankframework/pipes/CredentialCheckingPipeTest.java, credentialProvider/src/main/java/org/frankframework/credentialprovider/CredentialFactory.java, credentialProvider/src/main/java/org/frankframework/credentialprovider/FileSystemCredentialFactory.java, credentialProvider/src/main/java/org/frankframework/credentialprovider/FileSystemCredentials.java, credentialProvider/src/main/java/org/frankframework/credentialprovider/ICredentialFactory.java, credentialProvider/src/main/java/org/frankframework/credentialprovider/MapCredentialFactory.java, credentialProvider/src/main/java/org/frankframework/credentialprovider/WildFlyCredentialFactory.java, credentialProvider/src/test/java/org/frankframework/credentialprovider/CredentialFactoryTest.java, credentialProvider/src/test/java/org/frankframework/credentialprovider/CredentialResolverTest.java, credentialProvider/src/test/java/org/frankframework/credentialprovider/MockCredentialFactory.java, credentialProvider/src/test/java/org/frankframework/credentialprovider/PropertyFileCredentialFactoryTest.java, idin/src/main/java/org/frankframework/extensions/idin/IdinSender.java, idin/src/test/java/org/frankframework/extensions/idin/IdinSenderTest.java, idin/src/test/resources/credentialprovider.properties, idin/src/test/resources/credentials.properties, kubernetes/src/main/java/org/frankframework/credentialprovider/KubernetesCredentialFactory.java
backport for fixes for using multiple or no credential factories
=> Fix multiple credential providers

.github/dependabot.yml
NPM and Docker were not removed yet
=> Remove other reviewes from dependabot

core/src/test/resources/testBusApplicationContext.xml, messaging/src/test/resources/testBusApplicationContext.xml, pom.xml
Superseeds https://github.com/frankframework/frankframework/pull/9030, https://github.com/frankframework/frankframework/pull/9035, https://github.com/frankframework/frankframework/pull/9029.
=> Bump Spring and CXF

core/src/main/java/org/frankframework/core/ISender.java, core/src/test/java/org/frankframework/pipes/ForEachChildElementPipeTest.java, core/src/test/java/org/frankframework/senders/IbisLocalSenderTest.java
(cherry picked from commit b021800cbb712cea88e20b18de0be924642b79ac)
=> Fix "ISender#sendMessageOrThrow" closing result that has also been referenced in Session keys

console/backend/src/main/java/org/frankframework/console/configuration/SecurityChainConfigurer.java, ladybug/common/src/main/java/org/frankframework/ladybug/config/LadybugSecurityChainConfigurer.java, security/src/main/java/org/frankframework/lifecycle/servlets/OAuth2Authenticator.java, security/src/main/java/org/frankframework/lifecycle/servlets/ServletAuthenticatorBase.java
closes https://github.com/frankframework/frankframework/issues/9085
=> Fix oauth flow in standalone app

core/src/main/java/org/frankframework/jdbc/datasource/PoolingDataSourceFactory.java, core/src/main/java/org/frankframework/jta/narayana/NarayanaConfigurationBean.java, core/src/main/java/org/frankframework/jta/narayana/NarayanaJtaTransactionManager.java, core/src/main/resources/AppConstants.properties
(cherry picked from commit c2336d44d4e5b3a6a5e1585b5454f24004a9cb2a)
=> Add expiryScanner to either purge or move expired items

larva/src/main/java/org/frankframework/larva/Scenario.java, larva/src/main/java/org/frankframework/larva/Step.java, larva/src/test/java/org/frankframework/larva/StepTest.java
Apply review feedback from previous Larva PR
=> Larva minor improvements

core/src/main/java/org/frankframework/http/AbstractHttpSender.java, core/src/main/java/org/frankframework/http/AbstractHttpSession.java, filesystem/src/main/java/org/frankframework/filesystem/MsalClientAdapter.java, test/src/test/testtool/HttpSender/input.xml, test/src/test/testtool/HttpSender/output.xml, test/src/test/testtool/HttpSender/scenario01.properties
I've also added a scenario for the `CallConcurrentSharedHTTPResource` adapter, but I cant figure out a proper ignore rule..
=> Make HTTP timeout work based on the HttpSession (sharedResources)

core/src/main/java/org/frankframework/pipes/IfPipe.java, core/src/main/java/org/frankframework/stream/Message.java, core/src/main/java/org/frankframework/util/MessageUtils.java, core/src/test/java/org/frankframework/components/ComponentLoaderTest.java, core/src/test/java/org/frankframework/http/cxf/SoapProviderTest.java, core/src/test/java/org/frankframework/pipes/DataSonnetPipeTest.java, core/src/test/java/org/frankframework/pipes/IfPipeJsonPathTest.java, core/src/test/java/org/frankframework/pipes/IfPipeTest.java, core/src/test/java/org/frankframework/pipes/IfPipeXpathTest.java, core/src/test/java/org/frankframework/stream/MessageTest.java, core/src/test/java/org/frankframework/testutil/TestAssertions.java, core/src/test/java/org/frankframework/util/MessageUtilsTest.java, messaging/src/test/java/org/frankframework/extensions/mqtt/MqttClientFactoryTest.java
=> Message closed too early

core/src/main/java/org/frankframework/parameters/AbstractParameter.java, core/src/test/java/org/frankframework/parameters/ParameterTest.java
=> Improve JSON Path validation and evaluation in Parameter

console/frontend/src/main/frontend/src/app/components/file-viewer/file-viewer.component.ts, console/frontend/src/main/frontend/src/app/components/toasts-container/toasts-container.component.html, console/frontend/src/main/frontend/src/app/guards/auth.guard.ts, console/frontend/src/main/frontend/src/app/services/auth.service.ts, console/frontend/src/main/frontend/src/app/views/error/error.component.ts
=> Fix Console error page & logging page on framework startup error

console/frontend/src/main/frontend/src/app/views/adapterstatistics/adapterstatistics.component.html, console/frontend/src/main/frontend/src/app/views/adapterstatistics/adapterstatistics.component.ts, console/frontend/src/main/frontend/src/app/views/adapterstatistics/adapterstatistics.service.ts
=> Sort processing receivers statistics based on thread name

console/frontend/src/main/frontend/package-lock.json, console/frontend/src/main/frontend/package.json
=> Update frank-config-layout to 1.1.2

console/frontend/src/main/frontend/src/app/views/status/flow/flow-modal/flow-modal.component.scss, console/frontend/src/main/frontend/src/assets/css/style.css
This PR improves the flow modal size to use up all the available space the modal system lets me have without breaking anything
=> Improve flow modal window size

console/frontend/src/main/frontend/src/app/components/datatable/datatable.component.ts, console/frontend/src/main/frontend/src/app/components/th-sortable.directive.spec.ts, console/frontend/src/main/frontend/src/app/components/th-sortable.directive.ts, console/frontend/src/main/frontend/src/app/views/configurations/configurations-manage/configurations-manage-details/configurations-manage-details.component.ts, console/frontend/src/main/frontend/src/app/views/storage/storage-list/storage-list.component.html, console/frontend/src/main/frontend/src/app/views/storage/storage-list/storage-list.component.ts
=> Add sorting options in error store

aws/src/main/java/org/frankframework/filesystem/AmazonS3FileSystem.java, filesystem/src/main/java/org/frankframework/filesystem/AbstractConnectedFileSystem.java, filesystem/src/main/java/org/frankframework/filesystem/AbstractFileSystem.java, filesystem/src/main/java/org/frankframework/filesystem/AbstractFileSystemListener.java, filesystem/src/main/java/org/frankframework/filesystem/FileSystemActor.java, filesystem/src/main/java/org/frankframework/filesystem/ImapFileSystem.java, filesystem/src/main/java/org/frankframework/filesystem/LocalFileSystem.java, filesystem/src/main/java/org/frankframework/filesystem/exchange/ExchangeFileSystem.java, filesystem/src/main/java/org/frankframework/filesystem/smb/Samba1FileSystem.java, filesystem/src/main/java/org/frankframework/filesystem/smb/Samba2FileSystem.java
=> Handle failure to restore original file last-modified-time

console/frontend/src/main/frontend/src/app/views/scheduler/scheduler.component.html, console/frontend/src/main/frontend/src/app/views/scheduler/scheduler.component.scss, console/frontend/src/main/frontend/src/app/views/scheduler/scheduler.component.ts
Remove unnecessary information, sort job messages from newest to oldest & small visual improvements.
=> Cleanup scheduler & job information

console/frontend/src/main/frontend/src/app/services/server-time.service.ts
Fixes Console being very slow because of timezone error when converting time/date info to server timezone
=> Add errorhandling to server-time service

console/backend/src/main/java/org/frankframework/console/controllers/Adapters.java, console/backend/src/test/resources/management/web/init-with-roles.json, console/frontend/src/main/frontend/cypress/e2e/views/status.cy.ts, core/src/main/java/org/frankframework/configuration/Configuration.java, core/src/main/java/org/frankframework/configuration/ConfigurationDigester.java, core/src/main/java/org/frankframework/core/Adapter.java, core/src/main/java/org/frankframework/core/PipeLine.java, core/src/main/java/org/frankframework/jdbc/migration/AbstractDatabaseMigrator.java, core/src/main/java/org/frankframework/lifecycle/ConfiguringLifecycleProcessor.java, core/src/main/java/org/frankframework/lifecycle/events/AdapterMessageEvent.java, core/src/main/java/org/frankframework/lifecycle/events/ApplicationMessageEvent.java, core/src/main/java/org/frankframework/lifecycle/events/MessageEvent.java, core/src/main/java/org/frankframework/lifecycle/events/MessageKeepingEventListener.java, core/src/main/java/org/frankframework/management/bus/endpoints/AdapterStatus.java, core/src/main/java/org/frankframework/pipes/MessageSendingPipe.java, core/src/main/java/org/frankframework/receivers/Receiver.java, core/src/test/java/org/frankframework/http/openapi/OpenApiTestBase.java, messaging/src/main/java/org/frankframework/extensions/mqtt/MqttListener.java, messaging/src/main/java/org/frankframework/unmanaged/PollGuard.java, messaging/src/test/java/org/frankframework/jms/PushingJmsListenerTest.java, nn-specials/src/main/java/org/frankframework/extensions/fxf/FxfListener.java
There's a small API fix that will need to be backported.
I've made it so it's no longer required to have a Pipeline (by adding 2 null-checks).
Made it possible to send AdapterMessageEvents from inside pipes, senders e.t.c.
=> Implement AdapterMessageEvents

core/src/main/java/nl/nn/adapterframework/logging/IbisLoggerConfigurationFactory.java
Very silly error, StreamUtil uses a logger which causes the logger to not initialize...
=> Remove StreamUtil import from log initialisation classes

console/frontend/src/main/frontend/src/app/components/datatable/datatable.component.html, console/frontend/src/main/frontend/src/app/views/storage/storage-list/storage-list.component.ts
=> Fix filesystem message storage not displaying messages in list

core/src/main/java/org/frankframework/parameters/AbstractParameter.java, core/src/main/java/org/frankframework/parameters/DateParameter.java, core/src/test/java/org/frankframework/parameters/DateParameterTest.java
=> Try to improve parameter pattern parsing and formatting code

core/src/main/java/org/frankframework/core/PipeLineSession.java, core/src/main/java/org/frankframework/stream/OverflowToDiskOutputStream.java, core/src/main/java/org/frankframework/stream/SerializableFileReference.java, core/src/main/java/org/frankframework/util/CleanerProvider.java, core/src/main/java/org/frankframework/util/flow/graphviz/GraphvizEngine.java
Hopefully closes #9389
Prepares the code for being able to turn off leak-logging, for better performance.
=> Improving Leak Logging / Cleaners

core/src/main/java/org/frankframework/jdbc/datasource/ObjectFactory.java, core/src/main/java/org/frankframework/jdbc/datasource/ResourceObjectLocator.java, core/src/main/java/org/frankframework/mongodb/MongoClientFactory.java, core/src/main/java/org/frankframework/mongodb/MongoClientFactoryFactory.java, core/src/main/java/org/frankframework/mongodb/MongoDbSender.java, core/src/main/resources/SpringApplicationContext.xml, core/src/test/java/org/frankframework/mongodb/MongoDbSenderTest.java, messaging/src/main/java/org/frankframework/extensions/mqtt/MqttClientFactory.java, messaging/src/main/java/org/frankframework/extensions/mqtt/MqttClientFactoryFactory.java, messaging/src/main/java/org/frankframework/extensions/mqtt/MqttFacade.java, messaging/src/main/java/org/frankframework/extensions/mqtt/MqttListener.java, messaging/src/main/java/org/frankframework/extensions/mqtt/MqttSender.java, messaging/src/main/resources/springJms.xml, messaging/src/test/java/org/frankframework/extensions/mqtt/MqttClientFactoryFactoryTest.java, messaging/src/test/java/org/frankframework/extensions/mqtt/MqttSenderTest.java
=> Fix ObjectFactories

console/frontend/src/main/frontend/src/app/views/jdbc/jdbc-browse-tables/jdbc-browse-tables.component.ts
=> Fix Console JDBC Tables displaying message count

console/frontend/src/main/frontend/src/app/views/storage/storage-list/storage-list-dt/storage-list-dt.component.html
=> Message store disable button when its not current action

core/src/main/java/org/frankframework/metrics/PrometheusMeterServlet.java, core/src/test/java/org/frankframework/metrics/PrometheusMeterServletTest.java
=> Add Content-Type for Prometheus metrics endpoint

console/frontend/src/main/frontend/src/app/components/datatable/datatable.component.html, console/frontend/src/main/frontend/src/app/components/datatable/datatable.component.scss, console/frontend/src/main/frontend/src/app/components/datatable/datatable.component.ts, console/frontend/src/main/frontend/src/app/components/th-sortable.directive.ts, console/frontend/src/main/frontend/src/app/views/storage/storage-list/storage-list.component.ts
=> Make datatable columns sortable

pom.xml
Update aws.version, json-smart
=> Prepare release: update dependencies (7.9)

console/frontend/src/main/frontend/src/app/pipes/literal.pipe.spec.ts, console/frontend/src/main/frontend/src/app/pipes/literal.pipe.ts, console/frontend/src/main/frontend/src/app/views/environment-variables/environment-variables.component.html, console/frontend/src/main/frontend/src/app/views/environment-variables/environment-variables.component.ts
=> Add literal pipe to escape most whitespace characters

pom.xml
https://github.com/frankframework/frankframework/pull/9693
=> Bump org.jboss.narayana.jta:narayana-jta from 7.2.2.Final to 7.3.0.Final

aws/src/main/java/org/frankframework/filesystem/AmazonS3FileSystem.java, core/src/main/java/org/frankframework/util/MessageUtils.java, filesystem/src/main/java/org/frankframework/filesystem/LocalFileSystem.java, filesystem/src/test/java/org/frankframework/filesystem/LocalFileSystemTest.java
=> Make reading file extended attributes more robust when there are character conversion issues

pom.xml
https://github.com/frankframework/frankframework/pull/9693
=> Upgrade Narayana to mitigate session leak
