frankframework/frankframework

README.md

ManageDatabase link referred to Example instead of Util. Fixed this.

Link to ManageDatabase also corrected

---

core/src/main/java/nl/nn/adapterframework/core/IDualModeValidator.java
core/src/main/java/nl/nn/adapterframework/core/IXmlValidator.java
core/src/main/java/nl/nn/adapterframework/core/PipeLine.java
core/src/main/java/nl/nn/adapterframework/pipes/Json2XmlValidator.java
core/src/main/java/nl/nn/adapterframework/pipes/MessageSendingPipe.java
core/src/main/java/nl/nn/adapterframework/pipes/XmlValidator.java
core/src/main/java/nl/nn/adapterframework/soap/SoapValidator.java
core/src/main/java/nl/nn/adapterframework/soap/Wsdl.java
core/src/main/java/nl/nn/adapterframework/soap/WsdlUtils.java
core/src/test/java/nl/nn/adapterframework/pipes/WsdlXmlValidatorMixedModeTest.java
core/src/test/java/nl/nn/adapterframework/pipes/XmlValidatorTest.java
core/src/test/java/nl/nn/adapterframework/soap/WsdlTest.java

WSDL now works based on interface IXmlValidator, and does not need to be (and is) no longer aware of mixed mode

ART-953 fix generation of wsdls for mixed mode validators

---

webapp/src/main/webapp/iaf/gui/css/style.css
webapp/src/main/webapp/iaf/gui/js/controllers.js
webapp/src/main/webapp/iaf/gui/views/ShowConfigurationStatus.html

- Change red 'error feeling' in showConfigurationStatus to a more neutral style
- Replace dropdown configurations list with tabbed list
- Fix when switching tabs results in switching between adapter summaries
- Change adapteroverview to a more compact style
- Change adapter summary to configuration summary

Change stop adapter / receiver button style to a more neutral style

---

core/pom.xml
webapp/pom.xml

jaxen version has been updated from 1.1.6 to 1.2.0
org.apache.servicemix.specs.jaxws-api-2.2 dependency added to the core

Update jaxen version and add jaxws-api dependency to the core

---

cmis/src/main/java/nl/nn/adapterframework/extensions/cmis/CmisSender.java

By default datetime fields are send as a value in milleseconds. This leads to differences in time if the client is in a different timezone than the server. To fix this problem, the datetime fields have to be send in ISO format. This is done by setting the BROWSER_DATETIME_FORMAT to EXTENDED.

Added parameter BROWSER_DATETIME_FORMAT to send dates in ISO format

---

core/src/main/java/nl/nn/adapterframework/align/ScalarType.java
core/src/main/java/nl/nn/adapterframework/align/XmlTo.java
core/src/main/java/nl/nn/adapterframework/align/content/ElementContainer.java
core/src/main/java/nl/nn/adapterframework/align/content/JsonDocumentContainer.java
core/src/main/java/nl/nn/adapterframework/align/content/JsonElementContainer.java
core/src/main/java/nl/nn/adapterframework/align/content/MapContentContainer.java
core/src/main/java/nl/nn/adapterframework/align/content/TreeContentContainer.java
core/src/test/resources/Align/DataTypes/Strings-compact.json
core/src/test/resources/Align/DataTypes/Strings-full.json
core/src/test/resources/Align/DataTypes/Strings.properties
core/src/test/resources/Align/DataTypes/Strings.xml

Avoid empty strings being rendered as '{}', but render them as proper empty strings

Fix empty String handling in XML to JSON conversion

---

core/src/main/java/nl/nn/adapterframework/extensions/test/IbisTester.java

When running scripted tests, the resultString contains a valid value ("All scenarios passed") which was not evaluated as true.
Instead of adding another endsWith method, changed the method endsWith to contains, so all valid scenarios are evaluated as true.

Update IbisTester: change validation of resultString

---

cmis/src/main/java/nl/nn/adapterframework/extensions/cmis/CmisSender.java
cmis/src/main/java/nl/nn/adapterframework/extensions/cmis/CmisUtils.java
cmis/src/main/java/nl/nn/adapterframework/extensions/cmis/server/CmisEventDispatcher.java
cmis/src/main/java/nl/nn/adapterframework/extensions/cmis/server/CmisSecurityHandler.java
cmis/src/main/java/nl/nn/adapterframework/extensions/cmis/server/HttpSessionCmisService.java
cmis/src/main/java/nl/nn/adapterframework/extensions/cmis/server/impl/IbisDiscoveryService.java
cmis/src/main/java/nl/nn/adapterframework/extensions/cmis/server/impl/IbisRepositoryService.java
cmis/src/test/java/nl/nn/adapterframework/extensions/cmis/CmisTestObject.java
cmis/src/test/java/nl/nn/adapterframework/extensions/cmis/TestBindingTypes.java
cmis/src/test/java/nl/nn/adapterframework/extensions/cmis/TestGetAction.java

Add CmisSecurityHandler available to the pipeline
Implement DiscoveryService.getContentChanges
Return property types when no value has been supplied
Remove some unnecessarily logging
Bugfix make folder optional when creating new document
Bugfix NPE when cmis object has no baseTypeId
Bugfix display,local and query where not returned in cmis properties

Solve several cmis issues

---

core/src/main/java/nl/nn/adapterframework/pipes/ForEachChildElementPipe.java

Hierbij de aangepaste ForEachChildElementPipe.
Ik heb ook de test aangepast, die check ik morgen in. 
Nu alvast de pipe zelf, omdat men er op zit te wachten

Fix escaping of attributes in ForEachChildElementPipe

---

test/src/main/configurations/MainConfig/ConfigurationJavascript.xml
test/src/main/configurations/MainConfig/JavaScript/JavascriptTest.js
test/src/test/testtool/JavascriptSender/scenario03/step02.txt

Changed the JavascriptSender Callback Larva test scenario to call and use the EchoSender instead of the FileSender. This is done to simplify
the test scenario and avoid potential write permission errors.

Change JavascriptSender Larva test scenario

---

test/src/main/configurations/HTTP/ConfigurationHttpListenerSender.xml
test/src/main/configurations/HTTP/ConfigurationRestListener.xml
test/src/main/configurations/HTTP/ConfigurationWebServiceListenerSender.xml
test/src/main/configurations/HTTP/ConfigurationWebServiceListenerSenderAddress.xml
test/src/main/configurations/HTTP/ConfigurationWebServiceListenerSenderAttachments.xml
test/src/main/configurations/HTTP/ConfigurationWebServiceListenerSenderNoSoap.xml
test/src/main/configurations/HTTP/ConfigurationWebServiceListenerSenderServiceNamespaceURI.xml
test/src/main/configurations/MainConfig/DeploymentSpecifics.properties
test/src/main/configurations/WSS_HTTP/ConfigurationHttpListenerSender.xml
test/src/main/configurations/WSS_HTTP/ConfigurationRestListener.xml
test/src/main/configurations/WSS_HTTP/ConfigurationWebServiceListenerSender.xml
test/src/main/configurations/WSS_HTTP/ConfigurationWebServiceListenerSenderNoSoap.xml
test/src/main/resources/DeploymentSpecifics.properties
test/src/test/testtool/CorrelationMessageId/common.properties
test/src/test/testtool/HttpListenerSender/common.properties
test/src/test/testtool/IbisConsole/showConfiguration.properties
test/src/test/testtool/IbisConsole/showConfigurationStatus_TomCatBTM.properties
test/src/test/testtool/IbisConsole/showConfigurationStatus_TomCatSpringDSTA.properties
test/src/test/testtool/IbisConsole/showConfigurationStatus_WAS.properties
test/src/test/testtool/IbisConsole/showConfigurationStatus_WLP.properties
test/src/test/testtool/IbisConsole/showLogging.properties
test/src/test/testtool/WsdlGenerator/common.properties

The web.contextpath property can now be empty without causing a double forward slash in the url
where this property is used. The forward slash after using the variable
has been removed and the contextpath should now be given ending with a
forward slash, e.g. now use "iaf-test/" instead of "iaf-test".

Changed the web.contextpath property.

---

test/src/main/resources/DatabaseChangelog.xml

Removed the autoIncrement=true attribute for creating the tables
IBISDATA and IBISTEMP when using liquibase for Ibis4Test. This is
because this attribute is not necessary and caused an incorrect query
when running Ibis4Test with MySQL and MariaDB. Note that if you have
already run Ibis4Test before using a local database you need to drop
your Databasechangelog table before running Ibis4Test with liquibase
again.

Removed the autoIncrement=true attribute in DatabaseChangelog.xml.

---

RELEASES.md
core/src/main/java/nl/nn/adapterframework/configuration/JmxMbeanHelper.java

When configs are loaded, unloaded or reloaded a lot of warnings and errors occur. This is caused by the class JmxMBeanHelper which can not handle configs and a bug in retrieving the ObjectName which differs from the real one which is registered.

Bugfix (un)loading configs

---

core/src/main/java/nl/nn/adapterframework/doc/IbisDocPipe.java

The link of the new ibisdoc application went to http://localhost:8080/iaf/ibisdoc when clicking on it instead of http://localhost:8080/iaf-example/iaf/ibisdoc which resulted in a 404. This has now been fixed

Fix bug in link to ibisdoc

---

test/src/main/tools/setupDir/setupDir.xml

The setupDir caused larva scenario's to crash due to zip dir being created when it shouldn't.

Removed zip dir from setupDir

---

core/src/main/resources/xml/xsl/uglify.xsl

When a Beautiful configuration is loaded in the framework, uglify.xsl is used to convert the configuration to the old style. When automatic schema validation is configured by adding the xsi:noNamespaceSchemaLocation attribute to the Beautiful config, this attribute is not removed from the converted configuration. This results in a lot of "does not have an attribute" warnings.
This change removes everything related to the XMLSchema Instance namespace during the conversion.

Remove XMLSchema Instance namespace from Beautiful configuration

---

RELEASES.md
core/src/main/java/nl/nn/adapterframework/pipes/ForEachChildElementPipe.java
core/src/main/java/nl/nn/adapterframework/senders/XsltSender.java
core/src/main/java/nl/nn/adapterframework/util/TransformerPool.java
core/src/main/java/nl/nn/adapterframework/xml/TransformerFilter.java
core/src/main/resources/AppConstants.properties
core/src/test/java/nl/nn/adapterframework/pipes/ForEachChildElementPipeTest.java
core/src/test/java/nl/nn/adapterframework/util/XsltStreamingTest.java
core/src/test/java/nl/nn/adapterframework/xslt/XsltErrorTestBase.java
ladybug/src/main/java/nl/nn/ibistesttool/IbisDebuggerAdvice.java

This appeared to cause NullPointerExceptions in Xalans
TransformerHandlerImpl, therefor we disabled this setting.
Also because it is using more memory than expected, e.g.
ForEachChildElementPipe with elementXPathExpression still goes out of
memory on large files

Disable streaming XSLT

---

test/src/main/tools/setupDir/setupDir.xml
test/src/test/testtool/RestListener/common.properties
test/src/test/testtool/Zip/ZipWriter/scenario 01.properties
test/src/test/testtool/Zip/ZipWriter/scenario 02.properties

Een aantal Larva scenario's gaf een verschil op directorynamen met een kleine "c" en een grote "C". Dit is nu gefixt door de canonical directorynamen met elkaar te vergelijken.
Verder gaan de Zip-scenario's fout als de directory ${testdata.dir}/zip al bestaat. Ik heb dat gefixt door deze directory niet meer aan te maken in <setupDir.xml>. Beter nog zou zijn om bij het aanmaken van de directory eerst te controleren of hij al bestaat.

Fix Larva test scenarios directory name not equal

---

example/pom.xml

H2 now wants explicit declaration of current work dir usage.
Updated pom.xml for Jetty mvn plugin to pass the explicit declaration as system property.

Fix mvn jetty:run for newer H2 version

---

core/src/main/java/nl/nn/adapterframework/configuration/ConfigurationDigester.java
core/src/main/java/nl/nn/adapterframework/configuration/ConfigurationUtils.java
core/src/main/java/nl/nn/adapterframework/configuration/HostnamePropertyPlaceholderConfigurer.java
core/src/main/java/nl/nn/adapterframework/configuration/IbisContext.java
core/src/main/java/nl/nn/adapterframework/configuration/LowerCasePropertyPlaceholderConfigurer.java
core/src/main/java/nl/nn/adapterframework/configuration/OverwritePropertyPlaceholderConfigurer.java
core/src/main/java/nl/nn/adapterframework/extensions/esb/EsbSoapWrapperPipe.java
core/src/main/java/nl/nn/adapterframework/extensions/fxf/FxfPropertyPlaceholderConfigurer.java
core/src/main/java/nl/nn/adapterframework/parameters/Parameter.java
core/src/main/java/nl/nn/adapterframework/pipes/MessageSendingPipe.java
core/src/main/java/nl/nn/adapterframework/pipes/PutSystemDateInSession.java
core/src/main/java/nl/nn/adapterframework/statistics/StatisticsKeeper.java
core/src/main/java/nl/nn/adapterframework/statistics/percentiles/PercentileEstimatorBase.java
core/src/main/java/nl/nn/adapterframework/util/AppConstants.java
core/src/main/java/nl/nn/adapterframework/webcontrol/FileViewerServlet.java
core/src/test/java/nl/nn/adapterframework/configuration/ClassLoaderManagerTest.java
core/src/test/java/nl/nn/adapterframework/util/AppConstantsTest.java
core/src/test/resources/AppConstants/AppConstants.properties

Make sure properties are set throughout all AppConstants singletons
Unify put/set methods
Disallow use of getInstance(null)
Add logging to property loading

Make sure properties are set throughout all AppConstants singletons

---

core/src/main/java/nl/nn/adapterframework/lifecycle/IbisApplicationInitializer.java
core/src/main/java/nl/nn/adapterframework/lifecycle/IbisApplicationServlet.java

Turns out it's a lot more complicated to start the framework through Spring's WebApplicationInitializer (SPI). The WebApplicationInitializer has to be available on the classpath of the webapp that's being ran, and not (hidden) within a dependency!
Since this file was in the core module, it worked on eclipse+tomcat, as eclipse wired all modules on the classpath. The original changes have been cleaned up (see #297) and this reverts some functions back to their previous location.

Classpath issue spring spi

---

RELEASES.md
core/src/main/java/nl/nn/adapterframework/util/AppConstants.java
core/src/main/resources/AppConstants.properties

Table names in a database might be upper-, lower- or random-case. This converts the tablenames in the rowset results to uppercase.

Set jdbc.convertFieldnamesToUppercase default to true

---

ladybug/src/main/java/nl/nn/ibistesttool/LadybugPipe.java

Since most of these small changes are interdependant, I combined all of them into one pull request.
Summary:
- Passed reports are counted rather than failed ones
- Applicable metadata is logged even in the event of an error
- Error messages are now added to the report log message
- Generic writeToLogOrSysOut() method
- Concluding message that summarizes the results of all run reports

Add various LadybugPipe improvements

---

core/src/main/resources/AppConstants.properties
ladybug/pom.xml
ladybug/src/main/resources/springIbisTestTool.xml

Allows Frank developers to configure the maximum memory usage for Ladybug reports (as implemented in [this pull request](https://github.com/ibissource/ibis-ladybug/pull/15)) in a property file.

Add Spring attribute for ibistesttool.maxMemoryUsage

---

test/src/test/testtool/XmlBuilderThreadSafety/scenario01/in.txt

H2 blijkt toch ook met de default Oracle tabel DUAL om te kunnen gaan. Waarschijnlijk omdat MODE=Oracle wordt gebruikt.

Add 'from dual' (required for Oracle, not H2)

---

core/pom.xml
ladybug/pom.xml
ladybug/src/main/java/nl/nn/ibistesttool/tibet2/Storage.java
larva/pom.xml

In Storage.java 153 queryForInt() hqs been deprecated and replaced with queryForObject

Migration of Spring Framework from 3.2.16.RELEASE to 4.3.25.RELEASE

---

test/src/test/testtool/XmlQuerySender/common.properties

Voor de Oracle functies EMPTY_BLOB() en EMPTY_CLOB() is geen equivalent in H2. Het beste alternatief is een lege string hiervoor te gebruiken. Dit leidt tot een verschil wanneer een SELECT op zo'n BLOB- of CLOB-veld wordt gedaan. Dit pull request vervangt een lege string in de output van de BLOB- en CLOB-velden met de NULL-waarde zodat er geen verschil is wanneer het scenario met een Oracle of een H2 database gerund wordt.

Fix Larva scenarios XmlQuerySender

---

core/src/main/java/nl/nn/adapterframework/pipes/IteratingPipe.java
core/src/main/java/nl/nn/adapterframework/pipes/JsonXsltPipe.java
core/src/main/java/nl/nn/adapterframework/pipes/XmlSwitch.java
core/src/main/java/nl/nn/adapterframework/senders/XsltSender.java
core/src/main/java/nl/nn/adapterframework/util/XmlUtils.java
core/src/test/java/nl/nn/adapterframework/pipes/ForEachChildElementPipeTest.java
core/src/test/java/nl/nn/adapterframework/senders/XsltSenderTest.java
core/src/test/resources/ForEachChildElementPipe/NamespacedXPath/expected.xml
core/src/test/resources/ForEachChildElementPipe/NamespacedXPath/input.xml
core/src/test/resources/Xslt/XPathWithNamespace/expected-xslt1.txt
core/src/test/resources/Xslt/XPathWithNamespace/expected-xslt2.txt
core/src/test/resources/Xslt/XPathWithNamespace/input.xml

It is still not possible to create an XPath with a default namespace
specified in namespaceDefs.

Fix bug in XpathEvaluator-creation

---

core/src/main/java/nl/nn/adapterframework/pipes/XmlIf.java

IbisDoc reports version 1 while the default is version 2.

Update IbisDoc for XmlIfPipe to report the correct default XSLT version

---

test/src/main/configurations/UTIL/ConfigurationLarva.xml
test/src/main/configurations/UTIL/Larva/xsl/CreateMail.xsl
test/src/main/resources/DeploymentSpecifics.properties

In Ibis4TestIAF wordt altijd automatisch begonnen met een testrun. Dit gaat via de Larva-adapter. De resultaten hiervan dienen onmiddelijk bij de relevante personen worden gemeld zodat zij op de hoogte zijn van de gezondheid van de geteste versie van het framework. Zoals het er stond moesten de geaddresseerden hard gecodeerd worden neergezet. De voorgestelde oplossing laat de mailadressen binnen de applicatie geformuleerd worden.
Heb in /test/src/main/configurations/UTIL de ConfigurationLarva.xml en de bijbehorende CreateMail.xsl aangepast. ConfigurationLarva pakt de property "mailaddresses" op die geformuleerd staat in deploymentspecifics als een comma-separated list. Het eerst item in deze lijst wordt het "To"-veld, de rest van de lijst komt indien aanwezig in het "CC" veld.

Added mailaddresses property to test module

---

core/src/main/java/nl/nn/adapterframework/pipes/Json2XmlValidator.java

The Json2XmlValidator can generate a JsonSchema from its XML-Schema. To make this available to developers, this was displayed as 'configuration warning'. As this appeared to clutter the console, this 'warning' has been removed. The schema can now be found in the log file, when the validator is configured at startup.

Avoid JsonSchema of Json2XmlValidator to clutter the console

---

ladybug/src/main/java/nl/nn/ibistesttool/Debugger.java
ladybug/src/main/java/nl/nn/ibistesttool/DeploymentSpecificsBeanPostProcessor.java
ladybug/src/main/java/nl/nn/ibistesttool/IbisDebuggerAdvice.java

With this change, an event is fired when the Ladybug report generator is switched off. 
This event is used to switch off the ibisdebugger completely.

Toggle IbisDebugger state when Ladybug ReportGenerator is changed

---

core/src/main/java/nl/nn/adapterframework/configuration/classloaders/ClassLoaderBase.java
core/src/main/java/nl/nn/adapterframework/configuration/classloaders/JarBytesClassLoader.java

Allows the use of custom classes placed on the classpath of the application server, or when enabled, classes that are in a configuration (jar).
NOTE: When a custom class has been loaded in the JVM, you can no longer change it... Reloading the configuration will not reload the loaded java-class!

Allow the use of custom code in configurations

---

test/src/main/configurations/UTIL/ConfigurationLarva.xml
test/src/main/configurations/UTIL/Larva/xsl/CreateMail.xsl
test/src/main/resources/DeploymentSpecifics.properties

Extends https://github.com/ibissource/iaf/pull/526 to allow setting additional recipients that will only get the e-mail when tests fail.

Enable setting additional recipients for errors in the test module

---

ibm/src/main/java/nl/nn/adapterframework/extensions/ibm/IMSSender.java

IbisDoc did not contain documentation for the transaction code as the IbisDoc annotation was above the getter. Switched around getter and setter, so that the IbisDoc annotation is above the setter, resulting in it being shown in the IbisDoc.

IbisDoc for IMS transaction code was not shown

---

core/src/main/java/nl/nn/adapterframework/filesystem/AmazonS3FileSystem.java
core/src/main/java/nl/nn/adapterframework/filesystem/ExchangeFileSystem.java
core/src/main/java/nl/nn/adapterframework/filesystem/FileSystemActor.java
core/src/main/java/nl/nn/adapterframework/filesystem/FileSystemListener.java
core/src/main/java/nl/nn/adapterframework/filesystem/FileSystemPipe.java
core/src/main/java/nl/nn/adapterframework/filesystem/FileSystemSender.java
core/src/main/java/nl/nn/adapterframework/filesystem/FtpFileSystem.java
core/src/main/java/nl/nn/adapterframework/filesystem/IBasicFileSystem.java
core/src/main/java/nl/nn/adapterframework/filesystem/LocalFileSystem.java
core/src/main/java/nl/nn/adapterframework/filesystem/Samba1FileSystem.java
core/src/main/java/nl/nn/adapterframework/filesystem/Samba2FileSystem.java
core/src/test/java/nl/nn/adapterframework/filesystem/BasicFileSystemTest.java
core/src/test/java/nl/nn/adapterframework/filesystem/FileSystemActorTest.java
core/src/test/java/nl/nn/adapterframework/filesystem/FileSystemListenerTest.java
core/src/test/java/nl/nn/adapterframework/filesystem/MockFileSystem.java

- Implement copyFile() method in all known FileSystems, except for ftp
- Add action 'copy' to FileSystemActor (and FileSystemPipe and -Sender)
- Add attribute 'logFolder' to FileSystemListener

Add method copyFile() to IBasicFileSystem

---

core/src/main/java/nl/nn/adapterframework/jdbc/JdbcTransactionalStorage.java
test/src/test/testtool/MessageStoreSenderAndListener/common.properties
test/src/test/testtool/MessageStoreSenderAndListener/scenario01.properties
test/src/test/testtool/MessageStoreSenderAndListener/scenario01/out.xml
test/src/test/testtool/MessageStoreSenderAndListener/scenario02/out-01.xml

Backport of changes to JdbcTransactionalStorage from master to 7.5.
storeMessageInDatabase() used to return a ratjetoe of result formats.
Now it either returns the value of the key of the newly inserted record in ibisstore, enclosed in <id/>, or a uniformly formatted message stating that a matching message already exists.

Let JdbcTransactionalStorage return uniform responses for all dbmses

---

core/src/main/java/nl/nn/adapterframework/http/rest/ApiListener.java
core/src/main/java/nl/nn/adapterframework/http/rest/ApiListenerServlet.java
core/src/main/java/nl/nn/adapterframework/http/rest/ApiServiceDispatcher.java
core/src/main/java/nl/nn/adapterframework/http/rest/ContentType.java
core/src/main/java/nl/nn/adapterframework/http/rest/MediaTypes.java
core/src/test/java/nl/nn/adapterframework/http/rest/ApiListenerTest.java
core/src/test/java/nl/nn/adapterframework/http/rest/ContentTypeTest.java
core/src/test/java/nl/nn/adapterframework/http/rest/MediaTypeTest.java

Revert 88ead735ee4c673d67eeb14e3d77066977b04f6e
Add ability to set Character Encoding on response ContentType header (a508918f2b3172f2397d14154b9b30f26f180762)
No charset is set by default

Add ability to set character encoding on the response header

---

core/src/main/resources/AppConstants.properties
ladybug/pom.xml
ladybug/src/main/resources/springIbisTestTool.xml

Ladybug RELEASES.md between 2.0.15-20200330.174524 and 2.0.15-20200610.174932:
- Clone transformation and variableCsv too
- Add XmlStorage implementation
- Display number of stubbed checkpoints in Test tab
- Fix error on run in Test tab not being displayed

Use latest Ladybug version with XmlStorage support

---

.travis.yml
pom.xml

I noticed that my build time was almost 3 times as long because of the codecoverage tests. Since this only has to happen on build servers I've moved the reporting tool to a custom profile.

Move JaCoCo reporting tool to it's own Maven profile

---

test/src/main/resources/DeploymentSpecifics.properties
test/src/main/tools/setupDB/Postgresql/create_user.sql
test/src/main/tools/setupDB/Postgresql/create_user.xml
test/src/main/webapp/META-INF/context.xml

The test scenarios in the framework's test adapter will have to work on a postgres database.
This commit enables iaf to create a user and database via ant build.
And subsequently create the tables via liquibase in the postgres database

Added postgres database connectivity to iaf-test

---

larva/src/main/java/nl/nn/adapterframework/testtool/TestTool.java

To reduce the amount of logging sent in the mail by the LarvaPipe

Fix Larva silent log level

---

core/src/main/java/nl/nn/adapterframework/filesystem/FileSystemActor.java
larva/src/main/java/nl/nn/adapterframework/testtool/TestTool.java

If in any larva .read step the filename is specified as 'ignore', then the result of the test step is not compared to any expected value, but just accepted

Impl #1005 Option to ignore larva test step response

---

core/src/main/resources/IAF_Util/ConfigurationManageDatabase.xml

We were not able to use this adapter via Soapui, while it missing the address attribute in the WebServiceListener.
I added the address="ManageDatabase-ws" for WebServiceListener, and now it can be used with soap/http.

Change IAF_Util/ConfigurationManageDatabase.xml: add address so it can be used with soap/http

---

ladybug/pom.xml

Ladybug RELEASES.md between 2.0.15-20200814.171944 and 2.0.15-20200925.161114:
- Fix report filter for positive matching (report almost empty)
- Add tool tip to report filter text field
- Only log once when max checkpoints or max memory usage is exceeded

Upgrade to latest Ladybug version

---

core/src/main/java/nl/nn/adapterframework/webcontrol/api/ExecuteJdbcQuery.java
webapp/src/main/webapp/iaf/gui/views/ExecuteJdbcQuery.html

- Set trimSpaces to false for the directQuerySender instance used for execute query
- add ability to change it from the console.
Related to #992

Make trim optional for execute query

---

core/src/main/java/nl/nn/adapterframework/pipes/XmlSwitch.java
core/src/test/java/nl/nn/adapterframework/pipes/XmlSwitchTest.java
core/src/test/resources/XmlSwitch/selection.xsl

- Introduces storeForwardInSessionKey attribute to store resulting forward name in a session key.
- Deprecates serviceSelectionStylesheetFilename  attribute and introduces styleSheetName attribute for the same purpose.
Fixes #1003 
Fixes #1055

Introduce storeForwardInSessionKey attribute in XmlSwitch 

---

core/pom.xml
core/src/main/java/nl/nn/adapterframework/configuration/AbstractSpringPoweredDigesterFactory.java
core/src/main/java/nl/nn/adapterframework/configuration/AttributeCheckingRule.java
core/src/main/java/nl/nn/adapterframework/configuration/ConfigurationDigester.java
core/src/main/java/nl/nn/adapterframework/configuration/classloaders/ClassLoaderBase.java
core/src/main/java/nl/nn/adapterframework/configuration/digester/DigesterRule.java
core/src/main/java/nl/nn/adapterframework/configuration/digester/DigesterRulesHandler.java
core/src/main/java/nl/nn/adapterframework/configuration/digester/DigesterRulesParser.java
core/src/main/java/nl/nn/adapterframework/configuration/digester/FrankDigesterRules.java
core/src/main/java/nl/nn/adapterframework/doc/DigesterRulesParser.java
core/src/main/java/nl/nn/adapterframework/doc/IbisBeanMappingParser.java
core/src/main/java/nl/nn/adapterframework/doc/InfoBuilderSource.java
core/src/main/java/nl/nn/adapterframework/doc/objects/ChildIbisBeanMapping.java
core/src/main/java/nl/nn/adapterframework/monitoring/MonitorManager.java
core/src/main/java/nl/nn/adapterframework/pipes/CompressPipe.java
core/src/main/java/nl/nn/adapterframework/webcontrol/action/ShowMonitorExecute.java
core/src/main/resources/digester-rules.xml
core/src/main/resources/springCommon.xml
core/src/test/java/nl/nn/adapterframework/configuration/digester/FrankDigesterRulesTest.java
core/src/test/java/nl/nn/adapterframework/doc/TestDigesterRulesParser.java
core/src/test/java/nl/nn/adapterframework/pipes/CompressPipeTest.java
example/src/test/java/nl/nn/adapterframework/webcontrol/pipes/IbisConsoleTest.java
example/src/test/resources/webcontrol/pipes/ShowConfigurationStatus_all.xml
test/src/test/testtool/Validators/SoapValidator/scenario08.properties

I bumped into many issues while trying to parse the old XML digester rules file. It turns out that since version 2 most classes have become either package private or final so it's near impossible to extend. The DTD supplied by the dependency is also out of date creating inconsistent xml parsing/validating problems. Many bugs have been reported but since 2013 there has been no development activity. See: [DigesterRuleParser](https://issues.apache.org/jira/browse/DIGESTER-168), [properties-rule](https://user.commons.apache.narkive.com/QeKWeYQo/digester-xml-rules-set-properties-rule-and-ignoring-missing-properties),  [and dtd inconsistencies](https://stackoverflow.com/questions/11169761/when-using-commons-digester-xml-rules-how-do-i-exclude-some-attributes-of-the-x).

Upgrade commons digester

---

core/src/main/java/nl/nn/adapterframework/extensions/fxf/FxfWrapperPipe.java
core/src/main/java/nl/nn/adapterframework/filesystem/FileSystemActor.java
core/src/main/java/nl/nn/adapterframework/pipes/UnzipPipe.java
test/src/main/configurations/MainConfig/ConfigurationFxF3.xml
test/src/main/configurations/MainConfig/ConfigurationUnzip.xml
test/src/main/configurations/MainConfig/ConfigurationZip.xml

- rename checkDirectory to assumeDirectoryExists in UnzipPipe
- Introduce a createFolder attribute in FxfWrapperPipe to create the fxf.dir folder in case it does not exists
- fix unzip exception forward test scenario to create unzip folder at the beginning
Fixes #1065

fix test scenarios to create required folder automatically

---

core/src/main/java/nl/nn/adapterframework/http/HttpResponseHandler.java
core/src/main/java/nl/nn/adapterframework/http/HttpSender.java
core/src/main/java/nl/nn/adapterframework/http/WebServiceSender.java
core/src/test/java/nl/nn/adapterframework/http/WebServiceSenderResultTest.java
core/src/test/resources/nl/nn/adapterframework/http/mtom-multipart2.txt
core/src/test/resources/nl/nn/adapterframework/http/soapMultipart.txt
core/src/test/resources/nl/nn/adapterframework/http/soapMultipart2.txt

- multipartResponse attribute will be deprecated. Responses with a 'multipart/*' content-type will be detected automatically.
Fixes #1026

Fix #1026 Fix exception overriding in webservice sender

---

core/src/main/java/nl/nn/adapterframework/webcontrol/api/ExecuteJdbcQuery.java
core/src/main/java/nl/nn/adapterframework/webcontrol/api/ServletDispatcher.java
core/src/main/java/nl/nn/adapterframework/webcontrol/api/TestPipeline.java

```
2020-10-26 17:14:38,231 [http-nio-80-exec-2] requestUri [/iaf/api/jdbc/query] params [] method [POST] remoteHost [0:0:0:0:0:0:0:1] remoteAddress [0:0:0:0:0:0:0:1] remoteUser [null]
2020-10-26 17:14:38,262 [http-nio-80-exec-2] executing query [select * from ibisstore] on datasource [jdbc/ibis4test-oracle-docker] queryType [select] avoidLocking [false]
```
```
2020-10-26 17:23:05,735 [http-nio-80-exec-9] requestUri [/iaf/api/test-pipeline] params [] method [POST] remoteHost [0:0:0:0:0:0:0:1] remoteAddress [0:0:0:0:0:0:0:1] remoteUser [null]
2020-10-26 17:23:05,801 [http-nio-80-exec-9] testing pipeline of adapter [ApiListener_SimpleInsert]
```

Add pipeline message and execute query to Security Log

---

core/src/main/java/nl/nn/adapterframework/core/PipeLine.java
core/src/main/java/nl/nn/adapterframework/receivers/Receiver.java
core/src/main/java/nl/nn/adapterframework/util/Misc.java
core/src/main/java/nl/nn/adapterframework/webcontrol/action/ShowSecurityItems.java
core/src/main/java/nl/nn/adapterframework/webcontrol/api/ShowSecurityItems.java
webapp/src/main/webapp/iaf/gui/views/ShowSecurityItems.html

In case the transaction timeout is greater than the maximum transaction timeout, will add a configuration warning to be shown in the console

Show a warning for transaction timeout

---

core/src/main/java/nl/nn/adapterframework/core/IbisException.java
core/src/main/java/nl/nn/adapterframework/util/DomBuilderException.java
core/src/test/java/nl/nn/adapterframework/core/IbisExceptionTest.java

Should be merged into 7.5 and 7.6 too.

Fix #1292 Avoid recursion explosion in IbisException.getMessage()

---

core/src/test/java/nl/nn/adapterframework/xslt/ParallelXsltTest.java

ignore test failing on GitHub, with two extra alerts in logging.

Fix GitHub test issue in ParallelXsltTest

---

akamai/src/main/java/nl/nn/adapterframework/extensions/akamai/NetStorageSender.java
cmis/src/main/java/nl/nn/adapterframework/extensions/cmis/CmisHttpSender.java
core/src/main/java/nl/nn/adapterframework/http/HttpResponseHandler.java
core/src/main/java/nl/nn/adapterframework/http/HttpSender.java
core/src/main/java/nl/nn/adapterframework/receivers/Receiver.java
core/src/test/java/nl/nn/adapterframework/http/HttpSenderTest.java
core/src/test/resources/nl/nn/adapterframework/http/response/simpleMockedHttpGetWithoutPRC.txt

Also automatically close all IPullingListener responses, this is far from optimal as implementations should do `closeOnClose(PipeLineSession)`.

Close HTTP ResponseStream

---

frankDoc/src/main/java/nl/nn/adapterframework/frankdoc/FrankDocJsonFactory.java
frankDoc/src/test/resources/doc/examplesExpected/deprecated.json
frankDoc/src/test/resources/doc/examplesExpected/sequence.json
frankDoc/src/test/resources/doc/examplesExpected/simple.json

Frank!Doc - Niels commented in https://github.com/ibissource/iaf/issues/1716 that we have empty lists of attributes and children in the Frank!Doc JSON. This pull request is a fix for that.

JSON improvements - no empty lists of children

---

core/src/main/java/nl/nn/adapterframework/util/XmlUtils.java
core/src/test/java/nl/nn/adapterframework/util/XmlUtilsTest.java

Parameters sent to setTransformerParameters method is from Object type. There could be parameters like Boolean and Integer which cannot be Message at the moment. 
Closes #1690

Extend transformerParameter type check with Message

---

CONTRIBUTING.md
idin/src/main/java/nl/nn/adapterframework/extensions/idin/IdinSender.java

Fix failing tests in the build of the entire iaf repository. The build was started like:
$ mvn -PattachFrankDoc install
The error was:
[INFO] Running nl.nn.adapterframework.configuration.digester.ConfigurationDigesterTest
[ERROR] Tests run: 5, Failures: 0, Errors: 3, Skipped: 0, Time elapsed: 0.172 s <<< FAILURE! - in nl.nn.adapterframework.configuration.digester.ConfigurationDigesterTest
[ERROR] testConfigurationPreParser(nl.nn.adapterframework.configuration.digester.ConfigurationDigesterTest)  Time elapsed: 0.032 s  <<< ERROR!
java.io.IOException: Cannot get canonicalizer using [/xml/xsd/FrankConfig-compatibility.xsd]
at nl.nn.adapterframework.configuration.digester.ConfigurationDigesterTest.testConfigurationPreParser(ConfigurationDigesterTest.java:53)
Caused by: …

Fix failure of ConfigurationDigesterTest

---

core/src/main/java/nl/nn/adapterframework/pipes/MessageSendingPipe.java
core/src/main/java/nl/nn/adapterframework/stream/MessageOutputStream.java
core/src/main/java/nl/nn/adapterframework/stream/StreamingPipe.java
core/src/main/resources/FrankFrameworkConfigurationContext.xml
core/src/main/resources/log4j4ibis.xml

This PR adds debug logging for the creation of output streams.
The ladybug logging is still not good.
It appears to me that the AOP proxying of pipes and senders is broken, possibly after merge of #1686

Add debug logging for output streaming

---

frankDoc/src/main/java/nl/nn/adapterframework/frankdoc/model/FrankElementFilters.java

Frank attributes are created for setter methods and also setter methods inherited from a parent class. Some classes of the Frank!Framework inherit from Spring classes. Some setters of these Spring classes produced unwanted Frank attributes. This pull request fixes that.
The Frank element "Configuration" will still have attributes that we do not want with this pull request. Those are not related to Spring and will be fixed later.

Partially fix issue "Restrict which attributes developers can set on FrankElements #1883"

---

frankDoc/src/main/java/nl/nn/adapterframework/frankdoc/AttributeTypeStrategy.java
frankDoc/src/test/resources/doc/examplesExpected/sequence.xsd
frankDoc/src/test/resources/doc/examplesExpected/simple.xsd
frankDoc/src/test/resources/doc/examplesExpected/simpleForCompatibility.xsd

With this fix, XMLSpy should not report errors anymore about frankdoc.xsd. I tested that the frankdoc.xsd from this code works in Eclipse and VSCode. Before merging, can you check with XMLSpy? I do not have that application. I emailed the XSDs to Gerrit.

partial fix #1885 "ibisdoc.xsd regular expressions are not compliant"

---

ladybug/pom.xml
ladybug/src/main/java/nl/nn/ibistesttool/MessageCapturer.java
ladybug/src/main/resources/springIbisTestTool.xml

- Prevent reports in progress because of unclosed streams or threads that didn't start and aren't cancelled
- Visualize waiting for threads and streams

Prevent reports in progress

---

test/src/main/configurations/HTTP/ConfigurationRestListener.xml
test/src/main/configurations/HTTP/ConfigurationWebServiceListenerSender.xml
test/src/main/configurations/HTTP/ConfigurationWebServiceListenerSenderAttachments.xml

1 - WebServiceSender attribute [proxyUserName] is deprecated: Please use "proxyUsername" instead
2 - Base64Pipe attribute [convert2String] is deprecated: Please use "outputType" instead

Fix warnings in config HTTP

---

test/src/main/configurations/MainConfig/ConfigurationCorrelationMessageId.xml
test/src/main/configurations/MainConfig/ConfigurationMessageStoreSenderAndListenerPeek.xml

1 - WebServiceListener [CorrelationMessageIdXPath2] calling webservices via de ServiceDispatcher_ServiceProxy is deprecated. Please specify an address or serviceNamespaceURI and modify the call accordingly
2 -  MessageStoreListener [MessageStoreListener] attribute [peekUntransacted] already has a default value [true]

Fix MainConfig warnings

---

test/src/main/configurations/HTTP/ConfigurationHttpListenerSender.xml

Deze fix is voor de warning:
HttpSender attribute [inputMessageParam]: Use the <code>firstBodyPartName</code> attribute instead

HttpListenerSender warning fix for inputMessageParam to firstBodyPartName

---

webapp/pom.xml

which I forgot to remove when I removed struts..
xTags silently depends on Dom4J which was removed in #2028

Remove xTags dependency

---

webapp/pom.xml

Unsure why Jaxen was added to the webapp (https://github.com/ibissource/iaf/commit/26fe6584b1e5a0b3d5a6b890e23bb8db38bb52c4).
Might be related to ibis-xtags / dom4j as dom4j depends on the jaxen xpath parser.

Remove Jaxen dependency

---

tibco/src/main/java/nl/nn/adapterframework/extensions/tibco/GetTibcoQueues.java

Skip ACL when no user or empty username is found (7.6)

---

core/src/main/java/nl/nn/adapterframework/monitoring/ITrigger.java
core/src/main/java/nl/nn/adapterframework/monitoring/Monitor.java
core/src/main/java/nl/nn/adapterframework/monitoring/Trigger.java
core/src/main/java/nl/nn/adapterframework/webcontrol/api/ShowMonitors.java

For the Frank!Doc, we want to introduce an interface ITrigger that is implemented by classes Trigger, Alarm and Clearing. We do not want to do this in a single pull request. This pull request just introduces ITrigger and lets the existing class Trigger implement it.
I have done the following tests:
* Run the Larva tests.
* Checkout the master branch and have a screen with the monitors that exist in Ibis4Test. Stop the Frank!Framework but leave the screen with the monitors. Checkout this pull request and start Ibis4Test again. Open a new tab in the browser and view the monitors again. Compare the two pages with monitors. There was no difference.
* Hack Ibis4Example (not checked in) to have a configuration with a monitor. Supply test messages to the example adapter to trigger and clear the …

Introduce interface ITrigger

---

frankDoc/src/main/java/nl/nn/adapterframework/frankdoc/model/FrankElementFilters.java

It was not present in the first place in the XSDs.

Frank!Doc: Remove java.lang.Object from the JSON

---

core/src/main/java/nl/nn/adapterframework/util/StringResolver.java
core/src/test/java/nl/nn/adapterframework/util/StringResolverTest.java
test/src/main/configurations/MainConfig/ConfigurationAuthentication.xml
test/src/test/testtool/Authentication/scenario04.properties
test/src/test/testtool/Authentication/scenario04/Result.xml
test/src/test/testtool/Authentication/scenario05.properties
test/src/test/testtool/Authentication/scenario05/Result.xml

in #2191 a feature to expand credentials as properties has been introduced. This PR solves a security issue of that, by only allowing to expand credentials that have their authAlias listed in the system property `authAliases.expansion.allowed`. This property must be configured by an administrator as a -D property, in catalina.properties or as a WebSphere custom property.
Example:
`FixedResultPipe` with `returnString="username: ${credential:username:testAlias}; password:${credential:password:testAlias}"`
yields:
`username: testUser; password:testPassword`
but only when `authAliases.expansion.allowed=testAlias` is specified as custom property

Secure credential expansion

---

core/pom.xml

It seems the issue #2372 is back with the jackson dependency upgrade

Exclude activation api dependency from jackson dependency

---

copyrightExcludeFile.txt

IntelliJ generates the metadata/idea folders and a .iml file, which cause a copyright error when running it with the frank-runner

Add generated folders and file to copyrightExcludeFile.txt

---

core/src/main/java/nl/nn/adapterframework/scheduler/job/SendMessageJob.java

Use job name instead of hardcoded name

---

docker/appserver/WebSphere/src/scripts/configureTransactionService.py

This is required to accept a one phase resources in two phase transactions, such as ActiveMQ which does not support XA.

Set AcceptHeuristicHazard in WAS test container

---

core/src/main/java/nl/nn/adapterframework/filesystem/ConnectedFileSystemBase.java
core/src/main/java/nl/nn/adapterframework/filesystem/ExchangeFileSystem.java
core/src/main/java/nl/nn/adapterframework/filesystem/ImapFileSystem.java
core/src/main/java/nl/nn/adapterframework/receivers/Receiver.java
test/src/main/configurations/MainConfig/ConfigurationExchangeMail.xml

- do not release connection if it has been invalidated
- load properties required for MessageContext
- pass loaded message to MessageContext generator
- do not start listenerContainer if an exception occurred

Fix ExchangeMailListener problems

---

RELEASES.md
core/src/main/java/nl/nn/adapterframework/http/WebServiceListener.java
core/src/main/java/nl/nn/adapterframework/receivers/ServiceDispatcher.java
test/src/main/configurations/HTTP/ConfigurationWebServiceListenerSenderAddress.xml
test/src/main/configurations/HTTP/ConfigurationWebServiceListenerSenderAttachments.xml

The WebServiceListener used to bind to both the listeners name (which is determined based on the receiver name) AND the ` address` attribute.

Fix test adapter names and ensure only bound to address when provided

---

pom.xml

This is useful for the CI/CD of the Frank!Doc. The Frank!Doc CI/CD verifies whether it can process the files of the F!F. With this change, the Frank!Doc CI/CD will enforce that the build of the F!F uses the desired version of this doclet.

Allow using another version of the frank-doc

---

core/src/main/java/nl/nn/adapterframework/util/XmlUtils.java

Fix ignoring namespaces logic while creating xpath evaluator source (7.7)

---

core/src/main/java/nl/nn/adapterframework/filesystem/FileSystemActor.java
core/src/test/java/nl/nn/adapterframework/filesystem/FileSystemActorTest.java

Throw exception when file to read does not exist in fileSystems (7.7)

---

aspose/pom.xml
cmis/pom.xml
cmis/src/test/java/nl/nn/adapterframework/extensions/cmis/TestBindingTypes.java
core/pom.xml
pom.xml

Ik heb na alle wijzigingen de oude en nieuwe war files vergeleken, het enige verschil is de toevoeging van de javax.activation:1.1.1 dependency. De excludes staan er nu hard in om mogelijke problemen in de toekomst tegen te gaan. Nu wordt de oude `jakarta.activation:jakarta.activation-api:1.2.2` jar overschreven en de `com.sun.activation:jakarta.activation:2.0.1` gebruikt. De inhoud in een ander package staat (javax/jakarta), de jar's gebruiken de zelfde naam.. Supersedes #2392

Add explicit javax.activation:1.1.1 dependency

---

checkstyle.xml
core/pom.xml
core/src/test/java/nl/nn/adapterframework/util/XmlBuilderTest.java
core/src/test/resources/Ldap/expected/updateNewEntry.xml
ladybug/pom.xml
pom.xml

Disallows the use of javax annotation, xml.ws and xml.soap and enforces the use of (com.sun) based Jakarta dependencies instead.
The dependencies have been renamed but their contents is still the same (the javax package is still used).

Disallow the use of javax annotation, xml.ws and xml.soap

---

core/pom.xml
core/src/main/java/nl/nn/adapterframework/pipes/JsonWellFormedChecker.java
core/src/test/java/nl/nn/adapterframework/pipes/JsonWellFormedCheckerTest.java

Reduces the risk of an `StackOverflowError`, see https://security.snyk.io/vuln/SNYK-JAVA-ORGJSON-2841369

Reduce the use of org.json and use javax.json instead

---

webapp/src/main/webapp/iaf/gui/js/controllers.js

Appears to have been introduced in #2570 while adding exception_stopped and exception_starting.

Fix receiver in error state not appearing as error in console

---

core/src/main/java/nl/nn/adapterframework/http/HttpMessageEntity.java
core/src/main/java/nl/nn/adapterframework/jta/TransactionConnector.java
core/src/main/java/nl/nn/adapterframework/jta/TransactionConnectorCoordinator.java
core/src/main/java/nl/nn/adapterframework/pipes/XsltPipe.java
core/src/main/java/nl/nn/adapterframework/senders/JsonXsltSender.java
core/src/main/java/nl/nn/adapterframework/senders/XsltSender.java
core/src/main/java/nl/nn/adapterframework/stream/Message.java
core/src/main/java/nl/nn/adapterframework/stream/MessageOutputStream.java
core/src/main/java/nl/nn/adapterframework/stream/StreamingSenderBase.java
core/src/main/java/nl/nn/adapterframework/stream/ThreadLifeCycleEventListener.java
core/src/main/java/nl/nn/adapterframework/xml/ExceptionCatchingFilter.java
core/src/main/java/nl/nn/adapterframework/xml/ThreadConnectingFilter.java
ladybug/src/main/java/nl/nn/ibistesttool/IbisDebuggerAdvice.java

- Disable streaming xslt when attribute streamingActive is set to false
- Improve error handling when XsltSender cannot parse XML (and the ExceptionCatchingFilter is never called)

Fix resumeTransaction always being forced when tx sync is inactive

---

core/src/main/java/nl/nn/adapterframework/webcontrol/api/ApiExceptionHandler.java

Use status code from parent exception when available (7.8)

---

.lift.toml
.lift/setup.sh

Here are the Lift results from my fork https://lift.sonatype.com/results/github.com/mattjohnson/iaf/01GJD5YAYG3QC2Z0MMVZ5RF4QS
The tools all complete and show results. The dependency scanning failed and we'll continue to look into why that has failed.

Remove deletion of Lift ranker tool

---

webapp/src/main/webapp/iaf/gui/js/controllers.js

Seems to have been introduced in #2385 when the response was converted to JSON without updating the error response

Fix error response when browsing TX messages

---

core/src/main/java/nl/nn/adapterframework/http/rest/ApiListenerServlet.java
core/src/test/java/nl/nn/adapterframework/http/rest/ApiListenerServletTest.java

When there is an error in parsing multipart requests, return an error 400 ("Bad Request") instead of 500 ("Internal Server Error").

4254 Status 400 not 500 for bad multipart requests

---

core/src/main/java/nl/nn/adapterframework/http/rest/ApiListener.java
core/src/main/java/nl/nn/adapterframework/http/rest/ApiListenerServlet.java
core/src/main/java/nl/nn/adapterframework/http/rest/MediaTypes.java
core/src/test/java/nl/nn/adapterframework/http/rest/ApiListenerServletTest.java
core/src/test/java/nl/nn/adapterframework/http/rest/ApiListenerTest.java
core/src/test/java/nl/nn/adapterframework/http/rest/MediaTypeTest.java
example/src/test/java/nl/nn/adapterframework/extensions/test/TestIbisTester.java
test/pom.xml

First draft of changes to make sure XML is not accepted when JSON is specified, or rather: to make sure that when MediaType is specified (any other than `ANY`), the `Content-Type` request header has to be set.
NB: Creating this still as DRAFT PR so far because I still need to run the full test-suite.

Abort request when Content-Type does not match consumes

---

core/src/main/java/nl/nn/adapterframework/http/rest/ApiListenerServlet.java
core/src/test/java/nl/nn/adapterframework/http/rest/ApiListenerServletTest.java

Fix messageId handling in ApiListenerServlet when the correlationId header is also present.

Fix messageId handling in ApiListenerServlet

---

core/src/main/java/nl/nn/adapterframework/http/rest/ApiListenerServlet.java
core/src/test/java/nl/nn/adapterframework/http/rest/ApiListenerServletTest.java

(cherry picked from commit 3b134b68c47b811889dc4a99270a1f9572a940d5)

Return status 400 (instead of 500) for bad multipart requests (#4295)

---

core/pom.xml
docker/appserver/JBoss/pom.xml
docker/appserver/Tomcat/pom.xml
docker/appserver/WebSphere/pom.xml
docker/appserver/WebSphere/src/scripts/configureJdbc.py
docker/appserver/WildFly/pom.xml

Backport of PR https://github.com/ibissource/iaf/pull/3903.
Mysql artefact has moved, was already fixed in master. Now added to 7.8 branch for proper testing of jenkin issues

Backport of 'Migrate to new MySql maven project'

---

copyrightExcludeFile.txt
core/src/main/java/nl/nn/adapterframework/webcontrol/api/ShowSecurityItems.java

This change fixes the SQL Injection Warning that is triggered from the Security Items page; I have tested this using IAF Example (with and without the change) however I'm not sure if adding a unit-test is worth the effort?
NB: The bug only applies to 7.8 and earlier. It does not apply to 7.9, as the code for the Security Items has changed and no longer triggers this warning.

SQL injections warning not suppressed

---

docker/appserver/JBoss/src/configuration/standalone.xml
docker/appserver/WebSphere/src/scripts/configureJms.py
docker/appserver/WildFly/src/configuration/standalone.xml
test/src/main/webapp/META-INF/context.xml

When using ActiveMQ version 5.16.0 or higher "jms.xaAckMode=1" is need in the connection string to still be able to use an XAConnection/XASession without a transaction.
See [release notes ActiveMQ 5.16.0](https://issues.apache.org/jira/secure/ReleaseNote.jspa?projectId=12311210&version=12341032) Bug [AMQ-2659](https://issues.apache.org/jira/browse/AMQ-2659)

Fix ActiveMQ 5.16.5 issue in 7.8 release

---

test/src/main/configurations/JDBC/ConfigurationManageDatabaseWrapper.xml
test/src/test/testtool/ApiWsdlGenerator/common.properties
test/src/test/testtool/JmsListenerSender/FF/scenario03.properties
test/src/test/testtool/JmsListenerSender/FF/scenario04.properties
test/src/test/testtool/Validators/Schema/openapi-json.json
test/src/test/testtool/Validators/Schema/openapi-soap.json
test/src/test/testtool/Validators/Schema/openapi_post.json
test/src/test/testtool/Validators/SoapValidator/common.properties

Increase timeouts for 2 iffy iaf-test scenario's back to their originals from  #4151
- /JmsListenerSender/FF/scenario03 - JmsFFSender OK, exception in listener, with a missing 'E' record in the errorstore,
- /JmsListenerSender/FF/scenario04 - JmsFFSenderWithDatasource OK. with an unexpected message on the queue.

Change WSDL endpoints and Increase JMS scenario timeouts

---

docker/appserver/JBoss/src/configuration/standalone.xml
docker/appserver/WildFly/src/configuration/standalone.xml

As mentioned before in PR #3690, do not set xaAckMode for JBoss and WildFly.

Remove xaAckMode for JBoss and WildFly

---

core/src/main/java/nl/nn/adapterframework/validation/IntraGrammarPoolEntityResolver.java
core/src/main/java/nl/nn/adapterframework/validation/XSD.java
core/src/main/java/nl/nn/adapterframework/validation/XercesXmlValidator.java
core/src/test/java/nl/nn/adapterframework/validation/IntraGrammarPoolEntityResolverTest.java
core/src/test/java/nl/nn/adapterframework/validation/Json2XmlValidatorTest.java
core/src/test/resources/Validation/IncludeNonExistingResource/main.xsd

There were several defects in the `IntraGrammarPoolEntityResolver`.
- When a resources cannot be found it should throw an `XNIException`, see [ClassLoaderXmlEntityResolver](https://github.com/ibissource/iaf/blob/7.7-release/core/src/main/java/nl/nn/adapterframework/xml/ClassLoaderXmlEntityResolver.java#L77). This in turn should trigger an `error` in the [XercesXmlValidator preparser ErrorHandler](https://github.com/ibissource/iaf/blob/7.7-release/core/src/main/java/nl/nn/adapterframework/validation/XercesXmlValidator.java#L467).
The exception is rethrown, causing the validator/pipe to not start, and thus give the developer feedback of a missing import.
- When using absolute file paths Xerces appends the file protocol to each imported systemId. By manually prepending the `classpath` …

Fix local resource lookup when preparsing XSD's

---

core/src/main/java/nl/nn/adapterframework/filesystem/ExchangeAttachmentReference.java
core/src/main/java/nl/nn/adapterframework/filesystem/ExchangeFileSystem.java
core/src/main/java/nl/nn/adapterframework/filesystem/ExchangeMessageReference.java
core/src/main/java/nl/nn/adapterframework/filesystem/ExchangeObjectReference.java
core/src/main/java/nl/nn/adapterframework/filesystem/FileSystemListener.java
core/src/main/java/nl/nn/adapterframework/receivers/ExchangeMailListener.java
core/src/main/java/nl/nn/adapterframework/senders/ExchangeFolderSender.java
test-integration/pom.xml
test-integration/src/test/java/nl/nn/adapterframework/filesystem/ExchangeFileSystemTest.java
test-integration/src/test/java/nl/nn/adapterframework/filesystem/ExchangeMailListenerTest.java
test-integration/src/test/java/nl/nn/adapterframework/filesystem/ExchangeMailListenerTestBase.java
test-integration/src/test/java/nl/nn/adapterframework/filesystem/ImapFileSystemTest.java
test-integration/src/test/java/nl/nn/adapterframework/filesystem/MailFileSystemTestBase.java
test-integration/src/test/java/nl/nn/adapterframework/http/OAuthAccessTokenManagerTest.java

These are changes to make sure we can always reconnect a mail-message with the mailbox from which it was read.
This still needs to be tested against an actual exchange service.

Add mailbox reference to mail-messages

---

cmis/src/test/java/nl/nn/adapterframework/extensions/cmis/CmisHttpInvokerTest.java
cmis/src/test/java/nl/nn/adapterframework/extensions/cmis/CmisSenderTestBase.java
console/src/test/resources/DeploymentSpecifics.properties
core/src/main/java/nl/nn/adapterframework/errormessageformatters/ErrorMessageFormatter.java
core/src/main/java/nl/nn/adapterframework/management/bus/endpoints/BusEndpointBase.java
core/src/main/java/nl/nn/adapterframework/util/Misc.java
core/src/test/java/nl/nn/adapterframework/management/bus/endpoints/TestDatabaseMigrator.java
core/src/test/java/nl/nn/adapterframework/stream/MessageTest.java
credentialProvider/src/main/java/nl/nn/credentialprovider/util/Misc.java

Fix imports of `Misc` that were importing from the `credential-provider` module to instead import the version in `core` module.
NB: Moving `Misc` and some other util classes to a separate Maven module will be another PR, first I want to get the imports right.

Fix imports from the credential-provider project

---

.github/workflows/maven-build.yml
.mvn/wrapper/maven-wrapper.properties
copyrightExcludeFile.txt
core/src/main/java/nl/nn/adapterframework/core/Adapter.java
mvnw
mvnw.cmd

Use Maven Wrapper in Github Actions to avoid picking up Maven 3.9.0 which is not Frank!Doc compatible at the moment.
(cherry picked from commit 3997cd07f3a928ddfb22a8f4fe51bb8e5e034cc3)

(7.8) Fix GitHub Actions Maven build (#4579)

---

.github/workflows/maven-build.yml
.mvn/wrapper/maven-wrapper.properties
copyrightExcludeFile.txt
core/src/main/java/nl/nn/adapterframework/core/Adapter.java
mvnw
mvnw.cmd

Use Maven Wrapper in Github Actions to avoid picking up Maven 3.9.0 which is not Frank!Doc compatible at the moment.
(cherry picked from commit 3997cd07f3a928ddfb22a8f4fe51bb8e5e034cc3)

(7.7) Fix GitHub Actions Maven build (#4579)

---

cmis/pom.xml
core/pom.xml
core/src/main/java/nl/nn/adapterframework/jdbc/JdbcListener.java
core/src/main/java/nl/nn/adapterframework/jdbc/JdbcMessageBrowser.java
core/src/main/java/nl/nn/adapterframework/jdbc/dbms/JdbcSession.java
core/src/main/java/nl/nn/adapterframework/jdbc/dbms/MariaDbDbmsSupport.java
core/src/main/java/nl/nn/adapterframework/jdbc/dbms/MySqlDbmsSupport.java
core/src/main/java/nl/nn/adapterframework/lifecycle/IbisApplicationContext.java
core/src/main/java/nl/nn/adapterframework/lifecycle/VerifyDatabaseConnectionBean.java
core/src/main/java/nl/nn/adapterframework/management/bus/endpoints/AdapterStatus.java
core/src/main/java/nl/nn/adapterframework/unmanaged/DefaultIbisManager.java
core/src/main/resources/SpringApplicationContext.xml
core/src/main/resources/springUnmanagedDeployment.xml
core/src/test/java/nl/nn/adapterframework/testutil/mock/MockIbisManager.java
pom.xml

In CXF-Parent the `geronimo-jta_1.1_spec` is added through a profile (`java9-plus`), see [pom.xml](https://repo1.maven.org/maven2/org/apache/cxf/cxf-parent/3.5.5/cxf-parent-3.5.5.pom).

Create bean to validate database connectivity

---

webapp/src/main/webapp/iaf/gui/js/controllers.js

Remove double slash in monitoring url

---

core/src/main/java/nl/nn/adapterframework/configuration/ConfigurationUtils.java
core/src/main/java/nl/nn/adapterframework/core/IbisTransaction.java
core/src/main/java/nl/nn/adapterframework/jdbc/JdbcTransactionalStorage.java
core/src/main/java/nl/nn/adapterframework/jta/SpringTxManagerProxy.java
core/src/main/java/nl/nn/adapterframework/processors/TransactionAttributePipeLineProcessor.java
core/src/main/java/nl/nn/adapterframework/processors/TransactionAttributePipeProcessor.java
core/src/main/java/nl/nn/adapterframework/receivers/Receiver.java
core/src/main/java/nl/nn/adapterframework/util/Locker.java
core/src/test/java/nl/nn/adapterframework/jdbc/dbms/ConcurrentManagedTransactionTester.java
core/src/test/java/nl/nn/adapterframework/util/LockerTest.java

Add warnings to the `SpringTxManagerProxy.commit()` method when it silently does a rollback instead.
Normally when you commit a transaction marked for rollback-only, then there will be an exception. Current TX manager code does rollback without exception. This can hide the fact that a transaction was not actually committed and we want to find out how that happens and where, and how often.
Rename `IbisTransaction.commit()` to `.complete()` since that is what it is designed to do, not commit.

Add warning when transaction-mgr does silent rollback during commit

---

cmis/src/main/java/nl/nn/adapterframework/extensions/cmis/mtom/MtomProxy.java
core/src/main/java/nl/nn/adapterframework/configuration/ClassLoaderManager.java
core/src/main/java/nl/nn/adapterframework/util/ClassUtils.java
iaf-commons/src/main/java/nl/nn/adapterframework/util/StringUtil.java
iaf-commons/src/test/java/nl/nn/adapterframework/util/StringUtilTest.java

I've done a few UC and LC tests and it turns out the char[] conversion is faster:
char[]  1278314600
substr 1382596200
strbuf 1373397800
```
public static String charArr(String input) {
char[] c = input.toCharArray();
c[0] = Character.toLowerCase(c[0]);
return new String(c);
}
private static String subStr(String input) {
return input.substring(0, 1).toLowerCase() + input.substring(1);
}
private static String strBuff(String input) {
StringBuffer sb = new StringBuffer(input.length());
sb.append(Character.toLowerCase(input.charAt(0)));
sb.append(input.substring(1));
return sb.toString();
}
```

Fix loadOnStartup check in CmisProxyServlet

---

core/src/main/java/nl/nn/adapterframework/configuration/digester/ValidateAttributeRule.java
core/src/main/java/nl/nn/adapterframework/util/ClassUtils.java
core/src/test/java/nl/nn/adapterframework/configuration/digester/ValidateAttributeRuleTest.java
core/src/test/java/nl/nn/adapterframework/util/ClassUtilsTest.java
test/src/main/resources/DeploymentSpecifics.properties

Make `ClassUtils#convertToType` more generic
Reduce empty value console warnings
Add tests to cover #2763
Revert iaf-test jms queue suffix removal #4749

Make convertToType more generic, and reduce empty value console warnings

---

core/src/main/java/nl/nn/adapterframework/stream/SerializableFileReference.java
core/src/test/java/nl/nn/adapterframework/stream/SerializableFileReferenceTest.java

Previous changes could cause leaking of streams, which was not detected by tests in 7.8 branch.
(Streams would of course eventually be finalised but would not be closed on time)

Fix possible stream leak detected by tests in master

---

core/src/main/java/nl/nn/adapterframework/ftp/SftpSession.java

Only the `username` and `password` properties were working. 
The password is now retrieved from the `credentialFactory` so `authAlias` works again.

Fix authAlias in SftpSession.java

---

core/src/main/java/nl/nn/adapterframework/jdbc/DirectQuerySender.java
core/src/main/java/nl/nn/adapterframework/jdbc/FixedQuerySender.java
core/src/main/java/nl/nn/adapterframework/jdbc/JdbcListener.java
core/src/main/java/nl/nn/adapterframework/jdbc/JdbcQuerySenderBase.java
core/src/main/java/nl/nn/adapterframework/jdbc/QueryExecutionContext.java
core/src/main/java/nl/nn/adapterframework/jdbc/XmlQuerySender.java
core/src/main/java/nl/nn/adapterframework/jdbc/dbms/GenericDbmsSupport.java
core/src/main/java/nl/nn/adapterframework/jdbc/dbms/IDbmsSupport.java
core/src/test/java/nl/nn/adapterframework/jdbc/FixedQuerySenderTest.java
core/src/test/java/nl/nn/adapterframework/jdbc/JdbcTableListenerTest.java
core/src/test/java/nl/nn/adapterframework/jdbc/JdbcTestBase.java
core/src/test/java/nl/nn/adapterframework/jdbc/dbms/DbmsSupportTest.java
core/src/test/java/nl/nn/adapterframework/jdbc/dbms/H2DbmsSupportTest.java
core/src/test/java/nl/nn/adapterframework/jdbc/dbms/SqlTranslatorOracleToH2Test.java
core/src/test/java/nl/nn/adapterframework/jdbc/dbms/SqlTranslatorOracleToMsSqlTest.java
core/src/test/java/nl/nn/adapterframework/jdbc/dbms/TestBlobs.java

Make QueryExecutionContext a mostly read-only structure and simplify methods that use just the query-string, to take that query string as parameter so that fewer unneeded instances of QEC are created.
In FixedQuerySender, translate query only once instead of on every invocation.

Lcm JDBC code cleanups pt. 3

---

RELEASES.md
console/backend/pom.xml
console/backend/src/main/java/nl/nn/adapterframework/management/web/CompatibilityShowScheduler.java
console/backend/src/main/java/nl/nn/adapterframework/management/web/DeprecationFilter.java
console/backend/src/main/java/nl/nn/adapterframework/management/web/FrankApiBase.java
console/backend/src/main/java/nl/nn/adapterframework/management/web/Init.java
console/backend/src/main/java/nl/nn/adapterframework/management/web/ShowScheduler.java
console/backend/src/test/java/nl/nn/adapterframework/management/web/TestDeprecationFilter.java
console/backend/src/test/java/nl/nn/adapterframework/util/TestAppender.java
core/src/main/resources/AppConstants.properties

The scheduler endpoints have been renamed in #4069 from .../job/.. to .../jobs/..
These need to be backported (and a fix needs to be added to the release notes).

Add deprecation filter for older API endpoints

---

core/src/main/java/nl/nn/adapterframework/pipes/Json2XmlValidator.java
core/src/test/java/nl/nn/adapterframework/pipes/Json2XmlValidatorTest.java

Feature introduced in #4314 not taking into effect the accept header can be `*/*` or contain multiple values.

Fix Json2XmlValidator response type parsing

---

core/pom.xml
core/src/test/java/nl/nn/adapterframework/jdbc/JdbcTestBase.java
core/src/test/java/nl/nn/adapterframework/testutil/URLDataSourceFactory.java

Improve logging of test configuration.
(DB2 remains broken in the unit tests, CREATE TABLE statements in test appear incompatible w/DB2).
Backport of improvements also in 7.9.

Fix JDBC/JTA unit tests not running on MS-SQL

---

aspose/src/main/java/nl/nn/adapterframework/extensions/aspose/services/conv/impl/CisConversionServiceImpl.java
aspose/src/main/java/nl/nn/adapterframework/extensions/aspose/services/conv/impl/convertors/AbstractConvertor.java
aspose/src/test/java/nl/nn/adapterframework/extensions/aspose/pipe/PdfPipeTest.java
aspose/src/test/resources/Util/MessageUtils/utf8-with-bom.txt

(cherry picked from commit fd295cc60bbdef852ce9d3ec5e8cdecc69eb6bfd)

ASPOSE: Strip MimeType params for converters (7.8)

---

core/src/main/java/nl/nn/adapterframework/scheduler/job/SendMessageJob.java
core/src/test/java/nl/nn/adapterframework/scheduler/job/SendMessageJobTest.java

Closing multiple objects when possible. Add unit testing, was partly covered by other unit tests already. Mostly the configure method.

Job response not read and closed: close localSender, Message, PipeLineSession too (#5324)

---

larva/src/main/java/nl/nn/adapterframework/testtool/SenderThread.java
larva/src/main/java/nl/nn/adapterframework/testtool/queues/QueueWrapper.java

Also close these SenderResult objects. Came out of a search. 
More will follow separately.

Close SenderResult to avoid leaks

---

core/src/main/java/nl/nn/adapterframework/core/PipeLineSession.java
core/src/main/java/nl/nn/adapterframework/receivers/JavaListener.java
core/src/main/java/nl/nn/adapterframework/senders/IbisJavaSender.java
core/src/main/java/nl/nn/adapterframework/senders/IbisLocalSender.java
core/src/test/java/nl/nn/adapterframework/core/PipeLineSessionTest.java
core/src/test/java/nl/nn/adapterframework/senders/IbisLocalSenderTest.java

* Better fix for the issue of closed session keys after calling a sub-adapter, plus unit-tests that catch and demonstrate the problem.
* More complete fixes for closeables that appear in multiple sessions, and more tests added to catch different situations.

Do not close any session keys in sub-adapter that are also in calling adapter

---

core/src/main/java/nl/nn/adapterframework/core/PipeLineResult.java
core/src/main/java/nl/nn/adapterframework/core/PipeRunResult.java
core/src/main/java/nl/nn/adapterframework/core/SenderResult.java
core/src/main/java/nl/nn/adapterframework/stream/Message.java

Alternate fix that prevents a message in a result from ever having the value NULL.

Alternate fix for #5377, null result value

---

Docker.md

Linux doesn't have a lowercase $pwd variable set by default, but uppercase exists.
Please verify if the uppercase $PWD exists in Powershell on Windows with `echo $PWD`. This should output the current directory.

[docs] Docker compatibility with Linux

---

core/pom.xml
pom.xml

Only the core bumped beanutils, while other modules where using old vulnerable versions still.

Bump commons-beanutils to 1.9.4 for every module/project

---

pom.xml

Backport f3dd4e1ef2fdfb2e3c73c871c8b65402f85c6cd1, see #5429.

Reduce CI JavaDoc logging

---

ladybug/src/main/java/nl/nn/ibistesttool/PipeDescriptionProvider.java
ladybug/src/test/java/nl/nn/ibistesttool/TestPipeDescriptionProvider.java
ladybug/src/test/resources/log4j4ibis.xml
ladybug/src/test/resources/testFilename.xml
ladybug/src/test/resources/testSchemaLocation.xml
ladybug/src/test/resources/testWithTwoSchemaLocations.xml

Since https://github.com/ibissource/iaf/pull/5095 we no longer skip all even entries.

Fix for loop when using schemaLocation in Ladybug ResourceProvider

---

pom.xml

Use Maven Central repository first instead of downloading everything from Frank's Nexus first.
Came to see this while upgrading deps for Java 11.

Use Maven Central repository first

---

console/backend/src/main/java/nl/nn/adapterframework/management/web/RequestMessageBuilder.java
console/backend/src/main/java/nl/nn/adapterframework/management/web/ServletDispatcher.java
console/backend/src/main/java/nl/nn/adapterframework/management/web/ShowConfiguration.java
core/pom.xml
core/src/main/resources/log4j4ibis.properties
core/src/main/resources/log4j4ibis.xml
iaf-commons/src/main/java/nl/nn/adapterframework/util/HttpUtils.java
pom.xml

Results in the following log line:
`
2023-09-29 12:00:21,728 [http-nio-80-exec-2] created bus request from URI [PUT:http://localhost/iaf-test/iaf/api/server/logging] issued by remoteHost [0:0:0:0:0:0:0:1] remoteAddress [0:0:0:0:0:0:0:1] remoteUser [Admin] with headers [enableDebugger=true, logLevel=WARN, maxMessageLength=-1, logIntermediaryResults=true] payload [NONE]
`

Reduce and improve security logging

---

console/frontend/src/main/frontend/js/app/app.config.js
console/frontend/src/main/frontend/js/app/views/adapterstatistics/adapterstatistics.component.js
console/frontend/src/main/frontend/js/app/views/configurations/configurations-manage/configurations-manage.component.js
console/frontend/src/main/frontend/js/app/views/configurations/configurations-show/configurations-show.component.js
console/frontend/src/main/frontend/js/app/views/configurations/configurations-upload/configurations-upload.component.js
console/frontend/src/main/frontend/js/app/views/environment-variables/environment-variables.component.js
console/frontend/src/main/frontend/js/app/views/ibisstore-summary/ibisstore-summary.component.js
console/frontend/src/main/frontend/js/app/views/inlinestore/inlinestore.component.js
console/frontend/src/main/frontend/js/app/views/liquibase/liquibase.component.js
console/frontend/src/main/frontend/js/app/views/monitors/monitors.component.js
console/frontend/src/main/frontend/js/app/views/scheduler/scheduler-add/scheduler-add.component.js
console/frontend/src/main/frontend/js/app/views/scheduler/scheduler-edit/scheduler-edit.component.js
console/frontend/src/main/frontend/js/app/views/scheduler/scheduler.component.js
console/frontend/src/main/frontend/js/app/views/security-items/security-items.component.html
console/frontend/src/main/frontend/js/app/views/status/status.component.js
console/frontend/src/main/frontend/js/app/views/test-pipeline/test-pipeline.component.js

Also fixed various small issue found during testing
* inlinestore giving an error because appService wasnt being injected
* added $onInit to configurations-upload, this might not have been an actual issue but stability and consistency is important
Fixes issue found by @nielsm5 where moving from 'monitors' to 'manage configurations' would trigger monitors' rootscope$on which caused the router to transition back to 'monitors' page

add unregister for all rootscope $on handlers

---

core/src/main/java/nl/nn/adapterframework/extensions/test/IbisTester.java
example/pom.xml
example/src/test/java/nl/nn/adapterframework/extensions/test/TestIbisTester.java
iaf-commons/src/main/java/nl/nn/adapterframework/util/ClassUtils.java
larva/src/main/java/nl/nn/adapterframework/testtool/LarvaServlet.java
larva/src/main/java/nl/nn/adapterframework/testtool/TestTool.java
larva/src/main/java/nl/nn/adapterframework/testtool/XsltProviderListener.java
larva/src/main/java/nl/nn/adapterframework/testtool/queues/QueueCreator.java
larva/src/main/java/nl/nn/adapterframework/testtool/queues/QueueUtils.java
larva/src/main/java/nl/nn/adapterframework/testtool/queues/QueueWrapper.java
larva/src/main/java/nl/nn/adapterframework/testtool/queues/RelativePathDirectoryClassLoader.java
test/src/test/testtool/XsltProviderListener/scenario01.properties
test/src/test/testtool/XsltProviderListener/scenario02.properties

I broke the behavior in #3759 by using the reflection way of instantiating the XsltProviderListener. Before it used the `filename.absolutepath` property instead of the `filename`.

Make Larva able to retrieve relative resources

---

ladybug/src/main/resources/springIbisTestTool.xml
pom.xml

See [#1865](https://github.com/apache/logging-log4j2/issues/1865) why we've reverted...

Lock commons:fileupload and autowire testtool report task

---

core/src/main/java/nl/nn/adapterframework/collection/Collection.java
core/src/main/java/nl/nn/adapterframework/compression/ZipWriter.java
core/src/main/java/nl/nn/adapterframework/pipes/UnzipPipe.java
core/src/main/java/nl/nn/adapterframework/util/StreamCaptureUtils.java
test/src/main/configurations/MainConfig/ConfigurationZip.xml
test/src/test/testtool/Zip/ZipWriter/output-3.xml
test/src/test/testtool/Zip/ZipWriter/scenario03.properties

Tested that without this fix, the included IAF-Test scenario produces a ZIP file with only 0-byte files, like in the original issue. The scenario produces only `<result></result>` as output, manually checking the ZIP file shows 0 byte files.
With the fix the ZIP file contains the actual data it is supposed to.

Fix zip with empty files added by sub-adapters

---

core/src/main/java/nl/nn/adapterframework/http/rest/ApiListener.java
core/src/main/java/nl/nn/adapterframework/http/rest/ApiListenerServlet.java
core/src/main/java/nl/nn/adapterframework/jwt/JwtSecurityHandler.java
core/src/test/java/nl/nn/adapterframework/http/rest/ApiListenerServletTest.java

Introduce AnyMatchClaims attribute (#5201)

---

.github/workflows/codeql-java.yml
.github/workflows/maven-build.yml
pom.xml

For now this simplifies the build. Perhaps we can split up the minimal and full build at a later stage once https://github.com/ibissource/iaf/issues/5741 and https://github.com/ibissource/iaf/issues/5742 have been merged.

Remove Extra Modules profile

---

.github/dependabot.yml
CONTRIBUTING.md
QUICK_START.md
RELEASE.md
RELEASES.md
SECURITY.md
TESTING_WITH_IAF-TEST.md
console/frontend/src/main/frontend/js/app/components/pages/feedback-modal/feedback.html
console/frontend/src/main/frontend/js/app/components/pages/information-modal/information.html
console/frontend/src/main/frontend/js/app/components/pages/pages-footer.component.html
console/frontend/src/main/frontend/js/app/components/pages/pages-navigation.component.html
console/frontend/src/main/frontend/js/app/views/login/login.component.html
core/src/main/java/nl/nn/adapterframework/jta/btm/BtmDiskJournal.java
core/src/main/java/nl/nn/adapterframework/validation/IntraGrammarPoolEntityResolver.java
core/src/main/javadoc/overview.html
core/src/test/java/nl/nn/adapterframework/parameters/ParameterTest.java
docker/README.md
pom.xml
test-integration/src/test/java/nl/nn/adapterframework/filesystem/MailFileSystemTestBase.java
test-integration/src/test/resources/ExchangeMailAttachedMessage.xml
test-integration/src/test/resources/ExchangeMailNormal.xml
test-integration/src/test/resources/ExchangeMailNormalBody.txt
test-integration/src/test/resources/ExchangeMailNormalContents.txt
test-integration/src/test/resources/ExchangeMailNormalSimple.xml

I've considered to not add the test, but I think it's nicer to just replace it everywhere.
I did not replace ibissource/iaf-ci-images because it's not transferred yet.

Change referances from ibissource/iaf to frankframework/frankframework

---

console/backend/pom.xml
core/pom.xml
pom.xml

Originally it was thought that using version 1.1.1 would solve issues, however this was not the case...
See #3408 for the original dependency lock

Upgrade activation to 1.2.2

---

core/src/main/java/nl/nn/adapterframework/http/HttpSender.java
core/src/test/resources/Http/Responses/simpleMtomFromParametersAndMultipartXml.txt
core/src/test/resources/Http/Responses/simpleMtomFromParametersAndMultipartXmlNoPartName.txt
core/src/test/resources/Http/Responses/simpleMultipartFromParametersAndMultipartXml.txt
core/src/test/resources/Http/Responses/simpleMultipartFromParametersAndMultipartXmlNoPartName.txt

With #3564 and #3924 in mind, actually use the `type="file"` attribute to distinguish if a part should have a filename or not.
In a future version we also need to fix #3917 behavior where it should only lookup the filename (when not set in the part xml) but present in the MessageContext.

Actually implement type=file attribute when using multipartXml

---

core/src/main/java/nl/nn/adapterframework/core/PipeLineSession.java

The code in this method has been bothering me for a while and I had this change locally for a while now. This cleanup is safe against concurrent modifications, although I think our other code in Message and PipeLineSession had already been cleaned up so this was no longer a problem.
Regardless this is safe and does not create a new Iterator every time!

Minor code improvement in closing PipeLineSession

---

console/frontend/src/main/frontend/src/app/views/status/status.component.html

Adds the ability to ctrl+right click or use the context menu to open the statistics or message/pipe stores in a new tab

change adapter statistics & message store buttons to anchor tags

---

docker/Tomcat/webapp/src/scripts/entrypoint.sh

This makes it possible to change the JAVA_OPTS attributes in the Docker image if needed.
On Kubernetes this is needed to change the location of the heap dump.

Move user JAVA_OPTS to back so defaults can be overwritten

---

core/src/main/java/org/frankframework/http/rest/ApiListenerServlet.java

Remove leading comma in Access-Control-Allow-Methods response header

---

core/src/main/java/org/frankframework/soap/SoapWrapper.java
core/src/main/java/org/frankframework/soap/SoapWrapperPipe.java
core/src/test/java/org/frankframework/pipes/SoapWrapperPipeTest.java

* Prevents bug of reusing stored SoapVersion from previous SoapWrappers

SoapWrapper should try unwrapping with soap version 1.1 too (#6032)

---

core/src/main/java/org/frankframework/http/rest/ApiDispatchConfig.java

https://docs.oracle.com/javase/8/docs/api/java/util/Map.html#get-java.lang.Object-
get
V get(Object key)
Returns the value to which the specified key is mapped, or null if this map contains no mapping for the key.

Remove redundant containsKey check

---

core/src/main/java/org/frankframework/soap/SoapWrapper.java
core/src/main/java/org/frankframework/soap/SoapWrapperPipe.java
core/src/test/java/org/frankframework/pipes/SoapWrapperPipeTest.java

* Prevents bug of reusing stored SoapVersion from previous SoapWrappers

v8.0-branch - SoapWrapper should try unwrapping with soap version 1.1 too (#6032)

---

core/src/main/java/org/frankframework/pipes/IsUserInRolePipe.java
core/src/test/java/org/frankframework/pipes/IsUserInRolePipeTest.java

Dit is in de review niet opgemerkt maar bij nader inzien is dit niet toch niet zo handig.
Ik ging er vanuit dat als de notInRoleForward null is, het geen zin heeft om dan nog te vermelden om welke naam het ging.
Echter bij een tweede blik hierop blijkt dat het toch voor kan komen dat getNotInRoleForwardName() een gevulde string is en dat de gerelateerde forward niet gevonden kan worden.
Het lijkt mij een goed idee om dit te herstellen naar throw new ConfigurationException("could not find forward for notInRoleForwardName ["+ getNotInRoleForwardName()+"]");

Restore forward name in ConfigurationException thrown in isUserInRolePipe

---

core/src/main/java/org/frankframework/core/PipeLineSession.java
core/src/main/java/org/frankframework/http/RestListenerServlet.java
core/src/main/java/org/frankframework/http/rest/ApiCacheManager.java
core/src/main/java/org/frankframework/http/rest/ApiListener.java
core/src/main/java/org/frankframework/http/rest/ApiListenerServlet.java
core/src/main/java/org/frankframework/http/rest/ApiPrincipalPipe.java
core/src/main/java/org/frankframework/http/rest/ApiServiceDispatcher.java
core/src/main/java/org/frankframework/management/bus/endpoints/WebServices.java
core/src/test/java/org/frankframework/http/rest/ApiListenerPatternsTest.java
core/src/test/java/org/frankframework/http/rest/ApiListenerServletTest.java
core/src/test/java/org/frankframework/http/rest/ApiListenerTest.java
core/src/test/java/org/frankframework/http/rest/ApiServiceDispatcherTest.java
core/src/test/java/org/frankframework/http/rest/OpenApiTestBase.java
core/src/test/java/org/frankframework/management/bus/endpoints/TestWebServices.java

closes #5443 once implemented.
first draft, new test cases proof that ApiListener is succesfully registered with multiple methods.
might want to add more test cases to proof the added functionality.
open to suggestions for improvement

Support multiple methods for a single ApiListener 

---

cmis/src/main/java/nl/nn/adapterframework/extensions/cmis/CmisCustomAtomPubSpi.java
cmis/src/main/java/nl/nn/adapterframework/extensions/cmis/CmisCustomBrowserBindingSpi.java
cmis/src/main/java/nl/nn/adapterframework/extensions/cmis/CmisCustomWebServicesSpi.java
cmis/src/main/java/nl/nn/adapterframework/extensions/cmis/CmisHttpInvoker.java
cmis/src/main/java/nl/nn/adapterframework/extensions/cmis/CmisSender.java
cmis/src/main/java/nl/nn/adapterframework/extensions/cmis/CmisSessionBuilder.java
cmis/src/main/java/nl/nn/adapterframework/extensions/cmis/CmisUtils.java
core/src/main/java/nl/nn/adapterframework/http/HttpSenderBase.java

This should close the Apache HTTP Client used by Cmis Sender, however I do not yet have tests for this so the PR is still in draft.
However from this branch a version could be built to use for testing, I think.

Close CMIS HTTP Client properly to avoid leaking threads

---

.github/workflows/maven-build.yml

Build of 7.9-release branch now fails with error due to Sonar no longer supporting JDK11.
Not an issue for other branches.

Remove Sonar from the 7.9 build as Sonar no longer supports JDK11

---

console/frontend/src/main/frontend/src/app/views/storage/storage-list/storage-list.component.html
console/frontend/src/main/frontend/src/app/views/storage/storage-list/storage-list.component.ts
console/frontend/src/main/frontend/src/app/views/storage/storage.service.ts
console/frontend/src/main/frontend/src/app/views/test-pipeline/test-pipeline.component.ts

7.9 fix for having wrong `targetStates` type breaking (error) message store in the console
Fixes #5594

Fix wrong targetStates type breaking (error) message store in the console

---

console/frontend/src/main/frontend/src/app/views/configurations/configurations-manage/configurations-manage-details/configurations-manage-details.component.html
core/src/main/java/org/frankframework/management/bus/dto/ConfigurationDTO.java
core/src/main/java/org/frankframework/management/bus/endpoints/ConfigManagement.java

* Fixes configuration details page showing `[Object object]` instead of configuration name
* Fixes sql error caused by `rs.getDate` not being able to convert TIMESTAMP column in `ConfigManagement.getConfigsFromDatabase`

Fix configuration versions page & api giving back sql error

---

console/frontend/src/main/frontend/src/app/pipes/with-java-listener.pipe.ts
console/frontend/src/main/frontend/src/app/views/scheduler/scheduler-add-edit-parent.component.html
console/frontend/src/main/frontend/src/app/views/test-pipeline/test-pipeline.component.html

* Truncates adapter name and description shown in adapter dropdown lists
* Fixes small issue in add/edit scheduler page where it shows duplicates of adapters

Truncate adapter name and descriptions in select form elements

---

core/src/main/java/org/frankframework/soap/SoapWrapperPipe.java
core/src/test/java/org/frankframework/pipes/SoapWrapperPipeTest.java

InputWrapper used to Wrap, should always specify a SoapVersion (#5925)

---

core/src/main/java/org/frankframework/jms/BytesMessageInputStream.java
core/src/main/resources/AppConstants.properties
nn-specials/src/main/java/org/frankframework/extensions/esb/EsbJmsListener.java
nn-specials/src/test/java/org/frankframework/extensions/esb/EsbJmsListenerTest.java
test/src/main/configurations/JMS/ConfigurationEsbJmsListenerSender.xml
test/src/main/resources/DeploymentSpecifics.properties
test/src/test/testtool/EsbJmsListenerSender/common.properties
test/src/test/testtool/EsbJmsListenerSender/scenario01.properties
test/src/test/testtool/EsbJmsListenerSender/scenario02.properties
test/src/test/testtool/EsbJmsListenerSender/scenario03.properties
test/src/test/testtool/EsbJmsListenerSender/scenario04.properties
test/src/test/testtool/EsbJmsListenerSender/scenario05.properties
test/src/test/testtool/EsbJmsListenerSender/scenario06.properties
test/src/test/testtool/EsbJmsListenerSender/scenario07.properties
test/src/test/testtool/EsbJmsListenerSender/scenario08.properties
test/src/test/testtool/EsbJmsListenerSender/scenario09.properties
test/src/test/testtool/EsbJmsListenerSender/scenario10.properties
test/src/test/testtool/EsbJmsListenerSender/scenario11.properties
test/src/test/testtool/EsbJmsListenerSender/scenario12.properties
test/src/test/testtool/EsbJmsListenerSender/scenario13.properties
test/src/test/testtool/EsbJmsListenerSender/scenario14.properties
test/src/test/testtool/EsbJmsListenerSender/scenario14/in.xml
test/src/test/testtool/EsbJmsListenerSender/scenario14/out.xml
test/src/test/testtool/EsbJmsListenerSender/scenario15.properties
test/src/test/testtool/EsbJmsListenerSender/scenario15/in.xml
test/src/test/testtool/EsbJmsListenerSender/scenario15/out.xml

Fix reading JMS BytesMessage data after extracting message properties

---

core/src/main/java/nl/nn/adapterframework/jndi/AbstractXADataSourceFactory.java
core/src/main/java/nl/nn/adapterframework/jndi/PoolingJndiDataSourceFactory.java
core/src/main/java/nl/nn/adapterframework/jta/btm/BtmDataSourceFactory.java
core/src/main/java/nl/nn/adapterframework/jta/narayana/NarayanaDataSourceFactory.java

PoolingJndiDataSourceFactory shouldn't check for DataSource to be XA or not XA. It shouldn't know anything about XA.
Perhaps not the best fix but it seems to work.

Fix broken XADataSource check in PoolingJndiDataSourceFactory

---

core/src/main/java/org/frankframework/util/flow/MermaidFlowGenerator.java
core/src/test/java/org/frankframework/configuration/digester/MapPropertyDescriptorsTest.java
core/src/test/java/org/frankframework/configuration/digester/TestAnnotationUtils.java
core/src/test/java/org/frankframework/util/flow/UnloadableClass.java

I might have a test for this too but it requires changing the scanner to also allow scanning classes on the test classpath and I need to verify that there are no negative side-effects on other tests.

Make MermaidFlowGenerator more resilient to class loading errors

---

pom.xml

* Version 5.10.2 is causing issues atm
Version 5.10.2 reverts some updates from 5.10.1 so it should not break it, but it does.
https://junit.org/junit5/docs/5.10.2/release-notes/

Version pin JUnit to 5.10.1

---

core/src/main/java/org/frankframework/senders/IsolatedServiceCaller.java
core/src/main/java/org/frankframework/senders/IsolatedServiceExecutor.java
core/src/main/java/org/frankframework/senders/ParallelSenders.java
core/src/main/java/org/frankframework/senders/ShadowSender.java
core/src/test/java/org/frankframework/senders/IbisLocalSenderTest.java
core/src/test/java/org/frankframework/senders/ParallelSendersTest.java
core/src/test/java/org/frankframework/senders/ShadowSenderTest.java
core/src/test/resources/Senders/ParallelSenders/test10SubSendersNonRepeatableMessage.txt

* Calling Async sub-adapter should pass copy of original message (#6178)
* Improve reliability of ParallelSender and ShadowSender (#6194)
(cherry picked from commit b83119f8c5749634dd5462a8f22bd9db374577a7)

Fix async processing senders

---

test/src/test/testtool/TransactionHandling/FailureInNonDbPipe/scenario01/md-select.xml
test/src/test/testtool/TransactionHandling/FailureInNonDbPipe/scenario02/md-select.xml

All Larva tests should now pass under JDK17 and also JDK21.

Fix order of select to make it driver / JDK version independent.

---

core/src/main/java/nl/nn/adapterframework/pipes/AbstractPipe.java
core/src/main/java/nl/nn/adapterframework/pipes/JwtPipe.java
core/src/main/java/nl/nn/adapterframework/util/CredentialFactory.java
core/src/test/java/nl/nn/adapterframework/pipes/JwtPipeTest.java
credentialProvider/pom.xml
credentialProvider/src/main/java/nl/nn/credentialprovider/Credentials.java
credentialProvider/src/main/java/nl/nn/credentialprovider/ICredentialFactory.java
credentialProvider/src/main/java/nl/nn/credentialprovider/ICredentials.java
credentialProvider/src/main/java/nl/nn/credentialprovider/MapCredentials.java

Pad authAlias and sharedSecret parameter when jwtAllowWeakSecrets is true

---

core/src/main/java/nl/nn/adapterframework/filesystem/FtpFileSystem.java
core/src/main/java/nl/nn/adapterframework/pipes/FilePipe.java
core/src/test/java/nl/nn/adapterframework/filesystem/FileSystemActorTest.java
core/src/test/java/nl/nn/adapterframework/filesystem/FtpFileSystemActorTest.java
core/src/test/java/nl/nn/adapterframework/filesystem/FtpFileSystemTest.java
core/src/test/java/nl/nn/adapterframework/filesystem/FtpFileSystemTestHelper.java
core/src/test/java/nl/nn/adapterframework/filesystem/LocalFileServer.java
core/src/test/java/nl/nn/adapterframework/util/FileHandlerTestBase.java

(cherry picked from commit 35b2ba9d8c590633568625ca05037a0e72721cec)

Add FtpFileSystemActorTest and improve FTP implementation (#6317)

---

core/src/main/java/org/frankframework/jdbc/datasource/JdbcPoolUtil.java
core/src/main/java/org/frankframework/jndi/PoolingJndiDataSourceFactory.java
core/src/main/java/org/frankframework/jta/btm/BtmDataSourceFactory.java
core/src/main/java/org/frankframework/jta/narayana/NarayanaDataSourceFactory.java
core/src/main/resources/AppConstants.properties
core/src/test/java/org/frankframework/jta/btm/BtmDataSourceFactoryTest.java
core/src/test/java/org/frankframework/jta/narayana/NarayanaDataSourceFactoryTest.java

* Make name of configuration property clearer and make it more clear that BTM specific options only apply to XA datasource connection pools.
* Revert old name `transactionmanager.narayana.jdbc.connection.minPoolSize` for `transactionmanager.narayana.jdbc.connection.minIdle`.

Rename jdbc minPoolSize to minIdle

---

core/src/main/java/org/frankframework/senders/ReconnectSenderWrapper.java
core/src/test/java/org/frankframework/senders/ReconnectSenderWrapperTest.java

(cherry picked from commit cafd86f236bdcd00b83b89d5861a0c80c2f7e26c)

Add ReconnectSenderWrapper (#6338)

---

core/src/main/java/org/frankframework/jms/MessagingSource.java
core/src/main/resources/AppConstants.properties

Don't report idle connections, but current amount of connections in the pool

Reduce number of connections to JMS

---

aspose/src/main/java/org/frankframework/extensions/aspose/pipe/AmountOfPagesPipe.java
core/src/main/resources/AppConstants.properties
nn-specials/src/main/java/org/frankframework/extensions/esb/EsbJmsListener.java
nn-specials/src/test/java/org/frankframework/extensions/esb/EsbJmsListenerTest.java

Also changed some Javadoc default to `@Default`, which is better.

Add default property for forceMessageIdAsCorrelationId on RR EsbJmsListeners

---

core/src/main/java/org/frankframework/core/Resource.java
core/src/main/java/org/frankframework/pipes/ForEachChildElementPipe.java
core/src/main/java/org/frankframework/pipes/IteratingPipe.java
core/src/main/java/org/frankframework/pipes/XmlIf.java
core/src/main/java/org/frankframework/pipes/XmlValidator.java
core/src/main/java/org/frankframework/soap/SoapWrapper.java
core/src/main/java/org/frankframework/util/ClassLoaderUtils.java
core/src/main/java/org/frankframework/util/TransformerPool.java
core/src/main/java/org/frankframework/util/XmlUtils.java
core/src/test/java/org/frankframework/align/TestAlignNamespacesXml.java
core/src/test/java/org/frankframework/util/FunctionalTransformerPoolTestBase.java
core/src/test/java/org/frankframework/util/TransformerPoolTest.java
core/src/test/java/org/frankframework/util/XmlUtilsTest.java
core/src/test/java/org/frankframework/util/XsltStreamingTest.java
nn-specials/src/main/java/org/frankframework/extensions/bis/BisJmsListener.java
nn-specials/src/main/java/org/frankframework/extensions/bis/BisJmsSender.java
nn-specials/src/main/java/org/frankframework/extensions/bis/BisUtils.java
nn-specials/src/main/java/org/frankframework/extensions/bis/BisWrapperPipe.java
nn-specials/src/main/java/org/frankframework/extensions/esb/EsbJmsListener.java
nn-specials/src/main/java/org/frankframework/extensions/esb/WsdlGeneratorPipe.java
nn-specials/src/main/java/org/frankframework/extensions/fxf/FxfWrapperPipe.java

There is one more change that I want to do which is to move all calls of `TransformerPool.getInstance(XmlUtils.createXPathEvaluatorSource(..........))` to new overloaded methods `TransformerPool.getXPathTransformerPool(.....)`.
Then the remaining method `TransformerPool.getInstance(xslt, version)` can be made private or be deleted.

Clean up TransformerPool.getInstance()

---

core/src/main/java/org/frankframework/stream/Message.java
core/src/test/java/org/frankframework/util/XmlUtilsTest.java
core/src/test/resources/Util/MessageUtils/iso-8859-1.xml
core/src/test/resources/Util/MessageUtils/iso-8859-1_without_xml_declaration.xml
core/src/test/resources/Util/MessageUtils/utf8-with-bom.xml
core/src/test/resources/Util/MessageUtils/utf8-without-bom.xml
core/src/test/resources/Util/MessageUtils/utf8.xml

Took #6357 as a base and expanded the tests a tiny bit.

Use provided charset when converting to InputSource

---

console/frontend/src/main/frontend/src/app/views/ibisstore-summary/ibisstore-summary.component.html
console/frontend/src/main/frontend/src/app/views/jdbc/jdbc.service.ts
core/src/main/java/org/frankframework/management/bus/endpoints/IbisstoreSummary.java

Improves ibisstore table columns logic & adds configuration to the api response so table can correctly link to the right store (was undefined in frontend before)

Ibisstore fix table columns & link to store

---

console/backend/src/main/java/org/frankframework/management/web/FileViewer.java
console/backend/src/test/java/org/frankframework/management/web/TestFileViewer.java
console/frontend/src/main/frontend/src/app/components/file-viewer/file-viewer.component.html
console/frontend/src/main/frontend/src/app/components/file-viewer/file-viewer.component.scss
console/frontend/src/main/frontend/src/app/views/logging/logging.component.html
console/frontend/src/main/frontend/src/app/views/logging/logging.component.ts

File Viewer now accepts `accept` url parameter which will overwrite `Accept` header to serve the right content-type
Also a fix for how files are displayed within the console (Fixes #6448)

Fix log download & plain view

---

core/src/main/java/org/frankframework/http/openapi/OpenApiGenerator.java
core/src/main/java/org/frankframework/http/rest/ApiListenerServlet.java
core/src/main/java/org/frankframework/http/rest/ApiServiceDispatcher.java
core/src/main/java/org/frankframework/management/bus/endpoints/WebServices.java
core/src/test/java/org/frankframework/http/openapi/OpenApiTest.java
core/src/test/java/org/frankframework/http/openapi/OpenApiTestBase.java

This is NOT a bug. Code is moved to new package and improved unit testing.
Explanation why it is not a bug:
**Situation 1**
http://localhost/iaf-test/api/openapi.json => still works fine in master (8.1-SNAPSHOT) and works in 7.8 & 7.9.
**Situation 2**
http://localhost/iaf-test/iaf/api/webservices/openapi.json?uri=/exception (or other `uri=` examples)
Needs the configured `loadBalancer.url` property, and otherwise it shows an empty array.
Does work as expected in: 7.9.1, 8.0.0, 8.1. 
Previously, in 7.9.0 and lower versions, it always uses the request and always shows a value for the server.

Improve OpenAPI spec code

---

aspose/pom.xml
ladybug/pom.xml
pom.xml

Without this change, it downloads Jackson libraries from our private repo 👎🏻 (in a specific module)
Defining a `<repositories>` entry overwrites the default Maven Central entry, so that one should be added first. It works in the defined order.

Always use Maven Central first to find dependencies, secondly a special one

---

core/src/main/resources/AppConstants.properties

[IBM uses a default of 100 sessions per connection](https://www.ibm.com/docs/en/datapower-gateway/10.0.1?topic=commands-sessions-per-connection).
I've read somewhere that by default Tibco supports up to 250 sessions, so in order to be safe we shouldn't cross this limit.
The article also says the following, but I've yet to decipher what it actually means.
You define 5 total connections and 20 sessions per connection. With three active connections, a new session request generates the establishment of a fourth connection.

Use different defaults for Narayana JMS connection and session pools

---

cmis/src/main/java/org/frankframework/extensions/cmis/CmisHttpSender.java
cmis/src/test/java/org/frankframework/extensions/cmis/CmisHttpInvokerTest.java
core/src/main/java/org/frankframework/processors/ExceptionHandlingPipeProcessor.java
core/src/main/resources/SpringApplicationContext.xml
core/src/test/java/org/frankframework/http/HttpResponseMock.java
test/src/test/testtool/ClobAndBlob/scenario07/out.xml
test/src/test/testtool/Senders/scenario01/out.xml
test/src/test/testtool/UnzipPipeExceptionForwardTest/scenario01/out1.txt

Removed managed sender exceptions in #[5959](https://github.com/frankframework/frankframework/commit/55ef29d986106d278ee35e9596daa1d657c0b7e2#diff-3a1194e08b691760634fad4bc813cda839916b259d49eed0b58bebe3eec1cc26L497) but I have seem to have broken 2 individual problems.
- ErrorMessageFormatters where formatting the exception twice, see [UnzipPipeExceptionForwardTest/scenario01/out1.txt](https://github.com/frankframework/frankframework/pull/6497/files#diff-a7a022f73e74616e49a0109452fe06f5cd28da20fe60aaa8c0b2324ac2921847)
- InputOutputProcessor was no longer working when handling an exception.
This PR fixes the problems, though there are only integration-tests to prove this.
See the tests added in #5959 which remain been unmodified.
Also fixes CMIS exceptions accidently caught by …

Fix duplicated messages in exception forwards

---

console/frontend/src/main/frontend/src/app/app.component.ts
console/frontend/src/main/frontend/src/app/services/poller.service.ts
console/frontend/src/main/frontend/src/app/views/status/status.component.html
console/frontend/src/main/frontend/src/app/views/status/status.component.ts

Shows a toast when the `upSince` of one or multiple adapters have changed
Also a fix for manual config reload where poller in `startPollingForConfigurationStateChanges` didn't stop

Show toast on adapter reload

---

commons/pom.xml
console/war/pom.xml
console/war/src/main/java/org/frankframework/runner/ConsoleStandaloneInitializer.java
console/war/src/main/java/org/frankframework/runner/ConsoleWarInitializer.java
core/src/main/java/org/frankframework/lifecycle/ApplicationServerConfigurer.java
core/src/main/java/org/frankframework/lifecycle/FrankApplicationInitializer.java
core/src/main/java/org/frankframework/lifecycle/FrankEnvironmentInitializer.java
core/src/main/java/org/frankframework/lifecycle/ServletManager.java
core/src/main/java/org/frankframework/lifecycle/servlets/ApplicationServerConfigurer.java
core/src/main/java/org/frankframework/lifecycle/servlets/HttpSecurityConfigurer.java
core/src/main/java/org/frankframework/lifecycle/servlets/SecurityFilterChainConfigurer.java
core/src/main/java/org/frankframework/util/AppConstants.java
core/src/main/java/org/frankframework/util/Misc.java
core/src/test/java/org/frankframework/http/rest/ApiListenerTest.java
core/src/test/java/org/frankframework/lifecycle/ServletManagerTest.java
core/src/test/java/org/frankframework/testutil/mock/ServletManagerMock.java
ladybug/pom.xml
ladybug/src/main/java/org/frankframework/ibistesttool/Debugger.java
ladybug/src/main/java/org/frankframework/ibistesttool/runner/LadybugWarInitializer.java
ladybug/src/main/java/org/frankframework/ibistesttool/runner/TestToolWarInitializer.java
ladybug/src/main/resources/application.properties
larva/src/main/java/org/frankframework/extensions/test/IbisTester.java
security/src/main/java/org/frankframework/lifecycle/servlets/JeeAuthenticator.java
test/pom.xml
test/src/main/java/org/frankframework/runner/IafTestInitializer.java
test/src/main/resources/StageSpecifics_LOC.properties
test/src/main/resources/TestFrankContext.xml
test/src/main/resources/application.properties

I move a lot around to clean up the code as well as use it independently.
Spring automatically finds the `WebApplicationInitializer`s when running in a traditional WAR environment.
When using Spring Boot these implementations are ignored (!).
They will need to be either manually added as `PrimarySource` on the `SpringApplication` or defined in a bean config somewhere. Spring Boot listens to the `ServletContextInitializer` interface instead, which a traditional WAR environment does not find. At some point we need to make our 'runnables' a bit more generic so they can implement both interfaces, for now I've opted to not do that due to them being in the spring-boot-starter dependency, which is not part of our default classpath.

Make iaf-test (Spring) bootable

---

aws/pom.xml
pom.xml

Somehow the AWS libraries where not bumped by Dependabot, even though it is possible (S3 lib & SDK version).

Manage AWS dependencies through BOM import in parent pom. Upgrade AWS deps

---

console/frontend/src/main/frontend/src/app/views/security-items/security-items.component.html
console/frontend/src/main/frontend/src/app/views/security-items/security-items.component.scss
console/frontend/src/main/frontend/src/app/views/security-items/security-items.component.ts
console/frontend/src/main/frontend/src/app/views/security-items/security-items.service.ts

Added a table containing API actions and which role is able to do it.
I'm wondering if the name and placement of the table is correct, and if actions without description should be shown or not. If not, should the action name be kept or is the description enough?
I did not implement a way to highlight the current role.
Preview:

Add a role overview table

---

console/frontend/src/main/frontend/src/app/app-routing.module.ts
console/frontend/src/main/frontend/src/app/components/pages/pages-topinfobar/pages-topinfobar.component.ts
console/frontend/src/main/frontend/src/app/views/logging/logging.component.ts

It is still backwards compatible with the old URL's

Fix browser not going back with back action on logging page

---

core/pom.xml
filesystem/pom.xml
filesystem/src/main/java/org/frankframework/http/WebServiceNtlmSender.java
filesystem/src/test/java/org/frankframework/xml/StaxParserTest.java

Moved the (now deprecated) WebServiceNtlmSender as well.

Move FileSystem dependencies from core to their own module

---

pom.xml

I updated the Log4j2 implementation in #6544 but forgot about the 'version lock' in our parent pom.
I've grouped the log dependencies and updated it to the latest version.
Supersedes #6616 which I could not check out due to branch name problems...

Update SLF4J to API version 2.x

---

core/src/main/java/org/frankframework/jta/SpringTxManagerProxy.java

No longer do a silent rollback from commit, but instead let commit throw error as it should.

No longer swallow exception from commit if TX status is rollback-only

---

core/src/main/java/org/frankframework/core/Adapter.java
core/src/main/java/org/frankframework/core/PipeLineSession.java
core/src/main/java/org/frankframework/jdbc/MessageStoreSender.java
core/src/main/java/org/frankframework/jms/JMSFacade.java
core/src/main/java/org/frankframework/pipes/MessageSendingPipe.java
core/src/main/java/org/frankframework/pipes/RemoveFromSession.java
core/src/test/java/org/frankframework/http/cxf/SoapProviderStub.java
core/src/test/java/org/frankframework/monitoring/MessageCapturingEchoSender.java
core/src/test/java/org/frankframework/receivers/ReceiverTest.java
core/src/test/java/org/frankframework/testutil/TestFileUtils.java
filesystem/src/main/java/org/frankframework/filesystem/FileSystemListener.java
ladybug/src/main/java/org/frankframework/ibistesttool/MessageEncoder.java

Make all `@SneakyThrows` annotations explicit about the exceptions that could be thrown from the annotated methods to make it easier to trace what could be thrown.

Clean up SneakyThrows annotations

---

docker/.env

I've accidentally committed a wrong version while testing.

Revert FF!Test docker version in .env to 8.2.0-SNAPSHOT

---

RELEASES.md
pom.xml

It was broken since `d156a3eb` 07/11/2023 at 16:58h, since we've upgraded the mariadb driver, for the combination: MariaDB, Tomcat-BTM, ActiveMQ/ArtemisMQ

Revert mariadb.driver.version to 2.7.10 because it fails with BTM

---

RELEASES.md
core/src/main/java/org/frankframework/pipes/FixedResultPipe.java
core/src/test/java/org/frankframework/pipes/FixedResultTest.java
core/src/test/resources/FixedResult/fixedResultPipeInput.txt
test/src/main/configurations/MainConfig/ConfigurationParameters.xml
test/src/main/configurations/MainConfig/cache/resultTemplate.xml
test/src/test/testtool/Parameters/scenario06.properties
test/src/test/testtool/Parameters/scenario06/in.xml
test/src/test/testtool/Parameters/scenario06/out.txt
test/src/test/testtool/Parameters/scenario07.properties
test/src/test/testtool/Parameters/scenario07/in.xml
test/src/test/testtool/Parameters/scenario07/out.txt

By default the PipelineSession substitution delimiter has been changed from `${` to `?{` so it's consistent with the `FixedQuerySender`. Backwards compatibility key `useOldSubstitutionStartDelimiter` has been added so minimal change is required during upgrades. Note that when using caches in combination with `diskPersistent="true"` you may need to purge your cache!

Backport param substitution

---

RELEASES.md
core/src/main/java/org/frankframework/pipes/CompressPipe.java
core/src/test/java/org/frankframework/pipes/CompressPipeTest.java

The same result can be achieved by using parameters with the pattern attribute, which also gives the user more controll over the pattern substitutions.

Deprecate the CompressPipe filepatterns

---

checkstyle.xml
core/src/main/java/org/frankframework/configuration/AdapterManager.java
core/src/main/java/org/frankframework/jdbc/datasource/DataSourceFactory.java
core/src/main/java/org/frankframework/jdbc/datasource/FrankResources.java
core/src/main/java/org/frankframework/jdbc/datasource/TransactionalDbmsSupportAwareDataSourceProxy.java
nn-specials/src/main/java/org/frankframework/extensions/esb/WsdlGeneratorPipe.java

Fix some methods that still used imports from javax.annotation. Ban these imports in Checkstyle, along with some other imports from former javax packages.

Remove leftover javax.annotation imports

---

RELEASES.md
core/src/main/java/org/frankframework/pipes/FixedResultPipe.java
core/src/test/java/org/frankframework/pipes/FixedResultTest.java
core/src/test/resources/FixedResult/fixedResultPipeInput.txt
test/src/main/configurations/MainConfig/ConfigurationParameters.xml
test/src/main/configurations/MainConfig/cache/resultTemplate.xml
test/src/test/testtool/Parameters/scenario06.properties
test/src/test/testtool/Parameters/scenario06/in.xml
test/src/test/testtool/Parameters/scenario06/out.txt
test/src/test/testtool/Parameters/scenario07.properties
test/src/test/testtool/Parameters/scenario07/in.xml
test/src/test/testtool/Parameters/scenario07/out.txt

* Replaced the dollar sign with a question mark to avoid conflicting parameter substitution.
* Updated comments to reflect the new syntax.
Fixes #6787

Update FixedResultPipe parameter syntax to avoid conflicting substitution

---

core/src/main/java/org/frankframework/jdbc/JdbcFacade.java
core/src/test/java/org/frankframework/parameters/ParameterTest.java
core/src/test/java/org/frankframework/receivers/ReceiverTest.java
core/src/test/java/org/frankframework/testutil/mock/DataSourceFactoryMock.java

```
Error:  org.frankframework.receivers.ReceiverTest.testPollGuardStartTimeout -- Time elapsed: 4.363 s <<< ERROR! java.util.ConcurrentModificationException
at java.base/java.util.Vector$VectorSpliterator.forEachRemaining(Vector.java:1466)
at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509)
at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499)
at java.base/java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:921)
at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
at java.base/java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:682)
at org.frankframework.receivers.ReceiverTest.testPollGuardStartTimeout(ReceiverTest.java:962)
at …
```

Attempt to fix ConcurrentModificationException

---

filesystem/src/main/java/org/frankframework/filesystem/FileSystemActor.java
filesystem/src/main/java/org/frankframework/filesystem/LocalFileSystem.java
filesystem/src/test/java/org/frankframework/filesystem/FileSystemActorTest.java
filesystem/src/test/java/org/frankframework/filesystem/LocalFileSystemActorTest.java
filesystem/src/test/java/org/frankframework/filesystem/LocalFileSystemTestHelper.java

This extra test breaks the build after #6792 has been merged: the fix for that issue breaks on 2 filesystems, under conditions similar to the original problem but other filesystems than LocalFileSystem.

This extra test breaks the build after #6792 has been merged

---

commons/src/main/java/org/frankframework/util/DateFormatUtils.java
commons/src/test/java/org/frankframework/util/DateFormatUtilsTest.java

This is fix for date-parsing issue for 8.0.
It should be straightforward forward-port the change to 8.1 and master.
7.9 is not affected.

Fix for date parser

---

cmis/src/main/java/org/frankframework/extensions/cmis/servlets/WebServicesServletBase.java
core/src/main/java/org/frankframework/http/cxf/FrankCXFServlet.java
core/src/main/java/org/frankframework/http/cxf/SoapProviderServlet.java

Since Spring Boot 3.x all filter beans are picked up and loaded first, and for some reason the magnificent CXF people decided that their 'CXFServlet' class can sercretly behave as a filter as well. This breaks the load order as well the way initParameters are loaded, so for us this is a big no-go. Wrapping it in a class that only implements servlet (and not filter) ensures correct loading behavior.
This does not fix the `ServletDispatcher` issue, as that Servlet is being migrated away in #6755

Ensure all CXF endpoints are loaded as Servlet instead of a Filter

---

core/src/test/java/org/frankframework/jdbc/dbms/DbmsSupportTest.java

Fix the "queueing test". It needed an extra connection. Also, skip the test when the database does not support "skip locked" query functionality.
PS: the test is now properly skipped for H2 so it doesn't run in the CI environment. To properly execute the test, have at least 1 database running in Docker when running the tests. (Not MariaDB, other PR coming to fix that).

Fix DbmsSupportTest.testQueueHandling

---

core/src/main/resources/xml/xsl/adapter2mermaid.xsl

there was a bug in the xsl where exits were deleted if they weren't explicitly forwarded to. I removed the bit of code that removes such exits

Fix exit-forward when exit was never explicitly defined

---

core/src/test/java/org/frankframework/jdbc/datasource/TestBlobs.java
core/src/test/java/org/frankframework/scheduler/CheckReloadJobTest.java

These tests originally ran only for DatasourceTransactionManager, now again run only for DatasourceTransactionManager. They don't need to run for JTA transaction managers as well.

Use DatabaseTest instead of TxManagerTest for 2 tests

---

core/src/test/java/org/frankframework/jta/StatusRecordingTransactionManagerImplementationTest.java
core/src/test/java/org/frankframework/jta/TransactionConnectorTest.java
core/src/test/resources/AppConstants.properties

After merging this PR, it should be possible to to run tests with Maven with one of supported databases enabled, except MariaDB (which still fails, see issues #6910, #6911) and DB2 (not currently tested by me, DB2 JDBC driver seems to be missing some native-code dependencies).

Fix some JTA tests, disable some other broken JTA tests

---

core/src/test/java/org/frankframework/jdbc/dbms/DbmsSupportTest.java
dbms/src/main/java/org/frankframework/dbms/Dbms.java
dbms/src/main/java/org/frankframework/dbms/MariaDbDbmsSupport.java
dbms/src/test/java/org/frankframework/dbms/MariaDbDbmsSupportTest.java

Fix for the "Skip Locked Rows" support in MariaDB queries (#6897)
(cherry picked from commit 30124e234288173af468d2a40f81971ccf58c0fd)

Fix detection of "Skip locked row" support for MariaDB

---

core/src/main/java/org/frankframework/core/PipeLineSession.java
core/src/main/java/org/frankframework/parameters/ParameterList.java
core/src/main/java/org/frankframework/processors/CorePipeProcessor.java
core/src/main/java/org/frankframework/stream/Message.java
core/src/test/java/org/frankframework/monitoring/MonitorTest.java

1. A de-serialized messaged should also be scheduled to close
2. Add `message.isClosed()` to verify if a message was already closed
3. Add `message.assertNotClosed()` to verify if a message was *not* already closed
4. Add several key locations to assert the used message was not closed before. This prevents failures at odd locations, which are hard to find and fix.

Improve Message closing and fail when using a closed message

---

console/backend/src/main/java/org/frankframework/management/web/Configuration.java
console/backend/src/main/java/org/frankframework/management/web/FrankApiBase.java
console/frontend/src/main/frontend/src/app/components/th-sortable.directive.ts
console/frontend/src/main/frontend/src/app/utils.ts
console/frontend/src/main/frontend/src/app/views/configurations/configurations-manage/configurations-manage-details/configurations-manage-details.component.html
console/frontend/src/main/frontend/src/app/views/configurations/configurations-manage/configurations-manage-details/configurations-manage-details.component.ts

Also fixes the configuration upload endpoint, using an old function I didnt think was needed anymore so I had deleted it when moving over to Spring
Yes I know making an `anyCompare` that doesnt properly compare any `keyof T` type where T is the array of table items is kind of bad but I rewrote it like 3 times already, each time overengineering it too much for what is currently needed.
This is now a nice basis that can later be expanded if its _really_ needed.

Add search & sort to uploaded configurations table

---

console/backend/src/main/java/org/frankframework/management/web/configuration/WebConfiguration.java
console/war/src/main/resources/FrankConsoleContext.xml
core/src/main/resources/AppConstants.properties
core/src/main/resources/SpringEnvironmentContext.xml
management-gateway/src/main/java/org/frankframework/management/bus/InboundGatewayFactory.java
management-gateway/src/main/java/org/frankframework/management/bus/OutboundGateway.java
management-gateway/src/main/java/org/frankframework/management/gateway/HazelcastConfig.java
management-gateway/src/main/java/org/frankframework/management/gateway/HazelcastInboundGateway.java
management-gateway/src/main/java/org/frankframework/management/gateway/HazelcastOutboundGateway.java
management-gateway/src/main/java/org/frankframework/management/gateway/events/AbstractGatewayEvent.java
management-gateway/src/main/java/org/frankframework/management/gateway/events/ClusterMemberEvent.java

Can be used in combination with `implements ApplicationListener<AbstractGatewayEvent> {` and
```
@Override
public void onApplicationEvent(AbstractGatewayEvent event) {
System.err.println(event);
}
```
To retrieve a `ClusterMemberEvent` when a new member joins or leaves the cluster.

Add getMembers endpoint and add ApplicationEvents

---

core/src/main/java/org/frankframework/http/rest/MediaTypes.java

Het is niet volledig maar ik ben door [Common_types](https://developer.mozilla.org/en-US/docs/Web/HTTP/Basics_of_HTTP/MIME_types/Common_types) heen gegaan en heb daar alles uitgehaald.

Add more MediaTypes to ApiListeners

---

core/src/main/java/org/frankframework/stream/Message.java
core/src/main/java/org/frankframework/util/JdbcUtil.java
core/src/test/java/org/frankframework/core/PipeLineSessionTest.java
core/src/test/java/org/frankframework/stream/MessageTest.java
core/src/test/java/org/frankframework/util/JdbcUtilTest.java

As discussed with Tim, I try to split this up in different pull requests, to make it managable. This removes the static Message.asByteArray.

Remove Message.asByteArray

---

console/backend/src/main/java/org/frankframework/management/web/ConfigurationStatus.java
core/src/main/java/org/frankframework/management/bus/endpoints/AdapterStatus.java

Problems occured when two or more configurations contain an adapter with the same name.

Ensure adapter list returns all adapters

---

aws/src/main/java/org/frankframework/filesystem/AmazonS3FileSystem.java
aws/src/main/java/org/frankframework/filesystem/S3FileRef.java
aws/src/main/java/org/frankframework/senders/AmazonS3Sender.java
aws/src/test/java/org/frankframework/filesystem/AmazonS3FileSystemActorTest.java
aws/src/test/java/org/frankframework/filesystem/AmazonS3FileSystemTest.java
aws/src/test/java/org/frankframework/senders/AmazonS3SenderTest.java
filesystem/src/main/java/org/frankframework/filesystem/ftp/FtpFileSystem.java
filesystem/src/main/java/org/frankframework/filesystem/sftp/SftpFileSystem.java
filesystem/src/main/java/org/frankframework/filesystem/smb/Samba1FileSystem.java
filesystem/src/main/java/org/frankframework/filesystem/smb/Samba2FileSystem.java
filesystem/src/test/java/org/frankframework/filesystem/BasicFileSystemTest.java
filesystem/src/test/java/org/frankframework/filesystem/FileSystemActorCustomFileAttributesTest.java
filesystem/src/test/java/org/frankframework/filesystem/LocalFileSystemTestHelper.java
filesystem/src/test/java/org/frankframework/filesystem/mock/MockFileSystemWithAttachmentsTest.java

The goal here is purely to fix the folder (name) issues and allow file properties to be set/shared between methods.

Use an AWS S3 file reference instead of misusing the S3Object

---

ladybug/src/main/resources/springIbisTestToolTestLadybugReportTableDifferentViewsDifferentColumns.xml

This PR will help the Ladybug team to test Ladybug. The columns in the report table can be different for different views. We would like to test that the shown columns do change when you change views. And a bug was found when changing views is combined with filtering.
Without this PR, we have to manually add a springIbisTestToolCustom.xml in frankframework/ladybug/src/main/resources before letting the Frank!Runner compile the FF!. With this PR, we will be able to do:
```
...\frank-runner\specials\ladybug$ .\restart.bat -Dcustom=TestLadybugReportTableDifferentViewsDifferentColumns
```
provided we have the right `build.properties` files in place.

Have extra springIbisTestTool variant to support testing Ladybug

---

commons/src/main/java/org/frankframework/util/PropertyLoader.java
tibco/src/main/java/org/frankframework/extensions/tibco/GetTibcoQueues.java
tibco/src/main/java/org/frankframework/extensions/tibco/SendTibcoMessage.java
tibco/src/main/java/org/frankframework/extensions/tibco/TibcoEmsProperties.java
tibco/src/main/java/org/frankframework/extensions/tibco/TibcoUtils.java
tibco/src/test/java/nl/nn/adapterframework/extensions/tibco/TibcoJndiPropertiesTest.java
tibco/src/test/java/org/frankframework/extensions/tibco/TibcoJndiPropertiesTest.java
tibco/src/test/resources/jndi.properties
tibco/src/test/resources/log4j4ibis.xml

Backport of #7137
(cherry picked from commit 2ead7a9a4d462b5f1d0b6ce0e34684ee5a8bb56f)

Implement custom properties for Tibco classes

---

core/src/main/java/org/frankframework/management/bus/endpoints/HealthCheck.java
core/src/test/java/org/frankframework/management/bus/endpoints/TestHealth.java

server/health --> verifies all configuraties are started
configuration/name/health --> verifies all adapters are started
configuration/name/adapters/name/health --> detailed health info per adapter

Split health checks so each endpoint only target it's own scope

---

console/frontend/pom.xml

Reverts frankframework/frankframework#7270 becouse of this issue: https://github.com/mojohaus/exec-maven-plugin/issues/438

Revert "Bump org.codehaus.mojo:exec-maven-plugin from 3.3.0 to 3.4.0"

---

cmis/src/main/java/org/frankframework/extensions/cmis/CmisSender.java
commons/src/main/java/org/frankframework/doc/Unsafe.java
core/src/main/java/org/frankframework/configuration/SuppressKeys.java
core/src/main/java/org/frankframework/configuration/digester/ValidateAttributeRule.java
core/src/main/java/org/frankframework/encryption/HasTruststore.java
core/src/main/java/org/frankframework/http/HttpSessionBase.java
filesystem/src/main/java/org/frankframework/filesystem/ftp/FtpSession.java

Closes #2727 
Will be used for the following:
- A warning in the console when an unsafe attribute is used.
- A warning in the frankdoc to alert them that the use of this attribute might be unsafe.
The annotation sadly isn't as sophisticated as I would like it to be. A lambda in the annotation which returns true when the value is actually unsafe would be my prefered solution, but that is not possible because members of the annotation must be primatives. This means that this annotation is only really useful for boolean values with a safe default. Checking the length of a password is currently not possible for example, because it would mark the usage of the attribute as unsafe while that may not be the case.
The current non exhaustive list of unsafe attributes are the following:
- …

Add an unsafe annotation for unsafe attributes.

---

core/src/main/java/org/frankframework/pipes/XmlValidator.java
core/src/test/java/org/frankframework/pipes/XmlValidatorPipelineTest.java

Closes #6800 
Shows a configuration warning when the XmlValidator is in an incorrect state (failure forward and `throwException=true`).
The setup of the tests adds both forwards and set `throwException=true`, so some asserts had to be modified.

Show a console warning when the XmlValidator pipe is in an incorrect state.

---

core/src/main/java/org/frankframework/pipes/ReplacingInputStream.java
core/src/main/java/org/frankframework/pipes/ReplacingVariablesInputStream.java

Since the inputStreams didn't extend `FilterInputStream` anymore, `close()` wasn't implemented and the streams would not be closed correctly
Niels: we didn't see this working due to some IntelliJ issues. After a restart and fresh run after clean/install it did what we expected.

Fix inputstreams that weren't closed

---

larva/src/main/java/org/frankframework/larva/LarvaTool.java

`StringEscapeUtils.escapeJava` prefixed every backslash with another backslash, introducing issues when using windows paths. Reverted that change in LarvaTool.java. In other places, this shouldn't be a problem since the returned value is only used in logging.

Fix larva directory issues

---

core/src/main/java/org/frankframework/pipes/ReplacingInputStream.java
core/src/main/java/org/frankframework/pipes/ReplacingVariablesInputStream.java

Since the inputStreams didn't extend FilterInputStream anymore, 'close)' wasn't implemented and the streams would not be closed correctly

Fix ReplacerPipe

---

console/backend/src/main/java/org/frankframework/management/web/ConfigurationsEndpoint.java
console/backend/src/main/java/org/frankframework/management/web/ServerStatistics.java
console/frontend/src/main/frontend/src/app/views/configurations/configurations-manage/configurations-manage.component.html
console/frontend/src/main/frontend/src/app/views/configurations/configurations-manage/configurations-manage.component.ts
core/src/main/java/org/frankframework/configuration/ConfigurationUtils.java
core/src/main/java/org/frankframework/configuration/IbisContext.java
core/src/main/java/org/frankframework/configuration/IbisManager.java
core/src/main/java/org/frankframework/lifecycle/MessageEventListener.java
core/src/main/java/org/frankframework/management/bus/endpoints/AdapterStatistics.java
core/src/main/java/org/frankframework/management/bus/endpoints/BrowseMessageBrowsers.java
core/src/main/java/org/frankframework/management/bus/endpoints/BusEndpointBase.java
core/src/main/java/org/frankframework/management/bus/endpoints/ConfigManagement.java
core/src/main/java/org/frankframework/management/bus/endpoints/DatabaseMigrator.java
core/src/main/java/org/frankframework/management/bus/endpoints/HandleIbisManagerAction.java
core/src/main/java/org/frankframework/unmanaged/DefaultIbisManager.java
core/src/test/java/org/frankframework/management/bus/endpoints/TestDatabaseMigrator.java
management-gateway/src/main/java/org/frankframework/management/bus/BusMessageUtils.java

Retrieves all active configurations from the database & zips it into a file, downloadable through the new button in 'Configurations > Manage'

Download all active configurations

---

commons/src/main/java/org/frankframework/util/HttpUtils.java
core/src/main/java/org/frankframework/pipes/CsvParserPipe.java
core/src/main/java/org/frankframework/util/XmlBuilder.java
core/src/main/java/org/frankframework/xml/SaxElementBuilder.java
core/src/test/java/org/frankframework/pipes/CsvParserPipeTest.java

The SaxElementBuilder didn't check element names for invalid values. Fixed the last Sonar security issue from #7277  as well

Fix invalid element name in SaxElementBuilder

---

ladybug/src/main/resources/springIbisDebuggerAdvice.xml

fixes
```
2024-08-23 13:15:36,577 DEBUG [main] {} aspectj.AspectJExpressionPointcut - Pointcut parser rejected expression [      execution(       *       org.frankframework.processors.CorePipeLineProcessor.processPipeLine(        ..       )      )      and      args(pipeLine, messageId, message, pipeLineSession, ..)      ]: java.lang.IllegalArgumentException: warning no match for this type name: messageId [Xlint:invalidAbsoluteTypeName]
```
introduced in #7352

Fix copy paste error in AOP config

---

console/frontend/src/main/java/org/frankframework/console/ConsoleFrontend.java
core/src/main/java/org/frankframework/pipes/Base64Pipe.java

Due to the component-scan picking up the annotations twice the console frontend was loaded in without a servlet-path, causing it to listen to all endpoints.

Remove component annotation from console frontend servlet

---

batch/src/main/java/org/frankframework/batch/AbstractRecordHandler.java
batch/src/main/java/org/frankframework/batch/BatchFileTransformerPipe.java
batch/src/main/java/org/frankframework/batch/FieldPositionRecordHandlerManager.java
batch/src/main/java/org/frankframework/batch/FixedPositionRecordHandlerManager.java
batch/src/main/java/org/frankframework/batch/RecordHandlerManager.java
batch/src/main/java/org/frankframework/batch/RecordHandlingFlow.java
batch/src/main/java/org/frankframework/batch/RecordTransformer.java
batch/src/main/java/org/frankframework/batch/RecordXml2Sender.java
batch/src/main/java/org/frankframework/batch/RecordXmlTransformer.java
batch/src/main/java/org/frankframework/batch/Result2Filewriter.java
batch/src/main/java/org/frankframework/batch/Result2StringWriter.java
batch/src/main/java/org/frankframework/batch/ResultBlock2Sender.java
batch/src/main/java/org/frankframework/batch/StreamTransformerPipe.java
core/src/test/java/org/frankframework/compression/TestZipWriterPipe.java
core/src/test/java/org/frankframework/core/PipeLineTest.java
core/src/test/java/org/frankframework/http/HttpSenderTest.java
core/src/test/java/org/frankframework/http/WebServiceSenderTest.java
core/src/test/java/org/frankframework/parameters/ParameterTest.java
core/src/test/java/org/frankframework/pipes/ChecksumPipeTest.java
core/src/test/java/org/frankframework/soap/WsdlGeneratorTest.java
nn-specials/src/main/java/org/frankframework/errormessageformatters/Y01ErrorMessageFormatter.java
nn-specials/src/test/java/org/frankframework/core/TestDirectWrapperPipePipeLine.java

Fix a number of (easily fixable) maven build warnings. 
* Added `@Deprecated` annotation on classes already using '@deprecated' in the javadoc.
* Changed method calls to use the non-deprecated variant.

Fix maven build warnings (mostly usage of deprecated methods)

---

core/src/main/java/org/frankframework/jdbc/DirectQuerySender.java
core/src/main/java/org/frankframework/jdbc/FixedQuerySender.java
core/src/main/java/org/frankframework/jdbc/ResultSet2FileSender.java
core/src/main/java/org/frankframework/jdbc/StoredProcedureQuerySender.java
core/src/main/java/org/frankframework/jdbc/XmlQuerySender.java
core/src/test/java/org/frankframework/testutil/mock/FixedQuerySenderMock.java

Ik heb alvast de nieuwe notatie gehanteerd zoals gespecificeerd in https://github.com/frankframework/frank-doc/issues/210 - of is dat te vroeg?

Add ff-info tags to point out the default value of trimSpaces

---

larva/src/main/java/org/frankframework/larva/LarvaTool.java

I made a typo in one of my Larva scenarios and got an unhelpful NPE.
This changes helps users figure out what they did wrong in their Larva scenarios when they make a typo for what should be matching keypairs.

Better error messages for some errors in Larva scenarios

---

console/frontend/pom.xml

Allows you to omit copyright checking for the frontend of the console. Use command `mvn -DskipTests -Plicense.skip install` to also skip running the unit tests.

Improve build speed

---

console/frontend/src/main/frontend/src/app/views/jms/jms-browse-queue/jms-browse-queue.component.ts
console/frontend/src/main/frontend/src/app/views/jms/jms-send-message/jms-send-message.component.ts

JMS forms in the front-end were not sending boolean properties while the backend model expected this causing a failure to convert null to a boolean.
This PR improves error handling to show the error descriptions and always sends the required properties on a JMS form request

Fix JMS form issues

---

Docker.md

Removed the mention of previous context.xml file and updated descriptions for
current default files and directories in the Docker image. Also added a note
about logging appenders and updated references to environment variables in the
documentation.

docs: Update Docker.md to specify new default files and directories

---

core/src/main/java/org/frankframework/receivers/Receiver.java
core/src/main/java/org/frankframework/scheduler/job/ExecuteQueryJob.java
core/src/main/java/org/frankframework/scheduler/job/SendMessageJob.java
core/src/main/java/org/frankframework/stream/Message.java
core/src/test/java/org/frankframework/mongodb/MongoDbSenderTest.java
ladybug/debugger/src/main/java/org/frankframework/ladybug/Debugger.java
ladybug/debugger/src/main/java/org/frankframework/ladybug/MessageEncoder.java
larva/src/main/java/org/frankframework/larva/LarvaTool.java

`Message.close()` is not throwing for a while, but its throws-clause never got removed. Touches a surprising number of files.

Message.close() doesn't actually throw

---

core/src/main/java/org/frankframework/configuration/Configuration.java
core/src/main/java/org/frankframework/lifecycle/IbisApplicationContext.java
ladybug/debugger/src/main/java/org/frankframework/ladybug/IbisDebuggerAdvice.java
ladybug/debugger/src/main/java/org/frankframework/ladybug/LadybugDebugger.java
ladybug/debugger/src/main/resources/springIbisDebuggerAdvice.xml
ladybug/debugger/src/main/resources/springIbisTestTool.xml

Fixes both a typo (testTool) for autowiring byName, and module name to activate the AOP config.

Fix AOP config in configuration

---

filesystem/src/main/java/org/frankframework/filesystem/FileSystemActor.java

Clarified when the output type parameter is used

FileSystemActor - update javadoc for outputtype

---

copyrightExcludeFile.txt

Two file types that don't need a copyright but when I create them locally for tests, maven breaks on them.

Two more copyright-excludes

---

core/src/test/java/org/frankframework/management/bus/BusExceptionTest.java

Log4J2 2.25 will add some formatting changes that may add newlines before and/or after Exception messages.
By trimming the strings we do not depend on the presence or absence of such newlines.

Improve test for changes that may come in Log4J 2.25

---

larva/src/main/java/org/frankframework/larva/ScenarioRunner.java

I was able to test this with the following settings:
```
larva.adapter.active=true
larva.adapter.execute=Checksum
```
The first setting enables the Larva adapter config, the second tells the pipe where to look for scenario's. Calling this Pipe via 'test a pipeline' made me hit my breakpoint.

Use the correct writer based on silent setting

---

console/war/src/main/java/org/frankframework/console/runner/ConsoleStandaloneInitializer.java
console/war/src/main/resources/application.properties
ladybug/debugger/src/main/java/org/frankframework/ladybug/LadybugDebugger.java
ladybug/debugger/src/main/java/org/frankframework/ladybug/runner/LadybugWarInitializer.java
ladybug/debugger/src/main/resources/springIbisTestTool.xml
ladybug/rerunner/src/main/java/org/frankframework/ladybug/SpringBusRerunner.java
ladybug/rerunner/src/main/resources/testtool.properties

- Fix NPE when Ladybug rerun cannot find config
- Stop application when an error occurs during startup
- Change default property locations
- Allow XML storage to be stored on disk even when using DatabaseStorage
- Change exception messages when adapter or config cannot be find while in rerun
- Change whitespace in comment and solve Sonar issue

Fix NPE when Ladybug rerun cannot find config

---

core/src/main/java/org/frankframework/validation/IXSD.java
core/src/main/java/org/frankframework/validation/XSD.java
core/src/main/java/org/frankframework/validation/xsd/ResourceXsd.java
core/src/main/java/org/frankframework/validation/xsd/StringXsd.java
core/src/main/java/org/frankframework/validation/xsd/WsdlXsd.java

Comparing XSD by content is expensive. Do it less often.
The benefit is not huge so feel free to close without applying if you prefer.

Minor startup performance improvement by caching results of XSD compare

---

larva/src/main/java/org/frankframework/extensions/test/IbisTester.java
larva/src/main/java/org/frankframework/larva/LarvaServlet.java
larva/src/main/java/org/frankframework/larva/LarvaTool.java
larva/src/main/java/org/frankframework/pipes/LarvaPipe.java

Determine realPath in LarvaTool based on getResource, instead of outside it based on the servlet context.
@nielsm5 , ik denk dat dit de juiste plek is. Voor nu even als draft, ik kan iets vergelijkbaars natuurlijk ook aanpassen _buiten_ `LarvaTool`

Determine realPath in LarvaTool 

---

core/src/main/java/org/frankframework/pipes/ExceptionPipe.java
core/src/test/java/org/frankframework/pipes/ExceptionPipeTest.java

Closes #7706 
I think it's best to deprecate the `throwException` attribute and the `success` forward. A ConfigurationException is thrown when an invalid forward is used, so we must be careful when changing or removing forwards. A way to deprecate forwards might be a nice to have aswell?

Deprecate throwException and success forward for ExceptionPipe

---

core/src/test/java/org/frankframework/pipes/ExceptionPipeTest.java

Method does not exist.
Rename was forgotten in https://github.com/frankframework/frankframework/commit/4b1dcc7d1f90863157fab322ec0df7e48179fb8a

Fix compilation error for ExceptionPipeTest

---

core/src/main/java/org/frankframework/errormessageformatters/XslErrorMessageFormatter.java

Closes https://github.com/frankframework/frankframework/issues/7682
Normally the interface IParameter is used everywhere, which creates a group of Parameter, NumberParameter, BooleanParameter and DateParameter. Just using Parameter messes up the FrankDoc as it creates a seperate Parameter for this aswell.

Parameter is used incorrectly in XslErrorMessageFormatter

---

console/frontend/src/main/frontend/src/app/views/status/adapter-status/adapter-status.component.html

Added a check to prevent null pointer to listener when none are available in the adapter status page.

Fix js exception when no listener in receiver

---

console/frontend/src/main/frontend/src/app/app.component.html
console/frontend/src/main/frontend/src/app/app.component.ts
console/frontend/src/main/frontend/src/app/app.service.ts
console/frontend/src/main/frontend/src/app/components/pages/pages-topnavbar/pages-topnavbar.component.html
console/frontend/src/main/frontend/src/app/components/pages/pages-topnavbar/pages-topnavbar.component.ts
console/frontend/src/main/frontend/src/app/components/time-since.directive.ts
console/frontend/src/main/frontend/src/app/components/to-date.directive.ts
console/frontend/src/main/frontend/src/app/services/server-info.service.ts
console/frontend/src/main/frontend/src/app/services/server-time.service.spec.ts
console/frontend/src/main/frontend/src/app/services/server-time.service.ts
core/src/main/java/org/frankframework/management/bus/endpoints/ServerStatistics.java

Server now has timezone information in `/server/info`.
Console frontend has been updated to use the new ServerTime service which keeps track of the framework's timezone & epoch time.
TopNavBar time display & TimeSince & ToDate pipes have been updated to use the framework time.
This does not do anything for the statistics page yet as that needs to be reworked and seem broken (unrelated) now anyway

Get server timezone from FF Core & handle in console frontend

---

core/src/main/java/org/frankframework/stream/Message.java
core/src/main/java/org/frankframework/stream/OverflowToDiskOutputStream.java
core/src/main/java/org/frankframework/stream/SerializableFileReference.java
core/src/test/java/org/frankframework/stream/MessageTest.java

The logging of leaked items we had did not add any value to users, so now that we have a better logging I think it's better to remove it from older releases.
Since the cleaner in Message didn't actually do any work, it can be removed from there completely.

Remove logging of leaks that is now being made obsolete in 9.0

---

commons/src/main/java/org/frankframework/util/StringResolver.java
commons/src/test/java/org/frankframework/util/StringResolverTest.java
commons/src/test/resources/StringResolver.properties
docker/Tomcat/webapp/src/scripts/catalinaAdditional.properties

The `FileViewer.permission.rules` had a property that wasn't set anymore. Because of this: `*` (everything) got denied, and none of the logs were viewable. I've added a default to that property and added a second property (`credentialFactory.map.properties`) to deny access to.
This created a bug because it wasn't possible to have multiple defaults in a property. That has been fixed now.

Fix file viewing rule and string resolving with multiple defaults

---

console/frontend/src/main/frontend/package-lock.json
console/frontend/src/main/frontend/package.json

Reverts frankframework/frankframework#7972
The DomPurify update breaks the Console build.

Revert "Bump @types/dompurify from 3.0.5 to 3.2.0 in /console/frontend/src/main/frontend"

---

console/frontend/src/main/frontend/.eslintrc.js
console/frontend/src/main/frontend/package.json
console/frontend/src/main/frontend/src/app/components/monaco-editor/monaco-editor.component.ts
console/frontend/src/main/frontend/src/app/components/ng-mermaid/ng-mermaid.component.ts

Removes types that were required by mermaid's type definitions
Improves type import for monaco-editor
Locks typescript to version 5.4.x (required by angular v17, it would keep pulling latest on some occasions)

Console frontend Types cleanup

---

console/frontend/src/main/frontend/src/app/components/tab-list/configuration-tab-list.component.ts

Adjusts the filter condition in the tab list component to allow 
configurations with lengths greater than zero. This change ensures 
that configurations with a length of one are included in the tab list, 
improving the visibility of available options for users.

Fix filter condition for hiding configurations in tabs

---

docker/Tomcat/example/Dockerfile

This pull request introduces a significant enhancement to the Dockerfile by making the image registry configurable through a new `REGISTRY` argument. 
- Added a `REGISTRY` argument to the Dockerfile, which allows developers to specify the image repository dynamically.
- This modification facilitates building and testing of the Docker image in the CI, streamlining the development workflow and ensuring that changes can be validated before being pushed to the remote registry.
- Improved flexibility in managing Docker images.
- Enhanced local development experience by allowing for easier testing and validation of images.
This change is expected to improve the overall efficiency of the development process and make it easier for developers to work with Docker images in various environments.

chore(docker): make registry configurable in Dockerfile

---

core/src/main/java/org/frankframework/configuration/SpringEventErrorHandler.java
core/src/main/java/org/frankframework/management/bus/endpoints/Monitoring.java
core/src/main/java/org/frankframework/monitoring/MonitorManager.java
core/src/main/java/org/frankframework/monitoring/Trigger.java
core/src/main/resources/SpringApplicationContext.xml
core/src/test/java/org/frankframework/management/bus/endpoints/TestMonitoring.java
core/src/test/java/org/frankframework/monitoring/TriggerTest.java
core/src/test/java/org/frankframework/receivers/ReceiverTest.java
management-gateway/src/main/java/org/frankframework/management/bus/BusException.java

Make event handling asynchronous and add an error-handler.
Adding the error-handler will prevent the propagation of errors from events back to their publisher. Making event asynchronous seems like a logical thing to do, so the main process can continue while events are handled in the background, but isn't really part of the original issue.

Errors in events should not propagate back to the source

---

console/frontend/src/main/frontend/src/app/views/monitors/monitors.component.html
console/frontend/src/main/frontend/src/app/views/monitors/monitors.component.ts
console/frontend/src/main/frontend/src/app/views/monitors/monitors.service.ts
core/src/main/java/org/frankframework/monitoring/AbstractMonitorDestination.java
core/src/test/java/org/frankframework/monitoring/SenderMonitorAdapterTest.java

Fixes #7969 
There are two bugs at play here:
First, there is a bug in the frontend which doesn't send the name of the destination, but instead sends the index, thus adding a `0`.
The name of a destination is not required and will automatically be instantiated with the name of the class (`SenderMonitorAdapter` in this case). The destination is stored in a map with the name being a key. Two destinations without a name are overwritten in the map and only one shows up. This will be fixed by following Niels' suggestion and by making the name attribute mandatory.

7969 fix two bugs with monitoring

---

console/frontend/src/main/frontend/src/app/views/monitors/monitors-add-edit/monitors-add-edit.component.html

It's a lot of text, and it overflows if there is not enough space. It's not the best solution but for now it's the easiest...
Placeholders do not work when there is a default value. Though this not the best solution, and perhaps we should revamp all the forms, but at least it improves the current user-flow a bit...

Move placeholder text on edit-trigger page to a 'hint'

---

pom.xml

The Log4J2 2.23.1 code does not yet contain the problematic change that can cause the `ConcurrentModificationException`.

Downgrade Log4J2 to avoid exception when setting loglevel.

---

commons/src/main/java/org/frankframework/lifecycle/DynamicRegistration.java
core/src/main/java/org/frankframework/http/RestListener.java
core/src/test/resources/Management/securityItemsResponse.json
security/src/main/java/org/frankframework/lifecycle/servlets/AbstractServletAuthenticator.java

Reorder the default authorization roles in the RestListener, 
AbstractServletAuthenticator, andRegistration classes 
to maintain a consistent hierarchy.
The hierarchy goes from: few permissions -> more permissions

Reorder authorization roles for consistency

---

core/src/main/java/org/frankframework/scheduler/job/SendMessageJob.java
core/src/main/java/org/frankframework/util/StreamCaptureUtils.java
core/src/test/java/org/frankframework/util/StreamCaptureUtilsTest.java
ladybug/debugger/src/test/java/org/frankframework/ladybug/capture/TestOutputStreamCaptureWrapper.java

When an adapter was called via a SendMessageJob, the result was never read, resulting in "Captured stream was closed without being read". By applying this change, the output will be 'read' in that case.

Fix showing non-read stream in ladybug

---

console/frontend/src/main/frontend/src/app/app.module.ts
console/frontend/src/main/frontend/src/app/components/combobox/combobox.component.html
console/frontend/src/main/frontend/src/app/components/combobox/combobox.component.scss
console/frontend/src/main/frontend/src/app/components/combobox/combobox.component.spec.ts
console/frontend/src/main/frontend/src/app/components/combobox/combobox.component.ts
console/frontend/src/main/frontend/src/app/views/monitors/monitors-new/monitors-new.component.html
console/frontend/src/main/frontend/src/app/views/monitors/monitors-new/monitors-new.component.ts
console/frontend/src/main/frontend/src/app/views/test-pipeline/test-pipeline.component.html
console/frontend/src/main/frontend/src/app/views/test-pipeline/test-pipeline.component.ts
console/frontend/src/main/frontend/src/app/views/test-service-listener/test-service-listener.component.html
console/frontend/src/main/frontend/src/app/views/test-service-listener/test-service-listener.component.ts

This PR adds a "combobox" component. It acts as a dropdown with autocomplete. 
It can be used with just the keyboard by typing using the keys and pressing enter (or by filling in the whole value by hand and tabbing away) 
It can also be used with the mouse only, by clicking on the input and scrolling + clicking on the preferred option. 
A combination of this techniques is also possible.
Closes #5893

Add dynamic drop down to select an adapter in "Test a Pipeline" faster 

---

.github/workflows/maven-build.yml
pom.xml

They apparently released a new version but somehow this doesn't seem to be working properly yet..
https://github.com/projectlombok/lombok/issues/3722
For now it's probably best to just limit the version to 21 until Java 24 has been released (with full Lombok support)

Force max Java version because of Lombok support

---

core/src/main/resources/xml/xsd/FrankConfig-compatibility.xsd
core/src/main/resources/xml/xsd/FrankConfig.xsd
test/src/main/configurations/MainConfig/ConfigurationEsbSoapValidator.xml
test/src/main/configurations/MainConfig/ConfigurationInputOutputWrapper.xml
test/src/main/configurations/MainConfig/ConfigurationSoapWrapperPipe.xml
test/src/main/configurations/TX/MonitorConfig.xml
test/src/main/configurations/TX/TransactionHandlingMultiThread.xml
test/src/main/resources/DeploymentSpecifics.properties

We are now getting the follow XSD validation error. I think that in https://github.com/frankframework/frank-doc/pull/242 elements (used in batch processing) and ErrorMessageFormatters broke...
`
Validation error in [classpath:abcdef.xml] at line [3] when validating against schema [/xml/xsd/FrankConfig-compatibility.xsd]: cvc-complex-type.3.1: Value 'org.frankframework.errormessageformatters.SoapErrorMessageFormatter' of attribute 'className' of element 'ErrorMessageFormatter' is not valid with respect to the corresponding attribute use. Attribute 'className' has a fixed value of 'org.frankframework.errormessageformatters.ErrorMessageFormatter'.
`

Update FrankConfig XSD

---

core/src/test/java/org/frankframework/jdbc/dbms/DbmsSupportTest.java
dbms/src/main/java/org/frankframework/dbms/Dbms.java
dbms/src/main/java/org/frankframework/dbms/H2DbmsSupport.java
dbms/src/test/java/org/frankframework/dbms/H2DbmsSupportTest.java
test/src/main/configurations/MainConfig/ConfigurationExpectedSessionKeys.xml
test/src/main/configurations/MainConfig/ConfigurationFrankSender.xml
test/src/main/resources/Configuration.xml

`ON UPDATE SKIP LOCKED` is supported since H2 2.2.220.

Minor cleanup and enable skip-locked for H2 databases

---

core/src/main/java/org/frankframework/core/IConfigurable.java
core/src/main/java/org/frankframework/core/IListener.java
core/src/main/java/org/frankframework/core/IPipe.java
core/src/main/java/org/frankframework/core/ISender.java

I'm not sure their added JavaDoc really added that much and this cleans up the interfaces a bit.

Remove some overloads of the `configure()` method

---

core/src/main/java/org/frankframework/core/PipeLineSession.java
core/src/test/java/org/frankframework/core/PipeLineSessionTest.java
core/src/test/java/org/frankframework/processors/InputOutputPipeProcessorTest.java

Fix for ballooning PipeLineSession only.
Not yet cleaning up the `closeables`, that will be a separate PR.
After some consideration, I decided to put in just the same fix as is in 7.9 with only minor cosmetic changes, and a few small changes to the way it is tested.
Closes #8258

Copy fix from 7.9, with some minor changes

---

core/src/main/java/org/frankframework/core/PipeLineSession.java
core/src/test/java/org/frankframework/core/PipeLineSessionTest.java
core/src/test/java/org/frankframework/processors/InputOutputPipeProcessorTest.java

(cherry picked from commit 0af96569f97d2ddeb712357e40a65e1a64c46d96)

Reduce memory footprint when using iterating pipes and returned sessionkeys (#8528)

---

console/frontend/src/main/frontend/src/app/components/monaco-editor/monaco-editor.component.ts
console/frontend/src/main/frontend/src/app/components/tab-list/configuration-tab-list.component.ts
console/frontend/src/main/frontend/src/app/views/configurations/configurations-show/configurations-show.component.ts
console/frontend/src/main/frontend/src/app/views/status/status.component.ts

Change queryParamsHandling to 'merge' and add replaceUrl option in multiple components to improve URL anagement. 
This ensures that the application maintains a cleaner URL structure while navigating between tabs and views. 
Additionally, refactor variable declarations to use 'readonly' for better code clarity and immutability.

Fix query params handling so Configuration tabs persist on refresh

---

console/frontend/src/main/frontend/src/app/components/monaco-editor/monaco-editor.component.ts
console/frontend/src/main/frontend/src/app/components/tab-list/configuration-tab-list.component.ts
console/frontend/src/main/frontend/src/app/views/configurations/configurations-show/configurations-show.component.ts
console/frontend/src/main/frontend/src/app/views/status/status.component.ts

Change queryParamsHandling to 'merge' and add replaceUrl option  in multiple components to improve URL management. This ensures  that the application maintains a cleaner URL structure while  navigating between tabs and views. Additionally, refactor  variable declarations to use 'readonly' for better code  clarity and immutability.

fix: update queryParamsHandling and replaceUrl

---

ladybug/pom.xml

Ladybug doesn't load in the frank console after the changes of 7-2/11-2. Tried both versions but had to revert to the version of 25-12-2024 (commit 082a644).
9.0.0 should not be affected

Ladybug doesn't load in the console 

---

ladybug/pom.xml

I must've been wrong yesterday, but apparently the built version I used yesterday, wasn't completely up to date. Retested this explicitly and ladybug _is_ loading with this version.

Update ladybug version

---

ladybug/debugger/src/main/java/org/frankframework/ladybug/DeploymentSpecificsBeanPostProcessor.java

Ladybug added a new feature to allow reports to be deleted after a certain amount of days.
This change will allow developers to configure this feature via the app constants.
The property `ibistesttool.maxStorageDays` will allow developers to set a certain amount of days a report is allowed to be stored before it will automatically be removed upon the next report insertion.
By default, this property value is set to -1, which disables the feature.

Add property for ladybug report retention period

---

aspose/src/main/java/org/frankframework/extensions/aspose/services/conv/impl/CisConversionServiceImpl.java
aspose/src/main/java/org/frankframework/extensions/aspose/services/conv/impl/MediaTypeValidator.java
aws/src/test/java/org/frankframework/senders/AmazonS3SenderTest.java
commons/src/main/java/org/frankframework/util/StreamUtil.java
core/src/main/java/org/frankframework/stream/Message.java
core/src/main/java/org/frankframework/stream/SerializableFileReference.java
core/src/main/java/org/frankframework/util/MessageUtils.java
core/src/main/java/org/frankframework/util/XmlUtils.java
core/src/test/java/org/frankframework/http/cxf/SoapProviderTest.java
core/src/test/java/org/frankframework/pipes/ReplacerPipeTest.java
core/src/test/java/org/frankframework/stream/MessageTest.java
core/src/test/java/org/frankframework/util/MessageUtilsTest.java
core/src/test/java/org/frankframework/util/StreamCaptureUtilsTest.java

- For TIKA and CharsetDetector, do not use byte[] from the message but an InputStream that supports mark/reset. More efficient, and more correct, and less overhead on our side.
- Other uses of `Message.getMagic()` want a string, so remove `getMagic()` and the code it relies on, and instead provide a simple method `peek()` that returns a String and internally relies on being able to mark/reset the Reader or Inputstream of the message.
Some of the changes have been lifted from PR #8409 and I want to use the changes in this PR to finalize #8409.

Simplify peeking into message

---

console/war/pom.xml

Improved solution to #8473.
This should stop similar dependabot pr's from being created for every spring boot update

Use spring.boot.version variable as spring-boot-maven-plugin version

---

core/src/main/java/org/frankframework/management/bus/endpoints/ConfigManagement.java
core/src/test/java/org/frankframework/management/bus/endpoints/TestConfigManagement.java

Adds a configurations root tag around the configuration elements to make the returned xml valid.
fixes #8401

Add root tag around configuration elements

---

console/backend/src/main/java/org/frankframework/console/configuration/RegisterServletEndpoints.java
console/backend/src/main/java/org/frankframework/console/configuration/SecurityChainConfigurer.java
console/backend/src/test/java/org/frankframework/console/configuration/SecurityChainConfigurerTest.java
console/backend/src/test/java/org/frankframework/console/configuration/SecurityChainTestConfiguration.java
test/src/main/resources/DeploymentSpecifics.properties

Added spring security configuration to make sure that 'localhost' ip addresses can always access /**/health endpoints. This only applies if security is active on the console

Make health endpoints available for localhost without authorization

---

core/src/main/java/org/frankframework/jdbc/MessageStoreListener.java
test/src/main/configurations/JMS/Configuration.xml
test/src/main/configurations/JMS/ConfigurationMessageStoreListeners.xml
test/src/test/testtool/MessageStoreSenderAndListener/scenario03/out-queue.xml

The storage id key was missing in the message context. This fix correctly sets the value so the retry won't fail while trying to convert a message key to a storage id (resulting in a NumberFormatException)

Make sure the storage id is present to be able to resend the message

---

core/src/main/java/org/frankframework/parameters/AbstractParameter.java
core/src/test/java/org/frankframework/http/HttpSenderTest.java
core/src/test/java/org/frankframework/parameters/ParameterTest.java
core/src/test/java/org/frankframework/testutil/ParameterBuilder.java
core/src/test/resources/Http/Responses/simpleMockedHttpPostWithUrlPatternParam.txt

Closes #8559 
(cherry picked from commit 53534586e11c0fc9f5c40de01cf56b40d23380a1)

Fix broken parameter pattern substitution (#8561)

---

core/src/main/java/org/frankframework/receivers/Receiver.java
core/src/test/java/org/frankframework/jms/PushingJmsListenerTest.java
core/src/test/java/org/frankframework/jms/SlowListenerWithPollGuard.java
core/src/test/java/org/frankframework/receivers/MockPushingListener.java
core/src/test/java/org/frankframework/receivers/ReceiverTest.java
core/src/test/java/org/frankframework/receivers/SlowListenerBase.java
core/src/test/java/org/frankframework/receivers/SlowListenerWithPollGuard.java
core/src/test/java/org/frankframework/receivers/SlowPullingListener.java
core/src/test/java/org/frankframework/receivers/SlowPushingListener.java

Move some tests to new JmsPushingListenerTest (with a TODO for future improvement).
Remove all JMS dependencies from other tests, cleaning them up a bit.

Remove JMS dependency from ReceiverTest

---

core/src/main/java/org/frankframework/jdbc/datasource/FrankResource.java
core/src/main/java/org/frankframework/jdbc/datasource/FrankResources.java
core/src/main/java/org/frankframework/jdbc/datasource/ObjectCreator.java
core/src/main/java/org/frankframework/jdbc/datasource/ObjectFactory.java
core/src/main/java/org/frankframework/jdbc/datasource/ResourceObjectLocator.java
core/src/main/java/org/frankframework/jndi/JndiObjectLocator.java
core/src/test/java/org/frankframework/jdbc/datasource/ResourceObjectLocatorTest.java
core/src/test/resources/ResourceLocator/validResources.yml

We used to keep a list of predefined resources that could be located via the ResourceLocator.
This allows any lookup-prefix to be used, which allows ObjectFactories to be dynamically loaded.

Make the Resource Locator work with any type of prefix

---

core/src/main/java/org/frankframework/core/Adapter.java
core/src/main/java/org/frankframework/http/RestServiceDispatcher.java
core/src/main/java/org/frankframework/http/rest/ApiListenerServlet.java
core/src/main/java/org/frankframework/pipes/MessageSendingPipe.java
core/src/main/java/org/frankframework/processors/InputOutputPipeProcessor.java
core/src/main/java/org/frankframework/receivers/PullingListenerContainer.java
core/src/main/java/org/frankframework/receivers/Receiver.java
core/src/main/java/org/frankframework/scheduler/ConfiguredJob.java
core/src/main/java/org/frankframework/scheduler/NamedThreadFactory.java
core/src/main/java/org/frankframework/scheduler/job/SendMessageJob.java
core/src/main/java/org/frankframework/threading/ThreadNamingTaskDecorator.java
core/src/main/java/org/frankframework/util/CleanerProvider.java
core/src/main/java/org/frankframework/util/LogUtil.java
core/src/main/resources/SpringApplicationContext.xml
core/src/main/resources/log4j4ibis.xml
core/src/main/resources/quartz.properties
example/src/main/resources/ConfigurationHelloWorlds.xml

`Receiver#stop()` contains the following code: `ThreadContext.clearAll();` which prevents me from using the closable-logcontext in `Adapter#stop()`.

Replace some thread.setNames with closable-log-context

---

core/src/main/java/org/frankframework/parameters/AbstractParameter.java
core/src/test/java/org/frankframework/parameters/DateParameterTest.java
core/src/test/java/org/frankframework/parameters/ParameterTest.java

Fix 'time' in parameter pattern (#8632)

---

core/src/main/java/org/frankframework/jdbc/JdbcListener.java
core/src/main/java/org/frankframework/jdbc/MessageStoreListener.java
core/src/main/java/org/frankframework/jdbc/MessageStoreSender.java
core/src/main/java/org/frankframework/pipes/AbstractValidator.java
core/src/main/java/org/frankframework/pipes/JsonValidator.java
core/src/main/java/org/frankframework/pipes/XmlValidator.java
core/src/main/java/org/frankframework/soap/SoapValidator.java
core/src/test/java/org/frankframework/jdbc/JdbcTableListenerTest.java
core/src/test/resources/Migrator/ChangelogBlobTests.xml
messaging/src/test/java/org/frankframework/jms/PushingJmsListenerTest.java

MessageStoreSender only ever supported inserting message as BLOB, so I concluded that supporting anything else than BLOB in the MessageStoreListener doesn't actually make sense.
Also some cleanups in JDBC tests, remove unused parameter in AbstractValidator.
Make tests in PushingJmsListenerTest more stable.

MessageStoreListener only supports BLOB, forbid other message field types

---

core/src/main/java/org/frankframework/jdbc/JdbcListener.java
core/src/test/java/org/frankframework/jdbc/FixedQuerySenderTest.java
core/src/test/java/org/frankframework/jdbc/JdbcTableListenerTest.java
core/src/test/java/org/frankframework/jdbc/datasource/TestBlobs.java
management-gateway/src/test/java/org/frankframework/management/gateway/HazelcastEndToEndTest.java

Includes "fix" for #6910 and several other fixes including some fixes that are also part of PR #8659 already.
This is the last PR needed to make all tests work with all databases, _except_ DB2 which I currently cannot get to connect to at all.
Lastly includes a HazelCast test change that increases the timeout because locally for me, sometimes this test takes a bit longer for some reason.

Fixes for several more JDBC test related issues

---

core/src/main/java/org/frankframework/http/HttpMessageEntity.java

Removes
2025-04-01 13:29:17,467 WARN  [FF-Scheduler_Worker-2] {cid=0af401eb--747e5a25_195f171fe77_-7fc9, listener=Update temperature, adapter=Update temperature, pipe=Post temperature to ThingsBoard, sender=Post temperature to ThingsBoard-sender} http.HttpMessageEntity - overriding Message [null] charset with value supplied from content-type [UTF-8]

Conditionally suppress log warning

---

pom.xml
test/pom.xml

Hacky tacky way to disable test resources from being copied when maven tests are skipped.
See:
- https://maven.apache.org/guides/introduction/introduction-to-the-lifecycle.html
- https://maven.apache.org/surefire/maven-surefire-plugin/examples/skipping-tests.html

Skip copy-test-resources when skipTests is true

---

core/src/main/java/org/frankframework/http/rest/ApiListenerServlet.java
core/src/test/java/org/frankframework/http/rest/ApiListenerServletTest.java

Backport of d56ac431999e95bf61e93d308daba88ee35753cc

Fix NPE in ApiListenerServlet

---

core/src/test/resources/Jdbc/StoredProcedureQuerySender/DatabaseChangelog-StoredProcedures.xml

Backport of #8706 / #8728
(cherry picked from commit f506294825305de9887643ce1ae63a650084b407)

Fix PK name in test table

---

ladybug/common/pom.xml

Should be what we need, `mvn dependency:tree` says that the version is updated in the common module:
```
[INFO] org.frankframework:frankframework-ladybug-common:jar:9.0.1-SNAPSHOT
[INFO] +- org.ibissource:ibis-ladybug:jar:3.0-20250107.001038:compile
[INFO] |  +- org.wearefrank:ladybug-frontend:jar:0.1.0-20241213.164256:compile
[INFO] |  +- org.apache.cxf:cxf-rt-rs-client:jar:4.0.6:compile
[INFO] |  |  +- org.apache.cxf:cxf-rt-transports-http:jar:4.0.6:compile
[INFO] |  |  +- org.apache.cxf:cxf-core:jar:4.0.6:compile
```

Update ladybug CXF dependency version

---

core/src/test/java/org/frankframework/components/ComponentLoaderTest.java
core/src/test/java/org/frankframework/testutil/TestAssertions.java

When running tests in IntelliJ the ComponentLoaderTest cannot find the generated pom.properties file in modules.
Ignore it so that there is not always a failing test.

Ignore the ComponentLoaderTest when running tests within IntelliJ

---

core/src/main/java/org/frankframework/documentbuilder/json/JsonUtils.java
core/src/main/java/org/frankframework/pipes/JsonPipe.java
core/src/main/java/org/frankframework/soap/SoapWrapper.java
core/src/main/java/org/frankframework/util/TransformerPool.java
core/src/main/java/org/frankframework/util/XmlUtils.java
core/src/test/java/org/frankframework/pipes/JsonPipeTest.java

- Cache utility transformer-pools created by the SoapWrapper (as they should be!)
- Cache the transformer-pool in the JsonPipe as a utility transformer-pool
- Clean up the code that creates and caches the utility transformer pools.

Improved caching of TransformerPools

---

core/src/main/java/org/frankframework/http/rest/ApiListener.java
core/src/main/java/org/frankframework/http/rest/ApiListenerServlet.java
core/src/test/java/org/frankframework/http/rest/ApiListenerServletTest.java

Allow JWT Token to omit "Bearer" when it is a non-standard header.

---

core/src/main/java/org/frankframework/core/PipeLineSession.java
core/src/main/java/org/frankframework/processors/InputOutputPipeProcessor.java
core/src/main/java/org/frankframework/util/CleanerProvider.java
core/src/main/java/org/frankframework/util/XmlUtils.java
core/src/test/java/org/frankframework/processors/InputOutputPipeProcessorTest.java

This PR started off as me trying to add more test coverage and reduce the brain method in the `InputOutputPipeProcessor`.
I noticed some leaks in the leak log and added the values to the closeables list, however since they are String based messages, they are never closed.
Not sure what the way forward is here, do we trust the leak log, do we ignore String messages in there? Do we call close on Message but not set the value to null??

Refactor InputOutputPipeProcessor

---

core/pom.xml

Workaround for this bug in IntelliJ 2025.1: https://youtrack.jetbrains.com/issue/IDEA-368907/Annotation-Processor-configuration-is-misinterpreted

Workaround for bug in IntelliJ 2025.1

---

.github/ISSUE_TEMPLATE/1-bug.yml
.github/ISSUE_TEMPLATE/2-feature-request.yml
.github/ISSUE_TEMPLATE/3-epic.yml
.github/ISSUE_TEMPLATE/4-documentation.yml

Since GitHub now gives the same message, it is double. It also didn't render nicely. So now it is gone.

Remove tip about files in issue templates

---

core/src/main/resources/AppConstants.properties

* Adds a second '#' to a description line, so it will not be parsed as a property.
* Fixes an unintentional newline causing a deprecation tag to appear in the docs.

fix: AppConstants.properties formatting

---

core/src/main/java/org/frankframework/core/IPipe.java
core/src/main/java/org/frankframework/core/PipeRunResult.java
core/src/main/java/org/frankframework/processors/AbstractPipeProcessor.java
core/src/main/java/org/frankframework/processors/CheckMessageSizePipeProcessor.java
core/src/main/java/org/frankframework/processors/CorePipeLineProcessor.java
core/src/main/java/org/frankframework/processors/ExceptionHandlingPipeProcessor.java
core/src/main/java/org/frankframework/processors/InputOutputPipeLineProcessor.java
core/src/main/java/org/frankframework/processors/InputOutputPipeProcessor.java
core/src/main/java/org/frankframework/processors/LimitingParallelExecutionPipeProcessor.java
core/src/main/java/org/frankframework/processors/LockerPipeProcessor.java
core/src/main/java/org/frankframework/processors/LogPipeProcessor.java
core/src/main/java/org/frankframework/processors/MonitoringPipeProcessor.java
core/src/main/java/org/frankframework/processors/PipeProcessor.java
core/src/main/java/org/frankframework/processors/TrackPreviousPipeInMetadataProcessor.java
core/src/main/java/org/frankframework/processors/TransactionAttributePipeProcessor.java
core/src/main/java/org/frankframework/stream/Message.java
core/src/main/resources/SpringConfigurationContext.xml
core/src/main/resources/log4j4ibis.xml
core/src/test/java/org/frankframework/processors/CheckMessageSizePipeProcessorTest.java
core/src/test/java/org/frankframework/processors/ExceptionHandlingPipeProcessorTest.java
core/src/test/java/org/frankframework/processors/LimitingParallelExecutionPipeProcessorTest.java
core/src/test/java/org/frankframework/processors/LockerPipeProcessorTest.java
core/src/test/java/org/frankframework/processors/LogPipeProcessorTest.java
core/src/test/java/org/frankframework/processors/MonitoringPipeProcessorTest.java
core/src/test/java/org/frankframework/processors/PipeProcessorTestBase.java
core/src/test/java/org/frankframework/processors/TrackPreviousPipeInMetadataProcessorTest.java
test/src/main/configurations/MainConfig/ConfigurationCompactMessage.xml
test/src/test/testtool/ForEachChildElementPipe/01/out.json
test/src/test/testtool/ForEachChildElementPipe/05/out.json
test/src/test/testtool/ForEachChildElementPipe/common.properties

```log
2025-04-30 15:35:28,187 DEBUG [Thread-x] {mid=123, cid=456, listener=listener of [JavaListener], adapter=CompactMessage-JavaListener3, pipe=echo} processors.TransactionAttributePipeProcessor - executing pipe with transaction definition [PROPAGATION_SUPPORTS,ISOLATION_DEFAULT] in local TX environment with timeout [0]
2025-04-30 15:35:28,187 DEBUG [Thread-x] {mid=123, cid=456, listener=listener of [JavaListener], adapter=CompactMessage-JavaListener3, pipe=echo} processors.InputOutputPipeProcessor - compacting result message
2025-04-30 15:35:28,191 WARN  [Thread-x] {mid=123, cid=456, listener=listener of [JavaListener], adapter=CompactMessage-JavaListener3, pipe=echo} processors.MonitoringPipeProcessor - message [Message[2f3ea412:String]] duration [9] ms exceeds maximum allowed …
```

Take advantage of the logcontext in pipe processors

---

pom.xml

It should be as simple as this, maven config files etc have already been changed on the build/deployment servers.

Use the new Sonatype 'deploy to central' plugin

---

core/src/main/resources/AppConstants.properties

This is the exception / test failure I got, both in Maven and when running unit-tests from IntelliJ:
```
java.lang.NoClassDefFoundError: org/frankframework/configuration/classloaders/DirectoryClassloader (wrong name: org/frankframework/configuration/classloaders/DirectoryClassLoader)
at java.base/java.lang.ClassLoader.defineClass1(Native Method)
at java.base/java.lang.ClassLoader.defineClass(ClassLoader.java:1026)
at java.base/java.security.SecureClassLoader.defineClass(SecureClassLoader.java:150)
at java.base/jdk.internal.loader.BuiltinClassLoader.defineClass(BuiltinClassLoader.java:862)
at java.base/jdk.internal.loader.BuiltinClassLoader.findClassOnClassPathOrNull(BuiltinClassLoader.java:760)
at java.base/jdk.internal.loader.BuiltinClassLoader.loadClassOrNull(BuiltinClassLoader.java:681) …
```

Fix the name of the default DirectoryClassLoader in the AppConstants.properties

---

cmis/src/test/java/org/frankframework/extensions/cmis/CmisSenderTestBase.java
cmis/src/test/java/org/frankframework/extensions/cmis/TestBindingTypes.java
core/src/main/java/org/frankframework/compression/ZipIteratorPipe.java
core/src/main/java/org/frankframework/core/PipeLineSession.java
core/src/main/java/org/frankframework/http/RestListenerUtils.java
core/src/main/java/org/frankframework/http/WebServiceListener.java
core/src/main/java/org/frankframework/http/cxf/AbstractSOAPProvider.java
core/src/main/java/org/frankframework/jdbc/AbstractJdbcQuerySender.java
core/src/main/java/org/frankframework/parameters/DateParameter.java
core/src/main/java/org/frankframework/parameters/ParameterType.java
core/src/main/java/org/frankframework/soap/SoapWrapper.java
core/src/main/java/org/frankframework/util/JdbcUtil.java
core/src/test/java/org/frankframework/compression/ZipIteratorPipeTest.java
core/src/test/java/org/frankframework/parameters/DateParameterTest.java
core/src/test/java/org/frankframework/util/JdbcUtilTest.java
test/src/main/configurations/HTTP/ConfigurationRestListener.xml

- Create formatter once during configure
- No longer store zip-streams directly in the session but use messages (with context)
- Remove inputstream and bytes parameter types ([Deprecated in version 7.7](https://github.com/frankframework/frankframework/pull/2445))
- Cleanup old CMIS tests which no longer use StreamToServlet
- Remove StreamToServlet from JDBC Query Senders
After this the PipeLineSession should no longer contain raw InputStreams or Readers.

Minor cleanups and performance improvements

---

core/src/main/java/org/frankframework/pipes/IfPipe.java
core/src/main/java/org/frankframework/stream/Message.java
core/src/main/java/org/frankframework/util/MessageUtils.java
core/src/test/java/org/frankframework/pipes/IfPipeJsonPathTest.java
core/src/test/java/org/frankframework/pipes/IfPipeTest.java
core/src/test/java/org/frankframework/pipes/IfPipeXpathTest.java
core/src/test/java/org/frankframework/stream/MessageTest.java
core/src/test/java/org/frankframework/util/MessageUtilsTest.java

Closes #9012: IfPipe is supposed to pass on the input unmodified but when the input is a stream, there are various ways in which it can lose the input.

IfPipe can lose the input message

---

console/frontend/src/main/frontend/src/app/components/datatable/datatable.component.ts
console/frontend/src/main/frontend/src/app/components/th-sortable.directive.spec.ts
console/frontend/src/main/frontend/src/app/components/th-sortable.directive.ts
console/frontend/src/main/frontend/src/app/views/configurations/configurations-manage/configurations-manage-details/configurations-manage-details.component.ts
console/frontend/src/main/frontend/src/app/views/storage/storage-list/storage-list.component.html
console/frontend/src/main/frontend/src/app/views/storage/storage-list/storage-list.component.ts

Now by default sorts descending instead of hardcoded ascending order.
Added select input in 'Display and Search Filters' options to switch sort direction

Add sorting options in error store

---

security/src/main/java/org/frankframework/lifecycle/servlets/AbstractServletAuthenticator.java
security/src/main/java/org/frankframework/lifecycle/servlets/BearerOnlyAuthenticator.java
security/src/main/java/org/frankframework/lifecycle/servlets/NoOpAuthenticator.java
security/src/test/java/org/frankframework/lifecycle/servlets/BearerOnlyAuthenticatorTest.java
test/src/test/java/org/frankframework/runner/IafTestInitializerTest.java
test/src/test/java/org/frankframework/runner/KeycloakBearerOnlyAuthenticatorIntegrationTest.java
test/src/test/java/org/frankframework/runner/RunCypressE2eTest.java
test/src/test/java/org/frankframework/runner/RunLarvaTests.java
test/src/test/resources/test-realm.json

This is needed for the authentication in the framework. Extended the integration test for this, to actually reach an endpoint which needs a role. 
I had some struggles with keycloak, since you need to stop keycloak to do a complete export. But there isn't a command to stop keycloak. I managed to export users, but those were missing the roles, which I actually need in the test. After some tweaking in the import file I managed to figure out the syntax to actually provide a user _with_ a role mapping.

Modified bearer only authentication to expect roles in the token

---

console/frontend/src/main/frontend/src/app/views/storage/storage-list/storage-list-dt/storage-list-dt.component.html
console/frontend/src/main/frontend/src/app/views/storage/storage-list/storage-list-dt/storage-list-dt.component.ts

The resend or delete button will now show as disabled instead of also 
having a loading icon when the message is being processed while the 
button is not for the current action

Message store disable button when its not current action

---

core/src/main/java/org/frankframework/http/AbstractHttpSender.java
core/src/main/java/org/frankframework/http/AbstractHttpSession.java
core/src/test/java/org/frankframework/http/SharedHttpSenderTest.java

This refactor updates the `AbstractHttpSession` to use getters when accessing credentials, token endpoints, and authentication methods.
By switching to getters, the `AbstractHttpSender` can now override these methods to delegate to a referenced shared resource. This ensures that when a sharedResourceRef is configured, the sender uses the live authentication properties from the shared resource instead of its own local state.
Fixes:
* #9503

refactor: make HttpSender use shared resource properties via getters
